### ISSUE TITLE
Метод Authorize падает на Mono / .NET 4.0

### ISSUE THREAD

**Issue by DVZverrr** [vknet/vk#100]
При выполнении авторизации с логином и паролем метод падает с InvalidOperationException : request started. Выяснил следующее: в реализации HttpWebRequest в Mono при выполнении GetRequestStream выставляется флаг requestSent = true (исходники http://searchcode.com/codesearch/view/34856479/). При дальнейшем выполнении операций с объектом HttpWebRequest этот  флаг проверяется вызовом метода CheckRequestStarted, и если флаг поднят, то кидается тот самый Exception. В данном случае он возникает в методе public static WebCallResult Post(WebForm form) объекта WebCall. 
```
request.GetRequestStream().Write(formRequest, 0, formRequest.Length);
request.AllowAutoRedirect = false;
request.Referer = form.OriginalUrl; - здесь вылетает Exception.
```
Если переписать так:
```
request.Referer = form.OriginalUrl;
request.GetRequestStream().Write(formRequest, 0, formRequest.Length);
request.AllowAutoRedirect = false;
```
то все работает.

**Comment by CaCTuCaTu4ECKuu** [comment]
Спасибо, исправлено
