### ISSUE TITLE
GetConversationMembers 

### ISSUE THREAD

**Issue by justmavi** [vknet/vk#1000]
В этой функции есть параметр fields, который в отличии от vk api является обязательным. Делайте пожалуйста его необязательным, в больших случаях это ненужный параметр и для обхода ошибки придется создавать коллекцию, которая нигде не используется. 
![image](https://user-images.githubusercontent.com/36304554/83800550-a7585a00-a6b8-11ea-9fa3-7cd99900939d.png)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
