### ISSUE TITLE
Переименовать метод account.banuser в account.ban

### ISSUE THREAD

**Issue by 1dNDN** [vknet/vk#1002]
В [документации ВК](https://vk.com/dev/account.ban) этот метод называется именно ban.

**Comment by itsokto** [comment]
Кажется ВК переименовали этот метод, требуются изменения.
Account.BanUser будет помечен как Obsolete.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
