### ISSUE TITLE
AccountGetBannedResult содержит что-то невразумительное

### ISSUE THREAD

**Issue by 1dNDN** [vknet/vk#1004]
Этот класс содержит следующие поля:
```
public ulong Count { get; set; } // Общее количество записей на стене.
public ReadOnlyCollection<long> Items { get; set; } // Посты.
public ReadOnlyCollection<User> Profiles { get; set; } // Профили.
public ReadOnlyCollection<Group> Groups { get; set; } // Группы.
```
Этот класс используется для вывода результата работы метода `GetBanned`, который возвращает совершенно другие поля, согласно [документации](https://vk.com/dev/account.getBanned), а именно число результатов в поле Count и массив объектов пользователей в поле Items.

**Comment by inyutin-maxim** [comment]
Если я правильно помню то если передать extended, то ответ будет именно таким

**Comment by itsokto** [comment]
![image](https://user-images.githubusercontent.com/36706257/85156470-c9c6a780-b262-11ea-82ce-b42c89335b28.png)
