### ISSUE TITLE
Ошибка  "Суммарная длина для payload всех кнопок должен быть максимум 1000 символов."

### ISSUE THREAD

**Issue by GhoSTi4eG** [vknet/vk#1019]
`**Describe` the bug**
Выводится ошибка при многократном использовании кнопок(кол-во 10+)

**To Reproduce**
1. Нажимаю кнопки в самом поте по порядку
2. Кликаю на /итисс потом /иэиу и т.д. 
3. через пару кликов вижу ошибку

**Expected behavior**
Продолжение вывода информации, как и в предыдущие разы

**Screenshots**

![image](https://user-images.githubusercontent.com/65601313/86352264-2fa52d00-bc6e-11ea-9355-3175025aa5ed.png)

**Desktop (please complete the following information):**
 - OS: windows 10 home
 - Browser [yandex,]
 - Version [20.6.2.197]

**Smartphone (please complete the following information):**
 - Device:  Xiaomi
 - OS: Android 10
 - Browser [chrome]
 - Version [83,0,4103,106]

**Comment by GhoSTi4eG** [comment]
Проблема видимо была из-за того, что объявленный в самом начале  KeyboardBuilder key = new KeyboardBuilder(); копил в себе хлам, из-за того что юзался всеми вызовами, переделал для каждого свой, ошибка перестала появляться.

**Comment by inyutin-maxim** [comment]
KeyboardBuilder._totalPayloadLength не обнуляется
