### ISSUE TITLE
Access denied: no access to call this method

### ISSUE THREAD

**Issue by ronzhak** [vknet/vk#102]
Standalone приложение. Авторизация пройдена (Settings.All), токен получен. Выполняю метод: _vkApi.Wall.Post(-ИдГруппы, false, true, 'Тест'), получаю ошибку: Access denied: no access to call this method. Стена в группе закрытая, сообщение публикую от имени группы. Такой проблемы не было до сегодняшнего дня. На странице метода сообщение уходит.

**Comment by nekulin** [comment]
поиграйте с параметром from_group

**Comment by inyutin-maxim** [comment]
Проверил метод работает исправно. закрываю
