### ISSUE TITLE
Загрузка фотографии, что бы потом ее разместить на стене сообщества. photo:[]

### ISSUE THREAD

**Issue by SanteR1** [vknet/vk#103]
Добрый день, не могу нигде найти в чем ошибка. 
Подскажите пожалуйста, что я делаю не правильно?
Не получается загрузить фотографию на сервер в контакте для последующего использования ее на стене в сообществе.
`< //////
{***********

int appId = ********; // указываем id приложения
string email = "*********"; // email для авторизации
string password = "***********"; // пароль
Settings settings = Settings.All; // уровень доступа к данным

var api = new VkApi();
api.Authorize(appId, email, password, settings); // авторизуемся
var browser = new Browser();

var serverlink = api.Photo.GetWallUploadServer(********); // id группы, здесь узнаем путь, по которому будем заливать фотографию.

var sss = Browser.UploadFile(serverlink.UploadUrl, @"r:\tofile.jpg"); // загружаем фотографию на сервер.

var ass = browser.GetJson(serverlink.UploadUrl);   // не нашел у вас метода, с помощью которого посмотреть результат в ответ на загрузку фотографии.
// В ответ фото всегда приходит пустым []

var der = JsonConvert.DeserializeObject<RootObject>(ass); здесь разбираю по частям ответ, отдельно, photo, server и hash

var save = api.Photo.SaveWallPhoto(der.photo, null, ********,der.server,der.hash); // ну а здесь бессмысленно что то сохранять, из за фото []

}
public class RootObject // Может у вас реализовано это, что бы не городить этого мне?
{
public int server { get; set; }
public string photo { get; set; }
public string hash { get; set; }
}

Пожалуйста, подскажите, я уже весь интернет облазил.
Заранее спасибо!!!

**Comment by azhidkov** [comment]
Из чата:
еще вопрос
public class ServerData
{
public int server { get; set; }
public string photo { get; set; }
public string hash { get; set; }
}
public class VK
{
void Login()
{
api = new VkApi();
api.Authorize(appID, login, password, VkNet.Enums.Filters.Settings.Photos | VkNet.Enums.Filters.Settings.Wall);
VkNet.Model.UploadServerInfo server = api.Photo.GetWallUploadServer(api.UserId);
ServerData server_data = null;// JsonConvert.DeserializeObject<ServerData>(ImageUpload(server.UploadUrl, photo_path));
using (var client = new WebClient())
{
var answer = Encoding.UTF8.GetString(client.UploadFile(server.UploadUrl, photo_path));
server_data = JsonConvert.DeserializeObject<ServerData>(answer);
}
ReadOnlyCollection<Photo> attach = api.Photo.SaveWallPhoto(server_data.photo, server.UserId, null, server_data.server, server_data.hash);
}
}
и на последней строчке возвращает ошибку Invalid hash, хотя все данные в server_data правильные, ответ в строке var answer = Encoding.UTF8.GetString(client.UploadFile(server.UploadUrl, photo_path)); приходит в той форме, что описана в документации самого VK API
заранее спасибо за помощь

@chuvi1155 Nov 05 15:53

**Comment by inyutin-maxim** [comment]
Рабочий пример

**Comment by arretmoon** [comment]
Все равно не работает

**Comment by inyutin-maxim** [comment]
@arretmoon давайте обсудим в [telegram](https://t.me/joinchat/CHFCHxHqca0waHIe3-Fuqg)
