### ISSUE TITLE
Get

### ISSUE THREAD

**Issue by sinyev** [vknet/vk#1034]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. 
Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - [ ] .net 4.0
  - [x] .net 4.5
  - [ ] NETStandard2.0
  - [ ] другое. Указать строкой ниже.
  
2. Класс и метод в котором возникла проблема:

3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса:

```csharp
  // Вставьте пример кода сюда
```

4. JSON ответа. Для удобства сбора этих данных подключите логи (https://github.com/vknet/vk/wiki/Logging):

```json
{
  "response": {}
}
```

5. Если в примере не указаны конкретные значения параметров запроса укажите их здесь:

6. PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Telegram Chat](https://img.shields.io/badge/Chat-Telegram-0F80C1.svg)](https://t.me/VkDotNet), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by inyutin-maxim** [comment]
@sinyev Из описания абсолютно не понятно в чем ваша проблема, распишите более подробно что вы имели ввиду
