### ISSUE TITLE
VkNet.Exception.VkApiException: Validation required

### ISSUE THREAD

**Issue by SanteR1** [vknet/vk#104]
VkNet.Exception.VkApiException: Validation required: please open redirect_uri in browser 610063296

Я использую библиотеку на сервере с зарубежным ip, видимо вк беспокоится за мой аккаунт и просит с удаленного компа перейти по url возможно с  подтверждением капчи.
Может кто знает как это реализовать?

**Comment by CaCTuCaTu4ECKuu** [comment]
Если вопрос в единичном случае то можно с браузера залогинится и подтвердить, потом с api тоже должно заработать.
А вообще я так понял ошибка что-то возвращает, соответственно ее можно обработать, почитайте там в теме #89 я писал как обрабатывать Exception'ы, если вам это не понятно. Вы отследите как в браузере это сообщение обрабатывается и сделайте это у себя.

**Comment by CaCTuCaTu4ECKuu** [comment]
Возможности авторизации с капчей была добавлена, двухфакторная авторизация будет добавлена позже

**Comment by azhidkov** [comment]
Двухфакторая авторизация уже работает. Исправлено в 1.0.18 версии.

**Comment by CodyExho** [comment]
при запуске просит webcall.cs
