### ISSUE TITLE
Авторизация через Web

### ISSUE THREAD

**Issue by azhidkov** [vknet/vk#105]
Реализовать авторизацию через стандартный переход на сайт вконтакте и ввод логина/пароля.

**Comment by ResPasha** [comment]
Была такая необходимость. Сделал самостоятельно вне библиотеки, а затем подсунул библиотеке accesstoken и userid

**Comment by CaCTuCaTu4ECKuu** [comment]
http://authorize.vk.com?login=login&password=pass
Я не думаю что это нужно добавлять в библиотеку

**Comment by mokeev1995** [comment]
@CaCTuCaTu4ECKuu и что сейчас с этой ссылкой делать? редирект на главную страницу вк идёт.
идея вынести в какой-нибудь отдельный метод или как-то еще выглядит нормально

**Comment by CaCTuCaTu4ECKuu** [comment]
@mokeev1995 если подставить свой логин и пароль в нужные места то при переходе по ссылке вы можно получить куки с ssid

**Comment by mokeev1995** [comment]
@CaCTuCaTu4ECKuu попробовал, куки не посмотрел, но получил редирект на страницу логина. у меня двуфакторная авторизация

**Comment by CaCTuCaTu4ECKuu** [comment]
По-моему в библиотеке написана двухфакторная авторизация

**Comment by mokeev1995** [comment]
@CaCTuCaTu4ECKuu она то написана, но суть в том, что если хочется как-то это через WebView сделать, то надо как-то извращаться самому. Предложение было избавить пользователя от этих извращений

**Comment by beqabeqa473** [comment]
здравствуйте.

пишу аудио менеджер дла вкк.

досих пор использовал свои наработки, но уже есть полнофункциональный враппер.

раньше для авторизации я использовал webbrowser с сылкой
https://oauth.vk.com/authorize?client_id=xxxxxxxx&scope=audio,offline&redirect_uri=https://oauth.vk.com/blank.html&display=popup&v=5.27&response_type=token
и потом сохранял accesstoken и user id в файл настроек.

как мне сделать такуюже авторизацию через webbrowser?
или я могу использовать такойже тип, но потом я незнаю как передать этой библиотеке user id и access token.

**Comment by beqabeqa473** [comment]
может кто нибудь помочь?

**Comment by azhidkov** [comment]
Добрый день,

вы можете такой же тип авторизации, полученные затем accessToken, вы можете
использовать в методе Authorize (см.
https://github.com/vknet/vk/blob/master/VkNet/VkApi.cs#L330), примерно так:

```csharp

string accessToken = ... ; // accessToken от вашей авторизации
long userId = ...; // userId от вашей авторизации

var api = new VkApi();
api.Authorize(accessToken, userId);

```

On Thu, Feb 11, 2016 at 8:24 AM, beqa gozalishvili <notifications@github.com

**Comment by beqabeqa473** [comment]
спасибо, понятно.

просто небыло документировано, или я не нашел.

**Comment by beqabeqa473** [comment]
незнаю почему, но когда авторизуюсь так, у меня выходит invalid accesstoken exception

вот мой код

		private void Form3_Load(object sender, EventArgs e)
		{
            webBrowser1.Navigate("https://oauth.vk.com/authorize?client_id=5225662 &scope=audio,offline&redirect_uri=https://oauth.vk.com/blank.html&display=popup&v=5.27&response_type=token");

		}

		private void webBrowser1_DocumentCompleted(object sender, WebBrowserDocumentCompletedEventArgs e)
		{
			statusStrip1.Text = "Completed";
			try
			{
				string url = webBrowser1.Url.ToString();
				string str = url.Split('#')[1];
				if (str[0] == 'a')
				{
					Settings1.Default.token = url.Split('&')[0].Split('=')[1];
					Settings1.Default.id = url.Split('=')[3];
					Settings1.Default.auth = true;
                    var api = new VkApi();
                    api.Authorize(Settings1.Default.token, long.Parse(Settings1.Default.id));
                    //MessageBox.Show(Settings1.Default.token + "  " + Settings1.Default.id + "  " + Settings1.Default.auth);
					this.Close();
				}
			}
			catch (Exception ex)
			{

			}

**Comment by azhidkov** [comment]
Вы точно уверены, что в Settings1.Default.token валидный токен?

**Comment by beqabeqa473** [comment]
спасибо, работает.
