### ISSUE TITLE
Ошибки, с которыми столкнулся.

### ISSUE THREAD

**Issue by dx88** [vknet/vk#106]
1. messages.getHistory - выдает ошибку, якобы ответ пустой, хотя консоль показывает JSON массив, странно.
![image](https://cloud.githubusercontent.com/assets/13249146/9154718/3413c4ea-3ea7-11e5-896d-a575d193d485.png)
![image](https://cloud.githubusercontent.com/assets/13249146/9154728/6e937ffc-3ea7-11e5-9147-8e6434d9efb0.png)
2. Если включена двуфакторная авторизация - пролетаешь:(

**Comment by CaCTuCaTu4ECKuu** [comment]
Такая проблема есть. Насколько я помню двухфакторная авторизация не поддерживается сейчас.

**Comment by dx88** [comment]
Будет ли исправлена данная проблема?

**Comment by CaCTuCaTu4ECKuu** [comment]
В свободное время займусь, но если вы сами сможете доделать и сделать пулл было бы отлично

**Comment by dx88** [comment]
Исправил, сделал пулл.
![image](https://cloud.githubusercontent.com/assets/13249146/9359281/19a77d82-4699-11e5-84b4-3caf6db78010.png)
