### ISSUE TITLE
5.111 В объекте сообщения появилось поле template.

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#1060]
В объекте сообщения появилось поле  [template](https://vk.com/dev/bot_docs_templates?f=5.%20%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B%20%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9).

**Comment by sampletext32** [comment]
Эта Issue решена (возможно частично) - 
```
[JsonProperty("template")] 
public MessageTemplate Template { get; set; }
in class MessagesSendParams
```

**Comment by inyutin-maxim** [comment]
**Спасибо за проделанную работу**
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
