### ISSUE TITLE
5.114 В пересланных сообщениях и ответах теперь возвращается payload.

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#1062]
В пересланных сообщениях и ответах теперь возвращается payload.

**Comment by sampletext32** [comment]
Эта Issue решена - 
```
[JsonProperty("payload")] 
public string Payload { get; set; }
in class Message
```

**Comment by inyutin-maxim** [comment]
**Спасибо за проделанную работу**
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
