### ISSUE TITLE
5.115 В stories.getViewers изменился ответ

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#1063]
В [stories.getViewers](https://vk.com/dev/stories.getViewers) изменился ответ: в **items** теперь возвращается массив объектов. В объекте есть следующие поля: **is_liked** (bool) и **user_id** (int).

**Comment by y0ung3r** [comment]
Закрывайте тикет. Обновлено [этим](https://github.com/vknet/vk/commit/59516d47aa8c35a793893e6005ef5ae9a69b786e#diff-b6e4c339fbaa1866a1ad144ea6a0b68a3094ce54545956f0ba6b783995e35f53)  коммитом
