### ISSUE TITLE
5.118 изменен процесс загрузки историй.

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#1064]
[stories.save](https://vk.com/dev/stories.save):  изменен процесс загрузки историй. Начиная с этой версии, у методов [stories.getPhotoUploadServer](https://vk.com/dev/stories.getPhotoUploadServer) и [stories.getVideoUploadServer](https://vk.com/dev/stories.getVideoUploadServer) в ответе upload-сервера будет только один параметр **upload_result** (string). Для сохранения загруженных историй нужно дополнительно вызвать [stories.save](https://vk.com/dev/stories.save), передав туда полученный ранее **upload_result**.

**Comment by yeralexey** [comment]
Привет. Новичек на гитхабе. Возможно, не туда пишу или подтупливаю.

как этот стринг передать туда? json получил, код200 получил. и дальше туплю...

<Response [200]>
> c:\pyproj\vksmart\vksmart.py(23)<module>()
-> savestory = vk.stories.save(video = upload_results.json()['video'], server = upload_results.json()['server'], hash = upload_results.json()['hash'])
