### ISSUE TITLE
5.122 В объекте заказа информация о доставке и заказчике вынесена из основного объекта в новые подобъекты: delivery и recepient.

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#1067]
В объекте [заказа](https://vk.com/dev/_objects_market_order) информация о доставке и заказчике вынесена из основного объекта в новые подобъекты: **delivery** и **recepient**.

**Comment by ghost** [comment]
@inyutin-maxim  реализовано в #1428
