### ISSUE TITLE
Messages.Get System.NullReferenceException

### ISSUE THREAD

**Issue by ilya-vas** [vknet/vk#107]
Падает с исключением System.NullReferenceException
Если юзать либу из nuget, то такого не было, решил собрать от сюда и сразу упала

**Comment by CaCTuCaTu4ECKuu** [comment]
что-то я не понял что произошло и почему упало

**Comment by ilya-vas** [comment]
Возможно я криво собрал сборку, проверю и отпишусь!

**Comment by azhidkov** [comment]
Ошибка еще воспроизводится?

**Comment by ilya-vas** [comment]
Нет. Всё хорошо
