### ISSUE TITLE
Не корректная сериализация параметров запроса

### ISSUE THREAD

**Issue by ivanmem** [vknet/vk#1074]
Для отправки сообщений через метод Execute требуется получить параметры сообщения в виде JSON, поэтому нужен метод, который возвращает VkParameters, чтобы можно было из них получить JSON. В данный момент я держу у себя в проекте копию преобразования в VkParameters и вручную её актуализирую для своего проекта.
![screenshot](https://user-images.githubusercontent.com/33786293/94017813-89724a80-fdb8-11ea-93ac-8c43e7f47a98.png)

В данный момент преобразование происходит в методе MessagesCategory.Send и получить преобразованные данные не является возможным (метод сразу отправляет сообщение и возвращает результат запроса, а не VkParameters)

**Comment by itsokto** [comment]
Не вижу проблемы сереализовать MessageSendParams в json и передать в execute

**Comment by itsokto** [comment]
@xeleoss получилось?

**Comment by ivanmem** [comment]
> @xeleoss получилось?

А я вижу проблемы. С клавиатурой, с template, с content_source. Они просто так не серриализуются, поэтому этот метод и создан.

**Comment by itsokto** [comment]
Ага, я понял. ВК не принимает вложенные объекты.

**Comment by ghost** [comment]
Актуально? @xeleoss

**Comment by ivanmem** [comment]
Не знаю актуально или нет, откроем потом заново если что.
