### ISSUE TITLE
VkNet.Exception.CannotBlacklistYourselfException: 

### ISSUE THREAD

**Issue by sharpenjoyer** [vknet/vk#1076]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. 
Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - [x] .net 4.0
  - [ ] .net 4.5
  - [ ] NETStandard2.0
  - [ ] другое. Указать строкой ниже.
  
2. Класс и метод в котором возникла проблема:
Friends.GetOnline
3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса:

```csharp
  var getfriendonline = api.Friends.GetOnline(new FriendsGetOnlineParams {Order = VkNet.Enums.SafetyEnums.FriendsOrder.Hints });
```

4. JSON ответа. Для удобства сбора этих данных подключите логи (https://github.com/vknet/vk/wiki/Logging):

```json
// i donk know я не знаю
```

5. Если в примере не указаны конкретные значения параметров запроса укажите их здесь:

6. PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Telegram Chat](https://img.shields.io/badge/Chat-Telegram-0F80C1.svg)](https://t.me/VkDotNet), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by sharpenjoyer** [comment]
my code: 
**var api = new VkApi();**
            api.Authorize(new ApiAuthParams{
                Login = login, Password = pass, ApplicationId = 7601835});
            var getfriendonline = api.Friends.GetOnline(new FriendsGetOnlineParams {Order = VkNet.Enums.SafetyEnums.FriendsOrder.Hints});

**Comment by itsokto** [comment]
Post an exception message for further investigation.
.net4.0 is no longer supported by VkNet from 1.55.0 btw.

**Comment by 1dNDN** [comment]
При получении ошибки 15 от вк (Access denied) имя исключения CannotBlacklistYourselfException.
