### ISSUE TITLE
NullReferenceException при обработке Message.Body

### ISSUE THREAD

**Issue by DartPower** [vknet/vk#1079]
Проект на:
.NET Framework v4.8
VkNet 1.56.0

(Ахтунг: Я не так идеально шарю даже в базовом C# ну и в целом ну такое себе кодер, но по опыту чую, что это может быть регрессия, ибо делал по примеру который должен работать.)

Референс ошибки:
https://github.com/dpteam/DPTTS/blob/03644248f5bde22cc102cfcc9e03359be86db923/DPTTS/Program.cs#L66

При отправке сообщения в паблик отладчик возвращает:
System.NullReferenceException: "Ссылка на объект не указывает на экземпляр объекта."

**Comment by DartPower** [comment]
Сконвертировал проект, теперь он на .NET Core 3.1
Ошибка не ушла, пробовал ещё на VkNet "1.57.0" (свежий билд)
Тоже самое

**Comment by DartPower** [comment]
Уточнение ошибки: 
VkNet.Model.GroupUpdate.GroupUpdate.Message.**get** вернул null.

**Comment by itsokto** [comment]
Вам нужен объект GroupUpdate.MessageNew.Message
Читайте документацию по объекту Message, текст сообщения находится в Text.

**Comment by q00Dree** [comment]
Жесть, я из за своей тупости всю ночь просидел и не мог понять в чем дело, на 5.126 пытался получить этот объект Message и все время получал null. Ошибку искал везде, но не в версии. Я, конечно же видел, что MessageNew не null, но по примеру кода 5 месячной давности хотелось(кто то знает почему? -я нет!) работать именно с объектом Message. 

Правильно ли я понимаю, что Message работает только до 5.103 ?

**Comment by itsokto** [comment]
@q00Dree да.
