### ISSUE TITLE
Exception в UnBanUser 

### ISSUE THREAD

**Issue by justmavi** [vknet/vk#1081]
В VK API и для разблокировки группы и юзеров в группе используется один метод - groups.unban. Чтобы разбанить группу, необходимо передать в userId отрицательное значение (-groupId). 
Но при передаче отрицательного значения в userId получаем Exception - "отрицательное значение. Parameter: userId". Если передать не отрицательное значение (просто id группы без -), то в этот раз получаем Exception - "юзера нет в черном списке", хотя это не юзер, а группа и она состоит в ЧС.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
