### ISSUE TITLE
Wall.get

### ISSUE THREAD

**Issue by Prowka** [vknet/vk#109]
Использую ваш репозиторий только что скаченный 
вызываю 
 ReadOnlyCollection<Post> a = _vk.Wall.Get(ownerId, out totalCount, 10);
Возникло исключение Ссылка на объект не указывает на экземпляр объекта

**Comment by CaCTuCaTu4ECKuu** [comment]
Версия API не подхватывается автоматически и приходиться подставлять ее внутри метода. Буду смотреть

**Comment by inyutin-maxim** [comment]
смотрите  ошибку #121
