### ISSUE TITLE
Сложно сказать)

### ISSUE THREAD

**Issue by AntonRls** [vknet/vk#1093]
Здраствуйте! Я написал бота ВК, с помощью вашей библиотеки, но дело в том, что к сожалению, я не могу скомпилить под ubuntu, дабы юзать на vds. Можете, пожалуйста, подсказать как это реализовать)

**Comment by AntonRls** [comment]
UPD:
Смотрите, с помощью проб и ошибок, я выяснил, что ошибка именно изза вашей библиотеки. В ubuntu я ввожу mono и выдаёт это 
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Russilka.Program' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
  --- End of inner exception stack trace ---
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Russilka.Program' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
  --- End of inner exception stack trace ---

**Comment by inyutin-maxim** [comment]
@AntonRls А почему выбор пал на моно а не dotnet core?

**Comment by AntonRls** [comment]
Я честно говоря не знаю, что первым попалось) У меня на ubuntu vds, по этому только вчера начал изучать его, если с donet core работает, то збс будет)

**Comment by AntonRls** [comment]
В можете, пожалуйста, кинуть гайд как юзать это, я прост щас погуглил, нечего не нашел)

**Comment by inyutin-maxim** [comment]
@AntonRls Есть несколько статей на хабре.
Есть несколько примеров в репе [здесь](https://github.com/vknet/vk/tree/develop/examples)
Есть чат с сообществом [здесь](https://t.me/VkDotNet)

**Comment by AntonRls** [comment]
Спасибо!
