### ISSUE TITLE
Расширение функционала vk script

### ISSUE THREAD

**Issue by ekuizhev** [vknet/vk#1094]
Было бы очень не плохо, если для метода [execute](https://vk.com/dev/execute) добавится поддержка функций, без них совсем тяжко. Делаю мини генерацию хеш суммы (для приложения вк мини апп) и вычисление хеша это ад. Так же было очень не плохо, если добавился бы логический оператор xor (^) вместе с побитовым сдвигом (>>>).

**Comment by inyutin-maxim** [comment]
@ekuizhev Доброго времени суток, боюсь расширение языка vkscript это задача для самого вк ([Завести задачу](https://vk.com/bugs?act=add&product=0))
