### ISSUE TITLE
ArgumentOutOfRangeException при вызове метода Authorize

### ISSUE THREAD

**Issue by GoltikRee** [vknet/vk#110]
Метод Authorize выбрасывает ArgumentOutOfRangeException при использовании
таких настроек:
`Settings settings = Settings.All | Settings.Offline`
В версии 1.0.16 ошибка отсутствует.

**Comment by azhidkov** [comment]
Fixed in https://github.com/vknet/vk/commit/65f1327ace0e66f2d6a93563236011427a51b014
