### ISSUE TITLE
Photo.Url и любые иные поля связанные с Uri возвращают System.NullReferenceException.

### ISSUE THREAD

**Issue by Jagerente** [vknet/vk#1116]
При обращению к полям Photo связанным со ссылкой на объект, программа выдаёт NullReferenceException, однако остальные поля работают как надо.

**Comment by inyutin-maxim** [comment]
> При обращению к полям Photo связанным со ссылкой на объект, программа выдаёт NullReferenceException, однако остальные поля работают как надо.

Поясните при каком запросе так происходит, и по возможности как отвечает VK. Многие поля в моделях только для обратной совместимости, и так как вк к версионированию относится халатно, приходится все это хранить в моделях

**Comment by Jagerente** [comment]
> 
> 
> > При обращению к полям Photo связанным со ссылкой на объект, программа выдаёт NullReferenceException, однако остальные поля работают как надо.
> 
> Поясните при каком запросе так происходит, и по возможности как отвечает VK. Многие поля в моделях только для обратной совместимости, и так как вк к версионированию относится халатно, приходится все это хранить в моделях

```CS
var photos = await Bot.Vk.Photo.GetAsync(new PhotoGetParams 
            { 
                OwnerId = oID, 
                AlbumId = VkNet.Enums.SafetyEnums.PhotoAlbumType.Id(aID),
            }
            );

            foreach (var photo in photos)
            {
                Console.WriteLine(photo.Url.ToString());
            }
```

Ошибка
```
System.NullReferenceException
```

Однако если делать через Photo.Sizes, то всё работает.
```CS
Console.WriteLine(photo.Sizes[photo.Sizes.Count-1],Url.ToString());
```

**Comment by inyutin-maxim** [comment]
> > > При обращению к полям Photo связанным со ссылкой на объект, программа выдаёт NullReferenceException, однако остальные поля работают как надо.
> > 
> > 
> > Поясните при каком запросе так происходит, и по возможности как отвечает VK. Многие поля в моделях только для обратной совместимости, и так как вк к версионированию относится халатно, приходится все это хранить в моделях
> 
> ```cs
> var photos = await Bot.Vk.Photo.GetAsync(new PhotoGetParams 
>             { 
>                 OwnerId = oID, 
>                 AlbumId = VkNet.Enums.SafetyEnums.PhotoAlbumType.Id(aID),
>             }
>             );
> 
>             foreach (var photo in photos)
>             {
>                 Console.WriteLine(photo.Url.ToString());
>             }
> ```
> 
> Ошибка
> 
> ```
> System.NullReferenceException
> ```
> 
> Однако если делать через Photo.Sizes, то всё работает.
> 
> ```cs
> Console.WriteLine(photo.Sizes[photo.Sizes.Count-1],Url.ToString());
> ```

Ну собственно это та ситуация об обратной совместимости, да, правильно использовать sizes, ниже представлен пример данных от вк
``` json
{
	"response": {
		"count": 62,
		"items": [
			{
				"album_id": -7,
				"date": 1302516221,
				"id": 247648259,
				"owner_id": -1,
				"has_tags": false,
				"sizes": [
					{
						"height": 0,
						"url": "https://sun9-32.u...1621/s_f15991c2.jpg",
						"type": "s",
						"width": 0
					},
					{
						"height": 0,
						"url": "https://sun9-67.u...1621/m_4228adaf.jpg",
						"type": "m",
						"width": 0
					},
					{
						"height": 0,
						"url": "https://sun9-76.u...1621/x_46426f27.jpg",
						"type": "x",
						"width": 0
					}
				],
				"text": "",
				"user_id": 100,
				"likes": {
					"user_likes": 0,
					"count": 286
				},
				"reposts": {
					"count": 2
				},
				"comments": {
					"count": 21
				},
				"can_comment": 1,
				"tags": {
					"count": 0
				}
			},
			{
				"album_id": -7,
				"date": 1302712950,
				"id": 248743686,
				"owner_id": -1,
				"has_tags": false,
				"sizes": [
					{
						"height": 0,
						"url": "https://sun9-61.u...2/-5/s_80529ba4.jpg",
						"type": "s",
						"width": 0
					},
					{
						"height": 0,
						"url": "https://sun9-66.u...2/-5/m_5fe2d21f.jpg",
						"type": "m",
						"width": 0
					},
					{
						"height": 0,
						"url": "https://sun9-11.u...2/-5/x_06bffe46.jpg",
						"type": "x",
						"width": 0
					}
				],
				"text": "",
				"user_id": 100,
				"likes": {
					"user_likes": 0,
					"count": 153
				},
				"reposts": {
					"count": 0
				},
				"comments": {
					"count": 48
				},
				"can_comment": 1,
				"tags": {
					"count": 0
				}
			}
		]
	}
}
```
