### ISSUE TITLE
Get post id by video id

### ISSUE THREAD

**Issue by NitayTubi** [vknet/vk#1119]
Hi, 
If I have the OwnerId and the PhotoId I can get the PostId by: 
```
var photo = api.Photo.GetById(new List<string>() { "-<OwnerId>_<PhotoId>" }, true);
var postId = photo.First().PostId;
```
But in a video post - how can I get the PostId by using the OwnerId and VideoId?
Thanks :)

**Comment by ghost** [comment]
@NitayTubi VK does not return the PostId field for the Video, only for the Photo

**Comment by Panuchi** [comment]
Тему за исчерпанием закрываю. 
The answer was given above.

**Comment by ghost** [comment]
Закрываю, ответ дан выше, ВК не возвращает PostId для объекта Video.
