### ISSUE TITLE
Истечение токена

### ISSUE THREAD

**Issue by ilya-vas** [vknet/vk#112]
Иногда выкидывает исключение access_token has expired
Вопрос: это так и должно быть?

**Comment by azhidkov** [comment]
По-моему время жизни токена 86400 секунд, т.е сутки. Или он чаще выбрасывается?
Там какой-то странный код проверки появился, возможно он выбрасывает.

**Comment by CaCTuCaTu4ECKuu** [comment]
Да, так происходит потому что токен выдается максимум на сутки, я добавил метод RegreshToken и ивент, котторый оповещает об этом, но откровенно говоря его нужно проверить тщательнее

**Comment by CaCTuCaTu4ECKuu** [comment]
В оригинале по моей задумке должно быть что-то типа
VkApi.onTokenExpires += MyMethod(VkApi api) { api.RefreshToken(); }

**Comment by ilya-vas** [comment]
Чаще не выбрасывается. Софт просто работает всё время)

**Comment by azhidkov** [comment]
Тогда, по-хорошему, нужно для простой авторизации просто перезапрашивать токен без возникновения события. А при двухфакторной авторизации, кидать событие чтобы пользователь ввёл код.

**Comment by ilya-vas** [comment]
Спасибо за ответы

**Comment by Dramacydal** [comment]
Думаю, это неправильно, что приложение на 1 коннекте сутки работает

**Comment by CaCTuCaTu4ECKuu** [comment]
@Dramacydal у вас RefreshToken() обновляет токен? Событие OnTokenExpires вызывается?

**Comment by CaCTuCaTu4ECKuu** [comment]
Если выводиться ошибка access_token has expired - это нормально и нужно переавторизоватся.
Метод RefreshToken в связке с OnTokenExpires работает правильно.
