### ISSUE TITLE
Отсутствие метода stories.save

### ISSUE THREAD

**Issue by kurwanator1337** [vknet/vk#1123]
Для работы с историями отсутствует метод для постинга из официальной документации stories.save (https://vk.com/dev/stories.save). 
Имеется класс VkNet.Model.RequestParams.Stories.GetPhotoUploadServerParams для получения сервера загрузки истории, сама история VkNet.Model.Attachments.Story, но нет функций для ее загрузки в VK.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
