### ISSUE TITLE
Работа с прокси

### ISSUE THREAD

**Issue by aspidov** [vknet/vk#113]
Возможна ли работа этой библиотеки через прокси-сервер?

**Comment by HarkBack** [comment]
Поддерживаю.

**Comment by CaCTuCaTu4ECKuu** [comment]
Сейчас нет, но думаю когда-то будет реализовано

**Comment by HarkBack** [comment]
А если я в класс WebCall к конструктор добвлю настройки прокси для HttpWebRequest:
Request.Proxy = new WebProxy( proxyHost, proxyPort );
с последующей привязкой к другим методам, то это будет работать (теоретически)?

**Comment by HarkBack** [comment]
......работает.

**Comment by CaCTuCaTu4ECKuu** [comment]
Добавим
18 дек. 2015 г. 13:46 пользователь "EFLFE" <notifications@github.com>
написал:

**Comment by HarkBack** [comment]
Спасибо

**Comment by CaCTuCaTu4ECKuu** [comment]
Да это вам спасибо, а если пулл реквест пришлете и в библиотеку встроете
сразу (VkApi) то еще лучше будет

**Comment by HarkBack** [comment]
Сделаю, если закончу тест. Иногда сайт выдает ошибку 400. Тут или прокси не рабочие, или я что то не дописал в коде.

**Comment by HarkBack** [comment]
Делаю пулл реквест..

**Comment by CaCTuCaTu4ECKuu** [comment]
#158 Проверил, по коду выглядит в целом хорошо (может если пересмотреть в студии какие-то косметические изменения потом сделаются). Отличная работа!

**Comment by HarkBack** [comment]
Спасибо) Я правда только сейчас понял что у меня табуляция пробелами, из-за чего так много изменённых строк кода.

**Comment by digitallez** [comment]
Не работает прокси с NTLM авторизацией. Да и вообще, прокси авторизации что-то не видать.
Заработает если добавите в конструкторе `WebCall` перед `Result = new WebCallResult(url, cookies);` вот такой кусочек:
`if (Request.Proxy != null)
            {
                Request.Proxy.Credentials = CredentialCache.DefaultCredentials;
            }`
