### ISSUE TITLE
Сделать реализацию подписок на лонгпул события (группам и юзерам)!!!

### ISSUE THREAD

**Issue by ivanmem** [vknet/vk#1133]
Сделать что-то типо OnNewUpdates и OnNewUserUpdates. 
Чтобы при подписке на это событие можно было получать обновления из лонгпула. Это должно конфигурироваться как минимум с возможностью указать (Ts для сообществ, Pts для юзера)/Wait (не обязательно указывать, по умолчанию должно само определять, Wait = 25). 

Так же нужна будет подписка на ошибки OnNewUpdatesExceptions и OnNewUserUpdatesExceptions  .

**Comment by itsokto** [comment]
#740

**Comment by ivanmem** [comment]
Для групп https://github.com/vknet/vk/pull/1565

**Comment by ivanmem** [comment]
Для пользователей https://github.com/vknet/vk/pull/1587
