### ISSUE TITLE
Не прикрепляется ссылка в комментарий (Wall.CreateComment)

### ISSUE THREAD

**Issue by salicesmove** [vknet/vk#1144]
Не получается отправить комментарий с VkNet.Model.Attachments.Link
```
vkClient.Wall.CreateComment(new WallCreateCommentParams
            {
                OwnerId = -groupId,
                PostId = postId,
                Attachments = new List<VkNet.Model.Attachments.MediaAttachment>
                {
                   new VkNet.Model.Attachments.Link
                   {
                       Uri = new Uri("https://www.google.com"),
                       Title = "title",
                       Description = "desc",
                   }
                }
            });
```
Выдает исключение 
![image](https://user-images.githubusercontent.com/38703163/108718516-8f1eb880-752f-11eb-8932-26c3b8ee7d9c.png)
Если в параметры указать еще и Message, то комментарий запостится, но только с этим сообщением, без ссылки. В чем может быть проблема? При этом если передать эту же самую ссылку в Attachements для метода Wall.Post, то все запостится как надо, даже без Message. 
Заранее спасибо.
VkNet.1.60.0
.NET Framework 4.7.2

**Comment by y0ung3r** [comment]
Судя по документации VK API, метод createComment в поле attachments не поддерживает прикрепление ссылок. Очень странное поведение. Я делаю такой вывод из того, что, например, в https://vk.com/dev/wall.post указано, как прикреплять ссылки в виде url, а в createComment об этом ни слова. Конечно, это не показатель, но есть еще кое-что: я отладил ваш код и выяснил, что библиотека отрабатывает свой код как надо, но от VK API уже приходит ошибка в которой сказано, что раз Attachments пустой, нужно указать поле Message (Attachments, естественно, не пустой, но сервер обрабатывает его как пустой). Поэтому и возникает исключение приведенное вами.
Это точно косяк VK API и пока разработчики ВКонтакте не исправят эту проблему, исключение так и будет появляться.

Я создал тикет в баг-трекере ВК, отслеживать его состояние можно тут: https://vk.com/bug291440

**Comment by y0ung3r** [comment]
Обратите внимание на то, как VkNet спарсил указанные вами данные:
![image](https://user-images.githubusercontent.com/55300023/108956556-b8eff080-7691-11eb-8846-aacad04509a3.png)

Точно также эти данные парсит VK API на странице с документацией:
![image](https://user-images.githubusercontent.com/55300023/108956780-17b56a00-7692-11eb-87bc-e82d03778832.png)

**Comment by salicesmove** [comment]
Спасибо за ответ! Видел документацию, но тоже решил, что странное поведение и возможно недоработка. 
Будем ждать ответа от ВК.

**Comment by y0ung3r** [comment]
Кто то из сотрудников ВК сменил в баг-трекере метку "недоработка" на "пожелание", поэтому вывод такой: это, по их мнению, фича. А если фича, то расширять метод API они вряд ли будут (я думаю, что не будут вовсе).

В общем, ошибки со стороны VkNet никакой нет. То, что вам приходит исключение - это нормально. Просто пользуйтесь вложениями в этом методе в соответствии с документацией VK API.
