### ISSUE TITLE
Отсутствие audio_message в  MessageGetHistoryAttachmentsParams.MediaType 

### ISSUE THREAD

**Issue by jraiver** [vknet/vk#1145]
![image](https://user-images.githubusercontent.com/51187062/108867083-df684a00-7605-11eb-8673-4b08dc83d2ee.png)
![image](https://user-images.githubusercontent.com/51187062/108867192-fdce4580-7605-11eb-8398-471e126df735.png)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
