### ISSUE TITLE
Зависание при авторизации

### ISSUE THREAD

**Issue by shizzoff** [vknet/vk#1148]
1. Target для .NET используемый в проекте:
  - [x] .net 4.5
  - [ ] NETStandard2.0
  - [ ] другое. Указать строкой ниже.
  
2. Класс и метод в котором возникла проблема: VkApi.Authorize

3. Пример кода:

```csharp
  private void button1_Click(object sender, EventArgs e)
        {
            var api = new VkApi();

            api.Authorize(new ApiAuthParams
            {
                ApplicationId = 2685278,
                Login = textBox1.Text,
                Password = textBox2.Text,
                Settings = Settings.All
            });
            MessageBox.Show(api.Token);
        }
```

4. JSON ответа.:

Вместо ответа, форма в которой проходила авторизация зависает. Ждать не вариант, ибо даже после 5 минут ожидания никакого ответа от функции нету (программа застывает на ней).

**Comment by inyutin-maxim** [comment]
**Спасибо за проделанную работу**
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
