### ISSUE TITLE
Ошибка в поле класса

### ISSUE THREAD

**Issue by BlueXTX** [vknet/vk#1151]
1. Класс и метод в котором возникла проблема: MessageSendParams
2. RandomId должен быть int64 ('System.Nullable<long>'), согласно документации VK - https://vk.com/dev/bots_docs_2?f=3.%2B%D0%A1%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%2B%D0%BE%D1%82%2B%D0%B1%D0%BE%D1%82%D0%B0
3. Пример кода для воспроизведения проблемы:

```csharp
  _vkApi.Messages.Send(new MessagesSendParams
                    {
                        RandomId = (long) 100 // Cannot convert source type 'long' to target type 'System.Nullable<int>'
                    });
```

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
