### ISSUE TITLE
В методе VkApi.Messages.Delete отсутствуют необходимые параметры

### ISSUE THREAD

**Issue by Rogogomogofl** [vknet/vk#1165]
Согласно официальной документации https://vk.com/dev/messages.delete для удаления сообщений в групповой беседе необходимы параметры conversation_message_ids и peer_id, которые отсутствуют в библиотечной функции VkApi.Messages.Delete

**Comment by sampletext32** [comment]
Эта Issue уже решена.

```csharp
private IDictionary<ulong,bool> Delete(
    IEnumerable<ulong> messageIds, 
    IEnumerable<ulong> conversationMessageIds = null, 
    ulong? PeerId = null, 
    bool? spam = null, 
    ulong? groupId = null, 
    bool? deleteForAll = null)
in class MessagesCategory
```

Метод принимает conversationMesasgeIds и peerId, которые и указаны в Issue.
