### ISSUE TITLE
Перестала работать загрузка аудио файлов 

### ISSUE THREAD

**Issue by VINChe1990** [vknet/vk#117]
var client = new WebClient();

client.DownloadFileCompleted += delegate (object sender, AsyncCompletedEventArgs args)
{
 if (args.Error != null)
 {
  ExceptionHandler.СatchError(args.Error);
 }

 if (args.Cancelled)
{
 return;
}
};

client.DownloadFileAsync(URI, SAVE_FILE_PATH);

StackTrace:

System.Net.WebException: Исключение во время запроса WebClient. ---> System.ArgumentException: Путь содержит недопустимые знаки.
   в System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   в System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   в System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   в System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)

**Comment by VINChe1990** [comment]
Подскажите как теперь воспроизвести или скачать файл по Uri

**Comment by Dramacydal** [comment]
это у тебя локально с путем проблемы

**Comment by VINChe1990** [comment]
Спасибо, разобрался. Мой косяк
