### ISSUE TITLE
Символы, вместо кириллицы в ответ на Wall.GetById

### ISSUE THREAD

**Issue by titarenko-alexander** [vknet/vk#1171]
1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  -net.5.0
2. Класс и метод в котором возникла проблема:
Wall, GetById
3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса:

```csharp
  VkNet.VkApi vk = new();
            vk.Authorize(new ApiAuthParams()
            {
                Login = "xxxxxxxx",
                Password = "xxxxxxx",
                AccessToken = "xxxxxxxx"
            });
            var post = vk.Wall.GetById(new[] { "-39786657_92161", "-184661592_209831" });
            System.Console.WriteLine(post.WallPosts[0].Text);
            System.Console.WriteLine((post.WallPosts[1].Text));
```
Вывод:  
#soundclown
РЁРѕРє РєРѕРЅС‚РµРЅС‚!!!рџрџрџрџ

Сама по себе кириллица нормально выводится, пару дней назад всё работало.

И несколько дней назад появилась ошибка No data is available for encoding 1251, была исправлена добавлением Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); Возможно, это как-то связано с этими символами.

**Comment by titarenko-alexander** [comment]
Пока откатился до 1.63.0, тут всё работает отлично.

**Comment by guhbap** [comment]
```
static string tonormal(string input){

Encoding utf8 = Encoding.GetEncoding("UTF-8");
Encoding win1251 = Encoding.GetEncoding("Windows-1251");
byte[] utf8Bytes = win1251.GetBytes(input);
byte[] win1251Bytes = Encoding.Convert(utf8, win1251, utf8Bytes);
return win1251.GetString(win1251Bytes);
    }
```
Этот метод изменяет непонятные символы на нормальную кириллицу, Пока не пофиксят можно с помощью него делать

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
