### ISSUE TITLE
Cannot find variable 'm_domainTable' under Mono 3.2.8+dfsg-4ubuntu4

### ISSUE THREAD

**Issue by aleksandrbogdanov** [vknet/vk#118]
Из-за использования деталей реализации [CookieContainer](https://github.com/vknet/vk/blob/49207c16df020277cc49629a2bd6f6a30c7d5ec2/VkNet/Utils/Cookies.cs#L31) - библиотека не работает на mono (ни с авторизацией по email, ни по токену, что странно).

подробнее: http://stackoverflow.com/questions/29533534/cookiecontainer-mishap

Предлагаю ввести проверку версии VM в методе BugFixCookieDomain.

**Comment by CaCTuCaTu4ECKuu** [comment]
А есть вообще линуксоиды на постоянной основе кто-то? Было бы отлично получить пулл реквест с исправляшкой.
Насколько я помню CookieContainer это ключевая часть WebRequest, там еще вроде можно использовать CookieCollection вместо контейнера и все, кажется, работает, но это нужно проверить под Mono если я заменю

**Comment by inyutin-maxim** [comment]
У меня дома на ноуте kubuntu 15.10 второй системой стоит. до выходных нет времени исправить. поправь, а я вечером проверю

**Comment by CaCTuCaTu4ECKuu** [comment]
Я не могу понять что вообще делает метод BugFixCookieDomain. Что именно делается, не гуглится по-быстрому CookieContainer из моно и не могу глянуть какие поля там есть, я так понял нужно добавить что-то вроде #if Mono и там вместо m_domainTable указать то, что в моновском контейнере для перечисления, но опять таки  у меня есть в своей либе такой метод:
>public static CookieCollection parseCookies(CookieContainer _cookies)
            {
                CookieCollection res = new CookieCollection();
                FieldInfo fiDomainTable = typeof(CookieContainer).GetField("m_domainTable", BindingFlags.NonPublic | BindingFlags.Instance);
                Hashtable domainTable = (Hashtable)fiDomainTable.GetValue(_cookies);
                foreach (string uri in domainTable.Keys)
                {
                    object obPathList = domainTable[uri];
                    FieldInfo fiList = obPathList.GetType().GetField("m_list", BindingFlags.NonPublic | BindingFlags.Instance);
                    SortedList pathList = (SortedList)fiList.GetValue(obPathList);
                    foreach (string key in pathList.Keys)
                    {
                        CookieCollection cookies = (CookieCollection)pathList[key];
                        foreach (Cookie cookie in cookies)
                            res.Add(cookie);
                    }
                }
                return res;
            }

Но я не понимаю что делает BuxFix-ер этот

**Comment by aleksandrbogdanov** [comment]
Я полагаю это попытка решить что-то наподобие [этого бага](https://social.msdn.microsoft.com/Forums/en-US/1297afc1-12d4-4d75-8d3f-7563222d234c/httpwebrequest-incorrectly-works-with-cookiecontainer?forum=netfxnetcom), но в Mono его нет, поэтому давайте просто добавим #if Mono return; #endif и дело с концом.

**Comment by CaCTuCaTu4ECKuu** [comment]
@aleksandrbogdanov А у вас есть возможность сделать это и отправить пулл реквест или просто отписать здесь что именно должно получиться? А я бы проверил это под студией и если все норм в следующем релизе NuGet бага уже не будет

**Comment by inyutin-maxim** [comment]
@aleksandrbogdanov  mono 4.2.1 полет нормальный, извините ставить mono 3.2.8 нет желания чтобы проверить. падений я не обнаружил
код для теста:
``` csharp
var vk = new VkApi();
vk.Authorize(appID, email, pass, scope);
var counts = vk.Groups.GetById(new List<string>{"103292418"});
Console.WriteLine(counts[0].Name);
Console.ReadLine ();
```

**Comment by aleksandrbogdanov** [comment]
Mono 4+ смержилось с MS .NET, видимо это приватное поле появилось в том классe и хак снова заработал.

**Comment by inyutin-maxim** [comment]
так проблема все таки актуальна? Если вам не сложно внесите исправления, и пришлите пулреквест и мы с удовольствием его примем. 
PS. Вам проще будет проверить. Спасибо

**Comment by inyutin-maxim** [comment]
Считаю что задачу можно закрыть так как в mono 4.x проблема. Если у кого то есть возражения то внимательно слушаю :)
