### ISSUE TITLE
Русские буквы в названиях полей

### ISSUE THREAD

**Issue by sampletext32** [vknet/vk#1197]
[Файл](https://github.com/vknet/vk/blob/abfee66aab9da570d5e32c0d8075aa285bbe491e/VkNet/Model/Topic.cs)

Rider показывает, что "Created" написано с русской буквой 'С'. 
Я почти 100% уверен, что изменение сломает совместимость, так что оставлю в виде Issue.

Список файлов, в которых было замечено похожее поведение. [По необходимости дополню]
1) [Models/Currency](https://github.com/vknet/vk/blob/abfee66aab9da570d5e32c0d8075aa285bbe491e/VkNet/Model/Currency.cs)
2) [Models/Audio/AudioCatalogAudioAds](https://github.com/vknet/vk/blob/abfee66aab9da570d5e32c0d8075aa285bbe491e/VkNet/Model/Audio/AudioCatalogAudioAds.cs)

**Comment by inyutin-maxim** [comment]
@sampletext32 Добрый день!
Если у вас есть свободное время и желание нанести непоправимую пользу, я предлагаю текущие поля пометить атрибутом Obsolete с ошибкой компиляции, а рядом сделать правильные поля.
ну и прислать PR
