### ISSUE TITLE
Не работает метод WallCategory.Get

### ISSUE THREAD

**Issue by amerx** [vknet/vk#121]
Не работает метод WallCategory.Get для стены группы (owner_id передаю правильно, с минусом).
Падает response["count"]

**Comment by azhidkov** [comment]
Скорее всего падает, т.к. код пытается разбирать старый формат API.

**Comment by Inyutin** [comment]
Приведите пожалуйста пример, у меня не получилось воспроизвести пробовал так: _api.Wall.Get(-103292418,out count);

**Comment by amerx** [comment]
Именно сейчас к сожалению не смогу, т.к. на работе, и доступ к vk закрыт. Вызываю так: ReadOnlyCollection<Post> posts = _api.Wall.Get(-Group.Id, out poststotalcount); А можно у вас попросить скинуть исходники метода? я пробовал два варианта, и ни один не работает, вот они:1.) [Pure]public ReadOnlyCollection<Post> Get(long ownerId, out int totalCount, int? count = null, int? offset = null, WallFilter filter = WallFilter.All) { var parameters = new VkParameters { { "owner_id", ownerId }, { "count", count }, { "offset", offset }, { "filter", filter.ToString().ToLowerInvariant() } };VkResponseArray response = _vk.Call("wall.get", parameters);totalCount = response[0];return response.Skip(1).ToReadOnlyCollectionOf<Post>(r => r); }2.) [Pure] [ApiVersion("5.9")] public ReadOnlyCollection<Post> Get(long ownerId, out int totalCount, int? count = null, int? offset = null, WallFilter filter = WallFilter.All) { VkErrors.ThrowIfNumberIsNegative(() => count); VkErrors.ThrowIfNumberIsNegative(() => offset); if (filter == WallFilter.Suggests && ownerId >= 0) throw new ArgumentException("OwnerID must be negative in case filter equal to Suggests", "ownerId");var parameters = new VkParameters { { "owner_id", ownerId }, { "count", count }, { "offset", offset }, { "filter", filter.ToString().ToLowerInvariant() } };VkResponse response = _vk.Call("wall.get", parameters);totalCount = response["count"];VkResponseArray items = response["items"]; return items.ToReadOnlyCollectionOf<Post>(r => r);} 05.10.2015, 16:56, "[Raven]" <notifications@github.com>:Приведите пожалуйста пример, у меня не получилось воспроизвести пробовал так: _api.Wall.Get(-103292418,out count);—Reply to this email directly or view it on GitHub.

**Comment by Inyutin** [comment]
Код в API
```CSharp
	/// <summary>
        /// Возвращает список записей со стены пользователя или сообщества. 
        /// </summary>
        /// <param name="ownerId">Идентификатор пользователя. Чтобы получить записи со стены группы (публичной страницы, встречи), укажите её идентификатор 
        /// со знаком "минус": например, owner_id=-1 соответствует группе с идентификатором 1.</param>
        /// <param name="totalCount">Общее количество записей на стене.</param>
        /// <param name="count">Количество сообщений, которое необходимо получить (но не более 100).</param>
        /// <param name="offset">Смещение, необходимое для выборки определенного подмножества сообщений.</param>
        /// <param name="filter">Типы сообщений, которые необходимо получить (по умолчанию возвращаются все сообщения).</param>
        /// <returns>В случае успеха возвращается запрошенный список записей со стены.</returns>
        /// <remarks>
        /// Страница документации ВКонтакте <see href="http://vk.com/dev/wall.get"/>.
        /// </remarks>
        [Pure]
        [ApiVersion("5.9")]
        public ReadOnlyCollection<Post> Get(long ownerId, out int totalCount, int? count = null, int? offset = null, WallFilter filter = WallFilter.All)
        {
            VkErrors.ThrowIfNumberIsNegative(() => count);
			VkErrors.ThrowIfNumberIsNegative(() => offset);
			if (filter == WallFilter.Suggests && ownerId >= 0)
		        throw new ArgumentException("OwnerID must be negative in case filter equal to Suggests", "ownerId");

	        var parameters = new VkParameters { { "owner_id", ownerId }, { "count", count }, { "offset", offset }, { "filter", filter.ToString().ToLowerInvariant() } };

			VkResponse response = _vk.Call("wall.get", parameters);

            totalCount = response["count"];

            VkResponseArray items = response["items"];
			return items.ToReadOnlyCollectionOf<Post>(r => r);
        }
```

Я вызываю код следующим образом:
```CSharp
	int count;
	var posts = _api.Wall.Get(-103292418, out count);
```

Единственное что приходит в голову по вашей проблеме так это что у вас в Group.Id уже отрицательное число и поэтому происходит ошибка

**Comment by amerx** [comment]
Большое спасибо, сегодня вечером попробую!  05.10.2015, 17:59, "[Raven]" <notifications@github.com>:Код в API    /// <summary>
        /// Возвращает список записей со стены пользователя или сообщества. 
        /// </summary>
        /// <param name="ownerId">Идентификатор пользователя. Чтобы получить записи со стены группы (публичной страницы, встречи), укажите её идентификатор 
        /// со знаком "минус": например, owner_id=-1 соответствует группе с идентификатором 1.</param>
        /// <param name="totalCount">Общее количество записей на стене.</param>
        /// <param name="count">Количество сообщений, которое необходимо получить (но не более 100).</param>
        /// <param name="offset">Смещение, необходимое для выборки определенного подмножества сообщений.</param>
        /// <param name="filter">Типы сообщений, которые необходимо получить (по умолчанию возвращаются все сообщения).</param>
        /// <returns>В случае успеха возвращается запрошенный список записей со стены.</returns>
        /// <remarks>
        /// Страница документации ВКонтакте <see href="http://vk.com/dev/wall.get"/>.
        /// </remarks>
        [Pure]
        [ApiVersion("5.9")]
        public ReadOnlyCollection<Post> Get(long ownerId, out int totalCount, int? count = null, int? offset = null, WallFilter filter = WallFilter.All)
        {
            VkErrors.ThrowIfNumberIsNegative(() => count);
            VkErrors.ThrowIfNumberIsNegative(() => offset);
            if (filter == WallFilter.Suggests && ownerId >= 0)
                throw new ArgumentException("OwnerID must be negative in case filter equal to Suggests", "ownerId");

            var parameters = new VkParameters { { "owner_id", ownerId }, { "count", count }, { "offset", offset }, { "filter", filter.ToString().ToLowerInvariant() } };

            VkResponse response = _vk.Call("wall.get", parameters);

            totalCount = response["count"];

            VkResponseArray items = response["items"];
            return items.ToReadOnlyCollectionOf<Post>(r => r);
        }Я вызываю код следующим образом:    int count;
    var posts = _api.Wall.Get(-103292418, out count);Единственное что приходит в голову по вашей проблеме так это что у вас в Group.Id уже отрицательное число и поэтому происходит ошибка—Reply to this email directly or view it on GitHub.

**Comment by amerx** [comment]
Добрый день!
все, понял в чем проблема, возвращался json формата ниже 5.0.
Добавил в строку VkResponse response = _vk.Call("wall.get", parameters);
номер версии и заработало:
VkResponse response = _vk.Call("wall.get", parameters, false, "5.9");

а как у вас без этого работает?


05.10.2015, 17:59, "[Raven]" <notifications@github.com>:
> Код в API
>
> /// <summary> /// Возвращает список записей со стены пользователя или сообщества. /// </summary> /// <param name="ownerId">Идентификатор пользователя. Чтобы получить записи со стены группы (публичной страницы, встречи), укажите её идентификатор /// со знаком "минус": например, owner_id=-1 соответствует группе с идентификатором 1.</param> /// <param name="totalCount">Общее количество записей на стене.</param> /// <param name="count">Количество сообщений, которое необходимо получить (но не более 100).</param> /// <param name="offset">Смещение, необходимое для выборки определенного подмножества сообщений.</param> /// <param name="filter">Типы сообщений, которые необходимо получить (по умолчанию возвращаются все сообщения).</param> /// <returns>В случае успеха возвращается запрошенный список записей со стены.</returns> /// <remarks> /// Страница документации ВКонтакте <see href="http://vk.com/dev/wall.get"/>. /// </remarks> [Pure] [ApiVersion("5.9")] public ReadOnlyCollection<Post> Get(long ownerId, out int totalCount, int? count = null, int? offset = null, WallFilter filter = WallFilter.All) { VkErrors.ThrowIfNumberIsNegative(() => count); VkErrors.ThrowIfNumberIsNegative(() => offset); if (filter == WallFilter.Suggests && ownerId >= 0) throw new ArgumentException("OwnerID must be negative in case filter equal to Suggests", "ownerId"); var parameters = new VkParameters { { "owner_id", ownerId }, { "count", count }, { "offset", offset }, { "filter", filter.ToString().ToLowerInvariant() } }; VkResponse response = _vk.Call("wall.get", parameters); totalCount = response["count"]; VkResponseArray items = response["items"]; return items.ToReadOnlyCollectionOf<Post>(r => r); }
>
> Я вызываю код следующим образом:
>
> int count; var posts = _api.Wall.Get(-103292418, out count);
>
> Единственное что приходит в голову по вашей проблеме так это что у вас в Group.Id уже отрицательное число и поэтому происходит ошибка
>
> —
> Reply to this email directly or view it on GitHub.

05.10.2015, 17:59, "[Raven]" <notifications@github.com>:

**Comment by Inyutin** [comment]
Вполне возможно, что у меня работает по той причине, что у меня Newtonsoft.Json последней версии, я обновлял nuget пакеты, я попробую завести новый проект не обновляя пакеты и проверить, о результатах сообщу, спасибо за обратную связь.

**Comment by amerx** [comment]
Хорошо, понятно. Вам спасибо за ваш API!  06.10.2015, 13:27, "inyutin_maxim" <notifications@github.com>:Вполне возможно, что у меня работает по той причине, что у меня Newtonsoft.Json последней версии, я обновлял nuget пакеты, я попробую завести новый проект не обновляя пакеты и проверить, о результатах сообщу, спасибо за обратную связь.—Reply to this email directly or view it on GitHub.

**Comment by Inyutin** [comment]
![image](https://cloud.githubusercontent.com/assets/1781005/10304004/21c27696-6c20-11e5-9fcc-2c91ca237b8e.png)
Да, действительно на старой версии Newtonsoft.Json падает в этом месте

**Comment by CaCTuCaTu4ECKuu** [comment]
Немного наблюдений из разбора ошибок.
Версия VkApi, которая указывается перед методом [ApiVersionXX] не всегда подхватывается при компиляции и, соответственно, методы потом вызываются как без версии вообще, что приводит к множеству непонятных ошибок. У меня при одинаковых настройках среды обычно такого не бывает, я даже не знаю почему именно это происходит.
## Советую при возникновении ошибки в первую очередь 
проверить через HTTPAnalyzer или в исходниках (сформированный запрос перед отправлением) проверить отправляется ли на сервер ВК версия API

**Comment by amerx** [comment]
Хорошо, спасибо, буду иметь ввиду! 06.10.2015, 21:06, "CaCTuCaTu4ECKuu" <notifications@github.com>:Немного наблюдений из разбора ошибок. Версия VkApi, которая указывается перед методом [ApiVersionXX] не всегда подхватывается при компиляции и, соответственно, методы потом вызываются как без версии вообще, что приводит к множеству непонятных ошибок. У меня при одинаковых настройках среды обычно такого не бывает, я даже не знаю почему именно это происходит.Советую при возникновении ошибки в первую очередьпроверить через HTTPAnalyzer или в исходниках (сформированный запрос перед отправлением) проверить отправляется ли на сервер ВК версия API—Reply to this email directly or view it on GitHub.

**Comment by amerx** [comment]
Добрый день!У меня такой вопрос, что если я выхожу в интернет через прокси сервер?Ваш API это позволяет? или нужны доработки?Если нужны, то подскажите плиз. где что сделать? пробовал в модуле WebCall, HttpWebRequest задавать Credentials: Request = (HttpWebRequest)WebRequest.Create(url); Request.Accept = "text/html"; Request.UserAgent = "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)"; Request.CookieContainer = cookies.Container; NetworkCredential cred = new NetworkCredential(); cred.UserName = "amerkhanov"; cred.Password = "******"; cred.Domain = "******"; Request.Credentials = cred;Result = new WebCallResult(url, cookies);Но падает та же ошибка: Удаленный сервер возвратил ошибку: (407) Требуется проверка подлинности посредника.Ещё нюанс, у меня доступ к vk закрыт, и я веб запрос немного переделал(делаю запрос с сайта аномайзера). Спасибо за помощь!  06.10.2015, 21:06, "CaCTuCaTu4ECKuu" <notifications@github.com>:Немного наблюдений из разбора ошибок. Версия VkApi, которая указывается перед методом [ApiVersionXX] не всегда подхватывается при компиляции и, соответственно, методы потом вызываются как без версии вообще, что приводит к множеству непонятных ошибок. У меня при одинаковых настройках среды обычно такого не бывает, я даже не знаю почему именно это происходит.Советую при возникновении ошибки в первую очередьпроверить через HTTPAnalyzer или в исходниках (сформированный запрос перед отправлением) проверить отправляется ли на сервер ВК версия API—Reply to this email directly or view it on GitHub.

**Comment by inyutin-maxim** [comment]
Исправил, параметры вынес в отдельный класс, создал общий возвращаемый тип для Wall.Get. Закрываю задачу

**Comment by amerx** [comment]
Спасибо! 12.11.2015, 18:12, "inyutin-maxim" <notifications@github.com>:Closed #121.—Reply to this email directly or view it on GitHub.
