### ISSUE TITLE
Постоянно выкидывает exception - не верный логин или пароль

### ISSUE THREAD

**Issue by Hromon** [vknet/vk#1214]
- [x] NETStandard2.0
  
Класс и метод в котором возникла проблема:
VkApi.Authorize()

Верность паролей и логинов проверяли сотню раз.

Пример кода:
![image](https://user-images.githubusercontent.com/29508584/141084338-59834a78-933e-418d-8ac4-2cb4cf1115ae.png)

**Comment by Implx** [comment]
Такая же проблема, в двух приложениях слетела авторизация, надо смотреть...

**Comment by CaCTuCaTu4ECKuu** [comment]
Из того что я отследил
VkNet\Infrastructure\Authorization\ImplicitFlow\ImplicitFlow.cs
CreateAuthorizeUrl создает ссылку при переходе 

AbstractAuthorizationForm.ExecuteAsync при посте получает окно с запросом разрешения доступа для приложения (на узбекском языке кста), uri ответа - https://oauth.vk.com/authorize?client_id={AppID}&redirect_uri={uri}&response_type=token&scope=140492255&v=5.126&state=&display=mobile&m=7

ImplicitFlow.NextStepAsync воспринимает это как страницу неверного логина и пароля

Я немного не вкурсе что и как там должно быть в этом коде поэтому ковырять не хочу, есть мысли что сломалось?
Похоже когда писали все кейсы не обработали т.к. у человека что писал возможно не всплывало

Насчет разрешения, если пройти по ссылке ручками и разрешить приложению доступ то токен в браузере прилетает, но при повторной авторизации та же ошибка, но если снова перейти по ссылке в браузере то окно появилось другое - с списком прав и просьбой разрешить их все, не уверен что и почему т.к. приложение то у меня уже авторизовано, так сказать

Версия vknet - последняя сборка из гита
Приложение netcoreapp3.1 (net5.0 по идее)

**Comment by vborovin** [comment]
Здесь обсуждалось, мне помогло
https://github.com/vknet/vk/issues/997#issuecomment-959415142

**Comment by artem54325** [comment]
@vborovin Попробовал добавить ошибка осталось. Могу лишь авторизоваться через token(если руками вписать его) в AccessToken

**Comment by y0ung3r** [comment]
После того, как форма отправляется, должна появляться страница с подтверждением передаваемых приложению прав:
![image](https://user-images.githubusercontent.com/55300023/151427675-2e352e40-839e-43f6-8fa3-b2bf335c6c55.png)
С формы, соответственно, берется Action кнопки "Разрешить" и авторизация завершается

Но появляется это:
![image](https://user-images.githubusercontent.com/55300023/151427797-8fbc6029-ec88-41bc-8bf0-938536d582e8.png)

Код, который находится у нас в библиотеке полностью правильный, там даже исправлять нечего. ВК опять что то поломали и у меня даже нет идей как с этим бороться

**Comment by ghost** [comment]
Перенесено в #997
