### ISSUE TITLE
При получение списка групп пользователя, все группы пустые

### ISSUE THREAD

**Issue by artem54325** [vknet/vk#1217]
Авторизируюсь через ссылку (потому что через логин и пароль не работает):
https://oauth.vk.com/authorize?client_id=*&display=page&redirect_uri=https://oauth.vk.com/blank.html&scope=270338(wall|groups)&response_type=token&v=5.52
Вписываю токен и получаю список групп:

```
                   api.Authorize(new ApiAuthParams
                    {
                        ApplicationId = *,
                        AccessToken = "***",
                    });
                    var groups = api.Groups.Get(new GroupsGetParams
                    {
                        Fields = GroupsFields.Description,
                    }, true);
```

                 Но каждый раз список групп состоит только из ID без названия и описания.
                 Что может быть не так? Почему названия нету?

**Comment by ablearthy** [comment]
В документации [сказано](https://dev.vk.com/method/groups.get), что дополнительные поля возвращаются только, если передаётся `extended=1`. Возможно, стоит написать 
```
var groups = api.Groups.Get(new GroupsGetParams { Fields = GroupsFields.Description, Extended = true }, true);
```

**Comment by ghost** [comment]
> В документации [сказано](https://dev.vk.com/method/groups.get), что дополнительные поля возвращаются только, если передаётся `extended=1`. Возможно, стоит написать
> 
> ```
> var groups = api.Groups.Get(new GroupsGetParams { Fields = GroupsFields.Description, Extended = true }, true);
> ```

@inyutin-maxim можно закрыть, без параметра extended=1 возвращается только id групп.
