### ISSUE TITLE
Нигде не могу найти как установить превью для gif

### ISSUE THREAD

**Issue by mnxamoto** [vknet/vk#1218]
Когда загружаю gif в сообщения, то вместо превью белая картинка.
В результате выполнения функции Docs.Save возвращается объект, формат которого описан на данной странице https://vk.com/dev/objects/doc и у него есть поле preview, но не пойму как задать это поле самому или хотя бы получить в результате выполнения функции Docs.Save объект со сформированным полем preview.

У gif, которые я беру с сайта изначально отсутствует превью.
[Пример gif](https://upload-os-bbs.hoyolab.com/upload/2021/12/03/1015537/928630b392dbcaf8e06f098b7d97db04_8471697984390696722.gif?x-oss-process=image/resize,s_740/quality,q_80/auto-orient,0/interlace,1/format,gif)

**Comment by ghost** [comment]
@mnxamoto в методе нигде нельзя установить превью, но я проверил, с вашей гифкой всё в порядке, и в вк присутствует превью. Не знаю в чём у вас была проблема, но делал так:  https://github.com/vknet/vk/discussions/1104

**Comment by ghost** [comment]
Закрываю за исчерпанием.
