### ISSUE TITLE
Vk.Docs.GetMessagesUploadServer 

### ISSUE THREAD

**Issue by Siptrixed** [vknet/vk#1221]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. 
Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - [ ] .net 4.5
  - [ ] NETStandard2.0
  - [X] другое. Указать строкой ниже.
  .Net Xamarin
2. Класс и метод в котором возникла проблема:

Vk.Docs.GetMessagesUploadServer 

3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса:

```csharp
  var server = Vk.Docs.GetMessagesUploadServer(id, DocMessageType.Doc);
```

4. JSON ответа. Для удобства сбора этих данных подключите логи (https://github.com/vknet/vk/wiki/Logging):

```json
Error: one of the parameters specified was missing or invalid: peer_id
```

5. Если в примере не указаны конкретные значения параметров запроса укажите их здесь:

6. PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Telegram Chat](https://img.shields.io/badge/Chat-Telegram-0F80C1.svg)](https://t.me/VkDotNet), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by ablearthy** [comment]
Эта ошибка возникает из-за того, что `Vk.Docs.GetMessagesUploadServer` передаёт `VK API` ошибочный JSON-объект. Это произошло из-за того, что методы VK API обновились, а сама библиотека нет.

Посмотрим на этот метод в [документации](https://dev.vk.com/method/docs.getMessagesUploadServer). Надо передать JSON-объект, у которого два ключа: `peer_id` и `type`, однако в библиотеке метод [`Docs.GetMessagesUploadServer`](https://github.com/vknet/vk/blob/develop/VkNet/Categories/DocsCategory.cs#L222-L231) передаёт JSON-объект с двумя ключами: `group_id` и `type`, соответственно всё решается переименованием ключа в библиотеке.

**Comment by ivanmem** [comment]
На самом деле метод не обновлялся, а кто-то перепутал параметр и обновил его вместе с аналогичным методом из категории photos (в котором, как не смешно, тоже есть параметр peer_id, но его нет в доке).
https://github.com/vknet/vk/pull/1215

**Comment by Siptrixed** [comment]
> На самом деле метод не обновлялся, а кто-то перепутал параметр и обновил его вместе с аналогичным методом из категории photos (в котором, как не смешно, тоже есть параметр peer_id, но его нет в доке).
> https://github.com/vknet/vk/pull/1215

Жду обновлений

**Comment by ablearthy** [comment]
> (в котором, как не смешно, тоже есть параметр peer_id, но его нет в доке).

Действительно, в документации [написано](https://dev.vk.com/method/photos.getMessagesUploadServer), что есть `group_id`

А в [схеме](https://github.com/VKCOM/vk-api-schema/blob/master/methods.json#L16377-L16400) есть только `peer_id`

Притом, работает как `group_id`, так и `peer_id`. Думаю, стоит использовать `peer_id`

**Comment by ivanmem** [comment]
peer_id нужен для того, чтобы ботом залить фотку от имени пользователя или админа беседы, т.е. будет использован другой скрытый альбом. 
это очень важный момент. если лить через group_id, то сможете залить только 10к фоток и альбом будет переполнен, придется писать в ТП и ждать пока вам их удалят.

**Comment by ivanmem** [comment]
Зачем задачу закрыл? решения не вижу.

**Comment by Siptrixed** [comment]
> Зачем задачу закрыл? решения не вижу.

Случайно с телефона нажал видимо

**Comment by ablearthy** [comment]
Из [одного](https://github.com/VKCOM/vk-api-schema/issues/206) issue [репозитория ВКонтакте](https://github.com/VKCOM/vk-api-schema/):
> Документацию изменили, спасибо. Схеме - верить)

Так что верим схеме!

**Comment by ghost** [comment]
0fa24410cda084cb27f06e9421c040c2a000b261

**Comment by ghost** [comment]
Уже исправлено. @inyutin-maxim
