### ISSUE TITLE
VkNet.Model.MessageSearchResult отсутствует метод FromJSON

### ISSUE THREAD

**Issue by Siptrixed** [vknet/vk#1223]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. 
Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - [ ] .net 4.5
  - [ ] NETStandard2.0
  - [X] другое. Указать строкой ниже.
  Xamarin

2. Класс и метод в котором возникла проблема:
VkNet.Model.MessageSearchResult

3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса:

```csharp
    [Serializable]
    public class MessageSearchResult
    {
        [JsonProperty("count")]
        public ulong Count
        {
            get;
            set;
        }

        [JsonProperty("items")]
        public ReadOnlyCollection<Message> Items
        {
            get;
            set;
        }

        [JsonProperty("profiles")]
        public ReadOnlyCollection<User> Profiles
        {
            get;
            set;
        }

        [JsonProperty("groups")]
        public ReadOnlyCollection<Group> Groups
        {
            get;
            set;
        }

        [JsonProperty("conversations")]
        public IEnumerable<Conversation> Conversations
        {
            get;
            set;
        }
    }
```

4. JSON ответа. Для удобства сбора этих данных подключите логи (https://github.com/vknet/vk/wiki/Logging):

```json
{
    "response": {
        "count": XXXX,
        "items": [
            {
                "date": 1644956356,
                "from_id": -XXXX,
                "id": XXXX,
                "out": 1,
                "attachments": [],
                "conversation_message_id": XXXX,
                "fwd_messages": [],
                "important": false,
                "is_hidden": false,
                "peer_id": XXXX,
                "random_id": 2004308022,
                "text": "Сообщение тест"
            }
        ]
    }
}
```

5. Если в примере не указаны конкретные значения параметров запроса укажите их здесь:

6. PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Telegram Chat](https://img.shields.io/badge/Chat-Telegram-0F80C1.svg)](https://t.me/VkDotNet), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
