### ISSUE TITLE
Невозможно получить события VK Donut!

### ISSUE THREAD

**Issue by Siptrixed** [vknet/vk#1224]
![изображение](https://user-images.githubusercontent.com/94737852/157779077-87632227-b21f-4c66-a720-0b0e48b27b3c.png)
![изображение](https://user-images.githubusercontent.com/94737852/157779052-6ab2d42c-3e6d-46de-9583-cbb9e2032fa2.png)

**Comment by Siptrixed** [comment]
Все что требуется что-бы покрыть 100% входящих типов это сделать поле Raw
![изображение](https://user-images.githubusercontent.com/94737852/157782392-103e2747-1828-4991-8ca6-d3ea55d28690.png)

**Comment by Siptrixed** [comment]
Всего то в объект GroupUpdate надо добавить поле Raw, которое будет содержать ссылку на VkResponse

**Comment by inyutin-maxim** [comment]
@Siptrixed Доброго времени суток, вы могли бы сделать PR, и я бы выкатил новую версию. У меня к сожалению очень мало свободного времени, поэтому не могу обещать когда бы я этим занялся

**Comment by Siptrixed** [comment]
> @Siptrixed Доброго времени суток, вы могли бы сделать PR, и я бы выкатил новую версию. У меня к сожалению очень мало свободного времени, поэтому не могу обещать когда бы я этим занялся

Пожалуйста уточните какой PR вам нужен?
![Screenshot_20220311-165743.png](https://user-images.githubusercontent.com/94737852/157881650-418b8cbe-0518-4f10-85d7-91644b36f2e7.png)

Как будет время + желание сделаю PullRequest

**Comment by inyutin-maxim** [comment]
> > @Siptrixed Доброго времени суток, вы могли бы сделать PR, и я бы выкатил новую версию. У меня к сожалению очень мало свободного времени, поэтому не могу обещать когда бы я этим занялся
> 
> Пожалуйста уточните какой PR вам нужен? ![Screenshot_20220311-165743.png](https://user-images.githubusercontent.com/94737852/157881650-418b8cbe-0518-4f10-85d7-91644b36f2e7.png)
> 
> Как будет время + желание сделаю PullRequest

Ждем Pull Request :+1:

**Comment by Siptrixed** [comment]
> > > @Siptrixed Доброго времени суток, вы могли бы сделать PR, и я бы выкатил новую версию. У меня к сожалению очень мало свободного времени, поэтому не могу обещать когда бы я этим занялся
> > 
> > 
> > Пожалуйста уточните какой PR вам нужен? ![Screenshot_20220311-165743.png](https://user-images.githubusercontent.com/94737852/157881650-418b8cbe-0518-4f10-85d7-91644b36f2e7.png)
> > Как будет время + желание сделаю PullRequest
> 
> Ждем Pull Request 👍

#1226

**Comment by inyutin-maxim** [comment]
**Спасибо за проделанную работу**
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
