### ISSUE TITLE
Нельзя получить количество репостов публикации

### ISSUE THREAD

**Issue by lncendia** [vknet/vk#1228]
Когда я получаю публикации следующим образом:
var publications = await api.NewsFeed
            .SearchAsync(new NewsFeedSearchParams {EndTime = limitTime, Query = hashtag});
То я получаю массив элементов NewsSearchItem, который имеет такие свойства как Like и Comment, но не содержит Repost, хотя в документации указано, что такое свойство существует.
![image](https://user-images.githubusercontent.com/46266853/159571222-d26404a9-97ec-4758-bf82-bd1a74d15978.png)
Не планируется ли добавить это свойство в ближайшем?

**Comment by inyutin-maxim** [comment]
Вы можете внести вклад в проект и добавить самостоятельно и оно появится в библиотеке, сделав пул реквест

**Comment by 7Rd2d** [comment]
#1231

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
