### ISSUE TITLE
Получение ссылок на скачивание видео в FHD и 2K

### ISSUE THREAD

**Issue by sparrux** [vknet/vk#1233]
В вк давно появилась возможность загрузки видео в 1440px и 2160px. Вот [запрос](https://github.com/vknet/vk/pull/1232) с добавлением функционала

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet

**Comment by inyutin-maxim** [comment]
Сегодня вечером планирую выкатить релиз

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
