### ISSUE TITLE
Ошибка типа: MarketProductParams.SKU автосвойство типа int вместо string!!!

### ISSUE THREAD

**Issue by rogachev-aleksey** [vknet/vk#1234]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. 
Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - [ x] .net 4.5
  - [ ] NETStandard2.0
  - [ ] другое. Указать строкой ниже.
  
2. Класс и метод в котором возникла проблема: MarketProductParams

3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса:

```csharp
 long itemId = _vk.Markets.Add(new MarketProductParams {
            OwnerId = -_marketId,
            Name = _bus[b].name,
            Description = desc,
            CategoryId = 404,
            Price = _bus[b].price,
            OldPrice = _bus[b].price,
            MainPhotoId = mainPhoto,
            PhotoIds = dopPhotos,
            Deleted = false,
            Sku = "anyname"  //ошибка типа требуется int, хотя в спеках [5.131](https://dev.vk.com/reference/version/5.131) sku string
        });
```

4. JSON ответа. Для удобства сбора этих данных подключите логи (https://github.com/vknet/vk/wiki/Logging):

```json
{
  "response": {}
}
```

5. Если в примере не указаны конкретные значения параметров запроса укажите их здесь:

6. PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Telegram Chat](https://img.shields.io/badge/Chat-Telegram-0F80C1.svg)](https://t.me/VkDotNet), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
