### ISSUE TITLE
Ошибка Client version deprecated при вызове метода api.Audio.Get();

### ISSUE THREAD

**Issue by DragonNP** [vknet/vk#1246]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. 
Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - [ ] .net 4.5
  - [ ] NETStandard2.0
  - [x] NETFramework,Version=v4.8
  
2. Класс и метод в котором возникла проблема:
Audio.Get();

3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса:

```csharp
  api.Audio.Get(new AudioGetParams());
```

**Comment by ghost** [comment]
@DragonNP Скорее всего использовли старую версию VK API. 
Эта ошибка возникает при использовании старой версии приложения, которая уже не поддерживается.
Проверил метод сейчас - работает.
