### ISSUE TITLE
Wall.Get

### ISSUE THREAD

**Issue by Dersh** [vknet/vk#125]
Метод стал возвращать ошибку:
[ApiVersion("5.9")]
public ReadOnlyCollection<post> Get(long ownerId, out int totalCount, int? count = null, int? offset = null, WallFilter filter = WallFilter.All)

{

VkErrors.ThrowIfNumberIsNegative(() => count);

VkErrors.ThrowIfNumberIsNegative(() => offset);

if (filter == WallFilter.Suggests && ownerId >= 0)

throw new ArgumentException("OwnerID must be negative in case filter equal to Suggests", "ownerId");

var parameters = new VkParameters { { "owner_id", ownerId }, { "count", count }, { "offset", offset }, { "filter", filter.ToString().ToLowerInvariant() } };

VkResponse response = _vk.Call("wall.get", parameters);

totalCount = response["count"];

VkResponseArray items = response["items"];

return response[1].ToReadOnlyCollectionOf<post>(r => r);

}

Видимо было обновление API. Теперь response содержит количество записей в response[0] и элементы в response[1], response[2], response[3], ...
response["count"] и response["items"] теперь выдают NullReference exception.

**Comment by Inyutin** [comment]
Добрый день, попробуйте обновить библиотеку Newtonsoft.Json до последней версии

**Comment by CaCTuCaTu4ECKuu** [comment]
Проверьте, отправляется ли в запросе к серверу ВК версия API

**Comment by inyutin-maxim** [comment]
смотрите ошибку #121
