### ISSUE TITLE
VkNet.Model.Conversation CurrentKeyboard

### ISSUE THREAD

**Issue by PrincessLunaOfficial** [vknet/vk#1254]
Невозможно получить параметр CurrentKeyboard из беседы, так как в классе беседы этот JsonProperty имеет лишний пробел в конце имени и определен как:
[JsonProperty("current_keyboard ")]

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
