### ISSUE TITLE
VkNet.Model.user owner_state добавить свойство

### ISSUE THREAD

**Issue by ivanmem** [vknet/vk#1255]
![image](https://user-images.githubusercontent.com/33786293/200918351-0e4a7602-1e14-4660-8ca6-239abbf18a84.png)
Это поле можно указать в fields к методу dev.vk.com/method/messages.getConversationMembers
Пример значения:
```
{
  "state": 1,
  "photos": {
    "photo_1440_960": "https://vk.com/images/deactivated_1440_960.png",
    "photo_400": "https://vk.com/images/deactivated_400.png",
    "photo_200": "https://vk.com/images/deactivated_200.png",
    "photo_100": "https://vk.com/images/deactivated_100.png",
    "photo_50": "https://vk.com/images/deactivated_50.png"
  },
  "description": "К сожалению, нам пришлось заблокировать страницу Дани за нарушение правил сайта."
}
```

**Comment by ghost** [comment]
@inyutin-maxim ты добавил это)

**Comment by ghost** [comment]
https://github.com/vknet/vk/commit/40ee826fbbe31861eea1e6ffd1caf724d5a21646

скорее всего ещё надо добавить в FromJson(в будущих PR'ах в UserJsonConverter)
