### ISSUE TITLE
Свойство ReadState в сообщениях всегда null

### ISSUE THREAD

**Issue by QRFiling** [vknet/vk#1263]
При попытке узнать прочитано сообщение или нет, свойство Message.ReadState возвращает вместо нужного пречесления, null. 
В документации указано, что оно отсутствует для пересланных сообщений, однако мне не удалось его получить вообще ни для какого сообщения. Возможно есть другой способ узнать прочитано сообщение в лс или нет?

Проблема воспроизводится при получении сообщений как с помощью метода GetHistory, так и при получении нового сообщения (в объекте Message, который выл вытащен из LongPollHistoryResponse)

```csharp
                MessageGetHistoryObject history = await vk.Messages.GetHistoryAsync
                    (new MessagesGetHistoryParams { Count = 25, UserId = user.Id });

                string text = history.Messages.First().Text; //text = привет
                bool hasValue = history.Messages.First().ReadState.HasValue; //hasValue = false
```
Net.Framework 4.7.2
Версия nuget - 1.72.0

**Comment by ghost** [comment]
Начиная с версии VK API 5.81 данный параметр является устаревшим и более не используется
