### ISSUE TITLE
Xamarin - Поддержка мобильных платформ

### ISSUE THREAD

**Issue by azhidkov** [vknet/vk#13]
Airat952: "Здравствуйте, я учу Xamarin for Android, и Ваша библиотека была бы очень полезна. Будет ли поддержка мобильных приложений через Xamarin? Или все же придется искать другую библиотеку?"

Source discussion https://vk.codeplex.com/discussions/543712

**Comment by Povstalez** [comment]
Также интересует этот вопрос

**Comment by inyutin-maxim** [comment]
@Povstalez на данный момент поддержки нет, в дальнейшей перспективе развития проекта

**Comment by inyutin-maxim** [comment]
#318
