### ISSUE TITLE
Cannot access child value on Newtonsoft.Json.Linq.JValue 

### ISSUE THREAD

**Issue by kovart** [vknet/vk#131]
Выбрасывает при вызове метода "Groups.GetById". Newtonsoft.Json стоит последняя версия.

**Comment by kovart** [comment]
Newtonsoft.Json стоит самый последний

**Comment by Inyutin** [comment]
var groupObj = _api.Groups.GetById(1);
var groups = _api.Groups.GetById(new long[] {2, 3,4});

**Comment by kovart** [comment]
Нет, тут дело в том, что библиотека пытается взять "id" из поля city если оно существует. Но вк возвращает это поле всегда, правда с значением 0, если city не указан. Сейчас сделаю pull request.

**Comment by toyozoyes** [comment]
почему не дает ссылку на профиль?>

var message = vk.Messages.Send(new VkNet.Model.RequestParams.MessagesSendParams
                        {
                            UserId = 423741868,
                            Message = $"{friends.LastName}{friends.FirstName} : URL - {friends.Domain}"
                        });
