### ISSUE TITLE
groups.get возвращает всегда мои группы

### ISSUE THREAD

**Issue by curly-brace** [vknet/vk#140]
передаю в метод id пользователя, он все равно возвращает мои группы. что не так? использую сборку из NuGet

**Comment by curly-brace** [comment]
подскажите как это обойти можно. я чот уже голову сломал. большая часть классов и методов, используемых там, приватные. сейчас все уперлось в VkResponse. И главное я так и не понял почему не работает Groups.Get, но если сделать все руками, так как написано в либе вашей, то все срабатывает.

**Comment by inyutin-maxim** [comment]
Исправлено, в NuGet пакет это войдет только с выходом следующей версии, вы можете собрать самую актуальную из репозитория. Проблема была в передаваемом параметре uid, правильно использовать user_id
