### ISSUE TITLE
Когда переезд на NET Framework 7 ?

### ISSUE THREAD

**Issue by Victor564d** [vknet/vk#1422]
Интересует вопрос , когда случиться обновление библиотеки до возможности работать с 7-м дотнетом ....

**Comment by inyutin-maxim** [comment]
@Victor564d Добрый день! так как библиотека поддерживает таргет `netstandard2.0` то `net7` работает из коробки уже сейчас.
Так же хочу подчеркнуть что `NET Framework` перестал развиваться, и развивается `dotnet 7` (он же `dotnet core 7`).

PS. В будущем релизе завезу нативную сборку именно под `net7`
