### ISSUE TITLE
Перевести все места, где используется long на ulong

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#144]
В паре файлов обновил чтобы потом в своем приложении не менять, но библиотека перестала собираться. Цепочка тянется в какие-то глубины и я не разобрался что именно нужно добавить\исправить чтобы заработало. Если уж начали переводить то нужно тогда все перевести с long на ulong

**Comment by inyutin-maxim** [comment]
Обращение для всех. Что бы вдруг не возникло недоразумений это нужно делать вдумчиво и без фанатизма чтобы не сломать в другом месте, так как некоторые параметры должны быть знаковыми. Например передается в параметре без знака ид пользователя, со знаком ид сообщества. Внимательно изучайте документацию вконтакте и устанавливайте соответствующий  тип данных.

**Comment by CaCTuCaTu4ECKuu** [comment]
Model\User при изменении тянет за собой кучу других классов, которые в конце концов выдают ошибку приведения типов где-то связанных с VkResponse

**Comment by inyutin-maxim** [comment]
хм, ну будем смотреть, я так же по мере редактирования методов правлю типы данных. К сожалению это не такой быстрый процесс как хотелось бы

**Comment by CaCTuCaTu4ECKuu** [comment]
Знаете с чем я столкнулся? После перевода long на ulong у класса post ownerId остался long и каждый раз, когда мне нужно сделать Geoups.Get(Post.OwnerId) нужно писать new ulong[] { (ulong)ownerId } и я помню еще в нескольких местах был такой косяк и уверен еще есть где-то. С точки зрения реализации - все правильно, а вот удобство теперь пострадало, из за этого потерялась обратная совместимость, я уверен у многих такая проблема.
Вот это я наконец понял проблему из-за которой создал тему - проблема не в переводе long на ulong, а вот в этом вот и лично я считаю что нужно вернуть все как было с проверкой на отрицательное или создать перегружаемые методы в которые можно подавать старый формат и там будет происходить эта проверка.

**Comment by inyutin-maxim** [comment]
хм, действительно не приятный момент, ну что же боролись за чистоту кода и напоролись на потерю юзабельности, будем потихоньку откатывать, очень жаль что так получается

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну есть еще вариант с перегрузкой метода, тогда будет частично использоваться метод без проверки на отрицательное, а в случае необходимости с проверкой, хотя одна проверка, на производительности не очень то и скажется, а перегрузка это лишний код, но я считаю что лучше откатить. Но еще есть момент, у нас ведь только в одном месте значение может быть отрицательным - когда стену мы берем, можно отделить стену группы от стены пользователя, сделать 2 отдельных класса, которые будут наследоваться от одного родителя, но насколько много в таком случае придется переделывать... в общем мне нравится идея с использованием только положительных значений, но я не знаю как ее реализовать чтоб это смотрелось красиво, а так как сейчас получается что бока вылезли

**Comment by inyutin-maxim** [comment]
нет нет, плодить лишний код очень плохая практика, мы в нем утонем потом, переделано не так уж и много. можно вычленить места где есть ulong просто поиском. Давай договоримся кто то разом все поправит, или по мере правки классов и по отдельности?

**Comment by CaCTuCaTu4ECKuu** [comment]
Я пройдусь сегодня\завтра и все заменю в библиотеке и, возможно, в тестах, а вы потом давайте в тестах доделаете, я так предлагаю

**Comment by inyutin-maxim** [comment]
ок, я тогда не буду трогать классы где есть ulong, потому что работы еще море, кстати у меня вопрос, мы над каждым атрибутом стоит версия API а почему бы в одном месте не передавать последнюю? так бы мы быстрее смогли актуализировать библиотеку за счет обратной связи, как думаете?

**Comment by CaCTuCaTu4ECKuu** [comment]
Насчет версии, я думаю это правильно сделано. Я когда сам начал пользоваться я стал обновлять методы, которые мне нужны, а остальные не трогал, потому что это довольно много работы, где-то подправлял, где-то изменял потихоньку, а если версия будет одна для всех то при обновлении API VK чтоб обновить библиотеку нужно будет обновлять все и сразу и потом если какие-то баги их тоже отслеживать нужно не по последнему методу обновленному, а сразу по всем. Да и например поставить одну версию, а потом я, например, перестану работать с библиотекой, вы перестанете, будут другие люди и им ее править\обновлять будет значительно накладнее

**Comment by inyutin-maxim** [comment]
Ну ок, согласен. я просто спросил почему именно так было реализовано. Ну чтож будем плавно двигаться к очередному релизу

**Comment by CaCTuCaTu4ECKuu** [comment]
Я, пожалуй, в некоторых методах буду смотреть и вместо того чтобы выбрасывать NumberIsNegativeException буду передавать дальше Math.Abs от id метода, если это позволяет логика, тоесть там в одних местах явно указано что на вход подаеться id группы или id страницы, а в других wall id и соотв. id будь то задан явно id или получен откуда то где wallId может быть положительным и отрицательным то он сработает, мне кажется в этом есть логика, а если что можно будет убрать это

**Comment by inyutin-maxim** [comment]
хорошая идея, поделитесь потом опытом удобства использования этого подхода

**Comment by inyutin-maxim** [comment]
Товарищи а вы при разработке используете статические анализаторы кода, и какие если да?

**Comment by azhidkov** [comment]
>  над каждым атрибутом стоит версия API а почему бы в одном месте не передавать последнюю?

Раньше для разных методов были разные "последнии" версии api.

**Comment by inyutin-maxim** [comment]
> Раньше для разных методов были разные "последнии" версии api.
Я вас понял, просто сейчас везде передается актуальная версия( по меньшей мере которые я видел)

**Comment by azhidkov** [comment]
> Товарищи а вы при разработке используете статические анализаторы кода, и какие если да?

Я в основном использую Resharper + несколько лет назад проходился по этому проекту сканнером Gendarme http://www.mono-project.com/docs/tools+libraries/tools/gendarme/ К слову сказать, именно он советовал возвращать ICollection и IReadOnlyCollection у методов.

Также сейчас настроена проверка Coverity https://scan.coverity.com/projects/vknet

**Comment by azhidkov** [comment]
> Я вас понял, просто сейчас везде передается актуальная версия( по меньшей мере которые я видел)

Думаю, лучше оставить как есть. Можно доделать инжектор, чтобы он принимал номер последней версии, проходился по всем методам и проверял у каких методов не указана эта версия. И уже дорабатывать методы из этого списка.

**Comment by inyutin-maxim** [comment]
Могу предложить в плюс вышесказанному. 
В 2015 студии используется компилятор Roslyn на его базе написано уже немало диагностик и исправлений, а так же рефакторингов, не все могут позволить себе решарпер. 
Вот что можно так же использовать: 
* [GCop](https://goo.gl/BrcK0E)
* [Code Cracker](https://goo.gl/xjci8P)
* [C# Essentials](https://goo.gl/jC7rcC)
* [Refactoring Essentials](https://goo.gl/vBkZdB)

**Comment by inyutin-maxim** [comment]
Немного не по теме но хочу чтобы все приняли к сведению. Travis не собирал проект по нескольким причинам: 
* он не собирает проект если с его точки зрения в тестах есть ошибки, видимо версии разные на нем и у нас. 
* Ему не нравится если в метод передаются не все необязательные параметры. Он требует чтобы передавались все параметры

**Comment by CaCTuCaTu4ECKuu** [comment]
А я когда смотрел почему не собирает пробил ошибку в гугле и прочитал что это какой-то баг сборщика. Хотя в некотором роде это и есть баг (требует чтобы передавались все параметры)

**Comment by inyutin-maxim** [comment]
теперь наконец то buid status зелененький))

**Comment by CaCTuCaTu4ECKuu** [comment]
Да - на это приятно смотреть)

**Comment by CaCTuCaTu4ECKuu** [comment]
Я в чате, в общем

**Comment by inyutin-maxim** [comment]
Что наш Travis снова чудит, падает с ошибкой:  Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by CaCTuCaTu4ECKuu** [comment]
По поводу этого вообще ничего не скажу, я вручную с компиляторами не работал, в универе только для практики приходилось компилить и то это просто GCC был, а по факту небыло необходимости самому разбираться, а так времени не особо

**Comment by CaCTuCaTu4ECKuu** [comment]
Я там в чатике пару вопросов поднял

**Comment by inyutin-maxim** [comment]
Да собственно все просто, он не может получить библиотеки с сервера (порядка 150), потому и падает с этой ошибкой.
> Failed to fetch http://download.mono-project.com/repo/debian/pool/main/m/mono/libmono-corlib4.5-cil_4.0.5.1-0xamarin1_all.deb  Size mismatch

 Видимо что то с сервером, а вообще рекомендуют переходить как я понял на docker
> This job ran on our legacy infrastructure. Please read [our docs on how to upgrade](http://goo.gl/qAJTZd)

так же:
> Я там в чатике пару вопросов поднял

На тему авторизации?

**Comment by CaCTuCaTu4ECKuu** [comment]
Вчера, кажется, гитхаб подлагивал, может еще где-то местами лагает что-то, А по поводу тревис или докер - я в этом не компетентен, так что лучше я там где разбираюсь буду что-то кодить)
А так да, авторизация, я пожалуй там полазаю тогда сам разберусь и сделаю так как считаю правильно, там ничего принципиально не надо менять, думаю, просто работать будет правильнее

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu ок, я тоже не сильно компетентен в линуксах. Докер - это контейнеры, после перехода Travis должен будет работать в нем, сейчас как я понимаю все это крутиться на виртуальной машине, бенефиты в переходе на докер это уменьшение времени создания инстанса для сборки проекта. тему знаю очень поверхностно)

**Comment by azhidkov** [comment]
Travis'ом переодически лагает, можно перезапустить сборку вручную на странице самого проекта.
