### ISSUE TITLE
Требование авторизации для метода Wall.Get / Wall.GetExtended

### ISSUE THREAD

**Issue by mryabets** [vknet/vk#145]
Добрый день.
В документации указано, что токен требуется только в случаях с `filter=suggests` и `filter=postponed`.
https://vk.com/dev/wall.get
Может, в вызов `_vk.Call` добавить `skipAuthorization = (filter != WallFilter.Suggests && filter != WallFilter.Postponed)`?

**Comment by inyutin-maxim** [comment]
@mryabets боюсь это не самый корректный подход с точки зрения архитектуры, представляете во что превратиться метод если все исключительные ситуации вносить туда?

**Comment by inyutin-maxim** [comment]
да, возможно стоит передавать 3-им параметром то что вы указали выше. вы можете внести в проект свой вклад и внести свои изменения в код и прислать пул реквест

**Comment by mryabets** [comment]
@inyutin-maxim без исключительных ситуаций тоже не интересно.)
У ВК ведь где-то это так же обрабатывается, наверное.
Ок, щас попробую. Спасибо.

**Comment by inyutin-maxim** [comment]
закрыто пул реквестом#146
