### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by SFocus** [vknet/vk#147]
// обработчик получения кода
            Func<string> code = () =>
            {
                Console.Write("Please enter code: ");
                string value = Console.ReadLine();
                return value;
            };
Что ето за код? 
Питаюсь обробить каптчу 
 api.Authorize(код приложения, "логин", "пароль", Settings.Offline, code, sid, kaptcha);
Можно пример кода для обработки исключения Windows Form?

**Comment by CaCTuCaTu4ECKuu** [comment]
Насчет того как - смотрите #89
Насчет этой функции - при авторизации подается какой либо метод, который возвращает код на капче, который тут же обработает метод авторизации внутри библиотеки, но в данном конкретном случае я лично не совсем понимаю как должна выглядеть эта функция. Как автор коммита будет, думаю, он вам объяснит

**Comment by azhidkov** [comment]
>> Что ето за код?
Это код прохождения двух этапной авторизации. Если в настройках включена двухэтапная авторизация, будет вызван этот делегат, который должен собственно и вернуть код.

**Comment by SFocus** [comment]
<h4>ясно.. спасибо </h4>
