### ISSUE TITLE
Сериализция

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#148]
Я уже подключил сериализацию для части классов, но это не совсем кошерная сериализация, так сказать, в обьект я просто включил все, но есть кратковременные данные, которые не всегда имеет смысл хранить. Собственно думаю обсудить дальнейший путь. 
Варианта основных 2: просто включить сериализацию у всего для всех полей или вместо полей с геттерами и сеттерами там, где не нужна сериализация, вынести в переменную, указать [NoSerialization] и описать get\set для поля. Такое есть смысл делать, например, для поля Online или LastSeen у User и это, в оригинале, более правильный вариант + если большое кол-во данных то от этого есть выигрыш и все такое, ну вы поняли, единственный минус - больше строк кода, но мне кажется это мелочи.
По ходу я еще буду подключать сериализацию для нужных мне классов, не обещаю что пройду по всем (но думаю что все обновлю), но вы скажите что думаете, я буду делать как решим, а пока так как есть оставлю.

**Comment by azhidkov** [comment]
Два вопроса: 
1. Зачем здесь нужна сериализация?
2. Где посмотреть "Я уже подключил сериализацию для части классов"?

**Comment by CaCTuCaTu4ECKuu** [comment]
Посмотреть - коммит, зачем - кеширование, неудобно писать для каждого
класса структуру для бд, проще бинари вгонять и только айди оставлят

**Comment by inyutin-maxim** [comment]
Мои 5 копеек, я против атрибута сериализации ничего не имею, но он должен находиться над классом а не над комментарием, не приятно смотреть как студия все подчеркивает с замечанием

**Comment by CaCTuCaTu4ECKuu** [comment]
Оккай. Ну я думаю я тогда буду доделывать везде и я, наверное, буду тогда выносить поля которые не надо сериализовать. 
А на счет нужно\не нужно, можно, конечно, и описать методы и записывать только нужные поля, но вот я с базой sqlite кучу нервов экономлю просто вкидывая id-binary-last_update.
Если больше замечаний нет то можно закрывать

**Comment by inyutin-maxim** [comment]
Вроде нет. а если что можем и в чате обсудить какие то моменты
