### ISSUE TITLE
Загрузка аудио на сервер и сохранение

### ISSUE THREAD

**Issue by HELLRAiSER555** [vknet/vk#1497]
01. Dim bUploadFile As Byte() = Await webClient.UploadFileTaskAsync(strServerURI, fileNames(i))
02. Dim sUploadFile As String = Encoding.Default.GetString(bUploadFile)
Допустим файл ошибочный или еще чего вдруг, тогда sUploadFile  = "{""request_id"":""99bba020e0da407492af9609f142da26"",""error_code"":4611,""error_msg"":""Invalid File""}" или еще чего...
03. attIDAudioSave = api.Audio.Save(**sUploadFile**)
Exception {"Ссылка на объект не указывает на экземпляр объекта."}
Можно конечно и обработать json до сохранения, но зачем тогда vknet?

**Comment by ghost** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
