### ISSUE TITLE
Обновление Wall.Get

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#150]
Вижу метод Wall.Get изменили и указали устаревшим, в связи с этим возникли предложения и кое какие замечания.
Во первых я считаю не надо просто так помечать на удаление (ровно как и удалять) метод, который используется с самого создания библиотеки, а тем более заменяя его на метод, требующий на вход новый класс параметров который еще нужно добавить (последнее не сложно, но все равно я считаю это в минус). Касательно этого я считаю что метод можно оставить изменить его так, чтобы в нем создавались эти параметры из исходных данных и отправлялись на новый метод дабы не заставлять менять что-то в проекте потом.

Во вторых возникла идея, которая позволит таки избавиться от всех long и заменить их на ulong, но это довольно кардинальное предложение и будет много изменений т.к. смысл в том, чтоб убрать WallCategory полностью для пользователя, перенести функционал отдельно для VkApi.Groups.Wall и VkApi.Users.Wall, для удобства прийдется еще много чего продумать, сразу можно сказать что нужно т.к. содержание практически одинаковое у них, то или добавлять к каждому экземпляру поста тип (группа или страница) или изначально сделать GroupWallPost и UserWallPost какой-то. Но т.к. это приведет к потере обратной совместимости с большой частью функционала, так как записи это один из основных элементов, то это уже можно сделать как версию VkNet 1.5 и, как вариант, можно предусмотреть какую-то подключаемую прослойку для сохранения обратной совместимости.

**Comment by inyutin-maxim** [comment]
> Заменяя его на метод, требующий на вход новый класс параметров который еще нужно добавить (последнее не сложно, но все равно я считаю это в минус).

Здесь я с тобой не согласен. Метод выглядит ужасно когда в него передается целая туча параметров (5 это потолок, если больше то в отдельный метод)

> Касательно этого я считаю что метод можно оставить изменить его так, чтобы в нем создавались эти параметры из исходных данных и отправлялись на новый метод дабы не заставлять менять что-то в проекте потом.

Согласен, как то не подумал о том что можно просто перевызвать

Вторую часть нужно хорошо обдумать

**Comment by inyutin-maxim** [comment]
> Во первых я считаю не надо просто так помечать на удаление (ровно как и удалять) метод, который используется с самого создания библиотеки, а тем более заменяя его на метод

Помечать на удаление и правда не стоит.

я поправлю

**Comment by inyutin-maxim** [comment]
> чтоб убрать WallCategory полностью для пользователя, перенести функционал отдельно для VkApi.Groups.Wall и VkApi.Users.Wall

Можно к примеру в VkApi.Groups.Wall вызывать методы WallCategory которые относятся только к группам, для VkApi.Users.Wall соответственно и обратная совместимость не пострадает. Но что то мне подсказывает что за Wall потянется еще пол библиотеки

**Comment by inyutin-maxim** [comment]
Метод поправил, пометку о том что метод устаревший оставил с рекомендацией использовать новый метод, но убрал в тексте что может быть удален по причине того что он не возвращает все возможные данные

**Comment by CaCTuCaTu4ECKuu** [comment]
Я, кстати, не проверил сначала изменений в самом API сразу, но вижу метод все еще есть. Насчет кучи параметров - да, это нехорошо и я полностью согласен, на в данном конкретном методе их не очень много и большинство предопределены по умолчанию и сейчас метод довольно удобен в использовании.
Думаю решение правильное - отметить как устаревший, но удалять не стоит т.к. он вполне удобен, не всегда удобно создавать и определять переменную с параметрами когда можно вписать 4 параметра 2 из которых - 2 двузначных инта.
Я просто сейчас как раз работаю с проектом и этим всем пользуюсь и некоторые моменты мелкие (вроде long\ulong) сразу бросаются в глаза касательно удобства

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu думаю можем закрыть задачу? а обсуждение судьбы класса wall можем перенести в чат

**Comment by CaCTuCaTu4ECKuu** [comment]
А насчет изменений, я вот еще подумал, это получается уже отход от дублирования Vk API т.к. будет не порт. Я вечно про это забываю когда подумываю что-то изменить -_- для удобства использования в .Net
Да, думаю здесь больше все решили

**Comment by azhidkov** [comment]
> Метод выглядит ужасно когда в него передается целая туча параметров (5 это потолок, если больше то в отдельный метод)

Первоначально задумывалось, что методы в библиотеке идентичны методам вконтакте апи и вызываться будут через именованные параметры.

**Comment by CaCTuCaTu4ECKuu** [comment]
@azhidkov ну это и правильно, я вот просто забываю об этом иногда и думаю "а почему бы не сделать так, это ведь будет практичнее", а потом вспоминаю что это если ты шаришь в либе, а если человек по документации будет разбираться то это одни проблемы
