### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by DuDkaElfa** [vknet/vk#1503]
если в сообщении больше 3 фотографий Attachments.Count равен одному

**Comment by ghost** [comment]
@DuDkaElfa код можно получить?

**Comment by DuDkaElfa** [comment]
> @DuDkaElfa код можно получить?

только с фотографиями то есть если прикрепить 10 гифок например он получает все 10 но если это фотографии то больше трёх он принять не может

 if (message.Attachments.Count > 0)
                            {
                                Console.WriteLine(message.Attachments.Count);
                                foreach (VkNet.Model.Attachments.Attachment attachment in message.Attachments)
                                {
                                }
                             }

**Comment by DuDkaElfa** [comment]
вот видео с проблемой
https://youtu.be/jJxsgZjUoxk

**Comment by inyutin-maxim** [comment]
@DuDkaElfa Было бы продуктивнее получить json ответа от сервера, вместе с параметрами запроса. Для этого надо в проекте настроить логи если их еще нет:
https://github.com/vknet/vk/discussions/1112

**Comment by ghost** [comment]
@DuDkaElfa метод message.GetById использовали? У меня всё работает, count и 3 и 5 и 10.

**Comment by ghost** [comment]
@DuDkaElfa возможно стоит дождаться релиза новой версии VkNet, либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet

**Comment by Panuchi** [comment]
@DuDkaElfa ?

**Comment by DuDkaElfa** [comment]
использовать метод getbyid звучит как излишество ведь это ещё один лишний запрос к серверу

**Comment by ghost** [comment]
@DuDkaElfa так вы что используете? Какой метод?

**Comment by DuDkaElfa** [comment]
> 

я получаю сообщения из лонгпула и пытаюсь проверить какие прикреплены фотографии

**Comment by ghost** [comment]
> > 
> 
> 
> 
> я получаю сообщения из лонгпула и пытаюсь проверить какие прикреплены фотографии

Сможете реализовать логгер и прислать json ? #1112

**Comment by ghost** [comment]
Закрываю. Проверял несколько раз, проблема не воспроизводилась, автор не проявляет инициативы.

**Comment by ivanmem** [comment]
Это вам приходит сжатое событие с `is_croped: true`. Чтобы получить полное сообщение надо его получить по cmid.
