### ISSUE TITLE
Репосты записей

### ISSUE THREAD

**Issue by Juzzver** [vknet/vk#152]
Здравствуйте!
Интересует вопрос, как правильно реализовать репост записи? P.S> В доке совсем ни слова о репостах :(

Делаю в обработчике:
           int totalCount;
           var result = wall.Get(-55750004, out totalCount); // получаю список записей.
           foreach (var item in result) 
           {    
               if (item.Likes.Count > 0)
               this.textBox3.AppendText(String.Format("{0}\n", item.Text)); // удостоверяюсь, что записи существуют.
              // а вот как сделать репост найденных айтемов...
              // нашел такой метод:  wall.Repost(...);, но подходящего параметра для него в имеющемся списке не вижу.    
           }

**Comment by Juzzver** [comment]
С этим вопросом разобрался, решением стало:
 string obj = "wall" + item.OwnerId + "_" + item.Id;
 wall.Repost(obj);

Но возник другой вопрос.
Как быть, если репост идет из закрытых групп, в которых я состою? К примеру есть группа, где содержится пост по идентификатору: wall-82284948_187, я в этой группе состою и имею админские права, репост произвожу на свою же стену. Но при этом получаю исключение: VkNet.Exception.AccessDeniedException: Access denied: can't publish
Полный лог исключения: http://pastie.org/private/degxb1fxnekjfob8ttvm3w

Приложение при этом так же запускается от имени моей учетки. Не баг ли это?
Подскажите, решаема ли данная проблема?

**Comment by CaCTuCaTu4ECKuu** [comment]
А у записи "CanRepost" true? Может у приложения нет прав? Я посмотрю

**Comment by CaCTuCaTu4ECKuu** [comment]
Насчет перепостов из закрытых групп. Записи из закрытых групп моно отправлять только в личку, перепостить себе на стену или в другую группу нельзя изначально (попробуйте сделать это прям на сайте, у вас будет доступен только пункт отправки личным сообщением)
