### ISSUE TITLE
KeyboardButtonActionType open_photo

### ISSUE THREAD

**Issue by ivanmem** [vknet/vk#1522]
Видимо появился какой-то новый тип кнопки (open_photo) и при получении обновлений через `api.Groups.GetBotsLongPollHistoryAsync` - всё падает с ошибкой `JsonSerializationException`. 
```
"ClassName": "Newtonsoft.Json.JsonSerializationException",
"Message": "Error converting value \"open_photo\" to type 'VkNet.Enums.SafetyEnums.KeyboardButtonActionType'. Path 'client_info.button_actions[5]', line 23, position 18.",
```

Можно сделать так, чтобы вместо падения было null и где-нибудь лог ошибок?
Из-за таких ошибок парализуется работа всего бота. Он же не может игнорировать целый массив событий, а конкретное проигнорить нельзя.

**Comment by ivanmem** [comment]
Наверное эта задача частично решена в https://github.com/vknet/vk/issues/1511 , но всё равно надо подумать как избавиться от таких ошибок в будущем.

**Comment by ghost** [comment]
Исправлено. Нужен релиз.

**Comment by VKohai** [comment]
Уже есть полное решение проблемы?

**Comment by inyutin-maxim** [comment]
> Уже есть полное решение проблемы?

Пока не было релиза. Скоро сделаем

**Comment by ghost** [comment]
@inyutin-maxim 
`Можно сделать так, чтобы вместо падения было null и где-нибудь лог ошибок?
Из-за таких ошибок парализуется работа всего бота. Он же не может игнорировать целый массив событий, а конкретное проигнорить нельзя.`

Это возможно?

**Comment by inyutin-maxim** [comment]
> @inyutin-maxim `Можно сделать так, чтобы вместо падения было null и где-нибудь лог ошибок? Из-за таких ошибок парализуется работа всего бота. Он же не может игнорировать целый массив событий, а конкретное проигнорить нельзя.`
> 
> Это возможно?

Есть 2 пути решения, ввести в перечисление значение по умолчанию когда не смогло ничего сделать, теоретически надо писать конвертер и метить все свойства с типом энама этим конвертером.

Второй путь сделать все свойства с типом enum как наллабл. 

На вскидку так

**Comment by ivanmem** [comment]
> Второй путь сделать все свойства с типом enum как наллабл.

Нельзя, чтобы подобные ошибки были незамеченными, поэтому если оно будет null, то куда-то в лог должна записываться причина.

**Comment by inyutin-maxim** [comment]
> > Второй путь сделать все свойства с типом enum как наллабл.
> 
> Нельзя, чтобы подобные ошибки были незамеченными, поэтому если оно будет null, то куда-то в лог должна записываться причина.

Проблема в том что сериализатор не обладает логгером, как и его конвертеры

**Comment by ivanmem** [comment]
@inyutin-maxim может тогда сделаем для таких полей аналоги с постфиксом Raw в формате string? При null будем опираться на них.

**Comment by ghost** [comment]
Перенесено в #1556
