### ISSUE TITLE
Теперь можно переписываться с группой

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#154]
В связи с обновлением ВК которое позволяет переписываться с группами (и от их имени) теперь переписка может быть не только с пользователями и идентификатор может получать отрицательные значение. Если я правильно помню у нас такой поворот предусмотрен не был, так что вполне вероятно кто будет пользоваться такой фичей - у тех будет сразу все падать и крашится и бсоды и компы взорвутся. В общем, я там местами переделаю, если заметите - исправляйте. А еще я не знаю как назвать эту переменную правильно, это ведь вроде как собеседник тогда получается, но слово на инглише для этого совсем не привлекательное, что-то бы попроще, не UserID, но я пока оставляю такое название

**Comment by inyutin-maxim** [comment]
CompanionID вполне подходящее название, или InterlocutorID тоже как вариант

**Comment by inyutin-maxim** [comment]
Так как я функцию обновлял, считаю задачу закрытой, все входные параметры метода соответствуют тем что указаны в api vk
