### ISSUE TITLE
Как получить событие нового сообщения?

### ISSUE THREAD

**Issue by Timz** [vknet/vk#155]
Салют! Чтото не соображу. Есть vk.Messages.GetLongPollServer
А что дальше делать? как получить событие о новом сообщении?

**Comment by inyutin-maxim** [comment]
попробуйте использовать метод messages.getLongPollHistory

**Comment by Timz** [comment]
Спасибо. Но боюсь если я постоянно буду долбить этой проверкой, меня забанят )) Хотел сделать как в офф доках написано https://vk.com/dev/using_longpoll

**Comment by inyutin-maxim** [comment]
Вы можете обратиться за помощью к кому нибудь в чате [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/vknet/vk?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
Так как это не является ошибкой, я закрываю задачу.

**Comment by CaCTuCaTu4ECKuu** [comment]
Я решил сделать общую библиотеку для тривиальных решений такого типа и выложить ее в публичный доступ, так что вот - https://github.com/CaCTuCaTu4ECKuu/VkNetExtend

**Comment by azhidkov** [comment]
Я думаю такое лучше оформить как FAQ или что-то в этом духе, когда вверху список, чтобы можно было быстро пробежаться глазами, а уже ниже сами реализации. Большинству, думаю тоже, будет удобнее читать текст,  а не лазить в код.
