### ISSUE TITLE
Все параметры RequestParams привести к общему виду

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#156]
И обновить библиотеку в местах использования параметров

**Comment by inyutin-maxim** [comment]
Вопрос, почему ты выбрал исключительно структуры для приведения параметров?

**Comment by CaCTuCaTu4ECKuu** [comment]
Простой пример. Берем получение списка постов, создаем postgetparams и по
ходу итераций меняем только оффсет. При работе передается ссылка и если
объект изменить извне в другом потоке то изменится все. Такое накодить,
конечно, сложно, но возможно. Если не понятно что я имею ввиду то дома за
компом могу пример написать более подробный

**Comment by inyutin-maxim** [comment]
Я тебя понял, ок

**Comment by inyutin-maxim** [comment]
привел оставшиеся RequestParams к общему виду
