### ISSUE TITLE
Debugging, Step Into (F11)  1.20.0.0

### ISSUE THREAD

**Issue by SanteR1** [vknet/vk#157]
Подскажите, почему после обновления библиотеки (подключена через nuget) когда дебажу в VS2015 свой код через Step Into (F11) и например прохожу через эту строку var api = new VkApi();
то студия просит указать исходники VkApi.cs что бы пошагово пройти внутри библиотеки. На 1.18 версии такого нет. Не удобно) Теперь всегда так будет?

**Comment by CaCTuCaTu4ECKuu** [comment]
Это не ошибка, тем более сборки. Не используйте шаг с заходом или настройте
свой VS

**Comment by azhidkov** [comment]
@SanteR1 возможно не подтянулся файл VkNet.pdb. Проверьте, есть ли он в папке где находится VkNet.dll?

**Comment by CaCTuCaTu4ECKuu** [comment]
Если step into то шаг с заходом, можно нажать нет или отмена и больше, по
моему, спрашивать не будет

**Comment by SanteR1** [comment]
@azhidkov файл VkNet.pdb этот имеется. На старой сборке идут шагом с заходом и такого нет. Настройки в студии одинаковые, а в новой версии просит указать VkApi.cs
Причем ищет он по вашему пути, у меня таких папок нет.

@CaCTuCaTu4ECKuu там нет кнопки отмена, там просит сразу файл указать, если жму отмена, нажимаю шаг, то она следующий файл просит из сборки. Если нажать продолжить, то удет до следующего бряка. В одной студии старая сборка норм работает, а новая просит указывать файл. Оби установлены через nuget


Locating source for 'E:\Anton\github.com\vk\VkNet\VkApi.cs'. (No checksum.)
The file 'E:\Anton\github.com\vk\VkNet\VkApi.cs' does not exist.
Looking in script documents for 'E:\Anton\github.com\vk\VkNet\VkApi.cs'...
Looking in the projects for 'E:\Anton\github.com\vk\VkNet\VkApi.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cvt\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\msclr\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\sys\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thr\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\amd64\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\arm\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\concrt\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\i386\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\linkopts\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\stl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\vccorlib\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\crt\src\vcruntime\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\src\mfc\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\src\atl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include\'...
The debug source files settings for the active solution indicate that the debugger will not ask the user to find the file: E:\Anton\github.com\vk\VkNet\VkApi.cs.
The debugger could not locate the source file 'E:\Anton\github.com\vk\VkNet\VkApi.cs'.

**Comment by azhidkov** [comment]
>> В одной студии старая сборка норм работает, а новая просит указывать
файл. Оби установлены через nuget

А в какой версии нормально, и в какой нет?

Эту сброку я собирал в Visual Studio 2015 Community, 1.0.18 в 2013.

2015-12-07 12:08 GMT+03:00 SanteR1 <notifications@github.com>:

**Comment by Dramacydal** [comment]
Вообще как-бы чтобы идти по сурсам библиотеки нужны эти самые сурсы, или я
что-то не понимаю?
>> В одной студии старая сборка норм работает, а новая просит указывать
файл. Оби установлены через nuget

А в какой версии нормально, и в какой нет?

Эту сброку я собирал в Visual Studio 2015 Community, 1.0.18 в 2013.

2015-12-07 12:08 GMT+03:00 SanteR1 <notifications@github.com>:

> @azhidkov <https://github.com/azhidkov> файл VkNet.pdb этот имеется. На
> старой сборке идут шагом с заходом и такого нет. Настройки в студии
> одинаковые, а в новой версии просит указать VkApi.cs
> Причем ищет он по вашему пути, у меня таких папок нет.
>
> @CaCTuCaTu4ECKuu <https://github.com/CaCTuCaTu4ECKuu> там нет кнопки
> отмена, там просит сразу файл указать, если жму отмена, нажимаю шаг, то
она
> следующий файл просит из сборки. Если нажать продолжить, то удет до
> следующего бряка. В одной студии старая сборка норм работает, а новая
> просит указывать файл. Оби установлены через nuget
>
> Locating source for 'E:\Anton\github.com\vk\VkNet\VkApi.cs'. (No
> checksum.)
> The file 'E:\Anton\github.com\vk\VkNet\VkApi.cs' does not exist.
> Looking in script documents for 'E:\Anton\github.com\vk\VkNet\VkApi.cs'...

> Looking in the projects for 'E:\Anton\github.com\vk\VkNet\VkApi.cs'.
> The file was not found in a project.
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\include\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\include\cvt\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\include\msclr\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\include\sys\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\include\thr\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\amd64\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\arm\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\concrt\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\i386\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\linkopts\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\stl\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\vccorlib\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\crt\src\vcruntime\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\atlmfc\src\mfc\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\atlmfc\src\atl\'...
> Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio
> 14.0\VC\atlmfc\include\'...
> The debug source files settings for the active solution indicate that the
> debugger will not ask the user to find the file: E:\Anton\github.com
> \vk\VkNet\VkApi.cs.
> The debugger could not locate the source file 'E:\Anton\github.com
> \vk\VkNet\VkApi.cs'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vknet/vk/issues/157#issuecomment-162454498>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/vknet/vk/issues/157#issuecomment-162480596>.

**Comment by SanteR1** [comment]
@azhidkov  студия у меня одна 2015. Сборка ваша 1.18 версии при дебаге шагом работает как по мне - нормально, т.е. она не заходит в вашу библиотеку, а просто все выполняет на этом шаге и потом иду на следующий.
А ваша сборка 1.20 каждый раз просит указать файлы исходников.
Моя цель, что бы она не заходила в ваши исходники как это было в версии 1.18

**Comment by Dramacydal** [comment]
@SanterR1 это нормальная ситуация, чтобы не заходить в библиотеку надо использовать F 10 (step over)

**Comment by SanteR1** [comment]
Странно почему это так стало, а почему я тогда в другие библиотеки не проваливаюсь? Интересно что в таком коде я не вхожу, а просто выполняется строка хоть и жму шаг со входом?- var request = new xNet.HttpRequest()) Пакет через nuget стоит.

**Comment by SanteR1** [comment]
Включение и отключение режима "Только мой код" (Enable or disable Just My Code). (MSDN)
Поведение пошагового выполнения
При выполнении Шага с заходом (клавиша F11) внутрь кода, не написанного пользователем, отладчик выполняет этот код с переходом к следующему оператору пользователя.При выполнении Шага с выходом (сочетание клавиш: Shift + F11) отладчик переходит к следующей строке пользовательского кода.Если код пользователя не обнаруживается, выполнение продолжается до завершения работы приложения, достижения точки останова или возникновения исключения.
![Enable or disable Just My Code](https://i-msdn.sec.s-msft.com/dynimg/IC768654.jpeg)

**Comment by CaCTuCaTu4ECKuu** [comment]
Я же сказал что настройки студии нужно менять

**Comment by SanteR1** [comment]
Настройки правильные, они сразу такие были. Просто пришлось удалить pdb файл вашей библиотеки. Скорее всего при билде вашей библиотеки в нугет успользовались атрибуты, которые считали код "своим".
