### ISSUE TITLE
Почему VkNet.Model.User.Photo50 и его однополчане - поля, а не свойства?

### ISSUE THREAD

**Issue by AOmelaienko** [vknet/vk#159]
Собственно, subj. Это так задумано и так надо?

**Comment by inyutin-maxim** [comment]
Я конечно могу ошибаться, но в контексте нашей библиотеки, это особого значения не имеет, свойством это будет или нет. так как внутри свойств никакой логики не подразумевается. Расскажите вашу точку зрения по данному вопросу, очень интересно было бы узнать.

**Comment by AOmelaienko** [comment]
В контексте библиотеки — пожалуй, что и не имеет. В контексте её применения — вызывает необходимость дополнительных телодвижений при binding'е. Я не с претензией, если что, просто поинтересовался.

**Comment by inyutin-maxim** [comment]
Я вас понимаю, раз это вызывает неудобство то я приведу все к свойствам, спасибо за фидбек.

**Comment by AOmelaienko** [comment]
Большой нужды, по-хорошему, в этом нет. Этот binding полезен преимущественно при загрузке изображений по System.Uri, а оставлять этот процесс полностью на откуп UI не то чтобы разумный шаг. Просто немного бросается в глаза.

Кроме того, чисто теоретически в уже существующих проектах может осуществляться доступ к этим членам класса (полям) через reflection, так что может получиться немного breaking change.

Если Вы решили, что эта переделка в любом случае необходима, я мог бы взять её на себя и сделать потом pull request.

**Comment by CaCTuCaTu4ECKuu** [comment]
Вполне возможно что некоторым этот биндинг будет вполне полезен, если займетесь - отлично, думаю это будет хороший ход

**Comment by inyutin-maxim** [comment]
Я уже все сделал. сейчас залью изменения в репозиторий.

**Comment by inyutin-maxim** [comment]
Слава регулярным выражениям. Предложения или комментарии? задачу закрываю
