### ISSUE TITLE
Wall.Get возвращает System.NullReferenceException

### ISSUE THREAD

**Issue by HarkBack** [vknet/vk#160]
При вызове vk.Wall.Get для получения записей со стены пользователя, всегда возвращает ошибку System.NullReferenceException.
```cs
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в VkNet.Model.WallGetObject.FromJson(VkResponse response) в E:\GIT\FORK\vk\VkNet\Model\WallGetObject.cs:строка 40
   в VkNet.Categories.WallCategory.Get(WallGetParams params) в E:\GIT\FORK\vk\VkNet\Categories\WallCategory.cs:строка 86
   в Gettervk.Glazerkv.likeAva(Int64 memberId) в E:\GIT\Gettervk\Gettervk\Glazerkv.cs:строка 387
```
Хочу узнать, ошибка только у меня? Пока не имею понятия как проверить/исправить.

**Comment by CaCTuCaTu4ECKuu** [comment]
Если это не ошибка при подключении и компиляции библиотеки поставьте точку отладки в WallGetObject.FromJSON и пришлите исходный JSON (тот, что в токене, полный) и я исправлю

**Comment by HarkBack** [comment]
`{[
  892,
  {
    "id": 2310,
    "from_id": 262860615,
    "to_id": 262860615,
    "date": 1449871037,
    "post_type": "post",
    "text": "коротко о главном",
    "is_pinned": 1,
    "media": {
      "type": "audio",
      "owner_id": 2000439051,
      "item_id": 420732348
    },
    "attachment": {
      "type": "photo",
      "photo": {
        "pid": 390809363,
        "aid": -7,
        "owner_id": 262860615,
        "src": "http://cs630730.vk.me/v630730966/79f6/iOuw0G0VQEU.jpg",
        "src_big": "http://cs630730.vk.me/v630730966/79f7/DAb9CWXnkIs.jpg",
        "src_small": "http://cs630730.vk.me/v630730966/79f5/Xvfjrfarl-0.jpg",
        "src_xbig": "http://cs630730.vk.me/v630730966/79f8/Bq1PCVh-Vtc.jpg",
        "src_xxbig": "http://cs630730.vk.me/v630730966/79f9/HAObuNAuHoo.jpg",
        "src_xxxbig": "http://cs630730.vk.me/v630730966/79fa/-E2Af002T88.jpg",
        "width": 1280,
        "height": 1303,
        "text": "",
        "created": 1449870242,
        "access_key": "fdd1ae4d80f94d4a18"
      }
    },
    "attachments": [
      {
        "type": "photo",
        "photo": {
          "pid": 390809363,
          "aid": -7,
          "owner_id": 262860615,
          "src": "http://cs630730.vk.me/v630730966/79f6/iOuw0G0VQEU.jpg",
          "src_big": "http://cs630730.vk.me/v630730966/79f7/DAb9CWXnkIs.jpg",
          "src_small": "http://cs630730.vk.me/v630730966/79f5/Xvfjrfarl-0.jpg",
          "src_xbig": "http://cs630730.vk.me/v630730966/79f8/Bq1PCVh-Vtc.jpg",
          "src_xxbig": "http://cs630730.vk.me/v630730966/79f9/HAObuNAuHoo.jpg",
          "src_xxxbig": "http://cs630730.vk.me/v630730966/79fa/-E2Af002T88.jpg",
          "width": 1280,
          "height": 1303,
          "text": "",
          "created": 1449870242,
          "access_key": "fdd1ae4d80f94d4a18"
        }
      },
      {
        "type": "photo",
        "photo": {
          "pid": 390809755,
          "aid": -7,
          "owner_id": 262860615,
          "src": "http://cs630729.vk.me/v630729966/4a76/orT_8_qthiA.jpg",
          "src_big": "http://cs630729.vk.me/v630729966/4a77/K0QLc8rRUfY.jpg",
          "src_small": "http://cs630729.vk.me/v630729966/4a75/cor_b-a7IiI.jpg",
          "width": 500,
          "height": 482,
          "text": "",
          "created": 1449870516,
          "access_key": "640b08963dd9795dbb"
        }
      },
      {
        "type": "audio",
        "audio": {
          "aid": 420732348,
          "owner_id": 2000439051,
          "artist": "Lorenzo & StikkyLips",
          "title": "Naughty Good Girl",
          "duration": 278,
          "url": "http://cs611718.vk.me/u290013611/audios/459adb465479.mp3?extra=FzMK1A0848lQToR1Yko5faH-dPX8aNfO9k1WqP0UbhpkfxQNF3hyK3XC8tRo2PDrrD1eftyaI6LcIcoI6dDLdLfKat9nm-WUlGI",
          "performer": "Lorenzo & StikkyLips",
          "genre": 18
        }
      }
    ],
    "post_source": {
      "type": "vk"
    },
    "comments": {
      "count": 0,
      "can_post": 0
    },
    "likes": {
      "count": 9,
      "user_likes": 0,
      "can_like": 1,
      "can_publish": 1
    },
    "reposts": {
      "count": 0,
      "user_reposted": 0
    },
    "online": 0,
    "reply_count": 0
  }
]}`

**Comment by CaCTuCaTu4ECKuu** [comment]
У вас неправильно скомпилировалось и версия VkApi не подставилась из методов (ответ как у старой версии VkApi. Отсюда и ошибка.
Я не помню что там нужно делать, скачать все заново и попробовать пересобрать с нуля, где то уже не раз было об этом сказано - в случае NullReference проверяйте передается ли версия VkApi при отправке на сервер!

**Comment by azhidkov** [comment]
@HarkBack вы установили версию из nuget или сами собрали?

**Comment by HarkBack** [comment]
Сам собрал, так как на nuget версия без прокси. Ок, сейчас попробую решить

**Comment by inyutin-maxim** [comment]
Каков статус проблемы?

**Comment by HarkBack** [comment]
Не стал решать, так как комманда после сборки "$(TargetDir)Injector.exe" всегда выдавало ошибку, а библиотек к проекту Injector нету.

**Comment by HarkBack** [comment]
И прокси мне в данный момен не нужны пока что.

**Comment by inyutin-maxim** [comment]
@HarkBack  доброго времени суток, скажите каков статус задачи? мои предположения по вашей проблеме. 1е у вас не самая актуальная версия (Обновитесь из гитхаба и проверьте снова), 2е у вас не обновлены библиотеки зависимостей до последних версий это очень важно. Обязательно сообщите о результатах. Спасибо.

**Comment by HarkBack** [comment]
Ошибка может быть вызвана тем, что я убрал из postBuild Injector.exe (что он вообще делает)?

**Comment by kadkin** [comment]
проставляет параметр "api version" из атрибута метода

**Comment by b1tc0re** [comment]
Ребята помогите пожалуйста собрать библиотеку с исходников ?

**Comment by HarkBack** [comment]
По поводу ошибки, если у вас сборка с проксями работает без ошибок, значит это я что то сделал не так.

**Comment by inyutin-maxim** [comment]
@b1tc0re Возьмите здесь [VkNet от 01.02.2016 15:11](https://vk.com/doc32190123_437242762)

**Comment by CaCTuCaTu4ECKuu** [comment]
Нужно где-то описать этот момент с версией API, а эту проблему можно закрывать, дело именно в этом
