### ISSUE TITLE
CarouselElement - Keyboard format is invalid: action contains unknown fields

### ISSUE THREAD

**Issue by xiadosw** [vknet/vk#1604]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. 
Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - [ ] .net 4.5
  - [ ] NETStandard2.0
  - [x] другое. Указать строкой ниже.
  - [x] .net 7.0
  
2. Класс и метод в котором возникла проблема:
VkNet.Categories.MessagesCategory.Send

3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса:

```csharp
        Vk.Messages.Send(new MessagesSendParams
        {
            RandomId = 0,
            Message = "Test",
            PeerId = 1,
            Template = new TemplateBuilder()
                .SetType(TemplateType.Carousel)
                .AddTemplateElement(
                    new CarouselElementBuilder()
                        .AddButton("label", "extra", KeyboardButtonColor.Primary)
                        .SetTitle("Title")
                        .SetDescription("Description")
                        .Build()
                )
                .Build()
        });
```

4. JSON ответа. Для удобства сбора этих данных подключите логи (https://github.com/vknet/vk/wiki/Logging):

```json
{"error":{"error_code":911,"error_msg":"Keyboard format is invalid: template['elements'][0] action contains unknown fields","request_params":[{"key":"method","value":"messages.send"},{"key":"oauth","value":"1"},{"key":"random_id","value":"1705116839050"},{"key":"peer_id","value":"1"},{"key":"group_id","value":"0"},{"key":"template","value":"{\"type\":\"carousel\",\"elements\":[{\"title\":\"Title\",\"description\":\"Description\",\"photo_id\":null,\"photo\":null,\"buttons\":[{\"action\":{\"type\":\"text\",\"payload\":\"{\\\"button\\\":\\\"extra\\\"}\",\"label\":\"label\"},\"color\":\"primary\"}],\"action\":null}]}"},{"key":"v","value":"5.131"}]}}
```

5. Если в примере не указаны конкретные значения параметров запроса укажите их здесь:

6. PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Telegram Chat](https://img.shields.io/badge/Chat-Telegram-0F80C1.svg)](https://t.me/VkDotNet), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
