### ISSUE TITLE
audio.save -> Invalid Hash

### ISSUE THREAD

**Issue by alikhil** [vknet/vk#161]
При попытки сохранить аудио после загрузки выкидывает исключение с сообщением "Invalid Hash". Пробовал вводить поля audio,server,hash [здесь](https://vk.com/dev/audio.save) и это работало. 

![image](http://i.imgur.com/PHAAX60.png)
![im](http://i.imgur.com/7fM2Vz5.png)

**Comment by inyutin-maxim** [comment]
Есть подозрения что причина в том что у нас вызывается устаревшая версия api (v5.21), у меня к сожалению на данный момент нет свободного времени. Как только оно у меня появится я обязательно посмотрю в чем причина, или кто нибудь из моих коллег.

**Comment by inyutin-maxim** [comment]
Исправлено, задачу закрываю.

Пример использования:
``` csharp
// Получить адрес сервера для загрузки.
var uploadServer = _api.Audio.GetUploadServer();
// Загрузить аудиозапись.
var wc = new WebClient();
var responseAudio = Encoding.ASCII.GetString(wc.UploadFile(uploadServer, @"example.mp3"));
// Сохранить загруженную аудиозапись
var audio = _api.Audio.Save(responseAudio);
// Запостить на стену группы
_api.Wall.Post(-1, false, false, "Hello world", new List<MediaAttachment> {audio});
```

**Comment by undefinedjedi** [comment]
На дворе 2020г и эта ошибка повторяется...

**Comment by inyutin-maxim** [comment]
> На дворе 2020г и эта ошибка повторяется...

А если отбросить пафос, и приложить логи дело будет двигаться продуктивнее.
Пока кроме вас никто не жаловался больше.

**Comment by undefinedjedi** [comment]
Можете увидеть следующее
![audio save](https://user-images.githubusercontent.com/54280204/98773062-32244a00-23f9-11eb-8693-ac3d16982d09.png)

**Comment by inyutin-maxim** [comment]
> Можете увидеть следующее
> ![audio save](https://user-images.githubusercontent.com/54280204/98773062-32244a00-23f9-11eb-8693-ac3d16982d09.png)

Приложите пожалуйста участок кода которым пытаетесь загрузить аудио, создание сервера и аплоад

**Comment by chamskra66er** [comment]
Это код из начала поста.


var uploadServer = vkApi.Audio.GetUploadServer();
var wc = new WebClient();
var responseAudio = Encoding.ASCII.GetString(wc.UploadFile(uploadServer, @"fullPathexampleName.mp3"));        
var audio = vkApi.Audio.Save(responseAudio);

**Comment by chamskra66er** [comment]
Это код из начала поста.

`var uploadServer = vkApi.Audio.GetUploadServer();
var wc = new WebClient();
var responseAudio = Encoding.ASCII.GetString(wc.UploadFile(uploadServer, @"fullPathexampleName.mp3"));
var audio = vkApi.Audio.Save(responseAudio);`

**Comment by undefinedjedi** [comment]
Это код из начала поста

`var uploadServer = vkApi.Audio.GetUploadServer();
var wc = new WebClient();
var responseAudio = Encoding.ASCII.GetString(wc.UploadFile(uploadServer, @"fullPathexampleName.mp3"));
var audio = vkApi.Audio.Save(responseAudio);`

**Comment by idchlife** [comment]
Версия API 1.103(пробовал и 1.130). К сожалению Invalid hash.

Код указанный в примере выше.

Если использовать параметры из JSON ответа из консоли тут: https://vk.com/dev/audio.save

Все в порядке. Что библиотека может слать не так, что получается такая ошибка?

**Comment by inyutin-maxim** [comment]
@idchlife Подскажите использовали ли вы [VkNet.AudioBypass](https://github.com/shelln1ght/VkNet.AudioBypass) [nuget](https://www.nuget.org/packages/VkNet.AudioBypassService/)

**Comment by idchlife** [comment]
@inyutin-maxim нет, не использовали. Стоит его попробовать?

**Comment by inyutin-maxim** [comment]
@idchlife Так как VK закрыл публично API аудио, это единственный рабочий подход к закрытому API. Потому без нее любые ошибки могут быть, в том числе и такие. У нас в чате много обсуждали API для аудио. https://t.me/VkDotNet

**Comment by idchlife** [comment]
@inyutin-maxim хмммм я использую vknet.personalApi для работы с аудио. По сути загружаю аудио от сообщества. Через паблик я получаю ошибку что нет прав и т.д.

edit: моя ошибка, нет .personalApi, перепутал с другой библиотекой

**Comment by inyutin-maxim** [comment]
@idchlife Впервые слышу о vknet.personalApi. Предлагаю вам попробовать обсудить с ребятами из сообщества, возможно вам там помогут. про наличие прав интересно, может в правах группы не все разрешено, потому и не дает?

Наше сообщество:  https://t.me/VkDotNet

**Comment by idchlife** [comment]
@inyutin-maxim в сообществе к сожалению есть упоминания об этой проблеме но 0 решений. VkAudioBypass не помогает.

Аутентификацию делаю с ApplicationId, Login, Password, Settings (Settings.All)
В сообществе есть разрешение на добавление аудио.

Вот код что делает прикрепление аудио к сообщению:

```cs

          // .personalApi - апи, которая авторизована с параметрами что я написал выше

          var audioUploadServer = await vkMessageManager.personalApi.Audio.GetUploadServerAsync();

          var formContentAudioPath = new MultipartFormDataContent();
        
          var audioStreamContent = new StreamContent(File.OpenRead(message.AudioPath));
        
          formContentAudioPath.Add(
            audioStreamContent,
            "file",
            Path.GetFileName(message.AudioPath)
          );

          var wc = new WebClient();

          var audioResponse = Encoding.ASCII.GetString(wc.UploadFile(audioUploadServer, message.AudioPath));

          logger.LogInformation($"Audio UPLOAD RESULT: {audioResponse}");

         // ПАДАЕТ ТУТ Invalid Hash
          Audio audio = await vkMessageManager.personalApi.Audio.SaveAsync(
            audioResponse,
            null,
            message.AudioFilename != null ? message.AudioFilename : "audio.mp3"
          );
        
          nativeMessage.Attachments = new List<MediaAttachment>() {
            audio
          };
```

**Comment by idchlife** [comment]
Для тех кто столкнулся с подобной проблемой:

С Vk.Net апи проще загрузить аудио в сообщество ручками и после добавлять ссылку на него (найти ссылку можно через консоль браузера, вида https://vk.com/audio-5252532_45253) в конце текстового сообщения. ВК подхватит ссылку и добавит сам аудио в конце сообщения.

Да, ссылка все еще будет в тексте, но что поделать.

Не нашел, как отправлять audio_message в этой апи. В питоновской либе возмога есть прикреплять attachment вида "audio-5252532_45253", так что если вы с ней работаете вам проще, можете без ссылки в тексте отправлять.
