### ISSUE TITLE
Работа с товарами

### ISSUE THREAD

**Issue by ivanovevgeny** [vknet/vk#162]
С 1 января 2016 VK API поддерживает работу с товарами. 
https://vk.com/dev/market
Планируется ли реализация методов для работы с товарами в ближайшее время?

**Comment by inyutin-maxim** [comment]
Доброго времени суток, планируется, раз уж вы задачу завели))

**Comment by inyutin-maxim** [comment]
Готовы все методы кроме некоторых, так как есть проблемы с проверкой их работоспособности, в связи с чем откладывается на некоторое время их реализация.
Нереализованные методы:
- [ ]  http://vk.com/dev/market.reorderItems - Изменяет положение товара в подборке.
- [ ]  http://vk.com/dev/market.add - Добавляет новый товар.
- [ ]  http://vk.com/dev/market.edit - Редактирует товар.

**Comment by inyutin-maxim** [comment]
Пример использования метода http://vk.com/dev/market.add
``` csharp
// Получить адрес сервера для загрузки.
var uploadServer = Api.Photo.GetMarketUploadServer(103292418, true, 5,5,200);
// Загрузить фотографию.
var wc = new WebClient();
var responseImg = Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, @"test.jpg"));
// Сохранить загруженную фотографию
var photo = Api.Photo.SaveMarketPhoto(103292418, responseImg);
Api.Market.Add(new MarketProductParams
{
	OwnerId = -103292418,
	CategoryId = 200,
	MainPhotoId = photo.FirstOrDefault().Id.Value,
	Deleted = false,
	Name = "Телефон",
	Description = "Описание товара",
	Price = 10000
});
```

**Comment by inyutin-maxim** [comment]
Все методы реализованы, считаю задачу закрытой

**Comment by OlXC** [comment]
Один метод забыл  ,добавление в Недоступные товары и обратно.
