### ISSUE TITLE
Фото из поста

### ISSUE THREAD

**Issue by makeross** [vknet/vk#163]
Как сформировать attachment?

**Comment by inyutin-maxim** [comment]
доброго времени суток, сформировать аттачмент можно как минимум 2мя способами, загрузить из файла в вашей файловой системе или из уже загруженного на сервер vk. какой именно вас способ интересует?

**Comment by makeross** [comment]
Скопировать пост нужно в отдельный attachment. Я не могу понять как он формируется😦чтобы добавить его в новый пост. Он пишет что не может сконвертировать в mediaattachments

**Comment by inyutin-maxim** [comment]
Вопрос решен в личной переписке, задачу закрываю
