### ISSUE TITLE
Description/Dispay attributes

### ISSUE THREAD

**Issue by ProESM** [vknet/vk#164]
Приветствую!

Очень классная библиотека. Большое спасибо! В принципе, если нужны будут руки для помощи в расширении/дополнении - готов участвовать.

У меня такой вопрос - для многих enum (к примеру, UserSort и т.п.) было бы неплохо добавить рядом со элементами еще и аттрибут Description/Dispay для локализации значений и удобоваримому отображению (к примеру, русскоязычному). Данные enum можно использовать напрямую в качестве DataSource.

На данный момент я постоянно после обновления библиотеки из вашего репозитория добавляю вручную эти аттрибуты. Было бы неплохо, если они изначально были у вас. Избавило бы от лишних манипуляций.

Думаю, многим бы пригодилось. Что скажете?

**Comment by CaCTuCaTu4ECKuu** [comment]
Предлагайте пулл реквест, все хорошие предложения будут добавлены

**Comment by ProESM** [comment]
Хорошо. Обязательно сделаю. Все вместе мы сделаем библиотеки самой лучшей ;-)

**Comment by inyutin-maxim** [comment]
@ProESM Сделайте пулреквест, а мы подумаем над вашим предложением)

**Comment by inyutin-maxim** [comment]
@ProESM я задачу закрываю, присылайте пулреквесты, мы будем их рассмотривать и принимать, спасибо за участие.
