### ISSUE TITLE
UserSearchParams и Status

### ISSUE THREAD

**Issue by ProESM** [vknet/vk#165]
Приветствую!

Заметил, что для Status в значениях по умолчанию используется "(MaritalStatus) 0".
К тому же, тип значений не предполагает пустого значения (null).
При поиске пользователей (метод Search) не всегда задают статус пользователя. Но так как данное поле не предполагает пустого значения и по умолчанию выставляется 0, то во многих случаях результат запроса не соответствует ожидаемому. Получает, что нельзя задать поиск пользователей не указав явно какой-либо статус.

У себя изменил тип поля:
public MaritalStatus Status -> public MaritalStatus? Status.

Это позволило выполнять запросы поиска без указания статуса.

**Comment by inyutin-maxim** [comment]
Спасибо, учтем в следующем релизе

**Comment by inyutin-maxim** [comment]
Исправлено.
