### ISSUE TITLE
Невозможно получить фотографии из альбома методом Photo.Get

### ISSUE THREAD

**Issue by kpohodyaschiy** [vknet/vk#167]
Относительно недавно в vknet метод Photo.Get был изменен на передачу параметров через структуру VkNet.Model.RequestParams.Photo.PhotoGetParams, в которой AlbumId передается как  PhotoAlbumType : SafetyEnum<PhotoAlbumType>, что делает невозможным указание альбома по идентификатору, а позволяет получать только из служебных альбомов (Профиль, сохраненные фото, стена). Исправьте плиз, чтобы можно было так же указывать long albumID как это и задумано по протоколу.

**Comment by inyutin-maxim** [comment]
Исправлено. Пример использования:

``` csharp
int count;
var photos = Api.Photo.Get(out count, new PhotoGetParams
{
	AlbumId = PhotoAlbumType.Id(-7)
});
```

**Comment by kpohodyaschiy** [comment]
Thank you wery much!
Я даже как то не надеялся )

**Comment by inyutin-maxim** [comment]
Всегда пожалуйста
