### ISSUE TITLE
NuGet: Не удается найти пакет "VkNet"

### ISSUE THREAD

**Issue by HarkBack** [vknet/vk#169]
Я не знаю где ещё у кого задать такой вопрос. В интернете ничего не нашел. Не могу установить VkNet из Nuget:
```
PM> Install-Package VkNet
Install-Package : Не удается найти пакет "VkNet".
строка:1 знак:16
+ Install-Package <<<<  VkNet
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

**Comment by inyutin-maxim** [comment]
То есть у вас не устанавливается пакет из nuget?

**Comment by HarkBack** [comment]
Ага

**Comment by HarkBack** [comment]
Решил проблемму.

**Comment by inyutin-maxim** [comment]
хм, странно, я сейчас попробовал на стороннем проекте все ок, в качестве временного решения предлагаю вам архив с только что собранной библиотекой [VkNet](https://vk.com/doc32190123_437178341?hash=ad82d23eebcd3be9c5&dl=e5c983600fc2ca961e)

**Comment by inyutin-maxim** [comment]
Спасибо. Думаю можно закрывать?

**Comment by HarkBack** [comment]
Да. Странно что из двух источников пакетов (Nuget и MS and .NET) работает только All.
