### ISSUE TITLE
message send

### ISSUE THREAD

**Issue by kadkin** [vknet/vk#171]
Проблема такая, сообщения не могут отправится пользователю, если к нему ни разу не отправляли сообщения.
Ошибка "Permission to perform this action is denied"
разрешения выставляю All, пользователь в друзьях.
Но после того как напишешь хотя бы одно сообщение, то все в порядке.
в отправке указываю только 
UserId
Message
Guid

**Comment by CaCTuCaTu4ECKuu** [comment]
А пользователь разрешил отправлять ему сообщения? Вы у него не в черном
списке?

**Comment by kadkin** [comment]
в том то и дело что нет, через сайт отправляется, но после того как сообщение через сайт напишешь , то уже нормально отправляется

**Comment by kadkin** [comment]
только что попробовал пачку из 50 сообщений, отправились только 17 и после уже не отправляется, интервал 10 секунд, captcha проверяется автоматически

**Comment by kadkin** [comment]
может есть какое-то ограничение на вызов метода с приложения на 1 человека

**Comment by CaCTuCaTu4ECKuu** [comment]
Проверьте запросы м ответы все через http analyzer, что в ответ приходит?

**Comment by inyutin-maxim** [comment]
Пожалуйста сообщите о статусе проблемы. Если проблема не решена то проверьте выполнение этих условий:
900 - Нельзя отправлять сообщение пользователю из черного списка 
901 - Нельзя первым писать пользователю от имени сообщества.

**Comment by kadkin** [comment]
Добрый день, когда тестировал ошибка была 
"7 Нет прав для выполнения этого действия"
https://vk.com/dev/errors
сейчас еще не тестировал, с работы приду протестирую
-пользователь не из черного списке
-я не от имени сообщества отправляю сообщения

**Comment by inyutin-maxim** [comment]
@kadkin Свяжитесь со мной завтра во второй половине дня https://vk.com/inyutin_maxim

**Comment by inyutin-maxim** [comment]
@kadkin Каков статус проблемы? и пожалуйста скажите какие права имеет ваше приложение?

**Comment by kadkin** [comment]
посмотрел в логах , так же встречается эта ошибка, права All (в проблеме все описано), сейчас посмотрю конкретнее, попробую посмотреть на комп ошибка встречается

**Comment by CaCTuCaTu4ECKuu** [comment]
Вообще сколько были такие косяки это был где то косяк человека. Хот я не исключаю что может и какая-то ошибка. Сделайте пожалуйста подробный анализ отправляемых данных через HttpAnalyzer или подобную программу и посмотрите поточнее что отправляется и приходит в заголовках запросов. Посмотрите чем отличаются запросы которые выполняются успешно от тех что фейлятся. Сделайте это и будет сразу понятно в чем проблеса - в вк, в аккаунте или в библиотеке.

**Comment by kadkin** [comment]
да я понимаю, надо отловить человека к которому не доходят.
на праздниках если время будет посмотрю, нужно аккаунт спросить с которого
работает приложение и проверить уже

С уважением, Кадкин Игорь
+79199635059
igor@kadkin.com

4 марта 2016 г., 15:49 пользователь CaCTuCaTu4ECKuu <
notifications@github.com> написал:

**Comment by CaCTuCaTu4ECKuu** [comment]
Вы можете в коде прописать чтобы все ексепшины и действия в файл, например, логировались. Но просмотреть трафик все равно нужно. Во время ошибки смотрите какие данные последними были отправлены и какой пришел ответ

**Comment by inyutin-maxim** [comment]
@kadkin , @CaCTuCaTu4ECKuu  хм, столкнулся с той же проблемой, но это не проблема библиотеки, это видимо баг самого апи вк

**Comment by inyutin-maxim** [comment]
@kadkin , @CaCTuCaTu4ECKuu Задал вопрос ВК на что мне ответили что это защитный механизм vk и что я исчерпал какой то определенный лимит, из за чего выкидывает эту ошибку:

> 
> Максим Инютин
> messges.send vk api 5.45 очень странно себя ведет, не отправляет сообщение человеку если никогда ему раньше не писал, возвращает ошибку 7 Нет прав для выполнения этого действия. хотя из интерфейса сайта я могу написать этому человеку.
> 9 мар 2016 в 14:00|Удалить вопрос
> 
> Агент поддержки #1270
> Добрый вечер!
> 
> Укажите, пожалуйста, ссылку на этого пользователя.
> 
> С уважением,
> Команда поддержки ВКонтакте
> 9 мар 2016 в 22:25|Это хороший ответ|Это плохой ответ
> 
> Максим Инютин
> Я написал сценарий который поименно поздравлял всех девушек у меня в друзьях с 8м марта, и на некоторых возвращался код ошибки указанный выше, например на ней: https://vk.com/id192191023
> 9 мар 2016 в 22:30
> 
> Максим Инютин
> Так же к примеру ей ( https://vk.com/id122029167 ) не отсылалось из программы, а в ручную получилось
> 9 мар 2016 в 22:34
> 
> Агент поддержки #1270
> То есть, перед появлением ошибки Вы довольно много однотипных запросов делали, верно?
> 11 мар 2016 в 7:28|Это хороший ответ|Это плохой ответ
> 
> Максим Инютин
> Все так, был шаблонный текст с разницей что обращение по имени подставлялось, 21 сообщение разным людям отправилось без проблем, но ладно я бы понял что больше никому из кода не отправится, но я из любопытства обернул код в try ... catch , ошибки я пропускал (выводил на экран код и текст ошибки), и сообщение отправилось еще некоторым людям из оставшегося списка. затем я решил повторить эксперимент вдруг еще кому то отправится, но все кто остался у всех падала ошибка. Спасибо
> 11 мар 2016 в 9:08
> 
> Агент поддержки #1027
> Скорее всего, вы уперлись в лимит на однотипные действия, но почему-то вернулась некорректная ошибка.
> 12 мар 2016 в 4:38|Вы оставили положительный отзыв
> 
> Максим Инютин
> Мне просто важно узнать почему именно так происходит, я поддерживаю библиотеку с вашим API для .NET и эта ошибка происходит не только у меня
> 12 мар 2016 в 4:41
> 
> Агент поддержки #1270
> Максим, иных причин, кроме антиспам-лимита, в данной ситуации нет.
> 12 мар 2016 в 15:47|Вы оставили положительный отзыв
> 
> Максим Инютин
> Спасибо большое
> сегодня в 9:11
> 
> Максим Инютин
> Такой вопрос а почему вместо этой ошибки не возвращается ошибка с капчей? на мой взгляд это было бы правильнее, если можно ваши комментарии. Спасибо
> сегодня в 9:26
> 
> Агент поддержки #1270
> Потому что это не совсем тот же лимит, что и с капчей. Капча появляется, когда Вы часто совершаете действия. А здесь Вы их могли совершать не часто, но очень много.
> сегодня в 22:12|Вы оставили положительный отзыв
> 
> Максим Инютин
> Ну что ж, спасибо за помощь. Всего доброго

**Comment by CaCTuCaTu4ECKuu** [comment]
Мне кажется есть смысл подолбить поддержку еще чтобы ответил кто то более
компетентный, потому что "скорее всего" и "наверное" не оч то определенно.
Напиши ему чтобы он уточнил у разрабов, потому что нет нормального
оповещения о невыполненном действии и мутно все. Там по картинке будет
видно что ответил не обычный агент поддержки, а типа гуру
>
>

**Comment by CaCTuCaTu4ECKuu** [comment]
Напиши еще раз этому типу из техподдержки. Он не то разжевал, такой ошибки не должно быть и это не ошибка лимита т.к. если я правильно понял то падает она на рандомных людях и при повторной попытке тоже падает, если бы это был лимит то это срабатывало бы не на конкретных людей. Короче он нубас какой-то. У тебя код остался которым ты проверял - проверь есть ли еще и если есть я тоже попробую списаться

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu блин да как то неудобно, топик то уже закрыли, мож ты напишешь? кода увы нет, я просто выбирал всех девченок и по шаблону генерил поздравления с 8м марта
