### ISSUE TITLE
Document.Preview - ошибка при получении URI для response["photo"]

### ISSUE THREAD

**Issue by digitallez** [vknet/vk#177]
Во вложении документ, при получении его превью исключение "Can not convert Object to String."
Суть проблемы в том, что response["photo"] - не является объектом URI, а является объектом Photo:
``` csharp
internal static Previews FromJson(VkResponse response)
{
	var previews = new Previews
	{
		Photo50 = response["photo_50"] /* ?? response["photo"]*/,  //<< падает здесь.
		...
	}
}
```

**Comment by inyutin-maxim** [comment]
@digitallez  Доброго времени суток укажите пожалуйста при вызове какого метода падает ошибка. Так же укажите откуда брали библиотеку, из гитхаба или nuget

**Comment by inyutin-maxim** [comment]
У меня сейчас нет времени я завтра изучу вашу проблему подробнее

**Comment by digitallez** [comment]
Доброго. Спасибо. Это не к спеху. Брал из гитхаба - тут более новая версия. 
Метод: WallCategory.Get(WallGetParams params)
Вот текст исключения:

System.ArgumentException: Can not convert Object to String.
   в Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   в VkNet.Utils.VkResponse.op_Implicit(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponse.cs:строка 138
   в VkNet.Utils.VkResponse.op_Implicit(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponse.cs:строка 190
   в VkNet.Model.Previews.FromJson(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Model\Previews.cs:строка 51
   в VkNet.Utils.VkResponse.op_Implicit(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseToModelCastsGenerator.cs:строка 760
   в VkNet.Model.Attachments.Document.FromJson(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Model\Attachments\Document.cs:строка 71
   в VkNet.Utils.VkResponse.op_Implicit(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseToModelCastsGenerator.cs:строка 256
   в VkNet.Model.Attachments.Attachment.FromJson(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Model\Attachments\Attachment.cs:строка 190
   в VkNet.Utils.VkResponse.op_Implicit(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseToModelCastsGenerator.cs:строка 67
   в VkNet.Model.Post.<>c.<FromJson>b__111_0(VkResponse x) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Model\Attachments\Post.cs:строка 210
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseEx.cs:строка 38
   в VkNet.Utils.VkResponseEx.ToReadOnlyCollectionOf[T](VkResponse response, Func`2 selector) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseEx.cs:строка 51
   в VkNet.Model.Post.FromJson(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Model\Attachments\Post.cs:строка 195
   в VkNet.Utils.VkResponse.op_Implicit(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseToModelCastsGenerator.cs:строка 724
   в VkNet.Model.WallGetObject.<>c.<FromJson>b__16_0(VkResponse r) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Model\WallGetObject.cs:строка 46
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseEx.cs:строка 38
   в VkNet.Utils.VkResponseEx.ToReadOnlyCollectionOf[T](VkResponse response, Func`2 selector) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseEx.cs:строка 51
   в VkNet.Model.WallGetObject.FromJson(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Model\WallGetObject.cs:строка 43
   в VkNet.Utils.VkResponse.op_Implicit(VkResponse response) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Utils\VkResponseToModelCastsGenerator.cs:строка 1039
   в VkNet.Categories.WallCategory.Get(WallGetParams params) в D:\MyDoc\GitHubVisualStudio\vk\VkNet\Categories\WallCategory.cs:строка 84

**Comment by inyutin-maxim** [comment]
исправлено
