### ISSUE TITLE
Wall.GetById - несколько методов с очень похожей сигнатурой

### ISSUE THREAD

**Issue by digitallez** [vknet/vk#182]
Добрый день, господа. 
Проблема, совсем не критичная: не удается использовать новый метод 
`WallGetObject = Wall.GetById(Posts);`
где Posts это `IEnumerable<string>`
ругается: 
`Не удается неявно преобразовать тип "System.Collections.ObjectModel.ReadOnlyCollection<VkNet.Model.Post>" в "VkNet.Model.WallGetObject".`
Приходится писать так: 
`WallGetObject = Wall.GetById(Posts, null);`
Как бы проблема на самом деле вовсе и не проблема (null вторым параметром мне вообще никак не мешает), но как-то "не красиво получается".
Может я что-то не так делаю ?

----------
P.S.: Студия (или решарпер) подсвечивает в вашем методе второй параметр `bool? extended = null` с сообщением: "method with optional parameter is hidden by overload"

**Comment by inyutin-maxim** [comment]
@digitallez  В следующем релизе я думаю поправим, делаете все так

**Comment by inyutin-maxim** [comment]
@digitallez Исправлено
