### ISSUE TITLE
Updating your Markdown processor to Kramdown

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#183]
https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/

**Comment by inyutin-maxim** [comment]
@azhidkov Антон привет, если у тебя будет время, то нужна помощь по этой задаче, я лично с этим не сталкивался, выйди со мной на связь или здесь, или [вк](https://vk.com/inyutin_maxim)

**Comment by azhidkov** [comment]
Привет, документацию сегодня поправил. Из новых особенностей, при указании ссылок нельзя делать пробел между скобками (см. https://github.com/vknet/vk/commit/424f565459657987c7a22caefa673e7bb3e0236c) и должна быть обязательно пустая строка между заголовками (см. https://github.com/vknet/vk/commit/cf3a044ea6e1c4b48ba51535e1260fbd6975624c)
