### ISSUE TITLE
Как распознать смайлики в комментариях ?

### ISSUE THREAD

**Issue by mdibm** [vknet/vk#185]
Добрый день.
Пишу на C# .Net 4.0 
Создал на форме DataGridView 
Заполняю таблицу комментариями к постам группы WallID
```
int total_count;
ReadOnlyCollection<Comment> AllComments = api.Wall.GetComments(WallID, PostID, out total_count, null, false, 100, 0, 0);
foreach (var CurComment in AllComments)
  {
       //Здесь получаю текст комментария
       Text = CurComment.Text;
       
   }
```
Вопрос: Какой метод/способ позволит получать информацию о смайликах в тексте ? Сейчас у меня в DataGridView  выходят квадратики. Или это проблема с кодировкой?

**Comment by inyutin-maxim** [comment]
@mdibm Я так полагаю что все таки причина кроется в кодировке, нет метода получения смайлов

**Comment by CaCTuCaTu4ECKuu** [comment]
Смайлы это символы юникода, а если вы хотите выхватывать смайлы как ВК то вам нужно создать изображение с вашими смайлами и научить ваш элемент выводить их вместе с текстом

**Comment by DezmontDeXa** [comment]
Вообще в самом апи есть метод получения смайлов. Нужно лишь получить каким-то образом спец-символ. Может кто подскажет где кодировку нужно изменять?

**Comment by inyutin-maxim** [comment]
@DezmontDeXa 
> Вообще в самом апи есть метод получения смайлов.
Можно метод?
