### ISSUE TITLE
Для фильтров не хватает полей (Photo400Orig и т.д.)

### ISSUE THREAD

**Issue by mokeev1995** [vknet/vk#186]
при запросе пользователей у группы (а может и в других местах, не проверял) нет возможности взять у пользователя большую аватарку. Т.е. Photo400Orig, PhotoMaxOrig, PhotoMax, хотя в самом профиле это есть

Как я понимаю, достаточно добавить в класс UserFields соответствующие статические поля.

создал пулл-реквест #187 

Обнаружил, что это еще не все поля, которых не хватает, сейчас еще допилю

- [x] Nickname
- [x] Domain
- [x] Sex
- [x] BirthDate
- [x] City
- [x] Country
- [x] Timezone
- [x] Photo50
- [x] Photo100
- [x] Photo200Orig
- [x] Photo200
- [x] Photo400Orig
- [x] PhotoMax
- [x] PhotoMaxOrig
- [x] HasMobile
- [x] Contacts
- [x] Education
- [x] Online
- [x] OnlineMobile
- [x] FriendLists
- [x] Relation
- [x] LastSeen
- [x] Status
- [x] CanWritePrivateMessage
- [x] CanSeeAllPosts
- [x] CanPost
- [x] Universities
- [x] Connections
- [x] Site
- [x] Schools
- [x] CanSeeAudio
- [x] CommonCount 
- [x] Relatives
- [x] Counters

**Comment by mokeev1995** [comment]
#187

**Comment by mokeev1995** [comment]
Обнаружил, что это еще не все поля, которых не хватает, сейчас еще допилю

**Comment by mokeev1995** [comment]
Готово к слиянию

**Comment by inyutin-maxim** [comment]
Принял ваши исправления, задачу закрываю
