### ISSUE TITLE
Предложение по методу Authorize 

### ISSUE THREAD

**Issue by Insiderto** [vknet/vk#188]
Предлагаю ему возвращать bool при успешной авторизации.

**Comment by mokeev1995** [comment]
не вижу смысла, есть же поле IsAuthorized

**Comment by CaCTuCaTu4ECKuu** [comment]
@Insiderto раньше проверка осуществлялась по наличию AccessToken, сейчас есть поле isAuthorized, возможно что-то и будет когда-то возвращаться при вызове этого метода, но смысла в этом сейчас нет т.к. есть авторизация напрямую по токену, а не через логин пароль, а практичности к коду это особо не добавит
