### ISSUE TITLE
Добавление ассинхронности

### ISSUE THREAD

**Issue by mokeev1995** [vknet/vk#189]
Всё хорошо, но надо бы добавить async/await

**Comment by mokeev1995** [comment]
@inyutin-maxim и @azhidkov  и кто тут еще контрибьютит, обратите внимание)

**Comment by mokeev1995** [comment]
@CaCTuCaTu4ECKuu Тоже можешь сюда глянуть

**Comment by CaCTuCaTu4ECKuu** [comment]
@inyutin-maxim я думаю стоит для каждого набора методов создавать свой файл, в одном файле методы, которые принимают параметры одним обьектом, во втором файле перегруз тех же методов но асинхронный, а в третьем файле только пару основных значений принимающих внутри которых будет просто преобразование в что-то-тамObject и возвращение метода принимающего один параметр, мне кажеться если делать перегрузку методов в одном месте то там все настолько забьется. Или еще один вариант - написать .tt сценарий и продумать как с одного метода чтобы автоматически создавались асинхронные и несколько синхронных файлов

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu Привет, насчет асинхронных методов согласен. Предлагаю поступить следующим образом: создаем ***CategoryAsync.tt шаблон который генерит асинхронные методы, но перед этим каждый класс в котором есть методы помеченные как obsolete необходимо перенести в ***Category.Obsolete который будет partial Для ***Category и содержать в себе все устаревшие методы. Я не хочу чтобы они путались в основных классах. Комментарии, предложения?

**Comment by CaCTuCaTu4ECKuu** [comment]
Дада, именно это я и предлагал

понедельник, 15 февраля 2016 г. пользователь inyutin-maxim написал:

**Comment by CaCTuCaTu4ECKuu** [comment]
Займусь этим сегодня

понедельник, 15 февраля 2016 г. пользователь Влад Іващенко написал:

**Comment by CaCTuCaTu4ECKuu** [comment]
Я просто отписываюсь что да как. Короче насчет шаблона, я начал разбирать что нужно и понял что это тупо брать синхронный код, парсить его и формировать асинхронный и тот который с перегрузками принимает основные параметры потому что это сложно будет реализовать в шаблоне. Если делать таким образом, то нужно в каком-то одном формате полностью все переписать и описать это так, чтобы там отметки было удобно считывать насчет того какие переменные выносить в принимаемые параметры, какие нет, каким образом в каком месте асинхронность конкретно должна реализовываться, в общем я не смог определиться как и какой шаблон писать для всей библиотеки.

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu Предлагаю пообщаться вечером в skype и обсудить этот вопрос

**Comment by andrshevch** [comment]
как вы будете асинхронность реализовывать? асинхронные веб реквесты?

**Comment by andrshevch** [comment]
как-то в Task.Run пихать не хочеться

**Comment by mokeev1995** [comment]
@inyutin-maxim как дела с асинхронностью?

**Comment by inyutin-maxim** [comment]
Плохо) как и со свободным временем)

**Comment by CaCTuCaTu4ECKuu** [comment]
Для полноценной реализации асинхронности нужно сделать асинхронную версию базового метода вызова веб реквеста и ту часть, где идут тайминги и прочее проверить чтобы корректно работала.
Но учитывая то, что мы имеем апи такой вот можно просто запихивать весь код в Task.Run и все будет работать вполне себе хорошо.
Вот еще мысль появилась. Сделать асинхронный базовый метод, как я сказал сразу, но вместо дублирования всех методов, создать метод, который принимает функцию и оборачивает ее в Task.Run чтобы можно было вызывать что-то вроде await API.CallAsync(Api.Messages.Get(params));
Но не знаю можно ли такое реализовать чтобы результат был, хотя можно результат приводить вручную. В принципе если горит асинхрон то можно такой сделать костыль, с одной стороны, а с другой вполне себе жизнеспособный вариант

**Comment by n0namer** [comment]
Господа, а чем история с асинхронностью закончилась?

**Comment by mokeev1995** [comment]
@n0namer берёшь таск и...
проще говоря -- ничем)

**Comment by EarsKilla** [comment]
@ghost а что не так с асинхронными веб реквестами? 🤔

**Comment by mokeev1995** [comment]
@EarsKilla да ничего, что с ними может быть не так, если их нет :D

**Comment by inyutin-maxim** [comment]
@mokeev1995 @EarsKilla Точно ребят)) это масштабная задача, на нее нужно много времени, в этом году не будет скорее всего, хотя все может быть

**Comment by EarsKilla** [comment]
@mokeev1995 у того же `WebRequest` есть же асинхронные методы 🤔

**Comment by mokeev1995** [comment]
@EarsKila ага, только это api надо раскинуть на все методы :) так то несколько часов работы там точно есть :)

**Comment by inyutin-maxim** [comment]
@mokeev1995 @n0namer @EarsKilla кто хотел асинхронных методов собирай из github

**Comment by mokeev1995** [comment]
@inyutin-maxim как я понял, там не то чтоб очень настоящая асинхронность, да?) Task.Factory.StartNew -- это, конечно, хорошо, но внутри то операции всё так же синхронны..)

**Comment by inyutin-maxim** [comment]
@mokeev1995 ну в целом примерно так, если хотите настоящей асинхронности, то я готов принимать пулл реквесты)) у меня времени хватило на это. Просто нет особо желания поддерживать в 2х местах один и тот же код

**Comment by inyutin-maxim** [comment]
@mokeev1995 по факту основной массе нужно чтобы не висел ui поток, он не будет висеть
