### ISSUE TITLE
Ну никак не подружусь с Wall.Get

### ISSUE THREAD

**Issue by micl1962** [vknet/vk#19]
var user = vk.Users.Get(@"hzzzarium", ProfileFields.All);
long userID = user.Id;
var lsW = vk.Wall.Get(userID, out cou, 1, 0, WallFilter.Owner);
var user3=vk.Users.Get(@"svetka_v_baletkah", ProfileFields.All)
var lsW1 = vk.Wall.Get(user3.ID, out cou, 1, 0, WallFilter.Owner);
оба обращения выдают исключение
"Ссылка на объект не указывает на экземпляр объекта." 
т.е.сейчас просто не удается получить вообще никакие записи со стены((
VkNet 1.0.4 установил NuGet-ом
Простите великодушно меня бестолкового - что я делаю не так????
Windows 7. VS 2012. NET Framework 4.5 (до 4.5.1 не обновлял пока)
Спасибо.

**Comment by igorlevashov** [comment]
Здравствуйте, а у меня возникает такая ошибка: The type 'market' of attachment is not defined.”
