### ISSUE TITLE
метод audio.search не передает параметр count.

### ISSUE THREAD

**Issue by beqabeqa473** [vknet/vk#195]
здравствуйте.

метод audio.search не передает в url параметр count.

делаю так.

int totalCount = 300;
var audiolist = vk.audio.search(textbox1.Text, out totalCount);

может я что-то делаю не правильно?

спасибо заранее за помощь.

**Comment by azhidkov** [comment]
Добрый день,

в параметре out totalCount возвращается общее количество записей удостоверяющий критерию поиска. Для задания количества записей в выборке вам необходимо указать параметр count (не totalCount), см. https://github.com/vknet/vk/blob/master/VkNet/Categories/AudioCategory.cs#L289

**Comment by beqabeqa473** [comment]
спасибо, сделал.

**Comment by inyutin-maxim** [comment]
Полагаю проблема решена, задачу можно считать закрытой

**Comment by beqabeqa473** [comment]
да спасибо.
