### ISSUE TITLE
Старая версия библиотеки в nuget

### ISSUE THREAD

**Issue by AlexandrButenko** [vknet/vk#196]
Последний коммит с обновлением api 5 дней назад, а последнее обновление nuget библиотеки - в декабре. Как работать с библиотекой?

Надо бы это дело поправить.

**Comment by mokeev1995** [comment]
клонируешь репозиторий, открываешь в VS проект, компилируешь, используешь)
пока не допилит человек все фитчи, как я понял, он не собирается в нугет выкладывать) можешь попытаться ускорить его работу)

**Comment by inyutin-maxim** [comment]
@AlexandrButenko На данный момент, библиотека почти готова к релизу, есть несколько задач которые необходимо покрыть, а пока, либо обращайтесь ко мне за актуальной версией библиотеки, либо как говорит предыдущий оратор, клонировать репозиторий и собрать ее самому.

**Comment by inyutin-maxim** [comment]
Всем страждущим, промежуточные версии буду выкладывать в репозитории в разделе релизы с меткой пре релиз [ссылка](https://github.com/vknet/vk/releases)
