### ISSUE TITLE
Беда с методом поиска групп.

### ISSUE THREAD

**Issue by Mereng** [vknet/vk#197]
`var gr = new VkNet.Model.RequestParams.GroupsSearchParams()`;
`gr.Query = "music";`
`int p;`
`var g = lol.Groups.Search(out p, gr);`
получаем исключение "System.ArgumentException" Can not convert Object to Int32.

Метод в библиотеке с Nuget  работает прекрасно.
P.S Код написал для примера

**Comment by inyutin-maxim** [comment]
Спасибо, исправлено

**Comment by inyutin-maxim** [comment]
@Mereng [ссылка](https://github.com/vknet/vk/releases) на версию с исправлением, иливы можете собрать библиотеку сами
