### ISSUE TITLE
Нашел еще баги в Likes.GetList() и Stars.GetByGroup()

### ISSUE THREAD

**Issue by Mereng** [vknet/vk#198]
var p = new VkNet.Model.RequestParams.LikesGetListParams();
p.OwnerId = -79867008;
p.ItemId = 425;
p.Type = VkNet.Enums.SafetyEnums.LikeObjectType.Post;
lol.Likes.GetList(p);

Ловим System.ArgumentException Can not convert Object to Int64
Со статисткой та же беда. Подозреваю, что могут быть еще где-то, пока тестил только то, что мне нужно

**Comment by inyutin-maxim** [comment]
@Mereng  Спасибо, Я в перспективе собираюсь переписать тесты для всех реализованных методов с помощью чего смогу отловить большую часть скрытых багов, а ваш баг постараюсь поправить в ближайшее время

**Comment by Mereng** [comment]
@inyutin-maxim Спасибо, буду ждать.

**Comment by inyutin-maxim** [comment]
@Mereng Исправлено
