### ISSUE TITLE
метод audiosave: invalid hash.

### ISSUE THREAD

**Issue by beqabeqa473** [vknet/vk#199]
здравствуйте.

может я делаю что-то нетак, но при попытке сохранить аудио мне выдается invalid hash.

вот мой код.

                        var uploadurl = Vk.vk.Audio.GetUploadServer();
                        string filepath = @"d:\1.mp3";
                        var c = new WebClient();
                        string response = Encoding.UTF8.GetString(c.UploadFile(uploadurl, "POST", filepath));
                        Vk.vk.Audio.Save((long)Vk.vk.UserId, response, null, null);

**Comment by inyutin-maxim** [comment]
@beqabeqa473 единственное что может быть не так, так это если версия из nuget, используйте библиотеку [отсюда](https://github.com/vknet/vk/releases) релиз в nuget будет позже. Пожалуйста сообщите помогло ли вам обновление библиотеки

**Comment by beqabeqa473** [comment]
в документации ввк написано что надо передавать хеш.
в этом случае библиотека сама передает или мне надо както его передавать?

**Comment by beqabeqa473** [comment]
скомпилированной библиотеки нет?

**Comment by inyutin-maxim** [comment]
Я готов общаться, вк :  http://vk.com/inyutin_maxim  


>Воскресенье, 21 февраля 2016, 7:36 -08:00 от beqa gozalishvili <notifications@github.com>:
>
>скомпилированной библиотеки нет?
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Максим Инютин
mail: inyutin_maxim@mail.ru,
skype: light_vs_l
vk: http://vk.com/inyutin_maxim
Разработчик .NET

**Comment by inyutin-maxim** [comment]
@beqabeqa473 Напишите мне [ВКонтакте](https://vk.com/inyutin_maxim) или в skype: light_vs_l

**Comment by beqabeqa473** [comment]
спасибо, аудио сохранилось.
