### ISSUE TITLE
Wall.AddComment

### ISSUE THREAD

**Issue by swerux** [vknet/vk#200]
Подскажите как дальше быть. Как приложить документ к посту?
```
WallAddCommentParams wallset = new WallAddCommentParams();
wallset.OwnerId = -666666; // id группы 
wallset.PostId = 6664; // id Поста
wallset.FromGroup = false;
wallset.Text = "test";
wallset.Attachments =  ??? ;
VK.Wall.AddComment(wallset);
```

**Comment by inyutin-maxim** [comment]
@swerux а откуда вы хотите его взять? он уже загружен или вы хотите загрузить его программно?

**Comment by swerux** [comment]
Документ публичный doc164777777_427138888 как пример

**Comment by inyutin-maxim** [comment]
[Docs.getById](https://vknet.github.io/vk/docs/getById/) - После успешного выполнения возвращает список объектов документов.

и результат присваиваете wallset.Attachments =  ??? ;

**Comment by swerux** [comment]
Если Вас не затруднит, можете продемонстрировать пример?

**Comment by inyutin-maxim** [comment]
Вечером на пишу, в данный момент я на работе, на всякий случай свяжитесь со мной вечером часов в 9 по Москве, [мой вк](https://vk.com/inyutin_maxim)

**Comment by inyutin-maxim** [comment]
Пример:
```csharp
var documents = Api.Docs.Get();
Api.Wall.AddComment(new WallAddCommentParams
{
	OwnerId = -103292418,
	Attachments = documents,
	PostId = 9
});
```
