### ISSUE TITLE
audioGenre изменить запись

### ISSUE THREAD

**Issue by beqabeqa473** [vknet/vk#201]
здравствуйте.

в вк есть такой жанр.
1001
Jazz & Blues которого нет в vknet, из-за чего приложение выдает исключение.

пожалуйста, добавьте этот жанр.

**Comment by inyutin-maxim** [comment]
@beqabeqa473 Все не совсем так, данный жанр есть в перечислении (AudioGenre.JazzAndBlues), но действительно была ошибка. Исправлено

**Comment by beqabeqa473** [comment]
да, не совсем правильно выразился, в enum было устаревшее обозначение.
