### ISSUE TITLE
SaveMarketPhoto. crop_data and crop_hash bug

### ISSUE THREAD

**Issue by vrazdobudko** [vknet/vk#202]
Параметры crop_data и crop_hash в saveMarketPhoto должны быть не обязательные.
https://vk.com/dev/photos.saveMarketPhoto

Если передать в Photo.GetMarketUploadServer параметр mainPhoto со значением false. 
То, после загрузки фото, сервер вернёт json без crop_data и crop_hash. И соответственно получим NullReferenceException в  Photo.saveMarketPhoto. 

Пример кода:
```csharp
      var uploadServer = VkApi.Photo.GetMarketUploadServer(groupId, false);
      var wc = new WebClient();
      var responseImg = Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, file));
      var photo = VkApi.Photo.SaveMarketPhoto(groupId, responseImg);
```
У себя поправил так.
VkNet\Categories\PhotoCategory.cs
в public ReadOnlyCollection<Photo> SaveMarketPhoto(long groupId, string response) 

 \-             var cropData = responseJson["crop_data"].ToString();
 \-             var cropHash = responseJson["crop_hash"].ToString();
 \+             var cropData = responseJson["crop_data"]?.ToString();
 \+             var cropHash = responseJson["crop_hash"]?.ToString();

**Comment by inyutin-maxim** [comment]
Исправлено, будет включено в очередную версию
