### ISSUE TITLE
VkResponseToManualEnumCastsGenerator.tt error

### ISSUE THREAD

**Issue by Montigomo** [vknet/vk#204]
Паттерн рассчитан на единоличное присутствие атрибута DefaultValue.
Но, допустим, в классе AddFriendStatus.cs он дополнен другим атрибутом, тут или сложный парсинг, или указывать его последним, ну не работает в том виде что есть сейчас. Написал на скорую для корректной генерации.

    		[DefaultValue]
		[Display(ResourceType = typeof (Resources), Name = "AddFriendStatus_Unknown")]
        Unknown = 0,

к примеру так(хотя коряво)

		var typePattern = @"public\s+enum\s+([a-zA-Z]+?)\s*\{[^\[]*\[DefaultValue\](?:\s*\[Display[^\]]*\])?[^\}]*\}";
		var defaultValuePattern = @"(\[DefaultValue\](?:\s*\[Display[^\]]*\])?\s*?([a-zA-Z][a-zA-Z0-9]*))";

**Comment by inyutin-maxim** [comment]
@Montigomo Я обнаружил уже эту ошибку, руки пока не доходят поправить, Спасибо большое

**Comment by Montigomo** [comment]
Вам спасибо за проделанную работу! )

**Comment by CaCTuCaTu4ECKuu** [comment]
@Montigomo Эта регулярка работает? Я прям сейчас могу внести правку если она корректна

**Comment by azhidkov** [comment]
Лучше проверить самому и не вносить непроверенные изменения в код.

2016-03-03 22:32 GMT+03:00 CaCTuCaTu4ECKuu <notifications@github.com>:

**Comment by CaCTuCaTu4ECKuu** [comment]
Да с виду правильная, просто "на скорую руку" смутило и спросил может эта
не все случаи перекрывает. Чтобы 2 раза не комитить

пятница, 4 марта 2016 г. пользователь azhidkov написал:

**Comment by azhidkov** [comment]
Да лучше всего вообще написать юнит-тесты для этого, чтобы уменьшить
человечский фактор.

2016-03-04 10:13 GMT+03:00 CaCTuCaTu4ECKuu <notifications@github.com>:

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu @azhidkov как появится свободное время если до меня никто не сделает я сделаю.

@azhidkov Мы как то обсуждали вопрос об выпиливании injector'a, есть какие нибудь подводные камни? Так как все реализованные методы приведены к актуальному состоянию API то быть может мы в одном месте будем передавать версию vk api? тесты я все собираюсь переписать потому что добрая часть из них устарела. Напиши мне или [вк](https://vk.com/inyutin_maxim) или [telegram](https://telegram.me/inyutin_maxim) или skype: light_vs_l

**Comment by Montigomo** [comment]
Работает вроде, но мне она не совсем нравится ) частный случай и под конкретный атрибут(Display) где-то была регулярка что вычисляет парные(закрывающиеся) скобки (любые) как время будет поищу и попробую допилить)

**Comment by inyutin-maxim** [comment]
Исправил под любые атрибуты до и после
