### ISSUE TITLE
Необработанное исключение типа "VkNet.Exception.InvalidParameterException"

### ISSUE THREAD

**Issue by WaL97** [vknet/vk#205]
Если в сообщениях, которые пытаемся получить имеются прикрепленные стикеры или посты со стены, то получаем ошибку:

> Необработанное исключение типа "VkNet.Exception.InvalidParameterException" в VkNet.dll
> Дополнительные сведения: The type 'sticker' of attachment is not defined.

или

> Дополнительные сведения: The type 'wall' of attachment is not defined.

- Пример кода для воспроизведения проблемы:
```csharp
  var col = vk.Messages.GetHistory(ChatId, true, out value,null,10);
  richTextBox1.Clear();
  foreach (var qwe in col)
                {
                        richTextBox1.SelectedText = Convert.ToString((qwe.Date + " " + qwe.Body + "\n"));
                }
```

**Comment by inyutin-maxim** [comment]
@WaL97 Сейчас проверим

**Comment by inyutin-maxim** [comment]
По вашей проблеме, для начала возьмите последнюю версию [здесь](https://github.com/vknet/vk/releases/tag/v1.20.1.6) и проверьте. Возможно вы используете версию из nuget, версия с гитхаба не выдает вашу ошибку.

Пример использования: 
```csharp
var chatHisory = _api.Messages.GetHistory(new MessagesGetHistoryParams
{
	PeerId = 2000000035 // id вашего чата
});
var userHistory = _api.Messages.GetHistory(new MessagesGetHistoryParams
{
	UserId = 32190123 // id пользователя с которым вы вели переписку
});
```

Пожалуйста отпишитесь по проблеме

**Comment by inyutin-maxim** [comment]
@WaL97 Здравствуйте, каков статус ошибки?

**Comment by inyutin-maxim** [comment]
@WaL97 Я задачу закрываю, Соберите последнюю версию и если это не исправит ошибку отпишитесь снова
