### ISSUE TITLE
VK Api - messages.getDialogs - Не возвращает непрочитанные диалоги

### ISSUE THREAD

**Issue by yanzhelanov** [vknet/vk#209]
https://api.vkontakte.ru/method/messages.getDialogs?count=0&unread=1&access_token=***
Здравствуйте, Помогите пожалуйста!
Данный запрос выдаёт ошибку 100, даже если дописывать параметр с версией, всё равно выходит ошибка 100.
Кто - нибудь может помочь?

**Comment by inyutin-maxim** [comment]
@yanzhelanov Добрый день, меня немного пугает ссылка которую вы приложили все давно работает через https://api.vk.com+/method/ и наша библиотека именно так обращается к API VK. Отсюда вопрос вы используете нашу библиотеку или что то свое у вас?

**Comment by inyutin-maxim** [comment]
@yanzhelanov так же, вас не смущает что у вас в параметрах count = 0?

**Comment by yanzhelanov** [comment]
@inyutin-maxim Да, я использую свою библиотеку. Параметр "count" на нуле, потому что мне нужно узнавать только кол-во непрочитанных диалогов, а их "body" меня не интересует. Обе ссылки запросов работают, как api.vk.com, так же и api.vkontakte.ru. 
https://api.vk.com/method/messages.getDialogs?unread=1&access_token=***
Даже такой запрос мне возвращает ошибку 100.

**Comment by inyutin-maxim** [comment]
@yanzhelanov Наша библиотека возвращает правильное значение, посмотрите нашу имплементацию, может это вам чем то поможет

Так же:
Вот ответ на запрос https://vk.com/dev/messages.getDialogs?params[count]=0&params[unread]=1&params[v]=5.45
```csharp
response: {
count: 1,
items: []
}
```

В count количество непрочитанных диалогов. Считаю задачу закрытой

**Comment by yanzhelanov** [comment]
Спасибо, @inyutin-maxim ! 
Надо было дописать параметр "v", мой недочёт...

**Comment by inyutin-maxim** [comment]
@yanzhelanov Всегда пожалуйста
