### ISSUE TITLE
Отсутствует ожидание (sleep) между запросами, что приводит к "Too many requests per second".

### ISSUE THREAD

**Issue by DaleTernes** [vknet/vk#210]
VkApi.cs:
`public string Invoke(string methodName, IDictionary<string, string> parameters, bool skipAuthorization = false)
        {`

            if (RequestsPerSecond > 0 && LastInvokeTime.HasValue)
            {
                lock (_expireTimer)
                {
                    var span = LastInvokeTimeSpan.Value;
                    LastInvokeTime = DateTimeOffset.Now;
                    if (span.TotalMilliseconds < _minInterval)
                    {
                        Thread.Sleep(_minInterval - (int)span.TotalMilliseconds);
                    }
                }
            }
Как я вижу - LastInvokeTime всегда null, присвоения нет, поэтому задержки тоже нет.
Исправить бы.

**Comment by CaCTuCaTu4ECKuu** [comment]
Очень хорошо подмечено, я видимо конкретно завтыкал когда рефакторил этот класс что упустил самое главное.

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu Кстати тест после этого стал падать, я хотел поправить но забыл

**Comment by DaleTernes** [comment]
Ребят, как бы мне получить исправленную dll? У меня не компилится ваш проект, тучи ошибок сыпет...

**Comment by CaCTuCaTu4ECKuu** [comment]
Скачай зип, извлеки, запусти солюшн, правой кнопкой на VkNet и "собрать решение" без всего остального. Наверное тесты падают

**Comment by CaCTuCaTu4ECKuu** [comment]
@DaleTernes сегодня и завтра могу зайти по удаленке и посмотреть быстро в чем проблема если ни в какую не компилируется. Я помню у кого-то на VS2015 RC не работало, но сейчас студия уже релизнулась так что

**Comment by DaleTernes** [comment]
Да как бы не так. На все обращения к полям в конструкторе каждой структуры ругается.
Error	21	Backing field for automatically implemented property 'VkNet.Model.RequestParams.AccountSaveProfileInfoParams.Status' must be fully assigned before control is returned to the caller. Consider calling the default constructor from a constructor initializer.	

и еще не понимает "?" в этой строке:
var cropData = responseJson["crop_data"]?.ToString();

**Comment by CaCTuCaTu4ECKuu** [comment]
Напишите версию студии, ОС, какой установлен фреймворк? Вы не меняли в настройках приложения целевую платформу? Никаких изменений не вносили в файлы проекта?

**Comment by DaleTernes** [comment]
MS VS 2013 Professional
.NET Framework 4.6.00079
Win 10
Ничего не менял, уже два раза попробовал с нуля скачать и построить. Одно и то же. Мне бы dll-ку и всё)

**Comment by kadkin** [comment]
вроде это ругается на конструктор структур

С уважением, Кадкин Игорь
+79199635059
igor@kadkin.com

2016-03-16 20:31 GMT+03:00 Dale <notifications@github.com>:

**Comment by CaCTuCaTu4ECKuu** [comment]
@DaleTernes скинуть то я скину dll, ну а фиксики то остануться. Может попробуй с NuGet промежуточные версии устанавливать из тех, которые здесь выкладывает @inyutin-maxim
В общем сегодня-завтра я могу глянуть

**Comment by inyutin-maxim** [comment]
@DaleTernes В проекте используется версия языка C# 6, MS VS 2015, попробуйте скачать новую студию и собрать в ней. Так же библиотека компилируется в .NET 4.0. Спасибо

**Comment by DaleTernes** [comment]
@inyutin-maxim Да, дело было в версии компилятора. Под 2015 студией всё скомпилилось. Всем спасибо.
