### ISSUE TITLE
И снова "Too many requests per second."

### ISSUE THREAD

**Issue by DaleTernes** [vknet/vk#211]
Снова надо править метод VkApi.Invoke ().
`
if (RequestsPerSecond > 0 && LastInvokeTime.HasValue)

            {
                lock (_expireTimer)
                {
                    var span = LastInvokeTimeSpan.Value;
                    LastInvokeTime = DateTimeOffset.Now;
                    if (span.TotalMilliseconds < _minInterval)
                    {
                        Thread.Sleep(_minInterval - (int)span.TotalMilliseconds);
                    }
                    
                }
            }`

LastInvokeTime присваивается до Thread.Sleep и следующий запрос опирается на некорректное время отправки предыдущего. 

Но, исправив этот недочёт у себя, я всё равно (хоть и редко) получаю "Too many requests per second"...
У меня один выход - поставить 2 в RequestsPerSecond, вместо 3.
Но это медленно! Нужна возможность выставлять _minInterval снаружи, либо RequestsPerSecond сделать не целочисленным.

**Comment by kkohno** [comment]
я кстати в либу рекомандовал бы добавить запоминание последнего запроса - тк многие места такие как капча или описанный выше требует повторного запроса. И переделать архитектуру обработки ошибки с этим учетом.

**Comment by kkohno** [comment]
на днях кстати займусь этим у себя в проекте - могу потом выслать доработки))

**Comment by CaCTuCaTu4ECKuu** [comment]
@kkohno я тоже думал что это будет полезно, но не добавлял потмоу что вот почему. Если в разных потоках будут выполняться разные действия то код типа 
```
try {
somemethod();
} catch {
api.lastmethod();
}
```
может выполнить другой код. Такая же замануха может случиться даже если в одном потоке будет такое выполняться потому что всякие ивенты и таймеры и все такое.
А на счет проблемы с превышением я не понял что именно сейчас не работает, но сделать лучше можно однозначно, если есть предложения - предлагайте

**Comment by kkohno** [comment]
Я думал сделать обработку исключения на уровне АПИ - чтобы она в этом случае долбилась и добивалась поставленной задачи - выполнить команду. Тоесть если делать, обработку ошибки на уровне апи то думаю сделать потокобезопасную очередь команд в методе Invoke  - должно вроде работать

**Comment by CaCTuCaTu4ECKuu** [comment]
Кто-то писал про флаг который ставиться который изолирует какие-то данные между потоками так что изменения в пределах определенных у каждого потока будут свои, но реализовывать на уровне АПИ как по мне плохой вариант для такого проекта. Если будет какая-то проблема то как знать хочет ли пользователь чтобы там само долбилось без конца или хочет прекратить в случае ошибки, в каждом конкретном случае для проблем лучше подбирать оптимальное кол-во попыток и в том числе вариантов их обработки. Но опять таки, все варианты присылайте, это не помешает учитывая что сейчас вообще проект только 1 человек поддерживает

**Comment by kkohno** [comment]
дак а что если обработку сделать так, что все настройки обработки берутся из специального класса. В проекте будет один стандартный класс обработки ошибок. Если юзер хочет чтото поменять то он либо меняет конфигурацию экземпляра этого класса, либо в конструктор апи передает свой класс обработчик,поддерживающий специальный интерфейс обработчика?

**Comment by CaCTuCaTu4ECKuu** [comment]
Саму ошибку я закрываю.
Насчет этого да, я думал насчет какого-то класса обертки или каких-то настроек, но просто мне смутно представляется как это реализовать. Фишка в том что в любом случае нужно привязать как-то конкретный метод к конкретным настройкам. Вот у меня, кстати, только что появилась идея, но опять таки не уверен как это лучше реализовать, но суть в том чтобы сделать как вы сказали полноценный класс для обработки ошибок сделать в нем что-то типа возможности создавать конфигурации обработки, потом когда ты хочешь обрабатывать ошибки в методе ты вызываешь что то типа
```
ExceptionClassObject.AddHandler(VkApi.Method, HandlerID);
или 
ExceptionClassObject.AddHandler[id] += VkApi.Method
```
то было бы круто. Второй вариант мне нравиться даже больше. Только опять таки вопрос в том как изолировать одинаковые методы вызываемые в разных местах

**Comment by kkohno** [comment]
Я имел ввиду сделать стандартный обработчик простых ошибок типо более 3 раз в секунду запрос или флуд ексепшн от вконтакте. А так мой метод если описать то в классобработки ошибок можно задать и обработчики Вашим методом тоже. В классе обработки приемущество в том, что если обработка не понравилась то переписываем уже по интерфейсу новый класс обработки ошибок или его дополняем и архитектуру не меняем.

**Comment by kkohno** [comment]
кстати если экземпляр обработчика равен null то либа чтобы работала как сейчас к примеру

**Comment by CaCTuCaTu4ECKuu** [comment]
Кстати насчет задержек. У меня еще была мысль сделать что-то типа конвеера в который складываются запросы, но мне было откровенно лень продумывать менеджер в котором будет реализовано все должным образом плюс не уверен что игра стоит свет и от этого будет выгода, а если и будет то нужна ли эта выгода в повседневной жизни так сказать

**Comment by kkohno** [comment]
дак заюзать потокобезопасную очередь если и выполнять по очереди команды то былобы вобще норм думаю. опятьже очереди эти есть в либах

**Comment by kkohno** [comment]
эх, на днях или на след неделе мне всеравно это писать придется походу - могу потом показать свою версию этого момента))

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu  Последние изменения сломали половину функционала, пожалуйста используй тесты при отладке

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu ты только тесты поломал как я понял, все вроде работает, можешь не парится о тестах, я все равно перевожу все на nunit3, закончу и солью ветки
