### ISSUE TITLE
Возможно ли использовать на сервере? 

### ISSUE THREAD

**Issue by thegreengree** [vknet/vk#214]
Добрый день! 
При использовании вашей библиотеки на локальной машине никаких проблем не возникает.
Я сейчас делаю проект в котором мне необходимо залить ВК бота на Azure сервер, где он в фоновом режиме будет работать и отвечать на сообщения, которые ему будут приходить. В Azure я использую WebJobs, просто беру C# консольное приложение, закидываю все файлики в zip и собственно туда кидаю. И каждый раз я в итоге ударяюсь об капчу Unhandled Exception: VkNet.Exception.VkApiException: Validation required: please open redirect_uri in browser 1120226107. 
И я в курсе, что можно взять url и seed, но как мне это поможет?
Собственно вот и вопрос, я могу вообще это сделать или как?

**Comment by CaCTuCaTu4ECKuu** [comment]
Раскрою вам маленький секрет. https://anti-captcha.com

**Comment by thegreengree** [comment]
Ну за бабосы все сделать можно, а подругому никак?

**Comment by CaCTuCaTu4ECKuu** [comment]
Ручками :)

**Comment by thegreengree** [comment]
Если бы я ручками умел, я бы здесь помощи не искал :c Просто почему на локальной машине все ок, а на сервере все плохо? Я глупый, не понимаю :/

**Comment by inyutin-maxim** [comment]
@thegreengree Запилите Asp.NET MVC приложение, в котором пользователь должен ввести свои логин и пароль например через OAuth. на каждого пользователя будет отдельная сессия, но выпадение капчи исключить нельзя, или использовать сторонние сервисы или давать пользователям вводить их самим

**Comment by CaCTuCaTu4ECKuu** [comment]
У ВК есть свои алгоритмы определения различной надежности и прочего и они сами решают когда капча должна срабатывать, а когда нет. В вашем случае думаю все дело в айпи с которого выполняются действия, вк решил что эта сессия "не надежна" и решил включить для вас капчу. На все подобные вопросы ответа нет потому что они не разглашают ни своих алгоритмов ни условий, только общие какие то слова можно услышать если спросить.

**Comment by thegreengree** [comment]
Понятненько тогда.. В общем, спасибо большое тогда. У вас отличная либа, удачи :)

**Comment by inyutin-maxim** [comment]
@thegreengree Спасибо, всего доброго
