### ISSUE TITLE
Как определить количество записей. которые доступны для чтения

### ISSUE THREAD

**Issue by kkohno** [vknet/vk#215]
Как известно все запросы вконтакте, возвращающие список элементов возвращают и их количество.Те если я скажем хочу получить всех друзей, которых скажем 10к то читаю за запрос 1000 друзей и далее по 3 раза в секунду, причем ВК всегда при ответе указывает сколько всего друзей у меня есть т.е. эти 10к, чтобы я мог прочитать все до конца. Вопрос: почему в либе не все методы возвращают это количество? Или если это както в либе читается поиному то как?
пример:  API.Friends.Get
И почему например нижеприведенный метод имеет на выходе тип со знаком?
public ReadOnlyCollection<User> Search(out int itemsCount, UserSearchParams @params)
тоесть этот: API.Users.Search

**Comment by inyutin-maxim** [comment]
@kkohno По порядку, не все методы возвращают потому что ни всем это нужно.
Это не понял:
>И почему например нижеприведенный метод имеет на выходе тип со знаком?
> public ReadOnlyCollection Search(out int itemsCount, UserSearchParams @params)
с каким знаком?

Так же, если тебе нужно получить пользователей как объекты тебе придется выполнить несколько запросов, именно поэтому там есть сдвиг, таково ограничение АПИ вк.
Надеюсь ответил на вопросы

**Comment by kkohno** [comment]
по поводу со знаком: int - это знаковый тип а при некоторых запросах может быть огромное число результатов. Зачем половину значений тратить вникуда, когда отрицательных не может быть в ответе. 
насчет вывода элементов: я у себя либо допилил вот так:
API.Wall.Get(param, out totalCount);
где totalCount - это какраз count из результат см https://vk.com/dev/wall.get
Вот как выглядит ответ вконтакте:
response: {
count: 191,
items: [{ ...
Тоесть этот count нужно знать, чтобы прочитать полностью все записи со стены, если их больше 1000 и не делать лишних запросов к АПИ

**Comment by inyutin-maxim** [comment]
@kkohno  Мне кажется у вас есть некоторое недопонимание, знаковый тип не везде нужен вы правы, я даже вводил в одно время беззнаковые типы, но это обернулось некоторыми проблемами. Ты прав я не везде возвращаю количество всего для методов, Out параметры это плохо, я бы такой вообще их из кода убрать. Не всем нужен этот параметр. Посмотри этот [топик](https://github.com/vknet/vk/issues/86) здесь есть некоторые ответы на ваши вопросы

**Comment by CaCTuCaTu4ECKuu** [comment]
Знаковый тип используется из за проблем совместимость старых версий апи,
может к версии 2.0 уберется.

**Comment by kkohno** [comment]
насчет не всем нужны - почему бы перегруженые методы не сделать? Или как вариант возващать всегда не набор элементов а структуру ответа, которая подходит подо все запросы

**Comment by inyutin-maxim** [comment]
Насчет структуры ответа я уже думал но боюсь это очень много переделывать придется, насчет перегруженных методов, вам никто не мешает помочь в этом :-) если будет желание участвовать в развитии проекта напишите мне, обсудим некоторые детали

**Comment by inyutin-maxim** [comment]
так как задача по смысловой нагрузке дублирует задачу #86 эту я закрываю
