### ISSUE TITLE
!!! Пожалуйста прочтите, от этого зависит судьба развития библиотеки !!!

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#216]
Уважаемые пользователи библиотеки, грядут перемены, и для исправления некоторых проблем библиотеки необходимо внести изменения которые потенциально могут сломать обратную совместимость, суть изменения заключается в замене у методов которые возвращают коллекцию на кастомную которая содержит поле TotalCount (поле count из ответа vk) ( #86 ) и собственно коллекцию данных, в следствии чего я хочу выкинуть все методы содержащие out параметры, так как они потеряют актуальность, конечно можно эти методы объявить как устаревшие. Пожалуйста ваши вопросы и комментарии и предложения?

PS: Убедительная просьба проголосовать за ниже представленные варианты

**Comment by inyutin-maxim** [comment]
Объявить методы как Obsolete(Устаревшие) и добавить методы с новым типом данных который в себе содержит поле TotalCount

**Comment by NuarkNoir** [comment]
Конечно же обновляйте! Но методы содержащие out'ы выкидывать не надо, объявите их устаревшими.

**Comment by inyutin-maxim** [comment]
Отделить новую версию библиотеки и развивать ее и выбросить ненужный код

**Comment by inyutin-maxim** [comment]
NuarkNoir commented 43 seconds ago
Конечно же обновляйте! Но методы содержащие out'ы выкидывать не надо, объявите их устаревшими.

**Comment by inyutin-maxim** [comment]
@NuarkNoir извините, я хотел чтобы мои комментарии были последовательны

**Comment by NuarkNoir** [comment]
@inyutin-maxim извините за прерывание очереди сообщений

**Comment by CaCTuCaTu4ECKuu** [comment]
Если библиотека обновлена до последней версии то, наверное, надо сделать
резил полноценный на нюгеит, потом все обновить и переделать, сделав версию
с obsolete, и поддерживать ее немного, а потом и вовсе убрать старые методы
спустя несколько релизов

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu Я еще несколько вещей поправлю и можно снова релиз выпустить

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну в общем как то так. Если кто то в процессе использования какого то
конечного продукта то он успеет дописать и все не поламается, а если пишут
какую то приложуху с перспективой поддержки то рано или поздно все равно
прийдется обновлятся, по моему варинт оптимальный

**Comment by kkohno** [comment]
ну вообще в таких случаях как верно выше написано - сперва объявляется устаревшими, потом через релиз вообще выкидываются методы

**Comment by Rammun** [comment]
А еще было бы хорошо выделить интерфейс у VkApi, чтоб не приходилось писать оболочки поверх для тестирования.

**Comment by inyutin-maxim** [comment]
@Rammun Вы имеете ввиду чтобы была возможность делать Mock объект класса VkApi?

**Comment by mainefremov** [comment]
@inyutin-maxim, есть следующая проблема. Не все методы изначально содержали out, таким образом будет конфликт.

**Comment by inyutin-maxim** [comment]
@mainefremov Заберите последнюю версию, я унаследовался от ReadOnlyCollection<T> чтобы не ломать совместимость, но чтобы использовать поле нужно использовать либо var либо VkCollection<T> При объявлении переменной
