### ISSUE TITLE
Необязатальная авторизация

### ISSUE THREAD

**Issue by LightSunrider** [vknet/vk#217]
Некоторые методы VKAPI (например: wall.get) по умолчанию не требуют access_token. Я пробовал провести авторизацию без параметров (вызвать метод Authorize с чистым ApiAuthParams) и просто пропустить вызов Authorize, но программа "кидает" исключения. :disappointed:
Интересная ситуация происходит если не вызвать Authorize, а сразу вызывать методы. "Кидать" исключение начинает файл Utilities.cs в функции PreetyPrintJson на строке 69 (JsonReadException).

**Comment by inyutin-maxim** [comment]
Может вы и правы, как завершу другие задачи посмотрю почему так происходит и может поправлю, но пока что просто авторизуйтесь. Приведите пример используемого вами метода для отладки. Спасибо

**Comment by LightSunrider** [comment]
К примеру, этот пример бросает VkApiException в файле WebCall.cs на строке 113
```
var vk = new VkApi();
vk.Authorize(new ApiAuthParams {
	//ApplicationId = 000000,
	//Login = "",
	//Password = "",
	//Settings = Settings.All
});

var l = vk.Wall.Get(new WallGetParams {
	OwnerId = 1
});

Console.WriteLine(l.TotalCount);
```

**Comment by inyutin-maxim** [comment]
@LightSunrider Спасибо, как освободится время разберемся в чем проблема

**Comment by mryabets** [comment]
В `photos.get` тоже [указано](https://vk.com/dev/photos.get):

> Этот метод можно вызвать без ключа доступа. Возвращаются только общедоступные данные.

При `skipAuthorization = false` метод `Photo.Get` нормально отрабатывает.

**Comment by alexkrafts** [comment]
`Groups.Search() `c `skipAuthorization = true` тоже выкидывает исключение. 
Думаю в случае с группами стоит убрать возможность доступа без авторизации, т.к. в [офф документации ](https://vk.com/dev/groups.search) написано
![image](https://cloud.githubusercontent.com/assets/18279336/17727520/843543e0-6462-11e6-8244-8d2907131bdd.png)

как я понимаю, под словом можно они подразумевают нужно. Этот метод без токена всегда выкидывает ошибку.

**Comment by inyutin-maxim** [comment]
Исправлено поведение по умолчанию теперь `skipAuthorization = false` но оставлена возможность дергать метод и без авторизации
