### ISSUE TITLE
не могу разобраться в действии 

### ISSUE THREAD

**Issue by ilidan753** [vknet/vk#218]
не могу разобраться в действии Messages.GetHistory

  var col = api.Messages.GetHistory(229049059, false, out value); 

                Console.WriteLine(col);
Подчёркивает value и ругается на неё.
![image](https://cloud.githubusercontent.com/assets/18134475/14099099/27ac1a34-f5ce-11e5-98da-2cb7eca21f26.png)

**Comment by inyutin-maxim** [comment]
``` csharp
var history = _api.Messages.GetHistory(new MessagesGetHistoryParams
{
	UserId = 32190123
});
```

смотрите документацию пожалуйста: https://vknet.github.io/vk/messages/getHistory/

**Comment by ilidan753** [comment]
![image](https://cloud.githubusercontent.com/assets/18134475/14100363/8e425c40-f5d8-11e5-87cf-597cdbd92149.png)

**Comment by inyutin-maxim** [comment]
@ilidan753  Какая у вас версия библиотеки?

**Comment by ilidan753** [comment]
1.20.0

**Comment by inyutin-maxim** [comment]
@ilidan753 В nuget доступна версия 1.21 скорее всего там ваша проблема уже исправлена. Отпишитесь как проверите. Спасибо

**Comment by ilidan753** [comment]
обновил до версии 1.21. Ошибка не исправлена.

**Comment by inyutin-maxim** [comment]
@ilidan753 давайте я вечером к вам подключусь и помогу с вашей проблемой

**Comment by ilidan753** [comment]
Хорошо.

**Comment by inyutin-maxim** [comment]
@ilidan753 Напишите мне в [контакт](https://vk.com/inyutin_maxim), skype: light_vs_l или [телеграм](https://telegram.me/inyutin_maxim)
