### ISSUE TITLE
Неизвестная ошибка

### ISSUE THREAD

**Issue by ilidan753** [vknet/vk#219]
![image](https://cloud.githubusercontent.com/assets/18134475/14100695/1174fee0-f5db-11e5-85b6-3611e63526c7.png)

как это исправить?

**Comment by inyutin-maxim** [comment]
@ilidan753 Какая у вас версия библиотеки?

**Comment by ilidan753** [comment]
1.20.0

**Comment by kadkin** [comment]
А он не свой объект пытается использовать?

С уважением, Кадкин Игорь
+79199635059
igor@kadkin.com

2016-03-29 10:34 GMT+03:00 inyutin-maxim <notifications@github.com>:

**Comment by ilidan753** [comment]
Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
Ошибка	CS1503	Аргумент 1: не удается преобразовать из "YTBK.MessagesGetHistoryParams" в "VkNet.Model.RequestParams.HistoryGetParams".	YTBK	C:\Users\Kom\Desktop\рб\YTBK\YTBK\Program.cs	26	Активно

**Comment by inyutin-maxim** [comment]
@kadkin Спасибо за помощь. Я так понимаю что проблема в устаревшей версии библиотеки так как у меня на актуальной версии все работает корректно

**Comment by kadkin** [comment]
как в воду глядел))

С уважением, Кадкин Игорь
+79199635059
igor@kadkin.com

29 марта 2016 г., 10:42 пользователь ilidan753 <notifications@github.com>
написал:

**Comment by kadkin** [comment]
@ilidan753  вот так вот попробуй, ты создал свою структуру и используешь ее, когда нужно подсунуть от VkNet

```
var history= _api.Messages.GetHistory(new VkNet.Model.RequestParams.MessagesGetHistoryParams{
	UserId=32190123
});
```

**Comment by ilidan753** [comment]
Этот вариант помог но в консоль выводится вот это
![image](https://cloud.githubusercontent.com/assets/18134475/14101483/8b3e625c-f5e0-11e5-9018-b92eed012b5c.png)

**Comment by kadkin** [comment]
тут уже проблема не в библиотеке.
пытаешься вывести объект, ну у структуры не переопределен метод ToString()
думаю что можно закрывать

**Comment by ilidan753** [comment]
Спасибо)
