### ISSUE TITLE
Не могу найти метод для получения новых сообщений от всех пользователей.

### ISSUE THREAD

**Issue by mrAppleXZ** [vknet/vk#221]
Здравствуйте! Не могу найти метод для получения новых сообщений от всех пользователей.
Messages.GetDialogs возвращает только количество, Messages.GetHistory - сообщения от определенного юзера, а Messages.Get я вообще не понял, что делает.

**Comment by inyutin-maxim** [comment]
Доброго времени суток
[Messages.Get](http://vk.com/dev/messages.get) - Возвращает список входящих либо исходящих личных сообщений текущего пользователя.
[Messages.GetHistory](https://vk.com/dev/messages.getHistory) - Возвращает историю сообщений для указанного пользователя.
[Messages.GetDialogs](https://vk.com/dev/messages.getDialogs) - Возвращает список диалогов текущего пользователя.


Для моментального получения входящих сообщений используйте [LongPoll сервер](https://vk.com/dev/using_longpoll)

**Comment by mrAppleXZ** [comment]
@inyutin-maxim а можно пример использования longpoll'а, пожалуйста?

**Comment by CaCTuCaTu4ECKuu** [comment]
https://github.com/CaCTuCaTu4ECKuu/VkNetExtend/blob/master/LongPoolWatcher.cs

**Comment by inyutin-maxim** [comment]
@mrAppleXZ Вы решили свою проблему? пожалуйста отпишитесь

**Comment by mrAppleXZ** [comment]
@inyutin-maxim да, решил.
