### ISSUE TITLE
при запуске просит webcall.cs

### ISSUE THREAD

**Issue by CodyExho** [vknet/vk#222]
WebCall.cs

**Comment by CaCTuCaTu4ECKuu** [comment]
Сразу скажу - при запуске ничего не просит.
Почитайте еще раз как правильно подключать библиотеки к своим проектам, убедитесь что у вас актуальная версия фреймворка и ваша IDE работает с последней версией языка c#.
В общем тему закрываю. Проверьте внимательно всё.
