### ISSUE TITLE
Wall, WallGetParams, CaptchaKey, CaptchaSid

### ISSUE THREAD

**Issue by SanteR1** [vknet/vk#223]
Добрый день, суть проблемы такова, что на многих методах может выпасть исключение CaptchaNeededException, но отправить повторный запрос не получится, ибо в WallGetParams нет возможности указать CaptchaKey,CaptchaSid.

Так же например методы Wall, нет возможности передавать CaptchaKey,CaptchaSid.

**Comment by inyutin-maxim** [comment]
Как будет свободное время обязательно добавлю, спасибо большое

**Comment by CaCTuCaTu4ECKuu** [comment]
Возможно быстрее будет простосоздать класс с этими полями и сделать его
родителем для wallgetparams, тогда останется только убрать лишнее. Или
организовать интерфейс и тогда сразу покажет где не хватает

**Comment by SanteR1** [comment]
Судя по описанию на vk.com/dev, капча может где угодно впасть.

**Comment by inyutin-maxim** [comment]
@SanteR1 Предлагаю решение вашей проблемы, используйте подход АОП и реализуйте декоратор который будет перехватывать ошибку капчи и дописывать в параметры необходимые поля, так же вы тем самым сможете помочь проекту выявив методы которые требуют капчу. За подробностями предлагаю пообщаться лично в [вк](https://vk.com/inyutin_maxim) или [телеграм](https://telegram.me/inyutin_maxim), задачу закрываю, параметры добавлю сегодня в течение дня
