### ISSUE TITLE
access_token has expired

### ISSUE THREAD

**Issue by SanteR1** [vknet/vk#225]
Есть какой-то метод для проверки access_token истек ли он?
Т.е. что бы можно было проверять, если он истек, сделать  _api.RefreshToken(null);

**Comment by inyutin-maxim** [comment]
@SanteR1 Посмотрите топик #112 возможно вам это поможет

**Comment by SanteR1** [comment]
@inyutin-maxim ,
Подскажите, вот так он будет сам проверять и обновлять?
`api.OnTokenExpires += api => api.RefreshToken();`
Или нужно try-catch ловить VkNet.Exception.UserAuthorizationFailException
и только потом вызывать ивент?

**Comment by inyutin-maxim** [comment]
Я думаю вам больше поможет с этим вопросом @CaCTuCaTu4ECKuu

**Comment by CaCTuCaTu4ECKuu** [comment]
Кстати, когда получает токен он возвращает expires, но если мне не изменяет память то в VkApi Aurhorize не возвращает его и я то ли не подумал то ли лень было, его надо бы запоминать.
Сейчас, по идее, нет такого поля, но первый запрос по истечению срока вернет ошибку TokenExpired и на нее можно забиндить RefreshToken.
А событие - вы уловили суть. Создаете делегат и чпок рефреш, единственное что либа не выполнить заново тот вызов, во время которого и выскочил ексепшн, тобишь этот момент нужно писать вручную :(

**Comment by SanteR1** [comment]
Просто если много методов, то придется в каждом try-catch добавлять RefreshToken. Не особо удобно конечно. 
А никаким методом из vkapi не проверить "годность токена", например isAutorization, UserId?
И еще при получении токена, в каком виде возвращается expires. На его основании потом как то можно валидность проверять?

**Comment by CaCTuCaTu4ECKuu** [comment]
Сейчас нет 😞

**Comment by CaCTuCaTu4ECKuu** [comment]
СтопЭ, есть же событие OnTokenExpires, когда я писал то делал так чтобы оно срабатывало за 10 секунд до реального истечения срока.

**Comment by inyutin-maxim** [comment]
@SanteR1 Проверьте предположение CaCTuCaTu4ECKuu и отпишитесь решило лиэто вашу проблему

**Comment by SanteR1** [comment]
Вот как у меня было сделано
`_api2.OnTokenExpires += _api2 => _api2.RefreshToken();`

**Comment by CaCTuCaTu4ECKuu** [comment]
Так и было задумано, а что, не работает корректно таким образом?

**Comment by SanteR1** [comment]
Ну на тот момент я по другому делал через OnTokenExpires, потом сделал как выше, а проверить точно не мог, потому как IIS убивает пул и потом запускается заново приложение. Думаю что работает.

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну я тоже думаю должно работать)
