### ISSUE TITLE
Что с board.getTopics и board.getComments ?

### ISSUE THREAD

**Issue by Timz** [vknet/vk#226]
Салют. Хочу получить список обсуждений у группы и список сообщений в этих обсуждениях.
Не очень понял как с помощью вашего api это делать.

**Comment by inyutin-maxim** [comment]
@Timz На данный момент board в API не реализовано, но вы можете можете использовать _vk.Call("board.getTopics", parameters) и разбирать ответ в собственные структуры/классы

**Comment by Timz** [comment]
благодарю!
