### ISSUE TITLE
Поддержка Universal Windows Platform

### ISSUE THREAD

**Issue by acedened** [vknet/vk#227]
Попытался установить пакет в UWP-проект, но, к сожалению, оказалось, что библиотека эту платформу не поддерживает. Было бы неплохо, если бы поддержка появилась.

**Comment by inyutin-maxim** [comment]
@acedened Поддержка планируется в будущих версиях, но это огромная работа

**Comment by acedened** [comment]
@inyutin-maxim Могу помочь, если известно, что именно надо переделывать

**Comment by inyutin-maxim** [comment]
Половину используемых библиотек и классов нужно заменить на аналоги которые поддерживают UWP, предлагаю сделать ветку от моей ветки VkCollection и посмотреть что к чему, свяжитесь со мной часов в 9 по москве через [vk](https://vk.com/inyutin_maxim) или [telegram](https://telegram.me/inyutin_maxim)

**Comment by acedened** [comment]
@inyutin-maxim Хорошо, отпишу к этому времени в Telegram

**Comment by virtyaluk** [comment]
@acedened, вот взгляни на мой [проект](https://github.com/virtyaluk/InTouch). Реализованы все клиентские методы, удобный асинхронный API, поддержка UWP, Xamarin (Android + iOS), .NET 4.5+, и многое другое.

**Comment by inyutin-maxim** [comment]
#318
