### ISSUE TITLE
Не могу получить стенку группы если алиас дефолтный

### ISSUE THREAD

**Issue by Timz** [vknet/vk#228]
Салют! Есть группа у которой домен дефолтный, по маске club12345678 
Хочу получить ее стенку. Формирую запрос через WallGetParams.
Подставляю:
WallGetParams.Domain = "club12345678" не находит,
WallGetParams.OwnerId = "12345678" говорит пользователя нет.

Как быть?

**Comment by azhidkov** [comment]
Добрый день,

попробуйте добавить минус

```sharp
WallGetParams.OwnerId = "-12345678"
```

**Comment by Timz** [comment]
да, спасибо помогло!

**Comment by inyutin-maxim** [comment]
@azhidkov Антон, выйди пожалуйста со мной на связь
