### ISSUE TITLE
При авторизации из другого места происходит VkApiException

### ISSUE THREAD

**Issue by nrcpp** [vknet/vk#229]
Например если заходить через прокси, то VK требует подтверждения номера телефона, т.е. двухфакторная авторизация. Но библиотека не находит form element.

- Класс и метод в котором возникла проблема:
WebForm.GetFormNode

- Пример кода для воспроизведения проблемы:
```csharp
vk.Authorize(new ApiAuthParams
            {
                ApplicationId = appID,
                Login = email,
                Password = pass,
                Settings = scope,
                TwoFactorAuthorization = () => email.Substring(3, email.Length - 3 - 2)
            });
```

**Comment by inyutin-maxim** [comment]
@nrcpp Добрый день, что то с вашим кодом не так, не находите? [telegram](https://telegram.me/inyutin_maxim), [vk](https://vk.com/inyutin_maxim)

**Comment by inyutin-maxim** [comment]
@nrcpp Отпишитесь пожалуйста, и если ваша проблема решена то закройте задачу

**Comment by nrcpp** [comment]
Видимо проблема решается только авторизацией через форму, где пользователь должен вводить подтверждение номера. Хотелось бы видеть эту функцию встроенной в будущем.

**Comment by CaCTuCaTu4ECKuu** [comment]
Я думаю это возможно, просто ни у кого сейчас нет ресурса по времени чтобы этим заняться. Я считаю хорошим вариантом будет создание Exception-а в случае запроса, отловив который появится возможность вызвать метод доавторизации. Скрыть в VkApi.cs необходимый метод, а исключение будет возвращать внутри ссылку на делегат или что-то типа того

**Comment by alexandrmazur96** [comment]
Можно посмотреть где-то решение проблемы?
