### ISSUE TITLE
Ошибка 404

### ISSUE THREAD

**Issue by Prowka** [vknet/vk#234]
Не получается авторизоваться уже на первом шаге в методе WebCall возникает 404
я так понимаю  у всех такое сейчас началось или работате???

**Comment by Soniclev** [comment]
У меня работает

**Comment by inyutin-maxim** [comment]
@Prowka есть подозрение что у вас новый дизайн сайта, я прав?

**Comment by CaCTuCaTu4ECKuu** [comment]
Но ведь окно авторизации то же все равно...
Проблема все еще остается или прошла? Может ошибка была связана с ВК?

**Comment by inyutin-maxim** [comment]
@Prowka Проблема все еще проявляется? отпишитесь пожалуйста

**Comment by Prowka** [comment]
Прошу прощения, все заработало, были проблемы у самого VK
