### ISSUE TITLE
Как получить юзеров из контактов группы

### ISSUE THREAD

**Issue by Timz** [vknet/vk#235]
Салют! Подскажите сабж. Есть группа, у нее есть "Контакты" справа в колонке, для связи с владельцами этой группы. Как получить их Id?

**Comment by Soniclev** [comment]
Примерно так
```
foreach( var contact in group.Contacts )
{
    Console.WriteLine( contact.UserId ?? 0 );
}

```

**Comment by Timz** [comment]
" справа в колонке, для связи с владельцами этой группы" а не всех подряд

**Comment by Timz** [comment]
благодарю
