### ISSUE TITLE
Проблема с удалением друзей

### ISSUE THREAD

**Issue by Farrell23** [vknet/vk#238]
При попытке удалить друзей авторизированного пользователя вылетает ошибка:
"Исключение типа "System.ArgumentException" возникло в Newtonsoft.Json.dll, но не было обработано в коде пользователя
Дополнительные сведения: Can not convert Object to Int32."

``` csharp
   DeleteFriendStatus ss = Model.vk.Friends.Delete(list_id[i]);
```

Где переменная vk, является объектом класса VkApi, но при этом после вылета исключения, оно удаляет друга(Он переходит в подписчики), но желательно было без вылетов :D

**Comment by CaCTuCaTu4ECKuu** [comment]
Это в парсинге json проблема, там поля не совпадают. Видимо со старой версии никто так этим методом и не пользовался :D

**Comment by Farrell23** [comment]
:D желательно скорей исправить)

**Comment by inyutin-maxim** [comment]
@Farrell23 Проблема решена?
