### ISSUE TITLE
Вопрос по методу Wall.Post

### ISSUE THREAD

**Issue by Tilimilitrjamdij** [vknet/vk#239]
Добрый день. Есть ли какой-то пример работы с методом Wall.Post? Конкретно интересует работа с аттачами. У меня есть несколько строк типа "photo100172_166443618", но не могу разобраться, как добавить их к посту

**Comment by inyutin-maxim** [comment]
@Tilimilitrjamdij  Вам нужно передавать объекты. Вот пример с аудиозаписями
``` csharp
User user; 
var audios = _api.Audio.Get(out user, new AudioGetParams 
{ 
OwnerId = 32190123 
}); 
_api.Wall.Post(new WallPostParams 
{ 
OwnerId = -103292418, 
Attachments = audios, 
Message = "test" 
});
```

**Comment by Tilimilitrjamdij** [comment]
Уже разобрался, но все равно благодарю. В документации написано про список строк, это и ввело меня в небольшое заблуждение
