### ISSUE TITLE
SaveWallPhoto выдает NullReferenceException

### ISSUE THREAD

**Issue by ghost** [vknet/vk#24]
Еще раз здравствуйте. Вызов того метода почему-то выбрасывает исключение, все у себя в программе перепроверил, и переменную самого API.

**Comment by Taxils** [comment]
Приветствую, при попытке открыть файл WIN в fileviewpro возникает ошибка:
"System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта. в ns1.MainForm_1.method_16(String filePath, Boolean sameTab)"
как её избежать?

**Comment by Taxils** [comment]
Приветствую, при попытке открыть файл формата WIN в fileviewpro возникает ошибка:
"System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта. в ns1.MainForm_1.method_16(String filePath, Boolean sameTab)"
как её устранить?

**Comment by azhidkov** [comment]
Добрый день!

А где вы взяли файл в формте win? В исходниках проекта?

**Comment by Taxils** [comment]
Дело в том что на компьютере была переустановлена операционная система,
а это восстановленный файл сохранённого сеанса в Опере. написал сюда так как не нашёл соответствующею тему.
мне нужно просмотреть содержимое файла и восстановить его.

**Comment by azhidkov** [comment]
Боюсь, что ничем не смогу вам помоч. Могу подсказать касательно использования библиотеки vknet.

**Comment by Taxils** [comment]
Тогда не могли бы вы подсказать соответствующие форумы, сайты, книги.
Мне бы это очень помогло.
Спасибо.
