### ISSUE TITLE
Проблема с получением данных о беседах 

### ISSUE THREAD

**Issue by Farrell23** [vknet/vk#240]
Здравствуйте, возникла такая проблема, нужно получить список всех диалогов и бесед. Использую такой вариант: 

``` csharp
           public ReadOnlyCollection<Message> message { get; set; }

            MessagesDialogsGetParams param = new MessagesDialogsGetParams();
            param.Count = 200;
            param.PreviewLength = 50;

            MessagesGetObject mess = Model.vk.Messages.GetDialogs(param);
            message = mess.Messages;
```

НО, так я получаю лишь список диалогов, а беседы не отображаются .. как добраться до бесед?

**Comment by CaCTuCaTu4ECKuu** [comment]
Нужно будет проверить, возможно в парсере внутри message не распознает чат и, соответственно, нп приводит его к нужному типу. Можете сами исправить, если найдете, сейчас времени ни у кого нет. Смотрите в конструкторе и сравнивайте входной json и реализован ли код, который его парсит.

**Comment by volshebniks** [comment]
Проверил Беседы также возвращаются ... Chat_id для них заполняется.

**Comment by inyutin-maxim** [comment]
В списке есть беседы. закрываю задачу
