### ISSUE TITLE
Ошибка при считывании данных о группах

### ISSUE THREAD

**Issue by Farrell23** [vknet/vk#241]
Еще одна проблема на горизонте, авторизовался, но группы не отображает

![77586-clip-17kb](https://cloud.githubusercontent.com/assets/14282122/15714205/50c077b8-2822-11e6-999f-2104ba31c11b.png)

- Делаю так же в Друзях, Аудиозаписях все хорошо работает, а тут падение(

**Comment by CaCTuCaTu4ECKuu** [comment]
А вот и не авторизовались, в ошибке ясно написано, проверьте ка свой код, токена нет пишет

**Comment by Farrell23** [comment]
Так главное захожу с токеном после авторизации к Друзьям и в любые категории, а вот в Группы такая беда(( И объект класса VkApi статический, и нигде не изменяется

**Comment by CaCTuCaTu4ECKuu** [comment]
Вы авторизуетесь через токен или через логин пароль? Возможно с токеном какие-то косяки, недавно вообще только узнали что он вовсе не работал.

**Comment by Soniclev** [comment]
Вероятно это из-за аргумента true, он не дает засунуть access_token
_Файл VkApi.cs Строка 519_
`builder.AppendFormat("access_token={0}", skipAuthorization ? "" : AccessToken);`
Вызывается из _GroupsCategory.cs строка 85_
`var response = _vk.Call("groups.get", @params, true);`

**Comment by modink** [comment]
Такая же ошибка при вызове метода Users.Search.
Авторизация по логину и паролю. После авторизации заходит к друзьям, получает информацию по аудиозаписям друзей. Но при вызове  Users.Search выдает ошибку.

**Comment by Farrell23** [comment]
CaCTuCaTu4ECKuu, авторизируюсь по логину и паролю.

**Comment by modink** [comment]
Проблему решил путем замены аргумента true
 `var response = _vk.Call("groups.get", @params, true);`
на false
 `var response = _vk.Call("groups.get", @params, false);`

**Comment by CaCTuCaTu4ECKuu** [comment]
Ошибку будем смотреть когда время освободиться, а пока используйте то-то
вариант, что работает. Там с обновлением, видимо, какие то изменения
повлияли
03 июня 2016 г. 21:08 пользователь "modink" <notifications@github.com>
написал:

**Comment by CaCTuCaTu4ECKuu** [comment]
Я понял в чем у вас проблема, skipAuthorization нужно указывать true только для методов, которые можно вызывать анонимно, для всех остальных нужно использовать false
