### ISSUE TITLE
Ошибка при получении фотографий из альбома

### ISSUE THREAD

**Issue by oxozle** [vknet/vk#242]
Ошибка в методе RegisterPossibleValue. Скриншот http://take.ms/gUZHr
После выполнения строчки, маска становится равна 0.

**Comment by oxozle** [comment]
Видимо когда я пытаюсь скачать больше 64 альбомов. Регистрируются маски (не совсем понятно какие)

**Comment by inyutin-maxim** [comment]
@oxozle  Пока сложно ответить сейчас, давайте вечером попробуем связаться, и попробуем разобраться.

Мои контакты: [Вк](https://vk.com/inyutin_maxim) и [Телеграм](https://telegram.me/inyutin_maxim)

**Comment by oxozle** [comment]
В принципе ошибка легко обходится добавлением нового свойства для альбома, в обход SafetyEnum. Он, как мне кажется для идентификатора альбома совсем не нужен. Более того, ошибка может быть не только в фотках. Т.к. при каждому XXX.Id(..) - происходит регистрация значения объекта по маске, а если за сессию будет больше 64 запросов - маски кончатся.

**Comment by ivanovevgeny** [comment]
Столкнулся с аналогичной проблемой, планируется ли исправление?

**Comment by inyutin-maxim** [comment]
Исправление планирую, но только времени свободного катастрофически не хватает

**Comment by inyutin-maxim** [comment]
@oxozle , @ivanovevgeny Перепилил SafetyEnum в следующем [коммите](https://github.com/vknet/vk/commit/6cc0be91ee9967ed0d48cb9b3f30a841d394c3a4). Отпишитесь, ушла ли проблема.

PS Нужно собрать из Github чтобы проверить
