### ISSUE TITLE
InvalidCastException в методе BugFixCookieDomain (из Hashtable в Dictionary)

### ISSUE THREAD

**Issue by SamGitCode** [vknet/vk#244]
Класс: VkNet.Utils.Cookies
Метод: private void BugFixCookieDomain()
Строка: var table =	(Dictionary<string, string>)Container.GetType().InvokeMember("m_domainTable", BindingFlags.NonPublic | BindingFlags.GetField | BindingFlags.Instance, null, Container, new object[] { });
Сообщение: Unable to cast object of type 'System.Collections.Hashtable' to type 'System.Collections.Generic.Dictionary`2[System.String,System.String]'

m_domainTable в момент ошибки (из окна Locals в Visual Studio):
m_domainTable       Count = 1         System.Collections.Hashtable
                                [".vk.com"]       {System.Net.PathList}	

Использовал из VkApiRunner, метод wall.get, параметр owner_id со значением реального пользователя

**Comment by CaCTuCaTu4ECKuu** [comment]
Проверьте #243, у человека всп заработало. Отпишитесь потом

**Comment by SamGitCode** [comment]
Спасибо, поменял точно так же (до этого собирался применить ToDictionary), эта ошибка исчезла (осталась ошибка авторизации, но это другая тема). Не подскажете, где можно задать вопрос про appId?

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну спрашивайте здесь, не знаю что там не понятного с ним)
03 июня 2016 г. 18:36 пользователь "SamGitCode" <notifications@github.com>
написал:

**Comment by SamGitCode** [comment]
Всё, что мне нужно - программно управлять своим аккаунтом, хотя бы самые элементарные действия. Не очень понимаю, зачем vk для этого требуют регистрировать приложение, но понял что без appId никак не обойтись, т.к. уже ввёл номер телефона и пароль (те же что на сайте), но по прежнему получаю настойчивый призыв проверить свои данные в app.config. Нашел много одинаковых статей, где для взлома предлагают зарегистрировать сайт и скопировать оттуда appId, однако у меня пока нет личного сайта. Вопрос: могу ли я указать там любой сайт?

**Comment by SamGitCode** [comment]
И только что обнаружил свою страницу в состоянии "мы зафиксировали попытку взлома Вашей страницы", видимо из за моих же запросов :)

**Comment by SamGitCode** [comment]
В итоге создал пустое приложение и тут же получил нудный ИД. Видимо статьи что читал - старые.

**Comment by SamGitCode** [comment]
С appId разобрался, спасибо, всё работает.

**Comment by CaCTuCaTu4ECKuu** [comment]
Меня не было, идентификатор можно использовать от любого приложения, на
безопасности это никак не скажется потому что действия из под этого
приложения все равно никто кроме вас выполнять не сможет, хорошо что
разобрались, в документации ВК описано как работать с апи, если что то
непонятно проверьте сначала там, возможно вы просто что-то не так делаете,
так часть вопросов сразу отпадет, а там уже если какие то проблемы - пишите
03 июня 2016 г. 19:33 пользователь "SamGitCode" <notifications@github.com>
написал:

**Comment by CaCTuCaTu4ECKuu** [comment]
Единственное уязвимое место - момент отправки запроса, не помню
используется ли там https, внутрь библиотеки можно спокойно передавать
пароль как есть. Одно я могу сказать точно, к тому моменту как вам
понадобится думать об этом вы уже будете понимать что делать. Пользуйтесь и
не забивайте голову лишним

**Comment by SamGitCode** [comment]
К библиотеке то вопросов нет, она же открытая :) Я имел в виду именно локальное хранение пароля после того, как пользователь в первый раз его ввёл - чтобы хранить именно его кеш, который неможможно перевести обратно в пароль. И хотел узнать, поддерживает ли АПИ передачу именно хеша, а не оригинала пароля.

**Comment by CaCTuCaTu4ECKuu** [comment]
Алгоритм RSA можете использовать и локальное хранилище с кэшом, защищенное
другим паролем
