### ISSUE TITLE
Ошибка при поиске групп.

### ISSUE THREAD

**Issue by GaryFreeman** [vknet/vk#248]
Как сказано в документации ВКонтакте, метод `groups.search` необходимо вызывать с `access_token`. Но он вызывается без него:

```csharp
/// <summary>
/// Осуществляет поиск сообществ по заданной подстроке.
/// </summary>
/// <param name="params">Входные параметры выборки.</param>
/// <returns>
/// После успешного выполнения возвращает список объектов group.
/// </returns>
/// <remarks>
/// Страница документации ВКонтакте <see href="http://vk.com/dev/groups.search" />.
/// </remarks>
[ApiVersion("5.44")]
public VkCollection<Group> Search(GroupsSearchParams @params)
{
	return _vk.Call("groups.search", @params, true).ToVkCollectionOf<Group>(r => r);
}
```

Третий параметр метода `VkApi.Call` - `skipAuthorization`, я так полагаю, должен быть установлен в `false` в данном случае.

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну вы чего, ей, вы же после создания экземпляра VkApi должны вызвать метод Authorize который задаст access_token и потом просто вызываете методы, а skipAuthorization добавили для тех случаев, когда метод можно вызвать анонимно

**Comment by GaryFreeman** [comment]
`Authorize` то авторизует, запоминает `access_token`, но сама отправка токена зависит от наличия флага `skipAuthorization`.

```csharp
/// <summary>
/// Получить URL для API.
/// </summary>
/// <param name="methodName">Название метода.</param>
/// <param name="parameters">Параметры.</param>
/// <returns></returns>
internal string GetApiUrl(string methodName, IDictionary<string, string> parameters, bool skipAuthorization = false)
{
	var builder = new StringBuilder();

	builder.AppendFormat("{0}{1}?", "https://api.vk.com/method/", methodName);

	foreach (var pair in parameters)
	{
		builder.AppendFormat("{0}={1}&", pair.Key, pair.Value);
	}
	builder.AppendFormat("access_token={0}", skipAuthorization ? "" : AccessToken);

	return builder.ToString();
}
```

Обратите внимание на последнюю инструкцию перед `return`.

Вижу, что Вы уже поправили, но я бы не стал давать возможность задать `skipAuthorization` в Groups.Search, ибо это бессмысленно, работать будет только со значением `false`.

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну там потихоньку все исправится и будет как надо, а пока быстрофиксики
