### ISSUE TITLE
Как правильно сформировать Attachment в Messages.Send? Прикрепить вложение к сообщению.

### ISSUE THREAD

**Issue by ii778001** [vknet/vk#251]
Здравствуйте, не могу понять как правильно сформировать параметр вложения, для прикрепления к сообщению.
- VkNet.Categories.MessagesCategory.Send
- VkNet.Model.RequestParams.MessagesSendParams

- Пример кода для воспроизведения проблемы:
```csharp
VkNet.Model.RequestParams.MessagesSendParams param = new VkNet.Model.RequestParams.MessagesSendParams();

                    param.Domain = user.Domain;
                    param.Message = Message_Text;
                    param.UserId = user.Id;

                    param.Attachments = ???;

                        api.Messages.Send(param);
```
- param.Attachments имеет тип ```IEnumerable<MediaAttachment>  param.Attachments```,  где MediaAttachment - абстрактный класс, тогда как правильно заполнить этот параметр?

Из документации не совсем понял.
Attachment - Медиавложения к личному сообщению, перечисленные через запятую. Каждое прикрепление представлено в формате: <type><owner_id><media_id>.

**Comment by CaCTuCaTu4ECKuu** [comment]
На этот вопрос уже отвечали и, если я не ошибаюсь, не один раз, посмотрите в решенных

**Comment by Mereng** [comment]
Здравствуйте. Проблема та же, Только с создание комментария к фото. Фото загружаются на сервер и отдаются этому методу. Как быть с Attacments не пойму.
```
private void createComment(Photo mainPhoto, string text = null, IEnumerable<Photo> photos = null)
        {
            var attachments = new List<Attachment>();
            if(photos != null)
            {
                foreach(var photo in photos)
                {
                    var attach = new Attachment();
                    attach = ?;
                    attachments.Add(attach);
                }
            }
            var createCommentParams = new PhotoCreateCommentParams();
            createCommentParams.Attachments = attachments;
            createCommentParams.OwnerId = mainPhoto.OwnerId;
            createCommentParams.PhotoId = (ulong)mainPhoto.Id;
            createCommentParams.Message = text;
            vk.Photo.CreateComment(createCommentParams);
        }
```

**Comment by ii778001** [comment]
#251

**Comment by AlexKveeN** [comment]
Нашли решение? Уже третий день ничего найти не могу.
и как сказали ранее  "На этот вопрос уже отвечали и, если я не ошибаюсь". Вы ошибаетесь, перерыл все закрытые вопросы, нигде ничего о б этом нет.

**Comment by inyutin-maxim** [comment]
Для заинтересованных в данном вопросе, напишите мне после 19 часов по Москве, 
https://telegram.me/inyutin_maxim

**Comment by inyutin-maxim** [comment]
https://github.com/vknet/vk/wiki/FAQ
