### ISSUE TITLE
Не все поля user заполняются.

### ISSUE THREAD

**Issue by modink** [vknet/vk#252]
Не все поля user заполняются.

В классе ProfileFields не все поля описаны для получения.

Не хватает полей:
blacklisted_by_me
blacklisted
military
career
friend_status
is_friend
crop_photo
maiden_name
screen_name
is_hidden_from_feed
is_favorite
can_send_friend_request
wall_comments
exports
occupation
followers_count \ кажется это поле сервер вк всегда пустое возвращает, скорей всего из за того что оно дублируется в полях counters
home_town
verified

hidden: 1
deactivated

**Comment by CaCTuCaTu4ECKuu** [comment]
Это очень даже может быть, можете добавить и закоммитить.
С изменением версий api поля меняются и получается такие не состыковки.

**Comment by modink** [comment]
с полем deactivated не могу разобраться. 
что то в VkNet.Enums.SafetyEnums

```
public static TFilter FromJson(string response)
		{
			if (!PossibleValues.ContainsValue(response))
			{
				return null;
			}

			var result = PossibleValues.FirstOrDefault(o => o.Value == response);
			return new TFilter { _mask = result.Key };
		}
```
не находит возможные значения и возвращает null. В итоге поле не заполняется.

**Comment by CaCTuCaTu4ECKuu** [comment]
#255

**Comment by modink** [comment]
с полем deactivated и разбором Json этого поля. Вопрос остался открытый.

**Comment by CaCTuCaTu4ECKuu** [comment]
А в чем собственно проблема, если приходит поле deactivated то больше никаких полей не прийдет, это признак блокированного аккаунта (и, возможно, удаленного)

**Comment by modink** [comment]
Проблема в том что если приходит с сервера поле deactivated, в объекте user это поле не заполняется.  В Json это поле есть.  Проблема что не находит возможные значения

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну проще всего сделать так, чтоб при получении пля deactivated заполнялось все пустыми значениями или можно сделать класс User абстрактным и прописать как DeactivatedUser будет приводится к типу User (заполнять пустыми значениями)

**Comment by CaCTuCaTu4ECKuu** [comment]
Да, не абстрактным, а сделать DeactivatedUser : User и если есть поле deactivated делать return new DeactivatedUser(uid), в котором в конструкторе все поля будут заполнены пустыми значениями

**Comment by inyutin-maxim** [comment]
Последнее поддерживаю, что то вы из этого такую проблему сделали

**Comment by modink** [comment]
Что то я не так объяснил наверное ). Когда получаешь данные о заблокированном пользователе. Поля IsDeactivated и Deactivated в user пустые. Хотя в  ответе Json от сервера поле присутствует.

**Comment by inyutin-maxim** [comment]
Пришлите ответ, есть подозрение что просто ответ не парсится в поле правильно

**Comment by CaCTuCaTu4ECKuu** [comment]
А если пошагово дебажить в момент когда им присваивается значение все нормально?

**Comment by modink** [comment]
Нет. в
```
public static TFilter FromJson(string response)
        {
            if (!PossibleValues.ContainsValue(response))
            {
                return null;
            }

            var result = PossibleValues.FirstOrDefault(o => o.Value == response);
            return new TFilter { _mask = result.Key };
        }
```

при проверки условия `if (!PossibleValues.ContainsValue(response))` не находит возможные значения. ну и переходит на `return null;` 
`response` в этот момент равен  "banned"

**Comment by modink** [comment]
`{"response":[{"id":4190784,"first_name":"Катя","last_name":"Кондратьева","deactivated":"deleted","sex":1,"photo_50":"https:\/\/vk.com\/images\/deactivated_50.png","photo_100":"https:\/\/vk.com\/images\/deactivated_100.png","photo_200_orig":"https:\/\/vk.com\/images\/deactivated_200.png","photo_400_orig":"https:\/\/vk.com\/images\/deactivated_400.png","photo_max":"https:\/\/vk.com\/images\/deactivated_200.png","photo_max_orig":"https:\/\/vk.com\/images\/deactivated_400.png","online":0,"domain":"id4190784","can_post":0,"can_write_private_message":0}]}`

**Comment by CaCTuCaTu4ECKuu** [comment]
Если мне не изменяет память то такой JSON раньше разбирало. Я вот не знаю что за PossibleValues даже.
Времени нет, но вы держитесь там, а точнее я предлагаю выяснить откуда берется PossibleValues и чего не хватает конкретно в таком случае.

**Comment by cybersea54** [comment]
public sealed class Deactivated : SafetyEnum<Deactivated>
    {
		/// <summary>
		/// Удалено.
		/// </summary>
		public static readonly Deactivated Deleted = RegisterPossibleValue("deleted");

		/// <summary>
		/// Заблокировано.
		/// </summary>
		public static readonly Deactivated Banned = RegisterPossibleValue("banned");

		/// <summary>
		/// Активно.
		/// </summary>
		[DefaultValue]
		public static readonly Deactivated Activated = RegisterPossibleValue("activated");
}

Вот эти значения не инициализируются при вызове FromJson из SafetyEnums, соответственно ничего не находится. Проблема актуальна для всех SafetyEnums. Если перенести метод FromJson из SafetyEnums в Deactivated - все работает.

**Comment by inyutin-maxim** [comment]
Метод SafetyEnums переписан и теперь работает корректно

**Comment by inyutin-maxim** [comment]
Класс user приведен в соответствие с [документацией](https://vk.com/dev/objects/user)
