### ISSUE TITLE
Метод Photo.SaveWallPhoto не работает, ошибка Invalid Hash

### ISSUE THREAD

**Issue by heato** [vknet/vk#260]
![devenv_2016-06-12_14-20-13](https://cloud.githubusercontent.com/assets/8377362/15990841/d6078ee6-30a8-11e6-88d2-b24e3a3a98f4.png)

`var getWallUploadServer = api.Photo.GetWallUploadServer();
var web = new WebClient();
var response = Encoding.UTF8.GetString(web.UploadFile(getWallUploadServer.UploadUrl, "POST", FilePath));
var a = api.Photo.SaveWallPhoto(response, groupId: 107276883);`

`************** Текст исключения **************
VkNet.Exception.VkApiException: Invalid hash
   в VkNet.Utils.VkErrors.IfErrorThrowException(String json)
   в VkNet.VkApi.Invoke(String methodName, IDictionary`2 parameters, Boolean skipAuthorization)
   в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization)
   в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization, String apiVersion)
   в VkNet.Categories.PhotoCategory.SaveWallPhoto(String response, Nullable`1 userId, Nullable`1 groupId)
`

Версия самая последняя с гитхаба

**Comment by volshebniks** [comment]
Только что попробовал: (код на VB, но думаю все понятно)
` 
Dim server = _vk.Photo.GetWallUploadServer(GROUP_ID)
Dim web = New WebClient()
Dim strFilePath As String=Path.Combine(MyFolder, "testPhoto.jpg")
Dim response = Encoding.UTF8.GetString(web.UploadFile(server.UploadUrl, "POST", strFilePath))
Dim resSavePhoto = _vk.Photo.SaveWallPhoto(response, Nothing, GROUP_ID)
Dim mediaAttachments as New List(Of Attachments.MediaAttachment)
Dim objMediaAttachment as new Attachments.Photo
objMediaAttachment .Id = resSavePhoto.First().Id
objMediaAttachment .OwnerId=resSavePhoto.First().OwnerId
mediaAttachments.Add(objmediaAttachment)
 _vk.wall.post(New WallPostParams() With {.OwnerId = -GROUP_ID,.Attachments= mediaAttachments})
`
Всё работает
