### ISSUE TITLE
Метод api.Pages.Save, в результате номер страницы, но по номеру записи нет

### ISSUE THREAD

**Issue by SanteR1** [vknet/vk#261]
`var wiki = api.Pages.Save(text: "<b>Жирный текст 0111</b> Проверка Wiki ", groupId: 111111111, userId: 01010101, title: "011",pageId:null );
`
id группу указываю без -

Может кто протестировать создание вики страницы, потому что результат при сохранении дает номер записи, но потом но номеру этой записи не находит страницу.
После сохранения проверяю вот тут
https://new.vk.com/dev/pages.get

**Comment by SanteR1** [comment]
Проверял добавление через сайт vk
`https://new.vk.com/dev/pages.save`

Оставляю пустым поле page_id, все остальные поля заполняю.
Поле group_id указываю без знака -
После добавления, результатом приходит номер id созданной страницы.
Затем тут https://new.vk.com/dev/pages.get по этому номеру можно просмотреть запись.
Через VkNet при создании записи ошибок нет (результирующая запись начинается с цифр 52) Но вот потом под этим номером ничего не находит, если проверить эту страницу через https://new.vk.com/dev/pages.get вот что приходит в рузультате
`error_msg: 'One of the parameters specified was missing or invalid: page is not found, check global and site_preview params if page is not standard wiki',`

**Comment by SanteR1** [comment]
Получение URL API правильное, итоговое значение перед отправкой
`https://api.vk.com/method/pages.save?text=111111&groupId=12345678&user_id=123456789&title=1123132132123&v=5.50&access_token=***********************************1`
А вот что дальше, пошагово попадаю сюда
Дальше в этом методе Прямой вызов API метода
`public string Invoke(string methodName, IDictionary<string, string> parameters, bool skipAuthorization = false)`
на строку
`			VkErrors.IfErrorThrowException(answer);`
Далее вот сюда
`/// <summary>
        /// Ошибки VK.
        /// </summary>
        /// <param name="json">JSON.</param>
        /// <exception cref="VkApiException">
        /// Неправильный данные JSON.
        /// </exception>
        public static void IfErrorThrowException(string json)
{
            JObject obj;
            try
            {
                obj = JObject.Parse(json);
            }
            catch (JsonReaderException ex)
            {
                **throw new VkApiException("Wrong json data.", ex);**
            }
......`

**Comment by CaCTuCaTu4ECKuu** [comment]
Боюсь сейчас ни у кого нет времени и придется вам самому попытаться это исправить...

**Comment by CaCTuCaTu4ECKuu** [comment]
Есть какие-то подвижки? Могу посмотреть если вы не нашли проблему

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu Я точно ничего не правил, у меня последние месяца полтора времени почти нет на проект

**Comment by nulldev01** [comment]
Тоже встретился с такой проблемой. Сейчас посмотрю либу.
НО!! Вот это реально "crazy operator overloading" 
![crazy](https://cloud.githubusercontent.com/assets/17256467/17477097/e3dc558e-5d6b-11e6-89a5-34cf6194a937.png)

**Comment by SanteR1** [comment]
@CaCTuCaTu4ECKuu 
Через библиотеку у меня не получилось, пришлось по старинке делать в обход библиотеки и работать с  вики

**Comment by nulldev01** [comment]
Починил. Сейчас pull кину

**Comment by inyutin-maxim** [comment]
#276 Fixed Pages.Save method
