### ISSUE TITLE
Filter в GroupsGetMembersParams не соответствует заявленному в документации

### ISSUE THREAD

**Issue by soleg1990** [vknet/vk#263]
Вместо friends, unsure и managers другие поля. Не могу получить руководителей сообщества, администратором которого является текущий пользователь.

**Comment by CaCTuCaTu4ECKuu** [comment]
Все соответствует документации. 
См. https://new.vk.com/dev/groups.getMembers и VkNet/Model/Group/RequestParams/Groups
