### ISSUE TITLE
Api.Photo.GetOwnerPhotoUploadServer User authorization failed: no access_token passed.

### ISSUE THREAD

**Issue by Prog-Maker** [vknet/vk#264]
получаю ошибку User authorization failed: no access_token passed.  при вызове метода Api.Photo.GetOwnerPhotoUploadServer(Api.UserId);
Версия с nuget - 1.22.1

**Comment by Prog-Maker** [comment]
А в версии с гита нормально работает )))

**Comment by Prog-Maker** [comment]
По моему в nuget e версия 1.21 на самом деле.

**Comment by inyutin-maxim** [comment]
В nuget лежит версия от 4.07.2016, коммитов после этой даты не было, как то странно что из гитхаба работает а из nuget не работает, поясните пожалуйста

**Comment by Prog-Maker** [comment]
Посмотрите сами вот скрин  - http://hostingkartinok.com/show-image.php?id=28726c4b47373c6656a6f8c26c92c017

**Comment by Prog-Maker** [comment]
А вот собственно и причина ошибки в версии с нугета. В этой версии метод GetOwnerPhotoUploadServer передается с параметром true, т.е. как я понял без access_token`a
<a href='http://hostingkartinok.com/show-image.php?id=d15fb6f449606a57f4c606a1ab1996bc' title='image host'><img src='http://s8.hostingkartinok.com/uploads/thumbs/2016/07/d15fb6f449606a57f4c606a1ab1996bc.png' /></a>

**Comment by CaCTuCaTu4ECKuu** [comment]
Я так понял в последней версии с гитхаба проблема не актуальна?

**Comment by b1tc0re** [comment]
Такая же проблема у меня с методом.

```
int count;
var users = vk.Users.Search(out count, SearchParams).ToList();
```

Если вызвать через Invoke все нормально.

`var req = vk.Invoke("users.search", (VkParameters)SearchParams, false);`

**Comment by Soniclev** [comment]
@b1tc0re Библиотека с Nuget?На GitHub [исправлено](https://github.com/vknet/vk/blob/master/VkNet/Categories/UsersCategory.cs#L41)

**Comment by Prog-Maker** [comment]
Да с последней версией с гитхаба все нормально. С версией с нугет есть проблемы.
