### ISSUE TITLE
NullReferenceException в Place.FromJson при парсинге сообщения

### ISSUE THREAD

**Issue by Dehax** [vknet/vk#265]
Есть ситуация, когда в личном сообщении прикреплена карта, но сервер ВК возвращает только такую информацию в поле `geo.place`:

- title
- country
- city

но метод `Place.FromJson(VkResponse)` последней, на данный момент, версии VkNet v1.22.0.0 подразумевает, что, как минимум, свойства `Id` (параметр `place_id` или `id`) и `ShowMap` (параметр `showmap`) класса `Place` не могут быть null. Проблема заключается в [этой](https://github.com/vknet/vk/blob/v1.22.0.0/VkNet/Model/Place.cs#L84) строчке кода.

**Comment by inyutin-maxim** [comment]
Исправлено вами же)

**Comment by Dehax** [comment]
Извините, но мой Pull Request #267 отмечен как `Closed`, а не `Merged`, то есть проблема остаётся актуальной. Она будет исправлена позже?
