### ISSUE TITLE
Api.Groups.GetRequests(groupid, offset, count, fields) не работает, выводит Count = 0, хотя в группе есть заявки

### ISSUE THREAD

**Issue by AlexKveeN** [vknet/vk#270]
var.getRequests = Api.Groups.GetRequests(groupid, offset, count, fields: can_write_private_message);
        if (getRequests.Count > 0)
            {
                  foreach (VkNet.Model.User getreq in getRequests)
                { 

код работает но выводит постоянно count = 0.
авторизовался, токен получил, являюсь администратором группы.

**Comment by inyutin-maxim** [comment]
Ваш код избыточен, если коллекция пустая то foreach сразу просто выйдет из цикла, а то что Count возвращает 0 нужно посмотреть

**Comment by CaCTuCaTu4ECKuu** [comment]
![default](https://cloud.githubusercontent.com/assets/8963134/17362369/81b19fbe-597d-11e6-8ea9-44409f8bd2c3.PNG)
Все работает, разбирайтесь со своим кодом получше
