### ISSUE TITLE
как получить topics (обсуждения) из группы. 

### ISSUE THREAD

**Issue by volshebniks** [vknet/vk#271]
Ну могу понять как получить topics (обсуждения) из группы.

**Comment by Soniclev** [comment]
Пока что не реализовано

**Comment by volshebniks** [comment]
А можно мне тогда прав на добавление кода? Я б добавил :))

**Comment by inyutin-maxim** [comment]
@volshebniks сделайте форк и пришлите пул реквест

**Comment by inyutin-maxim** [comment]
#272 Реализация объекта Board (Обсуждения)
