### ISSUE TITLE
Метод GetAlbums(long ownerId) возвращает не все альбомы музыки

### ISSUE THREAD

**Issue by DimaZagrebelskiy** [vknet/vk#279]
Метод VkNet.Categories.AudioCategory.GetAlbums(long ownerId) возвращает не все альбомы музыки

**Comment by volshebniks** [comment]
А не все это сколько? просто по документации VK - максимальное значение 100.

**Comment by DimaZagrebelskiy** [comment]
из 5 альбомов 3 возвращает

**Comment by volshebniks** [comment]
не смог повторить ... из 5 вернулись все.  Но в текущем варианте кода не возвращается  AlbumId. Потому, что поле в JSON  его переименовали на "id". Поправил, согласно документации. Pull Request создал.

**Comment by inyutin-maxim** [comment]
@DimaZagrebelskiy  pull request принят, вы можете собрать библиотеку сами, либо дождаться релиза в следующем месяце, Пожалуйста отпишитесь была ли решена ваша проблема

**Comment by inyutin-maxim** [comment]
Полагаю что проблема решена, закрываю
