### ISSUE TITLE
Не получает все данные в методе photos.getAlbums

### ISSUE THREAD

**Issue by proggmatic** [vknet/vk#28]
Если передать методу photos.getAlbums (https://vk.com/dev/photos.getAlbums) параметры
needCovers: true и photoSizes: true

то нужно дополнительно возвратить массив из json-объекта "sizes".

То же самое касается метода photos.get и, видимо, остальных методов, работающих с фото.

Путь решения:
Я это решил путем модификации исходного кода. Было бы здорово включить в следующий релиз. Если нужен код, предоставлю, он несложный.

**Comment by inyutin-maxim** [comment]
Исправлено, закрываю
