### ISSUE TITLE
Проблема с Messages.Get

### ISSUE THREAD

**Issue by oriaraniar** [vknet/vk#280]
При использовании метода Messages.Get в АПИ ВК есть возможность получать не только сообщения юзера, но и сообщение сообщества, при авторизации через токен сообщества.

Однако в библиотеке не выводятся сообщения сообщества.
При использовании прямого вызова через Invoke всё норм, только приходится парсить json.
Возможно, где-то в глубинах библиотеки как-то некорректно обрабатываются полученные данные и  VkResponse не собирается.

Подозреваю, что во всеми методами, что от имени сообщества запускаются, ситуация аналогична.

**Comment by volshebniks** [comment]
Ради интереса проверил ...   Dim test= _vk.Messages.Get(New MessagesGetParams() With{.Count=50})
Сообщение возвращаются.  "Count" точно задаете? А то, хотя и написано "по умолчанию 20", но оно нигде в 20 не устанавливается по умолчанию и передается "0"

**Comment by oriaraniar** [comment]
Count не задавал. Понадеялся на описание и то, что в самом ВК его можно не задавать, оно там по-умолчанию ненулевое.

Благодарю. С указанием непустого Count всё стало норм.

**Comment by inyutin-maxim** [comment]
Постараемся к следующему релизу поправить
