### ISSUE TITLE
Не обрабатывается исключение CaptchaNeededException при использовании vk.Wall.Post

### ISSUE THREAD

**Issue by troyanym** [vknet/vk#281]
При вызове подобного кода:

       try {
            var vk = new VkApi();
            vk.Authorize(new ApiAuthParams
            {
                ApplicationId = appID,
                Login = email,
                Password = pass,
                Settings = scope
            });

            vk.Wall.Post(new WallPostParams
            {
                OwnerId = group,
                Message = text
            });

        }
        catch (VkNet.Exception.CaptchaNeededException cEx) {}

Вылетает ошибка приложения - "Входная строка имела неверный формат" (http://prntscr.com/c4q4w3)
Пробовал отловить другие исключения - безрезультатно
ПС: значения переменных передаю правильно... так как если задаю айди группы где нет капчи - все работает отлично

**Comment by volshebniks** [comment]
Не смог повторить вашу ошибку. Вообще ни ошибок, ни капчи ...Добавляю по 20 сообщений за раз.

**Comment by CaCTuCaTu4ECKuu** [comment]
Проверьте, возможно проблема в этом
`OwnerId = -group`

**Comment by CaCTuCaTu4ECKuu** [comment]
Проблема решилась?

**Comment by troyanym** [comment]
Проблема решилась... была в том что использовал в программе Netframework 4.0, при 4.5 проблема пропала...

**Comment by troyanym** [comment]
Всем спасибо кто пытался помочь!
