### ISSUE TITLE
vk.Messages.GetChatUsers отдает пустой массив

### ISSUE THREAD

**Issue by EarsKilla** [vknet/vk#283]
- Класс и метод в котором возникла проблема:
[vk.Messages.GetChatUsers](https://github.com/vknet/vk/blob/master/VkNet/Categories/MessagesCategory.cs#L542)
- Пример кода для воспроизведения проблемы:
```csharp
  var chatInfo = vk.Messages.GetChatUsers(new long[] { 10L }, VkNet.Enums.Filters.UsersFields.Online, VkNet.Enums.SafetyEnums.NameCase.Nom);
```
Возвращается пустой массив пользователей. Проблема решается если убрать возможность задания массива long и поменять параметр запроса с ``chat_ids`` на ``chat_id`` в [GetChatUsers](https://github.com/vknet/vk/blob/master/VkNet/Categories/MessagesCategory.cs#L542)

дебаггер подсказывает что проблема кроется [тут](https://github.com/vknet/vk/blob/master/VkNet/Utils/VkResponseEx.cs#L91) (или если вернуться немного назад, то [тут](https://github.com/vknet/vk/blob/master/VkNet/Categories/MessagesCategory.cs#L553))

почему возникает данная проблема при использовании запроса с параметром ``chat_ids``:

пришедший ответ в формате json не обрабатывается должным образом, выглядит он так:

```json
{
  292: [
    {
      id: 69028038,
      first_name: 'Andrey',
      last_name: 'Koneko',
      invited_by: 69028038,
      type: 'profile'
    },
    {
      id: 364801308,
      first_name: 'Koneko',
      last_name: 'Toujou',
      invited_by: 69028038,
      type: 'profile'
    },
    {
      last_name: '',
      first_name: 'test@test.test',
      id: -2125073939,
      invited_by: 69028038,
      type: 'profile'
    }
  ]
}
```

когда ожидается, что он будет выглядеть как-то так:
```json
[
  {
    id: 69028038,
    first_name: 'Andrey',
    last_name: 'Koneko',
    invited_by: 69028038,
    type: 'profile'
  },
  {
    id: 364801308,
    first_name: 'Koneko',
    last_name: 'Toujou',
    invited_by: 69028038,
    type: 'profile'
  },
  {
    last_name: '',
    first_name: 'test@test.test',
    id: -2125073939,
    invited_by: 69028038,
    type: 'profile'
  }
]
```

к сожалению фикс пока не могу сгенерировать (чтобы и так и так работало), поэтому оставил это тут как проблему

**Comment by CaCTuCaTu4ECKuu** [comment]
Проверьте, теперь проблемы нет?

**Comment by EarsKilla** [comment]
Теперь одаёт нормально список участников, но, если указать несколько диалогов, то сбросит всё в одну кучу. Желательно бы разделение прикрутить на чаты. Но для меня это не критично, в моём проекте запрашивается только один конкретный чат.
