### ISSUE TITLE
Апи товаров  метод добавления в Недоступные товары и обратно.

### ISSUE THREAD

**Issue by OlXC** [vknet/vk#286]
Товар можно удалить ,но нельзя на текущий  момент перевести в Недоступные.

**Comment by volshebniks** [comment]
интересный вопрос ... судя по документации VK на market_item, у товара есть поле "availability" - но отредактировать это поле методом Edit, нельзя .... нет его в списке параметров.

**Comment by OlXC** [comment]
провёл эксперимент ,опытным путём было установлено ,что если передать в market.edit товар то у него автоматическим путём снимается галочка Товар недоступен

**Comment by volshebniks** [comment]
а как вы смогли сделать его недоступным?

**Comment by OlXC** [comment]
галочку поставил)))

**Comment by inyutin-maxim** [comment]
Ответ поддержки:
> Максим Инютин
> В API нельзя сделать товар недоступным. Нет поля в методе edit, хотя через интерфейс сайта есть соответствующий флажок
> 13 ноя 2016 в 23:20
> 
> Агент поддержки #1628
> Здравствуйте, Максим!
> 
> Увы, пока подобного в API и правда нет. Само собой, в планах добавить.
> 
> Тёплой и солнечной осени!
> Команда поддержки ВКонтакте

**Comment by inyutin-maxim** [comment]
![image](https://user-images.githubusercontent.com/1781005/33423061-c3d35e28-d5c8-11e7-8ac2-da29af811d84.png)
