### ISSUE TITLE
проблема с полями отнаследованными от SafetyEnum

### ISSUE THREAD

**Issue by volshebniks** [vknet/vk#289]
Пример: 
класс: Group
поле public GroupType Type  имеет несколько допустимых возможных значений (page,group и т.д.)

если в конструкторе  не сделать  (сейчас не сделано)
`
        public Group(bool gag = true)
        {
            Type = new GroupType();
        }
`
то PossibleValues не заполняются и соответственно поле Type  всегда Null.

Может я чего не недопонимаю ... но кажется так. Верно для всех property отнаследованными от SafetyEnum.

**Comment by inyutin-maxim** [comment]
Вполне может быть что я не продумал этот момент, я либу то использую для мелких потребностей. использую крайне редко, да и времени сейчас ей заниматься совсем нет((

**Comment by volshebniks** [comment]
понятно.
Тогда еще вопрос - а зачем такие сложности с созданием mask в  SafetyEnum.? Да и теоретически  при такой генерации маски могут и кончится ...  я бы просто для генерации ключа hash бы считал  и не парился.

**Comment by inyutin-maxim** [comment]
это было написано ранее (до меня) и насколько я понял не совсем правильно потому что предела быстра достигает

**Comment by volshebniks** [comment]
Все оказалось несколько сложнее. Если класс имеет static свойства - то они инициализируются (один раз на приложение) при первом создании экземпляра класса или при первом вызове его метода. Но если первое обращение к классу это вызов его static метода, например FromJSON то свойства будут инициализированы после этого вызова, соответственно на момент выполнения  FromJSON коллекция PossibleValues будет пустая.

ничего кроме как 
в конструкторе VKAPI 
сделать что то такое (код на VB, но думаю все понятно)
`
        Dim asm as Assembly   =  Assembly.GetExecutingAssembly()
        For Each type As Type In asm.GetTypes()
            if type.BaseType IsNot Nothing AndAlso type.BaseType.Name="SafetyEnum`1"  
                Dim testType = Activator.CreateInstance(type)    
            End If
        Next
`
что гарантированно проинициализирует все такие классы, в голову не приходит.

**Comment by inyutin-maxim** [comment]
хм, ну это нужно проверять, времени пока катастрофически не хватает

**Comment by dvygolov** [comment]
подтверждаю такое поведение, столкнулся с ним при получение PostType из Post

**Comment by inyutin-maxim** [comment]
@volshebniks , @dvygolov Добавил активатор в процессе вызова FromJson
Прошу проверить ушла ли проблема. Соберите проект из Github
