### ISSUE TITLE
Падает при попытке парсинга альбома

### ISSUE THREAD

**Issue by proggmatic** [vknet/vk#29]
При попытке парсинга системного альбома исключение Can not convert Object to String.

Причина:
нужно поправить настройки приватности (https://vk.com/dev/privacy_setting)
для полей album.PrivacyView и CommentPrivacy. Там возвраащется объект, а не строка.
Кстати, вместо comment_privacy должен быть privacy_comment

**Comment by inyutin-maxim** [comment]
#29 исправил настройки приватности. Падение было поправлено в задаче #28 …
