### ISSUE TITLE
При попытке получить стену сообщениие о том, что пользователь спрятал её.

### ISSUE THREAD

**Issue by zldrq** [vknet/vk#291]
Свою стену, да.

```csharp
//...
Vk = new VkApi();
Vk.Authorize(new ApiAuthParams{ Settings = Settings.Wall }); //остальные параметры опущены для краткости
//авторазиция как таковая проходит успешно. приложение устанавливается в пользователя с разрешением доступа к стене

var prms = new WallGetParams{OwnerId = Vk.UserId, Count = 100};
var wallChunk = Vk.Wall.Get(prms);
```
имеем результат:
`{"Access denied: user hid his wall from accessing from outside"}`

**Comment by inyutin-maxim** [comment]
Пользователь скрыл свою стену от доступа извне

**Comment by Soniclev** [comment]
Скорее всего метод не вставляет access_token, потому что в [Line](https://github.com/vknet/vk/blob/master/VkNet/Categories/WallCategory.cs#L47) skipAuthorization = true

**Comment by inyutin-maxim** [comment]
@zldrq Пожалуйста соберите последнюю версию библиотеки и проверьте возникает ли проблема снова, пожалуйста отпишитесь

**Comment by zldrq** [comment]
я нашёл быстро, где косяк, у себя просто выключил SkipAuthorization в вашем коде.
насколько я понимаю, этому фиксы и посвящены, так что уверен, проблема не возникает
