### ISSUE TITLE
Проблема с ProfileFields.All, UsersFields.All

### ISSUE THREAD

**Issue by Masterzx777** [vknet/vk#293]
Использовал метод **Users.Search**. В сборке из nuget в этом методе [ошибка с токеном](https://yadi.sk/i/dhlq_Y6buKKnc): no access_token passed. Поэтому собирал отсюда, здесь с этим проблем нет.

Далее делаю запрос с такими параметрами:

``` csharp
  var users = Api.Vk.Users.Search( new UserSearchParams
            {
                Query = "Вася",
                Fields = ProfileFields.All // Здесь исключение: Ссылка на объект не указывает на экземпляр объекта
            });
```

[И получаю исключение.](https://yadi.sk/i/8nDsUnzKuKKrc)

Делаю запрос с другими параметрами:

``` csharp
  var users = Api.Vk.Users.Search( new UserSearchParams
            {
                Query = "Вася",
                Fields = ProfileFields.City 
            });
```

[Отрабатывает как надо.](https://yadi.sk/i/xq5w0zVjuKKtS)

И ещё вопрос такой, я так понимаю в **Fields** нельзя указать несколько конкретных параметров? Получается либо один, либо все?

**Comment by inyutin-maxim** [comment]
несколько можно через ProfileFields.City | ProfileFields.Name

**Comment by Masterzx777** [comment]
@inyutin-maxim 

> несколько можно через ProfileFields.City | ProfileFields.Name

Отлично.

В Groups.GetMembers с параметром UsersFields.All также непонятки..
[Выдаёт:](https://yadi.sk/i/f3drEGfluLCD8) One of the parameters specified was missing or invalid: fields could not contain common_count for unauthorized user

**Comment by volshebniks** [comment]
Если сделать запрос с Fields = ProfileFields.All  или с ProfileFields.Career - падает по следующим причинам:
1. поле Career  в User должно быть массивов 
2. поле From в  Career   должно быть "int?", а не просто "int", так как приходит не всегда. 

пофиксил

**Comment by Masterzx777** [comment]
@volshebniks 

> пофиксил

Видимо что-то ещё там.. [Так работает](https://yadi.sk/i/46CktMTiuLRsN)
```csharp
var users = Api.Vk.Users.Search(new UserSearchParams
                {
                    Query = "Вася",
                    Fields = ProfileFields.All
                });
```
[Так не работает](https://yadi.sk/i/54TRBPIruLRva)
```csharp
var users = Api.Vk.Users.Search(new UserSearchParams
                {
                    Query = "Вася",
                    Fields = ProfileFields.All, // Здесь исключение: Ссылка на объект не указывает на экземпляр объекта
                    Count = 1000
                });
```
[Так работает](https://yadi.sk/i/gCgvdjvluLRyF)
```csharp
var users = Api.Vk.Users.Search(new UserSearchParams
                {
                    Query = "Вася",
                    Count = 1000
                });
```

**Comment by inyutin-maxim** [comment]
@Masterzx777 Если вам не сложно соберите у себя проект и отпишитесь возникают ли проблемы после исправления

**Comment by inyutin-maxim** [comment]
@Masterzx777 Перепилил MultivaluedFilter, соберите из github
