### ISSUE TITLE
Изменение типа переменной VkApi.RequestsPerSecond

### ISSUE THREAD

**Issue by volshebniks** [vknet/vk#297]
После изменения типа переменной VkApi.RequestsPerSecond на float сборка не собирается

ошибка в _minInterval = (1000 / _requestsPerSecond) + 1;
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0266	Cannot implicitly convert type 'float' to 'int'. An explicit conversion exists (are you missing a cast?)	VkNet	E:\GIT\VK\VkNet\VkApi.cs	84	Active

Это  во первых, а во вторых - ну очень сомнительное изменение - так как - даже если я сделаю и 
private float _minInterval;
и вот тут тоже поправлю Thread.Sleep((int)_minInterval - (int)span.TotalMilliseconds);
то все эти float все равно округляться до int

Да и звучит странно - полтора запроса в секунду. - Это как? 

нужно делать запросы реже ... добавьте в свой код скажем Thread.Sleep(54321).

**Comment by CaCTuCaTu4ECKuu** [comment]
Звучит странно, но фактически работать будет. 2 запроса в 3 секунды или 1 запрос в 2 секунды будет работать при таких значениях.

**Comment by CaCTuCaTu4ECKuu** [comment]
#298 поправлено
