### ISSUE TITLE
Friends.Add неоднозначный вызов

### ISSUE THREAD

**Issue by oriaraniar** [vknet/vk#301]
При попытке использовать метод только с одним параметром, возникает неопределенность, поскольку существует 2 метода Add с разными сигнатурами, но в которых все параметры, кроме первого, необязательны.

Соответственно, использовать метод с указанием только одного параметра не представляется возможным.

**Comment by Soniclev** [comment]
Пока что можно вызывать так
`
VkApi.Friends.Add(1, follow: null);
`

**Comment by inyutin-maxim** [comment]
в следующем релизе будет исправлено
