### ISSUE TITLE
Ошибка в методе GroupsCategory.IsMember

### ISSUE THREAD

**Issue by oriaraniar** [vknet/vk#303]
userIds.ToList().Add(userId.Value);

Тут не происходит изменения переменной userIds, соответственно далее по коду отправляется пустой лист, что приводит к ошибке.

Студия подсказывает решение через дополнительную переменную
var enumerable = userIds as IList<long> ?? userIds.ToList();
enumerable.Add(userId.Value);

Да и в принципе метод нерабочий и какой-то странный
{ "extended", extended } - Это не работает, ибо  VkParameters - это коллекция строк и bool туда не пишется.

if (userIds != null)
		        {
		            ...
		        }
		        else
		        {
		            if (userId.Value < 1)
		            {
		                throw new ArgumentException("Идентификатор пользователя должен быть больше 0");
		            }
		            userIds= new List<long>
		            {
		                userId.Value
		            };
		        }

Всё, что после else - вообще непонятно. Зачем проверять на значение, если там null?

return result.ToReadOnlyCollectionOf<GroupMember>(x => x);
Возврат тоже нерабочий и всегда возвращает нулл

**Comment by volshebniks** [comment]
1. действительно { "extended", Convert.ToInt32(extended) } необходим
2. userIds.ToList().Add(userId.Value) - пофиксил 

pull request создан
у меня заработал.

**Comment by CaCTuCaTu4ECKuu** [comment]
#304
