### ISSUE TITLE
Метод Audio.Get возвращает не все аудиозаписи

### ISSUE THREAD

**Issue by impaxel** [vknet/vk#306]
Пробую получить 10 аудиозаписей. У меня (82685090) из 10 возвращает 9. У друга (65425263) 8 из 10. Если получить аудиозаписи, которые не удалось вернуть, через статус пользователя, то их Audio.Url = null.

**Comment by timonsk** [comment]
Такая же ситуация. Таже работает аналогичным образом с Audio.Search, ставишь Count 300, возвращает то 267 то 278, то еще чего но не ровно 300.

**Comment by volshebniks** [comment]
похоже баг на стороне VK.  записей не хватает уже в сыром json.

**Comment by CaCTuCaTu4ECKuu** [comment]
У меня на телефоне плеер с плагином ВК тоже не все аудиозаписи видит, лаги у ВК
