### ISSUE TITLE
Метод Execute и Invoke возвращают пустой ответ

### ISSUE THREAD

**Issue by timonsk** [vknet/vk#307]
Привет!
При вызове метода Invoke или Execute все время получаю {"response":[]} .
Пример с использованием Invoke : 
`Api.Invoke("execute.getTrackById", new Dictionary<string, string> {{ "trackId", "456239293"}});`

Пример с использованием Execute : 
`Api.Execute.Execute( @"return API.audio.getById({audios: ""-107408841_456239293""});"); `

В обоих случаях получаю {"response":[]}. Процедура на стороне ВК создана. Спасибо за ответ.

**Comment by volshebniks** [comment]
только что попробовал Api.Execute.Execute("return API.audio.getById({audios: ""-32015300_133000783""});")

Все вернулось правильно.

Если беру ваш пример ID возвращается пустой ответ.
