### ISSUE TITLE
Не понятно, как использовать Attachments.

### ISSUE THREAD

**Issue by WierdGreenCat** [vknet/vk#308]
var post = api.Wall.Post(new WallPostParams
            {
                OwnerId = XXXX,
                FromGroup = true,
                Attachments =  ???,
                Message = "RND"

            });

**Comment by volshebniks** [comment]
Использовать как то так: (код на VB, но думаю все понятно)
`
Dim mediaAttachments as New List(Of Attachments.MediaAttachment)
Dim objmediaAttachment as new Attachments.Photo  'Тип вложения
objmediaAttachment.Id = "428528120"   'это ID объекта который вы хотите прикрепить
objmediaAttachment.OwnerId=_vk.UserId  'ID владельца объекта
mediaAttachments.Add(objmediaAttachment)
                 
_vk.Wall.Post(New WallPostParams With {.OwnerId=_vk.UserId, .Message="Test", .Attachments=mediaAttachments})
`

**Comment by WierdGreenCat** [comment]
Спасибо,  уже разобрался. Использовал несколько извращенную форму.
VkNet.Model.Attachments.Link lnk = new VkNet.Model.Attachments.Link();
            Uri url = new Uri(text);
            lnk.Url = url;
            lnk.Image = text;
            lnk.IsExternal = true;
Attachments = new List<MediaAttachment> { lnk },

**Comment by inyutin-maxim** [comment]
https://github.com/vknet/vk/wiki/FAQ
Загляните сюда, я думаю это поможет

**Comment by inyutin-maxim** [comment]
отпишитесь пожалуйста по роблеме
