### ISSUE TITLE
Ошибка в авторизации

### ISSUE THREAD

**Issue by Aragas** [vknet/vk#309]
Здравствуйте. При авторизации у пользователя возникает непонятная ошибка, возможно, дело в парсере.

System specifications:
Operating system: Microsoft Windows NT 6.1.7601 Service Pack 1 [.NET]
Core architecture: 64 Bit
System language: English (United States)
Logical processors: 4
Error information:
Type: VkNet.Exception.VkApiException
Message: Form element not found.
HelpLink: Empty
Source: VkNet
TargetSite : HtmlAgilityPack.HtmlNode GetFormNode()
CallStack:
   at VkNet.Utils.WebForm.GetFormNode()
   at VkNet.Utils.WebForm.ParseInputs()
   at VkNet.Utils.WebForm..ctor(WebCallResult result)
   at VkNet.Utils.Browser.Authorize(UInt64 appId, String email, String password, Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey, String host, Nullable`1 port)
   at VkNet.VkApi.Authorize(UInt64 appId, String emailOrPhone, String password, Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey, String host, Nullable`1 port)
   at VkNet.VkApi.Authorize(ApiAuthParams params)
   at VKPlayer.Plugin.AudioPlayerSkin.AuthorizationForm_SubmitClicked(String login, String pass, String twofactor

Какие-то доп данные предоставить надо?

**Comment by inyutin-maxim** [comment]
приведите кусок кода где вы авторизуетесь, возможно вы что то из обязательных параметров не передаете
и еще укажите установлена ли у вашего аккаунта 2-хфакторная авторизация

**Comment by Aragas** [comment]
2факторка есть.
 API.Authorize(new ApiAuthParams
 {
    ApplicationId = XXXXX,
    Login = login,
    Password = pass,
    Settings = Settings.Audio,
    TwoFactorAuthorization = () => twofactor
 });

**Comment by inyutin-maxim** [comment]
Напишите мне в [телеграм]
(https://telegram.me/inyutin_maxim) или [vk](https://vk.com/inyutin_maxim)

**Comment by inyutin-maxim** [comment]
@Aragas Ваша проблема решена, и как вы достигли ее решения?

**Comment by inyutin-maxim** [comment]
Проблема решена из вашего фикса

**Comment by Paster-t** [comment]
Здравстуйте я с Украины. Пытаюсь осуществить авторизацию. Вот код:

```
VkApi vkapi = new VkApi();
var authparam = new ApiAuthParams();  
authparam.Login =+380 xxxx
authparam.Password = xxxx;
authparam.ApplicationId = xxxx
authparam.Settings = Settings.All;
vkapi.Authorize(authparam);   
``` 

На что получаю следующую ошибку: 

```
Необработанное исключение: System.AggregateException: Произошла одна или несколько ошибок. ---> System.Net.Http.HttpRequestException: Произошла ошибка при отправке запроса. ---> System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:443
   в System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   в System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Конец трассировки внутреннего стека исключений ---
   --- Конец трассировки внутреннего стека исключений ---
   в System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   в System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   в System.Threading.Tasks.Task`1.get_Result()
   в VkNet.Utils.WebCall.MakeCall(String url, IWebProxy webProxy)
   в VkNet.Utils.Browser.Authorize(UInt64 appId, String email, String password, Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey)
   в VkNet.VkApi.Authorize(UInt64 appId, String emailOrPhone, String password, Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey)
   в VkNet.VkApi.AuthorizeWithAntiCaptcha(UInt64 appId, String emailOrPhone, String password, Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey)
   в VkNet.VkApi.Authorize(ApiAuthParams params)
   в vk.Program.Main(String[] args) в E:\tester2\tester\vk\vk\Program.cs:строка 26
```


Авторизация пользователя не двухэтапная.
Может ли это быть связанно с блокировкой доступа в вк в нашей стране?

**Comment by Soniclev** [comment]
@Paster-t возможно это связанно с блокировкой. Попробуйте авторизоваться через прокси

**Comment by Paster-t** [comment]
Можно поподробней как настроить прокси. Я знаю что это. Мне нужны конкретные разъяснения, если можно.

**Comment by Mina888** [comment]
Хороший вопрос. Я тоже с Украины и меня интересует решение этой проблемы

**Comment by IIImatkos** [comment]
Когда передаешь параметры авторизации используй прокси.
vk.Authorize(new ApiAuthParams
            {
                ApplicationId = appID,
                Login = email,
                Password = pass,
                Settings = scope,
                Host = "127.0.0.01", //тут прокси сервер
                Port = 80 // порт
            });
