### ISSUE TITLE
При вызове api.Groups.Get - Ошибка: User authorization failed: no access_token passed

### ISSUE THREAD

**Issue by HackError** [vknet/vk#315]
При попытке вызова api.Groups.Get получаю Exception User authorization failed: no access_token passed. Авторизация двухфакторная. Проходит и авторизуется точно.

`groups = api.Groups.Get(
                new GroupsGetParams()
                {
                    UserId = api.UserId,
                    Extended = true,
                    Filter = GroupsFilters.Events,
                    Fields = GroupsFields.All
                });`

**Comment by HackError** [comment]
При вызове api.Users.GetSubscriptions(api.UserId,200) загружаются группы, но не все.

**Comment by Soniclev** [comment]
Какая версия библиотеки?На гите [исправлено](https://github.com/vknet/vk/blob/master/VkNet/Categories/GroupsCategory.cs#L86)

**Comment by Soniclev** [comment]
Бывает такое, что сервер возращает не всех подписчиков, групп и т.д.

**Comment by HackError** [comment]
Из NuGet - 1.23.0

**Comment by inyutin-maxim** [comment]
Есть подозрение что там не правильная сборка, следующий релиз будет в начале следующего месяца

**Comment by HackError** [comment]
Подтверждаю. Пересобрал с гита, всё работает.
