### ISSUE TITLE
api.Wall.Post и WallPostParams

### ISSUE THREAD

**Issue by HackError** [vknet/vk#316]
Хочу сделать пост на стену с фотографиями. Пост отдельно публикуется. Фотографии загружаются. Проблема только в attachments.

Каким образом добавлять в параметры Attachments? Attachments имеют тип IEnumerable[MediaAttachment]. Создавать объект Photo? Какие поля необходимо заполнить тогда у объекта?

**Comment by inyutin-maxim** [comment]
https://github.com/vknet/vk/wiki/FAQ

**Comment by inyutin-maxim** [comment]
@HackError  Пожалуйста отпишитесь ваша проблема решена?

**Comment by HackError** [comment]
Да, проблема решена, однако не обошлось без глюков. Фотографии загруженные на стену невозможно прикрепить к записи. Загружаются они точно, доступ по ссылке к ним есть, но получить их через api.Photo.GetById невозможно - Access Denied. Пришлось загружать в альбом и оттуда прикреплять.
