### ISSUE TITLE
Wall.Get не возвращает записи из закрытых групп

### ISSUE THREAD

**Issue by Andriy1218** [vknet/vk#317]
Пытаюсь получить записи из закрытых групп, в которых я состою: 
```
WallGetParams param = new WallGetParams 
{ 
Count = 5, 
OwnerId = -1 * groupId 
}; 
var posts = vk.Wall.Get(param);
```
Выскакивает AccessDeniedException(Access denied: this wall available only for community members).
И я пробивал получить записи со многих закрытых групп, в которых я состою, и получаю эту проблему.
Писал @inyutin-maxim, и он сказал что метод немного сломан и в нем не передается токен. Ошибка вроде в классе wallcategory.

**Comment by Soniclev** [comment]
Попробуй так
`
WallGetParams param = new WallGetParams 
{ 
Count = 5, 
OwnerId = -1 * groupId 
}; 
var posts = vk.Wall.Get(param, false);
`

**Comment by CaCTuCaTu4ECKuu** [comment]
Сегодня гляну.
Вместо -1 * groupId можно передавать сразу -groupId

**Comment by Andriy1218** [comment]
@Soniclev У метода Wall.Get нету такой перегрузки. Есть только два варианта: Wall.Get(WallGetParams param) и Wall.Get(long ownerId, out int totalCount, int? count = null, int? offset = null, WallFilter filter = null).

**Comment by Andriy1218** [comment]
@CaCTuCaTu4ECKuu У вас тоже не работает? Или я один такой?

**Comment by inyutin-maxim** [comment]
@Andriy1218 Соберите библиотеку из гитхаба

**Comment by Andriy1218** [comment]
@inyutin-maxim Только что попробовал. Той же самый exception выскакивает.

**Comment by inyutin-maxim** [comment]
@Andriy1218 Тесты починю и посмотрю, мой [vk](https://vk.com/inyutin_maxim) и [телеграмм](
https://telegram.me/inyutin_maxim), напишите мне, нужны будут данные для проверки

**Comment by inyutin-maxim** [comment]
@Andriy1218 Доброго времени суток свяжитесь пожалуйста со мной [vk](https://vk.com/inyutin_maxim) или [телеграмм](
https://telegram.me/inyutin_maxim) для разбора вашей проблемы

**Comment by qwertyo1** [comment]
Подпишусь, тоже с такой проблемой столкнулся. В комментариях под документацией к методу wall.get три месяца назад рабочий фикс писали. Не уверен, безболезненный ли он.
"Если группа закрыта, то возвращает access denied, не смотря на то, что 
пользователь состоит в группе. Судя по исходникам баг из-за того, что 
библиотека игнорит авторизацию и всегда в _vk.Call передаёт 
skipAutorization равной true. Для себя уже пофиксил, но хочу чтобы 
разрабы тоже у себя это исправили."

**Comment by inyutin-maxim** [comment]
@qwertyo1 Пул реквест в студию)

**Comment by qwertyo1** [comment]
@inyutin-maxim наваял)
