### ISSUE TITLE
Переход на UWP

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#318]

**Comment by inyutin-maxim** [comment]
Начал процесс перевода проекта, возникли следующие проблемы:

- [ ] - Атрибут Serializable отсутствует в UWP
- [ ] - Класс Timer отсутствует в UWP

---------
PS. Приветствуется помощь тех кто сталкивался с подобными проблемами

**Comment by Farrell23** [comment]
Если не ошибаюсь в UWP сделали получше таймер и он в классе DispatcherTimer - https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.dispatchertimer.aspx

**Comment by virtyaluk** [comment]
> Класс `SerializationInfo` отсутствует в UWP (Используется в `Exception`'ах) - (Временно закомментировал методы)

Классы `DataMember` и `DataContract` в связке с JSON.NET.

**Comment by inyutin-maxim** [comment]
@virtyaluk Спасибо за инфу)

**Comment by inyutin-maxim** [comment]
Вниманию страждущим, появилась первая рабочая альфа версия
На данный момент не работает таймер

**Comment by inyutin-maxim** [comment]
за сборкой обращаться ко мне в [вк](https://vk.com/inyutin_maxim)

**Comment by inyutin-maxim** [comment]
Поддерживаемые платформы:
- .NET Framework 4.5
- ASP.NET Core 1.0
- Windows 8
- Xamarin.Android
- Xamarin.iOS
- Xamarin.iOS (Classic)

**Comment by inyutin-maxim** [comment]
Перевел проект на [.NETStandard Library](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) исправил некоторые проблемы, переход можно считать оконченным

PLATFORM NAME	| ALIAS | Version
------------ |------------ | -------------
.NET Standard|netstandard|1.2
.NET Core|netcoreapp|1.0
.NET Framework|net|4.5.1
Mono/Xamarin|Platforms|vNext
Universal Windows Platform|uap|10.0
Windows|win|8.1					
Windows Phone|wpa|8.1					

Библиотека удовлетворяет спецификациям .NET Standard 1.2, она может быть использована только на платформах: .NET Framework 4.5.1 (и более новыми), .NET Core, Universal Windows Platform 10 (UWP) и Mono/Xamarin.

Ссылка на сборку с релизом [Здесь](https://github.com/vknet/vk/releases/tag/v1.25.0.0)

**Comment by Farrell23** [comment]
Огромное спасибо)

**Comment by inyutin-maxim** [comment]
Влил код для UWP сборки в master

Как это реализовано, есть 2 решения, каждое ссылается на свой проект(тип сборки, UWP или .NET 4.0)
Может есть подходы правильнее, жду комментариев в личку [вк](https://vk.com/inyutin_maxim) или [телеграмм](https://telegram.me/inyutin_maxim)
