### ISSUE TITLE
GetChatUsers выдает пустой массив пользователей.

### ISSUE THREAD

**Issue by AlexKveeN** [vknet/vk#320]
VkNet 1.23.0 с Nuget 
Ошибка с GetChatUsers. Выдает пустой массив пользователей.

Пример кода
List<long> ChatIDs = new List<long>(123456);
var GetChatInfo = Api.Messages.GetChatUsers(chatIds: ChatIDs, fields: UsersFields.Online ,nameCase: NameCase.Nom);

**Comment by Soniclev** [comment]
Соберите библиотеку из гита

**Comment by AlexKveeN** [comment]
Новая версия (1.24) выдает так же пустой массив. Проблема не решилась.

**Comment by inyutin-maxim** [comment]
@AlexKveeN Вы неправильно передаете ИД чата
У вас:
``` csharp
List ChatIDs = new List(123456);
```
Правильно:
``` csharp
List ChatIDs = new List(){123456};
```

**Comment by inyutin-maxim** [comment]
@AlexKveeN в конструктор передается capacity(емкость) списка
