### ISSUE TITLE
Значение было недопустимо малым или недопустимо большим для Int32.

### ISSUE THREAD

**Issue by b1tc0re** [vknet/vk#321]
- Класс и метод в котором возникла проблема:
Users.Search
- У одного из пользователей **174034224** . Полученный ответ. :
```json
{
  "company": "　",
  "country_id": 1,
  "city_id": 1041822,
  "until": 9.2233720368547779E+18,
  "position": "　"
}

```
Проблема в until

**Comment by b1tc0re** [comment]
- Класс и метод в котором возникла проблема:
VkResponce
```c#
public static implicit operator Uri(VkResponse response)
{
	return !string.IsNullOrWhiteSpace(response) ? new Uri(response) : null;
}
```
- У одного из пользователей **338028294** . Полученный ответ. :

```json
{
"id": 338028294,
"first_name": "Misha",
"last_name": "OrLove",
"photo_50": false,
"verified": 0
}
```
Проблема в photo_50

**Comment by inyutin-maxim** [comment]
ко второму вашему комментарию это ошибка данных, мы ориентировались на документацию

**Comment by inyutin-maxim** [comment]
Исправлено, будет включено в следующий релиз
