### ISSUE TITLE
Internal server error: could not check access_token now, check later.

### ISSUE THREAD

**Issue by Timz** [vknet/vk#323]
Салют. Вываливает баг указанный в сабже. на строке " For Each comm In vk.Wall.GetComments..."
Как сгенить ошибку не могу понять. Ошибка начала появляться пару дней назадю до этого все нормально работало. Вываливает например на парсинге коментов[ этого поста](https://vk.com/animator_group?w=wall-81549038_688_r690)
Что может быть?
        **'Для каждого поста на стенке. Начало
        For Each p As VkNet.Model.Post In wallz.WallPosts
            ...
            'Если есть коментарии, то обойти их
            If p.Comments.Count > 0 Then
                For Each comm In vk.Wall.GetComments(10, New WallGetCommentsParams With {.PostId = p.Id, .StartCommentId = 0, .OwnerId = p.OwnerId.Value})
                    ...
                Next
            End If
        Next
        'Для каждого поста на стенке. Конец**

upd. Проблема выскакивает раз в несколько часов в рандомных запросах. походу в какой то момент теряется токен или возможность его проверить

**Comment by inyutin-maxim** [comment]
@Timz Вам удалось обойти эту проблему?

**Comment by Timz** [comment]
нет. не могу отловить ее. выскакивает редко. раз в 2-3 суток.

**Comment by Soniclev** [comment]
@Timz  Как мне кажется, это внутренняя ошибка ВК
