### ISSUE TITLE
ReturnFriends

### ISSUE THREAD

**Issue by SFocus** [vknet/vk#324]
**Метод Apps.Get**

ReturnFriends - 1 – возвращает список друзей, установивших приложение. (Данный параметр работает только, если пользователь передал валидный access_token) 0 – не возвращать список друзей, по умолчанию. флаг, может принимать значения 1 или 0, по умолчанию 0

**как передать access_token?**

с передачей access_token разобрался но все таки как получить список друзей которие установили даное приложение? 
да и в моделе App.cs нету поля friends. как достать friends?)

**Comment by SFocus** [comment]
Ребят так как достать список друзей в приложение?

**Comment by inyutin-maxim** [comment]
@SFocus А вы передаете параметр fields?

**Comment by SFocus** [comment]
@inyutin-maxim а как передать?) что прописать после        

> Fields = 
?

**Comment by inyutin-maxim** [comment]
Оставьте, библиотека пока не решает проблему

**Comment by inyutin-maxim** [comment]
В новой версии будет исправлено. Заменил возвращаемый тип на [AppGetObject](https://github.com/vknet/vk/blob/master/VkNet/Model/AppGetObject.cs)
