### ISSUE TITLE
Возвращает VkNet.Model.User

### ISSUE THREAD

**Issue by slagusev** [vknet/vk#325]
Пробую получить список (id) друзей, после авторизации.
Но listBox заполняется "VkNet.Model.User"

```
            var users = api.Friends.Get(287******);
            listBox1.DataSource = users;
```

**Comment by inyutin-maxim** [comment]
@slagusev Не совсем пойму вашу проблему напишите мне [vk](https://vk.com/inyutin_maxim) и [телеграмм](
https://telegram.me/inyutin_maxim)

**Comment by Soniclev** [comment]
Класс User содержит поле Id, которое хранит id пользователя

**Comment by slagusev** [comment]
Из документации "После успешного выполнения возвращает список идентификаторов (id) друзей..." Так вот, за место ID, выводит items заполненные текстом "VkNet.Model.User"

**Comment by inyutin-maxim** [comment]
@slagusev Это сделано для того что если ты передаешь параметр fields то тогда возвращается именно объект пользователя, так что не считаю это проблемой
