### ISSUE TITLE
Список друзей

### ISSUE THREAD

**Issue by KsanderKage** [vknet/vk#326]
Пытаюсь получить список друзей:
var arr = VK.Friends.Get(new FriendsGetParams
                {
                    UserId = VK.UserId,
                    Fields = ProfileFields.All,
                });

Запрос падает со следующей ошибкой:
One of the parameters specified was missing or invalid: fields could not contain common_count for unauthorized user

stackTrace
в VkNet.Utils.VkErrors.IfErrorThrowException(String json) 
в VkNet.VkApi.Invoke(String methodName, IDictionary`2 parameters, Boolean skipAuthorization) 
в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization) 
в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization, String apiVersion) 
в VkNet.Categories.FriendsCategory.Get(FriendsGetParams params, Boolean skipAuthorization) 
в KsARP.Model.Vk.GetFriend() в D:\Ksander\Project\KsARP\Model\Vk.cs:строка 166

**Comment by inyutin-maxim** [comment]
@KsanderKage доброго времени суток, вы не передали один параметр, вот решение:

``` csharp
var arr = VK.Friends.Get(new FriendsGetParams
            {
                UserId = VK.UserId,
                Fields = ProfileFields.All,
            }, false);
```
