### ISSUE TITLE
FormatException при вызове Photo.SaveWallPhoto()

### ISSUE THREAD

**Issue by koheatel** [vknet/vk#327]
Файл `VkNet.cs` строка 649
`builder.AppendFormat($"{pair.Key}={pair.Value}&");`
должно быть
`builder.Append($"{pair.Key}={pair.Value}&");`
Во-первых, метод AppendFormat здесь неуместен т.к. строка уже форматирована при помощи интерполяции, во-вторых при вызове метода `Photo.SaveWallPhoto()` один из параметров - json строка photo.
Метод AppendFormat работает со строками вида `"{0} val {1}", arg1, arg2`, паттер генерируется в рантайме, т.е. json строка содержащая неэкранированные символы, как в данном случает json '{' и '}', будет крашить приложение.
Краш можно воссоздать любым загруженным изображением.

**Comment by inyutin-maxim** [comment]
исправлено, будет добавлено к следующей версии
