### ISSUE TITLE
Invalid authorization with login:password при двухфакторной аутентификации

### ISSUE THREAD

**Issue by exickdj** [vknet/vk#328]
Данная ошибка (Invalid authorization with login:password) возникает как при неправильных данных для входа, так и при двухфакторной аутентификации.
При входе в программу юзер получает окошко с текстбоксом для ввода шестизначного кода, даже если данные для входа не верны т.к. библиотека не различает эти две ошибки.
Должны быть две разные ошибки для этих двух ситуаций, насколько я знаю, при двухфакторке должно быть NeedValidationException.

**Comment by DarkKooller** [comment]
Мне кажется, что вк поменля что-то в API. Так как у меня есть бот, который отказывается работать, ссылаясь на эту же ошибку. https://psv4.vk.me/c810229/u8040701/docs/2272bb0d7b39/Snimok1.png?extra=47vKzvXEohH7raDCl021AWdsF8yLoXxqaLCPZdKWlyn_Z0JguN1GV0NgwskSxYaZ0kB_jtbnBS9hUtnHxtdegYC406ahibxsUxYZPF16gnH-v5sAs58F

**Comment by alexandrmazur96** [comment]
Та же проблема, при двухэтапной идентификации ловит совсем не ту ошибку (должна быть как написал топик стартер "NeedValidationException"), а выскакивает VkApiAuthorizationException.
Как узнать что пользователю нужна двухэтапная аутентификация?

**Comment by inyutin-maxim** [comment]
#336 исправлено по данной задаче

**Comment by anashkinyury** [comment]
А можно спросить? Есть сайт на asp.net vb.net, регистрация проходит, а аутентификация нет пишет "Email ID and password invalid". Что можно сделать? Заранее спасибо.

**Comment by inyutin-maxim** [comment]
> А можно спросить? Есть сайт на asp.net vb.net, регистрация проходит, а аутентификация нет пишет "Email ID and password invalid". Что можно сделать? Заранее спасибо.

Например реализовать OAuth для вк
