### ISSUE TITLE
Messages.GetDialogs

### ISSUE THREAD

**Issue by Sergeant13377** [vknet/vk#332]
- Класс и метод в котором возникла проблема:
  Messages.GetDialogs
- Пример кода для воспроизведения проблемы:

``` csharp
                     foreach (Message m in api.Messages.GetDialogs(new MessagesDialogsGetParams { Count = 200, Unread = true }).Messages)
                        {
                            Console.WriteLine(m.Body);
                        }
```

Суть проблемы в том, что достает только одно непрочитанное сообщение из диалога, последнее.
То есть, один диалог, одно сообщение, хотя в диалоге 30 непрочитанных...

**Comment by Soniclev** [comment]
Метод Messages.GetDialogs возращает список диалогов.Каждый диалог содержит только **одно** последнее сообщение.Чтобы получить несколько сообщений диалога, нужно использовать метод Messages.GetHistory

**Comment by Sergeant13377** [comment]
thx.
