### ISSUE TITLE
Photo.SaveWallPhoto не работает

### ISSUE THREAD

**Issue by rassvet85** [vknet/vk#333]
Класс и метод в котором возникла проблема:
Photo.SaveWallPhoto

При вызове метода возникает ошибка: 
An unhandled exception of type 'System.FormatException' occurred in mscorlib.dll
Additional information: Входная строка имела неверный формат.

Все прекрасно работало до 30 октября.

- Пример кода для воспроизведения проблемы:

                   var imageFile = Directory.GetCurrentDirectory() + @"\imageout\vkout.jpg";
                    var uploadServer = api.Photo.GetWallUploadServer(groupeid);
                    var uploadServerUri = uploadServer.UploadUrl;
                    var uploader = new WebClient();
                    var uploadResponseInBytes = uploader.UploadFile(uploadServerUri, imageFile); 
                    var uploadResponseInString = Encoding.ASCII.GetString(uploadResponseInBytes);
                    var jsonObject = (JObject)JsonConvert.DeserializeObject(uploadResponseInString);
                    var hashParameter = jsonObject["hash"].ToString();
                    var serverParameter = jsonObject["server"].ToString();
                    var photoParameter = jsonObject["photo"].ToString();
                    var photo = api.Photo.SaveWallPhoto(uploadResponseInString, null, (ulong)groupeid);

Весь код отработан без ошибок до последней команды.

**Comment by inyutin-maxim** [comment]
@rassvet85 Соберите из гитхаба или подождите новой версии
