### ISSUE TITLE
Не работает функция Photo.SaveMessagesPhoto в версии 1.24.0

### ISSUE THREAD

**Issue by AndreykaMrPvP** [vknet/vk#334]
Photo.SaveMessagesPhoto не работает в новой версии 1.24.0 (в 1.22.2 всё нормально)

Код:
```
var uploadServer = vk.Photo.GetMessagesUploadServer();
var wc = new WebClient();
var responseImg = Encoding.UTF8.GetString(wc.UploadFile(uploadServer.UploadUrl, @"1.jpg"));
var photo = vk.Photo.SaveMessagesPhoto(responseImg);
var send = vk.Messages.Send(new MessagesSendParams
{
UserId = user_id,
Message = "лови",
Attachments = photo
});
```

Сама ошибка:

> System.FormatException: Входная строка имела неверный формат.
>    в System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    в System.Text.StringBuilder.AppendFormat(String format, Object[] args)
>    в VkNet.VkApi.GetApiUrl(String methodName, IDictionary`2 parameters, Boolean skipAuthorization)
>    в VkNet.VkApi.Invoke(String methodName, IDictionary`2 parameters, Boolean skipAuthorization)
>    в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization)
>    в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization, String apiVersion)
>    в VkNet.Categories.PhotoCategory.SaveMessagesPhoto(String response)

**Comment by inyutin-maxim** [comment]
Ошибка уже исправлена, подождите новую версию или соберите из гитхаба

**Comment by inyutin-maxim** [comment]
@AndreykaMrPvP  Обновите библиотеку из nuget и отпишитесь

**Comment by AndreykaMrPvP** [comment]
@inyutin-maxim Всё заработало, спасибо.
