### ISSUE TITLE
Проблема с вложениями messages.get

### ISSUE THREAD

**Issue by denq04** [vknet/vk#335]
Прошу помочь с методом messages.get, а конкретнее с вложениями. Не получается получить url фотографии во вложении.
Получаю последнее полученное сообщение: 

var NewMess = VK.Messages.Get(new MessagesGetParams 
{ Out = MessageType.Received,
 Offset = 0,
 Count = 1,
 TimeOffset = 0 });`

Далее, с помощью этого я смог получить idфотографии:

NewMess.Messages[0].Attachments[0].Instance

Но, что делать дальше я не понимаю. Пытался получить фото по id, но требуется access_key для фото. И как его получить я тоже не знаю. Помогите с этим разобраться.

**Comment by inyutin-maxim** [comment]
Кастуй вложение к нужному типу а дальше все получится

**Comment by denq04** [comment]
Я не совсем понимаю как это сделать. В c# новичок, да и вообще в программировании.

**Comment by denq04** [comment]
Разобрался, спасибо вам большое.

**Comment by Soniclev** [comment]
var attachment = NewMess.Messages[0].Attachments[0];
if (attachment.Type == typeof(Photo))
{
    Photo photo = attachment.Instance as Photo;
}

**Comment by denq04** [comment]
Ну я сделал по другому, без проверки

((Photo)attachment).

**Comment by DezmontDeXa** [comment]
Скачал последнюю версию. В упор не вижу аттачей. 

`                            if (attach.Type == typeof(VkNet.Model.Attachments.Link))
                            {
                                VkNet.Model.Attachments.Link link = attach.Instance as VkNet.Model.Attachments.Link;
                                writer.AppendBody(link.Title + ": " + link.Url.ToString(), message.Type==VkNet.Enums.MessageType.Sended);
                            }`
Переменная link всегда null. 
С фото та же фигня. 
Может нужно что-то при запросе указать дополнительно?

**Comment by inyutin-maxim** [comment]
@DezmontDeXa [Помочь проекту](https://money.yandex.ru/to/410012783295317)
