### ISSUE TITLE
Проблема с двухэтапной аутентификацией.

### ISSUE THREAD

**Issue by alexandrmazur96** [vknet/vk#336]
Проблема в том, что делегат `_Func<string>_` срабатывает в любом случае, с любыми значениями логина и пароля. А если в настройках аккаунта отключена двухэтапная аутентификация, то войти не удастся, т.к. выбрасывает ошибки с message form not found. Что делать в этом случае? Как написать сейчас адекватную авторизацию?

**Comment by inyutin-maxim** [comment]
Сейчас видимо никак, будет время я поправлю

**Comment by EarsKilla** [comment]
@alexandrmazur96 у меня такой костыль на вооружении давно:
```cs
public bool AuthUsing2FA { get; set; } = false;

[JsonIgnore]
public Func<string> Auth2Fa { get; set; }

// ...

TwoFactorAuthorization = (this.AuthUsing2FA) ? Auth2Fa : default(Func<string>)
```
