### ISSUE TITLE
Group type is null

### ISSUE THREAD

**Issue by p4rnicke** [vknet/vk#337]
When calling the Groups.Get the returned group type is null.
I'm not sure, I guess the Type = response["type"] is not proper in the FromJson function at VkNet/Model/Group/Group.cs
The Type is a class, the response is just is just a simple string.

I tried to change this and send a PR, but the current build is failing, should be fixed first.
(Source file 'vk\VkNet\Utils\VkResponseToModelCastsGenerator.cs' could not be found.)

**Comment by Soniclev** [comment]
You should generate "VkResponseToModelCastsGenerator.cs" from T4 template to build project

**Comment by p4rnicke** [comment]
Ok, thanks.
But anyhow the Build Status: build failing on the github.
Isn’t it a problem?

**Comment by Soniclev** [comment]
Build failed on the Github, because Travis CI don't generate files from T4 templates.It is normal, but perhaps fix it

**Comment by p4rnicke** [comment]
Hey, the issue was the Type is null, not that I cannot build the project :)

**Comment by inyutin-maxim** [comment]
@p4rnicke Sorry

**Comment by p4rnicke** [comment]
When I build a debug version from source and use the DLL directly then the Group.Type is ok.
When I build a release version from source and use the DLL directly then the Group.Type is null.
If I use the nuget version then the Group.Type is null.
I do not understand the reason unfortunately.

**Comment by inyutin-maxim** [comment]
@p4rnicke In nuget is vknet the release version.
I need to investigate the example code in which the error occurs.

**Comment by p4rnicke** [comment]
I use it this way:
var groups = vk.Groups.Get(new GroupsGetParams() { UserId = userId, Extended = true });
foreach (var group in groups)
{
 if (group.Type == GroupType.Page)
...
At this point the group.Type is null, but in the debug version it is correct.
The type value was in the response (when I debugged it).

**Comment by p4rnicke** [comment]
It is not clear if you need anything more from me to reproduce the issue.
I have no clue how it can behave differently, I don't see any #if code blocks or such that could cause this issue.

**Comment by inyutin-maxim** [comment]
@p4rnicke Unfortunately at the moment there is no free time to correct this problemmu, i am try if possible to fix it

**Comment by p4rnicke** [comment]
Do you know what is causing the problem? I will fix it, if you have a clue.

**Comment by inyutin-maxim** [comment]
@p4rnicke Use Fiddler and look what the response from the server comes

**Comment by inyutin-maxim** [comment]
@p4rnicke please, build from github and check this problem

my worked code:
``` csharp
private static void Main()
{
	Api.Authorize(auth);
	Console.WriteLine("done");
	var res = Api.Groups.Get(new GroupsGetParams() {UserId = Api.UserId, Extended = true});
	Console.WriteLine(string.Join(Environment.NewLine, res.Select(x => x.Type.ToString())));
	Console.ReadLine();
}
```
