### ISSUE TITLE
Как сохранить изменения для поле career?

### ISSUE THREAD

**Issue by mrsatana666** [vknet/vk#338]
Ребята, приветствую, подскажите как быть?

Добавил объект в коллекцию

var users = vk.Users.Get(vk.UserId.Value, ProfileFields.All, null, false); 
users.Career.Add(new VkNet.Model.Career { GroupId= null, city=1 });

Но не знаю как сохранить изменения в профиле пользователя...

Речь если что о пункте карьера в профиле юзера

**Comment by Skrimsoft** [comment]
Привет. Через API нет возможности изменить карьеру. О том, какие данные профиля доступны для изменения,  можно узнать отсюда https://vk.com/dev/account.saveProfileInfo
Если ошибаюсь, прошу, поправьте.

**Comment by inyutin-maxim** [comment]
@mrsatana666  Все верно, к сожалению средствами API нет возможности редактировать эти данные

**Comment by mrsatana666** [comment]
Спасибо ребята, я это все читал,но в душе надеялся на чудо))
