### ISSUE TITLE
longpolling

### ISSUE THREAD

**Issue by EarsKilla** [vknet/vk#339]
Есть ли в планах делать работу с longpolling'ом?

У меня есть некоторые наработки, но я пока что не уверен представлять-ли их публике или нет, т.к. там есть один большой костыль с парсингом данных ответа от сервера, скорее всего не все поля может парсить, и не всё приводил к надлежащему виду (типа конвертирования времени сообщения из timestamp и прочего)

**Comment by inyutin-maxim** [comment]
@EarsKilla В планах есть, но пока есть более важные архитектурные задачи в связи с выпуском UWP сборки
