### ISSUE TITLE
Вход под прокси после капчи.

### ISSUE THREAD

**Issue by mrsatana666** [vknet/vk#341]
Появился вопрос, который был частично освещен в [Что происходит с вашей сборкой, если нужна Captcha?](https://github.com/vknet/vk/issues/89)

А если капча при авторизации возникла мы уже не можем под прокси авторизоваться получается? В перечислении autorize нет нужного, где задаются порт, хост, сид капчи и текст капчи ((

**Comment by inyutin-maxim** [comment]
https://github.com/vknet/vk/blob/master/VkNet/Model/ApiAuthParams.cs

**Comment by mrsatana666** [comment]
Вот я дуб)) Полез в старый метод и удивляюсь чего там ничего нет)) Пародньте) Закрывайте)

Спасибо,что ткнули носом!
