### ISSUE TITLE
[Предложение] Добавить Account.setPrivacy и Account.getPrivacySettings

### ISSUE THREAD

**Issue by pavlukivan** [vknet/vk#342]
Эти функции не документированы, но они есть
UPD: Они вызываются так:
https://vk.com/dev/privacy_setting
account.getPrivacySettings без аргументов (Наверное)
account.setPrivacy?key=profile|groups|...&value=friends|all|...

**Comment by inyutin-maxim** [comment]
в настоящее время методы недоступны
