### ISSUE TITLE
UWP Authorize Null Reference Exception

### ISSUE THREAD

**Issue by akusmin** [vknet/vk#343]
В методе BugFixCookieDomain()
В строке 
```
var table = (IDictionary)Container.GetType()
                                            .GetRuntimeFields()
                                            .FirstOrDefault(x => x.Name == "m_domainTable")
                                            .GetValue(Container);
```
Не находит поле m_domainTable из-за чего метод GetValue(Container) "рвет" с ошибкой.

Все поля, которые есть:
```
		[0]	"_domainTable"	string
		[1]	"_maxCookieSize"	string
		[2]	"_maxCookies"	string
		[3]	"_maxCookiesPerDomain"	string
		[4]	"_count"	string
		[5]	"_fqdnMyDomain"	string
		[6]	"s_headerInfo"	string
		[7]	"DefaultCookieLimit"	string
		[8]	"DefaultPerDomainCookieLimit"	string
		[9]	"DefaultCookieLengthLimit"	string
```

**Comment by akusmin** [comment]
В методе 
```
private WebCallResult MakeRequest(HttpResponseMessage response, Uri uri, IWebProxy webProxy)
```
Контейнер кук всегда будет пустой, т.к. не используется тот контейнер, с которым отправлялся запрос, инициализируется новый.


Метод BugFixCookieDomain отрабатывает в таком случае:

```
var table = (IDictionary)Container.GetType()
                                            .GetRuntimeFields()
                                            //.FirstOrDefault(x => x.Name == "m_domainTable")
                                            .FirstOrDefault(x => x.Name == "_domainTable")
                                            .GetValue(Container);
```

**Comment by inyutin-maxim** [comment]
@akusmin Слишком кардинальный подход, сломается работоспособность в другой сборке думаю есть вариант лучше 
``` csharp
var table = (IDictionary)Container.GetType()
                                            .GetRuntimeFields()
                                            .Where(x => x.Name == "m_domainTable" || x.Name == "_domainTable")
                                            .FirstOrDefault()
                                            .GetValue(Container);
```

Это в теории должно работать

**Comment by Montigomo** [comment]
А как быть в таком случае?
[](http://cinemo.org/images/vkapi.jpg)
когда нет таких кук вообще.

**Comment by inyutin-maxim** [comment]
@Montigomo Доброго времени суток, скажите пожалуйста в какой сборке проявляется проблема? UWP или Net4.0?

**Comment by inyutin-maxim** [comment]
#349 Добавлено к следующему релизу

**Comment by Montigomo** [comment]
Добрый? net.

**Comment by inyutin-maxim** [comment]
#349 не исправляет данную проблему. решил при помощи условной компиляции, в ближайшее время отправлю код если время будет

**Comment by AlexByte** [comment]
У меня после #349 перестало возникать NullReferenceException при работе с методами vk api в сборке UWP.

**Comment by inyutin-maxim** [comment]
@akusmin , @AlexByte, @Montigomo   Исправил при помощи условной компиляции, для .NET сборки будет применяться старый метод
