### ISSUE TITLE
Cookies.cs object reference exception

### ISSUE THREAD

**Issue by p4rnicke** [vknet/vk#344]
The BugFixCookieDomain function at VkNet.UWP/Utils/Cookies.cs throws object reference exception in the new UWP version.
I guess the problem is the table is not checked before using table.Keys
Was working with the previous solution using Hashtable.

**Comment by inyutin-maxim** [comment]
@p4rnicke  #343 The problem associated with this

**Comment by inyutin-maxim** [comment]
@p4rnicke Corrected by means of the conditional compilation, for .NET 4.0 of assembly will work as earlier
