### ISSUE TITLE
WallGetObject handling 1 returned item (object reference exception)

### ISSUE THREAD

**Issue by p4rnicke** [vknet/vk#345]
The FromJson function at Model\WallGetObject.cs does not handle correctly if wall.getbyid returns 1 item.
In fact it is not your fault but VK, it is not returning the count field if 1 item is returned.
I changed like this in my fork:
wallGetObject = new WallGetObject
                {
                    WallPosts = response["items"].ToReadOnlyCollectionOf<Post>(r => r),
                    Profiles = response["profiles"].ToReadOnlyCollectionOf<User>(r => r),
                    Groups = response["groups"].ToReadOnlyCollectionOf<Group>(r => r)
                };
                if (response["count"] != null)
                {
                    wallGetObject.TotalCount = response["count"];
                }
                else
                {
                    wallGetObject.TotalCount = 1;
                }

**Comment by inyutin-maxim** [comment]
@p4rnicke  Thank you, consider later
