### ISSUE TITLE
video model

### ISSUE THREAD

**Issue by p4rnicke** [vknet/vk#346]
The video response has an incorrect documentation at the API dev site I think (https://vk.com/dev/video_object)
It is the "old" version of the API I guess.
So if video.get returns an object then vknet is not able to map the fields correctly, the model does not handle a few fields.
The vknet implementation should be based on the current implementation.
I contacted VK about this issue, but maybe you have more influence...

**Comment by inyutin-maxim** [comment]
@p4rnicke  Unfortunately not, we have no influence, we are independent developers

**Comment by inyutin-maxim** [comment]
@p4rnicke Fixed. Build from Github
