### ISSUE TITLE
UWP Authorize. WebForm

### ISSUE THREAD

**Issue by akusmin** [vknet/vk#347]
В методе
```
public VkAuthorization Authorize(ulong appId, string email, string password, Settings settings, Func<string> code = null, long? captchaSid = null, string captchaKey = null,
                                         IWebProxy webProxy = null)
```
Ответная форма преобразует логин и пароль к EscapeDataString, что не должно быть.

Если делегат code не определен, то метод WebForm.FilledWith() упадет.

p.s. Вроде библиотека не новая. Возможно я использую устаревшие методы для авторизации пользователя, но все согласно вашим мануалам.

С небольшим тюнингом авторизация завелась.

**Comment by inyutin-maxim** [comment]
@akusmin Немного сумбурно написано, если вам не сложно свяжитесь со мной после 19:00 по Москве по [вк](https://vk.com/inyutin_maxim) или [телеграмм](https://telegram.me/inyutin_maxim), я хочу обсудить проблему

**Comment by inyutin-maxim** [comment]
#349 Добавлено к следующему релизу
