### ISSUE TITLE
Добавление параметров для распознавания капч

### ISSUE THREAD

**Issue by McDanilRus** [vknet/vk#348]
Здравствуйте. Пишу программу, в которой будет возможность публиковать записи на стену, добавлять аудиозаписи и т.д. Но при тестировании методов Audio.Add, Wall.Post обнаружил, что легко можно словить исключение CaptchaNeededException, но обработать его (предоставить пользователю возможность распознать капчу и отправить ответ) через библиотеку нельзя, т.к. отсутствуют необходимые параметры "captchaKey" и "captchaSid". Также просмотрев исходники библиотеки увидел, что они во многих методах отсутствуют. Можете, пожалуйста, добавить параметры для капч, хотя бы, в выше указанные методы?

**Comment by Freedamage** [comment]
Тоже интересно.

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну очевидно что нужно добавить параметры капча ки и капча сид к методам, которые могут выкидывать капчу. Если вы сделаете пулл реквест будет замечательно или подождите пока кто-то внесет необходимые изменения.
Можете посмотреть как это реализовано в случае с отправкой сообщения (https://github.com/vknet/vk/blob/master/VkNet.UWP/Model/RequestParams/Messages/MessagesSendParams.cs) и сделать по аналогии. Вы очень поможете если сделаете это
