### ISSUE TITLE
Не могу отправить координаты в сообщении

### ISSUE THREAD

**Issue by AlexanderPogorelov** [vknet/vk#350]
Здравствуйте. Столкнулся с проблемой, пытаюсь отправить в сообщении координаты

>                        owner.Messages.Send(new MessagesSendParams
>                         {
>                             UserId = vkMessage.UserId,
>                             Message = "г. Таганрог, ул. Фрунзе 66А",
>                             Lat = 47.217451,
>                             Longitude = 38.922743
>                         });

Получаю эксепшн

> Исключение типа "VkNet.Exception.InvalidParameterException" возникло в VkNet.dll, но не было обработано в коде пользователя
> 
> Дополнительные сведения: One of the parameters specified was missing or invalid: lat not float

Как починить? Версия библиотеки последняя из NuGet 1.25.00

**Comment by inyutin-maxim** [comment]
Ошибку я обнаружил, вот только пока нет времени поправить ее. Ошибка заключается в том что float передает в запрос в качестве разделителя "," а нужно передавать "."

**Comment by inyutin-maxim** [comment]
@AlexanderPogorelov, @EarsKilla В текущей версии для данного метода исправлено, для других возможных методов будет исправлено в следующих релизах
