### ISSUE TITLE
api для работы с сообществами

### ISSUE THREAD

**Issue by AndreykaMrPvP** [vknet/vk#351]
Есть, или будет ли, api для работы с сообществами?

Я имею в виду получение токена сообщества и использования его далее в программе (так-же, как и токен пользователя).

Ссылки на "сырой" vkapi:
https://vk.com/dev/implicit_flow_group // авторизация
https://vk.com/dev/groups // методы

Если то, о чём я написал - уже имеется в VkNET, то прошу ответить примерами использования и авторизации.

**Comment by EarsKilla** [comment]
собсно костылями получаем токен из первой ссылки (семпла нет, т.к. небыло необходимости в таком токене), дальше в vkNet суём токен и всё работает. На сколько я знаю, методы эти там есть

**Comment by AndreykaMrPvP** [comment]
Я и пишу о том, что методов нет.

**Comment by inyutin-maxim** [comment]
А вы хорошо смотрели перегрузки метода Authorize?

**Comment by AndreykaMrPvP** [comment]
AppID, лог, пасс и права. Больше ничего не вижу

**Comment by inyutin-maxim** [comment]
@AndreykaMrPvP https://github.com/vknet/vk/blob/master/VkNet.UWP/VkApi.cs#L375

**Comment by CaCTuCaTu4ECKuu** [comment]
Получите ключ доступа пользователя (для работы с клиента или для работы с сервера) с правами scope=groups и сделайте запрос к методу groups.get с параметром filter=admin, чтобы получить список идентификаторов администрируемых сообществ. 
Тобишь работа с сообществами отдельно не вынесена, для получения и отправки сообщений от имени группы используются методы категории Message (в крайнем случае должны) и для работы с группой методы Group.
Но это не точно, точно то что авторизация происходит через Authorize

**Comment by AndreykaMrPvP** [comment]
Завтра днём посмотрю и отпишусь о результатах. Спасибо

**Comment by MMaschine** [comment]
> собсно костылями получаем токен из первой ссылки

А можно пример такого костыля?

**Comment by EarsKilla** [comment]
@MMaschine я же написал, что у меня примера нет.

Можно взять авторизацию как сейчас она есть для пользовательских страниц, добавить метод для авторизации от группы основываясь на той авторизации
