### ISSUE TITLE
Некорректная работа методов Audio.Get и Friends.GetAvailableForCall 

### ISSUE THREAD

**Issue by Mracobes9** [vknet/vk#352]
Здравствуйте. Недавно начал пользоваться данной библиотекой и столкнулся с рядом проблем.
1) Метод Audio.Get возвращает не все аудиозаписи
2)Friends.GetAvailableForCall  возвращает пустой список
Эти проблемы возникали не только у меня. 
- Пример кода для воспроизведения проблемы:
```csharp
//запрос списка музыки
  var Music = vk.Audio.Get(UserId);
//запрос списка id друзей
var getAvailableForCall = _api.Friends.GetAvailableForCall(null,null);
```

**Comment by inyutin-maxim** [comment]
Насчет метода audio. Get не все записи могут возвращаться за счет того что некоторые аудиозаписи заблокированы.

Насчет Friends.GetAvailableForCall сложно сказать, нужно смотреть причину

**Comment by Mracobes9** [comment]
Я проверял на не заблокированных записях.

**Comment by inyutin-maxim** [comment]
Ну тогда это больше вопрос к вк, я ж думаю вы принимаете во Внимание что за раз может быть возвращено лимитированное количество данных

**Comment by Soniclev** [comment]
@Mracobes9 за один вызов audio.get можно получить максимум 5000 аудиозаписей.

**Comment by Andriy1218** [comment]
С 16 декабря метод audio.get вообще не будет работать. https://vk.com/dev.php?method=audio_api

**Comment by Mracobes9** [comment]
Большое спасибо за обьяснение.Я думаю, что дело все таки у вк, поскольку даже у сторонних  проверенных плееров возникает такая проблема
