### ISSUE TITLE
Работа с Video

### ISSUE THREAD

**Issue by Mracobes9** [vknet/vk#353]
Здравствуйте. Меня интересует такой вопрос, как через данную библиотеку воспроизвести видео из вк ? Пробовал метод Video.Get()[i].Player, но встроенный webControl и awesomius не воспроизводят ссылаясь на не доступность Flash Player(который у меня установлен и обновлен). И можно ли получить прямую ссылку на видео ?

**Comment by Soniclev** [comment]
Я нашел только 2 способа:
1. [Использование доверенного приложения](https://vk.com/dev/auth_direct).
2. Использование сторонних сервисов для вытягивания ссылок

**Comment by Mracobes9** [comment]
Не могли бы вы посоветовать такие сервисы

**Comment by Soniclev** [comment]
@Mracobes9 Я знаю только savefrom.net, но там нет API.Ответ они вроде стараются зашифровать ответ, я точно не знаю, так как в JavaScript не разбираюсь. Можно попробовать открывать видео в мобильной версии и оттуда вытягивать.К примеру, вот часть, которая содержится в странице видео в мобильной версии.

`<source src="https://cs634105.vk.me/u18748068/videos/6001e8d0d0.720.mp4?extra=H-BkW3iUr7ZUxQFi5G5OAHuDaEjlMelRNk_MPMshNSBIS8K1akiOJFTk2y8m9ohzB9F0CzvSwvhC6PQ8kcmsrb1yR_LYJ7plDFBOAzNCRWKqk1lBaTg1qXOoKwhQoFPBcvGAKUxSE5Qt" type="video/mp4"></source>`

`<source src="https://cs9-1v4.vk.me/p12/a7aabf6aa70e.480.mp4?extra=mYhpCqBNGvgCg9Ji9I7dkPj3pytCMah_DwuUkUCnNe14Cq9OPYu5L1CLxBjAmfVZIsyXOUwPnT6brs2jbF3SVs-C-KYQuAjvCQFn48XaHA7sPzk_Qi-qM9ml8wZxzmGALBmjFFaf2jiZ" type="video/mp4"></source>`

`<source src="https://cs9-6v4.vk.me/p16/a7aabf6aa70e.360.mp4?extra=QIm14lK55s6s-nZGTsFOgOgOFe94el8Exhj679Xxp2xmNL5CuopNszfdkATjYUC0oZYBOBeubb4nkslrjzmmkWB6W1wOAQ5P_TgcAyjfa2ISljBfMyQ63LEcrcMh-UKQSlxA5jw8rmdF" type="video/mp4"></source>`

`<source src="https://cs9-5v4.vk.me/p7/a7aabf6aa70e.240.mp4?extra=E84o1PtC1vltfhngFyWgGR24oPoxoJ1MAvhv4IhnpgvRZrwRvZEPbeYuK8vaQxvP2R1fFJ_RNIL_z66EpjlfVli-b49UHK2BWK_t9be-piR0FetjjvfUMX4a5iNzkHcqJw7NKnP5ku7l" type="video/mp4"></source>`

**Comment by EarsKilla** [comment]
Произведи авторизацию без VkNet (симулируя доверенное приложение), возьми получившийся токен, засунь в VkNet и будет тебе счастье

**Comment by Soniclev** [comment]
@Mracobes9 если Вы будете использовать доверенное приложение, не забудьте форкнуть эту библиотеку и добавить в класс Video поле files.

> Если в Вашем приложении используется прямая авторизация, возвращается дополнительное поле files, содержащее ссылку на файл с видео (если ролик размещен на сервере ВКонтакте) или ссылку на внешний ресурс (если ролик встроен с какого-либо видеохостинга).

**Comment by Mracobes9** [comment]
Спасибо всем за помощь. Решил проблему правда несколько иначе. Я подключил флэш плагин к awersomium и использовал  метод Video.Get()[i].Player
