### ISSUE TITLE
метод IsLiked

### ISSUE THREAD

**Issue by TravorNat784** [vknet/vk#356]
Привет, помогите разобраться как задействовать метод IsLiked.
Авторизация с помощью са приложения, другие используемые методы работают стабильно.

Пример из документации vk.net
var isLiked = _api.Likes.IsLiked(type: "type", itemId: 0);
После редактирования type и itemid выдает ошибку "Отсутствует аргумент, соответствующий требуемому формальному параметру "copied" ".

Судя по документации в вк copied возвращает значение и самому заполнять его не следует, в чем моя ошибка ?

**Comment by Soniclev** [comment]
Там ошибка в примере. Нужно ввести параметр copied.Пример:
```
bool isCopied = false;
bool isLiked = api.Likes.IsLiked(
    out isCopied,
    type: VkNet.Enums.SafetyEnums.LikeObjectType.Post,
    itemId: 859569,
    ownerId: -57128022);
```
