### ISSUE TITLE
Отправка капчи - Ошибка

### ISSUE THREAD

**Issue by ilidan753** [vknet/vk#359]
Здравствуйте. Как отправить решение капчи из метода Messages.Send? Принимаю ошибку через catch (VkNet.Exception.CaptchaNeededException cEx)
 {
string captchaUrl = cEx.Img.AbsoluteUri;
}

**Comment by ilidan753** [comment]
![image](https://cloud.githubusercontent.com/assets/18134475/21420687/ca7c8fbc-c87a-11e6-9860-c1a3249871ff.png)

Помучился. И пришёл к этому. Опять в ступоре. 
Ошибки: 
Ошибка	CS1503	Аргумент 5: не удается преобразовать из "long" в "VkNet.Model.Attachments.MediaAttachment".

Ошибка	CS1503	Аргумент 6: не удается преобразовать из "string" в "System.Collections.Generic.IEnumerable<long>".

**Comment by andrshevch** [comment]
используй MessagesSendParams

**Comment by inyutin-maxim** [comment]
@ilidan753 Вам нужно в блоке catch вызвать метод Messages.Send с параметрами капчи и все должно сработать

**Comment by inyutin-maxim** [comment]
@ilidan753 У вас получилось обработать исключение?
