### ISSUE TITLE
Проблема при вызове Audio.Get

### ISSUE THREAD

**Issue by Radzhab** [vknet/vk#361]
Пытаюсь получить список аудиозаписей.
 var audios = vk.Audio.Get(1);

Выдает следующее 
![image](https://cloud.githubusercontent.com/assets/2556411/21581248/c54a3c34-d03a-11e6-950e-a02f60815ada.png)

**Comment by CaCTuCaTu4ECKuu** [comment]
ВК закрыло публичный API для аудиозаписей в декабре 2016 года
