### ISSUE TITLE
Subscription.Type содержит null для профилей пользователей

### ISSUE THREAD

**Issue by interpol-kun** [vknet/vk#362]
Пусть v -- пользователь. Тогда, если у пользователя есть хотя бы один профиль в подписках, полученных запросом, тип этой подписки будет null вместо profile. 

var subs = vk.Users.GetSubscriptions(v.Id, 200, 0, null, true);
foreach(var v in subs){
    Console.WriteLine(v.Type);
}

Для сообществ будет типичное page, для профилей -- null. 
Сообщите, когда пофиксите.

**Comment by inyutin-maxim** [comment]
@InterpolKun Спасибо по возможности проверим и исправим

**Comment by inyutin-maxim** [comment]
@interpol-kun Проблема исправлена, соберите из github

мой рабочий пример:
``` csharp
private static void Main()
{
	Api.Authorize(auth);
	Console.WriteLine("done");
	var res = Api.Users.GetSubscriptions(Api.UserId.Value, 200, 0, null, true);
	Console.WriteLine(string.Join(Environment.NewLine, res.Select(x => x.Type.ToString())));
	Console.ReadLine();
}
```
