### ISSUE TITLE
The type 'market' of attachment is not defined

### ISSUE THREAD

**Issue by gerandkey** [vknet/vk#364]
При попытке взять записи сообщества со стены происходит эксепшн InvalidParameter.
Метод апи Wall.Get(new WallGetParams).
Проблема в том, что к некоторым записям прикреплены "Товары" в аттачментах, поэтому происходит исключение и не вытягиваются записи.

An unhandled exception of type 'VkNet.Exception.InvalidParameterException' occurred in VkNet.dll

Additional information: The type 'market' of attachment is not defined.

**Comment by inyutin-maxim** [comment]
@gerandkey Закрываю как дубликат. #367
