### ISSUE TITLE
Ошибка при использовании Wall.Get  The type 'market' of attachment is not defined.

### ISSUE THREAD

**Issue by igorlevashov** [vknet/vk#367]
Пытаюсь получить список постов в группе. Возникает ошибка при использовании Wall.Get. 
Ошибка: **The type 'market' of attachment is not defined.**

Заметил, что если в ленте постов есть пост Товары, т.е. о продаже какие либо товаров в группе, то позникает данная ошибка.

```
        var list = vk.Wall.Get(new WallGetParams
                    {
                        OwnerId = -878460,
                        Count = 100,
                        Extended = true
                    });

```

**Comment by gerandkey** [comment]
Завел такой баг 5 дней назад. Пока тишина
https://github.com/vknet/vk/issues/364

**Comment by inyutin-maxim** [comment]
@igorlevashov , @gerandkey Спасибо, проверим по возможности и исправим проблему

**Comment by inyutin-maxim** [comment]
@Soniclev Спасибо за исправление
