### ISSUE TITLE
Не работает сортировка комментариев в обсуждениях(boards).

### ISSUE THREAD

**Issue by igorlevashov** [vknet/vk#368]
Не работает сортировка комментариев в обсуждениях(boards). 

   var list = vk.Board.GetComments(new BoardGetCommentsParams
                        {
                            GroupId = 18130368,
                            TopicId = 34301382,
                            Count = 100,              
                            **Sort = SortOrderBy.Desc**
                        });

**Comment by inyutin-maxim** [comment]
@igorlevashov Спасибо, по возможности проверим

**Comment by inyutin-maxim** [comment]
@igorlevashov Исправлено, будет доступно в следующей версии.

Можете собрать из Github

**Comment by igorlevashov** [comment]
Ура, спасибо!
