### ISSUE TITLE
Как работает audio.get

### ISSUE THREAD

**Issue by 4FortyTwo2** [vknet/vk#370]
Не моу понять как работает audio.get, получаю странную штуку.

**Comment by inyutin-maxim** [comment]
@4FortyTwo2 Опишите странную штуку))

**Comment by inyutin-maxim** [comment]
@4FortyTwo2 А вообще есть подозрение что ваша странная штука связана с [этим](https://vk.com/dev/audio_api)

**Comment by CaCTuCaTu4ECKuu** [comment]
Я думаю часть методов audio нужно просто сделать private и релизнуть апдейт VkNet

**Comment by AlexByte** [comment]
Это ограничение можно обойти, так что считаю, что делать методы private не нужно.

**Comment by inyutin-maxim** [comment]
@AlexByte так поделитесь с публикой, а методы пока трогать не буду

**Comment by e2sembler** [comment]
@inyutin-maxim можно было замаскироваться под WP ид без проблем, но неделю назад накрыли лавку. Теперь нужен апп кей, который надо искать внутри самого приложения.
