### ISSUE TITLE
Добавление автоматизации обхода ошибки 17: Need Validation  в обработчик для needvalidationexception

### ISSUE THREAD

**Issue by e2sembler** [vknet/vk#374]
Собственно проблема в том, что при входе в VK c IP из другой страны вылезет ошибка с URL. На данный момент есть возможность только вручную обработать данную ошибку, используя webBrowser контрол. 
Нашел данный парсер https://github.com/Yashko/vk-validation-node на JS.

**Comment by dvygolov** [comment]
Добавляем в файл Browser.cs следующий код и радуемся жизни. Ну ещё в IBrowser.cs определение метода.
`       public VkAuthorization Validate(string validateUrl, string phoneNumber)
        {
            var validateUrlResult = WebCall.MakeCall(validateUrl, _webProxy);
            var codeForm = WebForm.From(validateUrlResult)
		        .WithField("code")
		        .FilledWith(phoneNumber.Substring(1,8));
            var codeFormPostResult = WebCall.Post(codeForm, _webProxy);

	        return EndAuthorize(codeFormPostResult, _webProxy);
        }`

Ах, да. Ещё в VkApi.cs это всё пробрасываем следующим образом:
`public void Validate(string validateUrl, string phoneNumber)
	    {
	        StopTimer();

			LastInvokeTime = DateTimeOffset.Now;
			var authorization = Browser.Validate(validateUrl,phoneNumber);
			if (!authorization.IsAuthorized)
			{
				throw new NeedValidationException("Не удалось автоматически пройти валидацию!",validateUrl);
			}
			var expireTime = (Convert.ToInt32(authorization.ExpiresIn) - 10) * 1000;
			SetTimer(expireTime);
			AccessToken = authorization.AccessToken;
	    }`

**Comment by inyutin-maxim** [comment]
@dvygolov Можете сделать пулл реквест)

**Comment by dvygolov** [comment]
@inyutin-maxim Сделано.
