### ISSUE TITLE
caption в Photo.SaveWallPhoto

### ISSUE THREAD

**Issue by rassvet85** [vknet/vk#375]
Добрый день! В апи контакта 5.62 появилась возможность вместе с загрузкой фото Photo.SaveWallPhoto добавлять описание к нему через параметр caption. Можете реализовать эту возможность в вашей библиотеке? 

Спасибо огромное за вашу работу!

**Comment by inyutin-maxim** [comment]
@rassvet85 Доброго времени суток, на данный момент нет свободного времени но вы можете помочь проекту, добавив поле самостоятельно и сделав пулл реквест

**Comment by rassvet85** [comment]
Ох, я совсем аматор на гитхабе. По идее нужно сделать изменения в эту строку 

+		public ReadOnlyCollection<Photo> SaveWallPhoto(string response, ulong? userId = null, ulong? groupId = null, string caption)
 		{
 			var responseJson = JObject.Parse(response);
 			var server = responseJson["server"].ToString();
@@ -250,6 +261,7 @@ public VkCollection<Photo> Get(PhotoGetParams @params, bool skipAuthorization =
 				{ "user_id", userId },
 				{ "group_id", groupId },
 				{ "photo", photo },
+				{ "caption", caption },
 				{ "server", server },
 				{ "hash", hash }
 			};

**Comment by inyutin-maxim** [comment]
@rassvet85 в класс PhotoGetParams нужно добавить соответствующее поле и в метод ToVkParameters дописать преобразование

**Comment by rassvet85** [comment]
В документации контакта https://vk.com/dev/photos.get почему то нет параметра "caption". Хотя в https://vk.com/dev/photos.saveWallPhoto этот параметр присутствует....

**Comment by Soniclev** [comment]
@rassvet85 если вы про "caption" как параметр метода, то он не нужен, потому что вы запрашиваете фотографию и вк возвращает информацию о ней (ссылки на изображения, количество лайков и отметок, включая текст описания изображения и т.д.).Если вы про "caption" как поле модели фотографии, то это поле "text"

**Comment by inyutin-maxim** [comment]
(#381) Исправлен метод SaveWallPhoto. string? –> string.
