### ISSUE TITLE
Авторизация через asp.net

### ISSUE THREAD

**Issue by Bezpro** [vknet/vk#376]
К сожалению не получается авторизоваться 
Выдает ошибку
The remote server returned an error: (401) Unauthorized.
Можно ли вообще авторизовываться с сервера используя эту библиотеку?

**Comment by e2sembler** [comment]
вы забыли добавить AppID в параметр логина. 
				api.Authorize(new ApiAuthParams
				{
					ApplicationId = Settings.Default.AppID,
					Login = login,
					Password = pass,
					Settings = VkNet.Enums.Filters.Settings.All
				});

**Comment by inyutin-maxim** [comment]
@Bezpro Доброго времени суток, ваша проблема решена?

**Comment by inyutin-maxim** [comment]
Считаю проблему решеной
