### ISSUE TITLE
Асинхронные методы

### ISSUE THREAD

**Issue by raphaelgolubev** [vknet/vk#378]
```csharp
        async void MyMethod() //какой-то мой метод
        {
            bool ArrayIsFull = false;
            VkNet.Model.User FromMessage;

            var NewDialogs = await vk.Messages.GetDialogs(new MessagesDialogsGetParams
            {
                Count = 200,
                Offset = 0,
                PreviewLength = 25,
                Unread = false
            }); //попытка вызова метода асинхронно
    ...
}
```

Как вызвать метод асинхронно?
В коде выше появляется исключение:
'MessagesGetObject' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'MessagesGetObject' could be found (are you missing a using directive or an assembly reference?)
Пробовал через thread, но в методе присутствует обращение к элементам управление из другого потока и приходится описывать обходные пути, что не есть хорошо. Все-таки, await-async выглядит гораздо более проще.

**Comment by CaCTuCaTu4ECKuu** [comment]
Откуда этот код? Я не помню такого и не нашёл его в MessageCategory

**Comment by raphaelgolubev** [comment]
> Откуда этот код? Я не помню такого и не нашёл его в MessageCategory

Это мой код из моего проекта

**Comment by CaCTuCaTu4ECKuu** [comment]
Если ничего не изменилось, то VkNet все еще не поддерживает асинхронные вызовы напрямую (более того, особого смысла в них нет т.к. у VK есть ограничение на кол-во запросов в секунду)
Но для реализации асинхронности для освобождения UI потока достаточно обернуть код.
var newDialogs = await Task.Run(() => { ваш код });

**Comment by raphaelgolubev** [comment]
> var newDialogs = await Task.Run(() => { ваш код });

Спасибо, сработало!
