### ISSUE TITLE
Users.GetSubscriptions некорректная работа в VS 2015

### ISSUE THREAD

**Issue by interpol-kun** [vknet/vk#382]
VS:
    Microsoft Visual Studio Community 2015
    Version 14.0.25431.01 Update 3
    Microsoft .NET Framework
    Version 4.6.01038

Xamarin:
    Xamarin Studio Community
    Version 6.1.4 (build 1)
    Microsoft .Net Framework: 4.6

Тестировались 2 одинаковые программы. Обе собирались в Xamarin Studio и в VS 2015 с Target Framework 4.6 с помощью MS Build.

Возьмем из любого заданного сообщества сколько угодно пользователей. К примеру, просмотрим подписки самого первого пользователя и для каждой подписки выведем её тип. При сборке в Xamarin Studio выдаются корректные значения page, group etc. (кроме ранее описанного мною бага в  #362 . При сборке в VS 2015 поле Type принимает значение null.

```csharp
var members = vk.Groups.GetMembers(parameters, true);
var subs = vk.Users.GetSubscriptions(members[0].Id, 200, 0, null, true);
foreach (var v in subs)
{
	Console.WriteLine(v.Type);
}
```

**Comment by inyutin-maxim** [comment]
@interpol-kun На данный момент проблема исправлена, соберите проект из github
