### ISSUE TITLE
Десериализация списка фото, все значения - null

### ISSUE THREAD

**Issue by AlexKveeN** [vknet/vk#383]
при попытке десериализации (Newtonsoft.Json) из текстового файла в список 
```csharp
  string[] photoBase = File.ReadAllLines(@"Files/photosBase.json");
  List<Photo> photos = JsonConvert.DeserializeObject<List<Photo>>(photoBase[0]);
```
Приходит список (22k+) фотографий, сколько их и должно быть. 
Но проблема что абсолютно все значения в каждом фото равняются null

Есть ли какие то варианты это исправить?

**Comment by inyutin-maxim** [comment]
@AlexKveeN не понятно какие данные сериализуются, нужен пример, без этого вам сложно будет помочь

**Comment by AlexKveeN** [comment]
@inyutin-maxim    
Идёт работа с статическим списком 
public static List<Photo> photo { get; set; }

Сереализация
```csharp
            string json = JsonConvert.SerializeObject(photo);
            File.WriteAllText(@"Files/photosBase.json", json);
```

Десереализация
```csharp
            string[] usersbase = File.ReadAllLines(@"Files/photosBase.json");
            photo = JsonConvert.DeserializeObject<List<Photo>>(usersbase[0]);
```

**Comment by inyutin-maxim** [comment]
@AlexKveeN  Приложите кусок json из файла

**Comment by AlexKveeN** [comment]
@inyutin-maxim Немного подождите, попытаюсь исправить, раньше всё нормально сереализовалось, а сейчас переписал код, и при сереализации переменная json получает значение [{},{},{}]

**Comment by AlexKveeN** [comment]
@inyutin-maxim Кстати, нашёл старый файл, и открыл его.
Наблюдаю следующую картину. Читает с файла правильно, но при десереализации что-то идёт не так и весь список приходит пустой. 
![image](https://cloud.githubusercontent.com/assets/20554989/22796764/49c94d14-ef04-11e6-820a-6ed5f02e6b91.png)
![image](https://cloud.githubusercontent.com/assets/20554989/22796848/b39027fe-ef04-11e6-8f60-01e691cc252b.png)

**Comment by inyutin-maxim** [comment]
@AlexKveeN  Что то мне кажется что ваш объект Json просто сформирован неправильно посмотрите из какого парсится у нас ([Ссылка](https://github.com/vknet/vk/blob/master/VkNet.UWP/Model/Attachments/Photo.cs#L174))

**Comment by AlexKveeN** [comment]
@inyutin-maxim Тогда вопрос, какие параметры обязательны для отправки фото (из беседы в лс) ?
Например для отправки документов я использовал OwnerId и Id

**Comment by inyutin-maxim** [comment]
@AlexKveeN  [vk](https://vk.com/inyutin_maxim) , [телеграм](
https://telegram.me/inyutin_maxim) напишите мне завтра

**Comment by CaCTuCaTu4ECKuu** [comment]
Мне тоже кажется что вы где-то не туда забрели. Я не понимаю что вы сериализуете и десериализуете. Сама суть в том, чтобы передать полученный объект в другое место без потери его свойств, а у вас все происходит в пределах одной программы, вы не передаете объекты другой программе или в другое место. Возможно вам просто нужно запомнить нужные вам строки из полученных данных, а потом использовать их при отправке?

**Comment by inyutin-maxim** [comment]
Проблема напрямую с библиотекой не связана, предлагаю решить ее и обсудить лично со мной ([vk](https://vk.com/inyutin_maxim) , [телеграм](
https://telegram.me/inyutin_maxim))
