### ISSUE TITLE
Медленная загрузка данных

### ISSUE THREAD

**Issue by raphaelgolubev** [vknet/vk#384]
При вызове методов getDialogs и getHistory пользователю приходится ждать полной загрузки более минуты. Собственно вопрос в том, как кэшировать сообщения и диалоги, то есть загрузить основную массу один раз и все, да так, чтобы никто не смог подобраться собственно к самим диалогам и к историям переписки? Как наиболее корректно реализовать это в WinForm приложении?

**Comment by Soniclev** [comment]
Я думаю, что данные нужно шифровать, а ключ хранить с помощью [переменных вк](https://vk.com/dev/storage)

**Comment by CaCTuCaTu4ECKuu** [comment]
Проблема не связана непосредственно с библиотекой, поэтому я её закрываю, но насчет того как хранить скажу. 
Во первых вы можете хранить их в памяти, периодически выкидывая лишнее и оставляя только новые, если вас волнует вопрос безопасности то скажу так. Кто захочет - выковыряет нужные данные из памяти и отыщет в исходниках ключ шифрования. В общем безопасность самого приложения как такового это вообще отдельный вопрос.
Или второй вариант который и советую использовать - SQLite.
Вы можете под каждого пользователя создавать свою мини базу и шифровать ее хешем логина пароля от самого ВК, там можно хранить не только сообщения, но и хешировать превьюшки или даже полные изображения, аудиозаписи и прочее, в общем все, к чему может внезапно попытаться получить доступ пользователь.
При запросе какого-то ресурса в своем коде вы сначала должны проверить локальное хранилище (SQLite базу) и в случае отсутствия там данных уже получаете ресурс, сохраняете локально и выводите пользователю.
