### ISSUE TITLE
Vknet 1.26 Auth params w/ proxy is broken 

### ISSUE THREAD

**Issue by e2sembler** [vknet/vk#385]
System.UriFormatException: "Invalid URI: The format of the URI could not be determined."

Выходит при использование данного кода 
api.Authorize(new ApiAuthParams { Login = login, Password =pass, ApplicationId = Settings.Default.AppID, Settings = VkNet.Enums.Filters.Settings.All, Host=s[0], Port=Convert.ToInt32(s[1]) }); 
Вызывается из-за использования прокси

**Comment by inyutin-maxim** [comment]
@e2sembler У меня нигде нет прокси сервера, чтобы тестировать, будем рады исправлению

**Comment by inyutin-maxim** [comment]
@e2sembler Исправлено, будет добавлено в следующем релизе
