### ISSUE TITLE
При отправке сообщений ошибка: Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.

### ISSUE THREAD

**Issue by AlexKveeN** [vknet/vk#386]
При отправке сообщения у которого кол-во немного превышает 1000 символов, выходит данная ошибка
Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.
при повторных попытках отправки выдает уже новую ошибку =>

Удаленный сервер возвратил ошибку: (414) Request-URI Too Long.

 В exception Stack.Trace
   в VkNet.Utils.WebCall.GetResponse()
   в VkNet.Utils.WebCall.MakeRequest(IWebProxy webProxy)
   в VkNet.Utils.WebCall.PostCall(String url, IEnumerable`1 parameters, IWebProxy webProxy)
   в VkNet.Utils.Browser.GetJson(String methodUrl, IEnumerable`1 parameters)
   в VkNet.VkApi.<>c__DisplayClass148_0.<Invoke>b__0()
   в VkNet.VkApi.Invoke(String methodName, IDictionary`2 parameters, Boolean skipAuthorization)
   в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization)
   в VkNet.Categories.MessagesCategory.Send(MessagesSendParams params)

**Comment by inyutin-maxim** [comment]
@AlexKveeN  Боюсь это внутренняя ошибка vk

**Comment by DW365** [comment]
Если работать через post, то такой ошибки нет. А ваша библиотека, судя по всему, работает через get

**Comment by DW365** [comment]
Проснифал запросы - ошибка возникает из-за того, что идет post запрос, однако парамтеры дополнительно в url передаются

**Comment by DW365** [comment]
http://joxi.ru/Drl9anqFNWPQmP

**Comment by inyutin-maxim** [comment]
@AlexKveeN , @DW365 Исправлено, соберите проект из github
