### ISSUE TITLE
При запросе market One of the parameters specified was missing or invalid: only groups supported

### ISSUE THREAD

**Issue by Rammun** [vknet/vk#387]
- Пример кода для воспроизведения проблемы:
```csharp
  _vkApi = new VkApi();
  this.Autorize();
  var markets = _vkApi.Markets.Search(new MarketSearchParams
            {
                OwnerId = id,    // 65772109
                Query = query,  // Тест
                Count = MARKET_MAX_COUNT
            });
```
- Возвращает:
"One of the parameters specified was missing or invalid: only groups supported"

Помогите, в чем может быть причина? По документации, только один параметр обязательный.
Может ли быть эта ошибка, если у группы нет маркета?

**Comment by Soniclev** [comment]
Попробуйте `OwnerId = -id`

**Comment by Rammun** [comment]
Да, спс, с этим разобрался, когда в исходники залез, там есть коммент на это. Но теперь говорит, что не разрешено. При авторизации указываю все разрешения. Какие еще должны быть разрешения?

**Comment by Soniclev** [comment]
@Rammun я пробовал вызывать этот метод, но он тоже возвращал access denied. У этой группы закрыты товары или они доступны для подписчиков

**Comment by AlexByte** [comment]
> там есть коммент на это
Где про это написано?

**Comment by Rammun** [comment]
В файле MarketCategory, стр. 95.
`<param name="ownerId">Идентификатор владельца товаров. Обратите внимание, идентификатор сообщества в параметре owner_id необходимо указывать со знаком "-" — например, owner_id=-1 соответствует идентификатору сообщества ВКонтакте API (club1)  целое число, обязательный параметр (целое число, обязательный параметр).</param>`
Интелесенс это не показывает.
Об этом собственно и в доках vk написано.

**Comment by inyutin-maxim** [comment]
@Rammun , @Soniclev , @AlexByte Считаю проблему решеной

@Rammun Готовы к предложениям по улучшению документации и библиотеки в целом, а так же с удовольствием ждем pull request'ы
