### ISSUE TITLE
SaveWallPhoto: Invalid Hash

### ISSUE THREAD

**Issue by YaNet-Production** [vknet/vk#388]
Кратко:

    var uploadServer = vk.Photo.GetWallUploadServer(133444576);// Получаем ссылку
    var responseFile = Encoding.UTF8.GetString(new System.Net.WebClient().UploadFile(uploadServer.UploadUrl, iname));//Загружаем
    var Saved = vk.Photo.SaveWallPhoto(responseFile);//Сохраняем
    //                   ^ Invalid hash exception

**Comment by Bezpro** [comment]
Та же ошибка 
`WebClient client = new WebClient();
                        Uri uri = new Uri(phoro[0].Sizes[phoro[0].Sizes.Count-1].Src.AbsoluteUri.ToString());
                        client.DownloadFileAsync(uri, "1.jpg");
                        Thread.Sleep(1000);
                        var uploadServer = api.Photo.GetWallUploadServer(ourid);
                         Загрузить фотографию.
                        var wc = new WebClient();
                        var responseImg = Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, @"1.jpg"));
                         Сохранить загруженную фотографию
                        var photos = api.Photo.SaveWallPhoto(responseImg, null, 1);`

**Comment by inyutin-maxim** [comment]
У меня все получилось без проблем, ниже код отправки в мою группу:
``` csharp
// Получить адрес сервера для загрузки.
var uploadServer = Api.Photo.GetWallUploadServer(103292418);
// Загрузить файл.
var wc = new WebClient();
var responseFile = Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, @"C:\Users\Raven\Pictures\test.jpg"));
// Сохранить загруженный файл
var photos = Api.Photo.SaveWallPhoto(responseFile,null, 103292418);

var messages = Api.Wall.Post(new WallPostParams
{
	Attachments = photos,
	Message = "test photo",
	OwnerId = -103292418

});

```

@YaNet-Production , @Bezpro Так как проблемы нет, ошибку закрываю
