### ISSUE TITLE
Уберите зависимость на HtmlAgilityPack

### ISSUE THREAD

**Issue by dvygolov** [vknet/vk#389]
Насколько я вижу, библиотека не используется, а лишняя зависимость подтягивается.

**Comment by Rammun** [comment]
Кстати нугет мне ее почему то автоматом не подтянул, пришлось ее руками ставить.

**Comment by inyutin-maxim** [comment]
@dvygolov, @Rammun Неиспользуемые зависимости убраны из проекта, после очередного релиза все должно быть впорядке
