### ISSUE TITLE
PostType у NewsFeed всегда null

### ISSUE THREAD

**Issue by dvygolov** [vknet/vk#390]
При десериализации из JSON значения поля post_type оно не преобразуется корректно в объект PostType, а всегда остаётся null. Связано это с тем, что у SafetyEnum на момент преобразования оказывается не заполненным словарь PossibleValues. Прилагаю скриншот.
![image](https://cloud.githubusercontent.com/assets/9249545/22853255/100749ba-f06b-11e6-9821-7fcf16f90048.png)

**Comment by inyutin-maxim** [comment]
@dvygolov Попробуйте собрать новую версию из github и отпишитесь решилась ли проблема, спасибо
