### ISSUE TITLE
Groups.Search не возвращает данные о группе Description и MembersCount 

### ISSUE THREAD

**Issue by Rammun** [vknet/vk#391]
![vk](https://cloud.githubusercontent.com/assets/12098829/22861204/0f4f8d98-f124-11e6-9af0-57ff3d242759.PNG)
- Пример кода для воспроизведения проблемы:
```csharp
 var groups = _vkApi.Groups.Search(new GroupsSearchParams
            {
                Query = query,   // Test
                Count = GROUP_MAX_COUNT,  // 1000
            });
```

**Comment by CaCTuCaTu4ECKuu** [comment]
Провозился в вашей проблемой, а оказалось надо было сначала на сайте глянуть документацию
https://vk.com/dev/groups.search
Метод Search не возвращает поля Description и MemberCount, смотрите нужный вам метод в документации к API
