### ISSUE TITLE
Ошибка отображения информации о заблокированных пользователях. 

### ISSUE THREAD

**Issue by e2sembler** [vknet/vk#392]
При использование Users.Get() на заблокированном пользователе значение IsDeactivated всегда равен false, а Deactivated и DeactivateReason равны null.

**Comment by dvygolov** [comment]
Думаю, что это одна и та же проблема с #289 
В том решении описан кривой, но рабочий workaround

**Comment by inyutin-maxim** [comment]
@e2sembler Добавил активатор в процессе вызова FromJson
Прошу проверить ушла ли проблема. Соберите проект из Github
