### ISSUE TITLE
AlbumId не получается задать параметр

### ISSUE THREAD

**Issue by ipbatman** [vknet/vk#393]
Хочу получить список фотографий со стены. Затыкаюсь на идентификаторе альбома. Тут какая то проблема с типами? Или я не могу так явно указать идентификатор (противоречит документации)?
Подскажите кто чем может?

var get_photo = vk.Photo.Get(new VkNet.Model.RequestParams.PhotoGetParams
 {
    OwnerId = -ХХХХХХХХХХ,
    AlbumId = "wall",
    Extended = true
});

**Comment by Soniclev** [comment]
Пока что можно использовать только id. Для системных альбомов есть неизменяемые id. 

Альбом | ID
------|---
profile | -6
wall | -7
saved | -15

**Comment by Soniclev** [comment]
@ipbatman Тогда нужно примерно так:
```
var get_photo = vk.Photo.Get(new VkNet.Model.RequestParams.PhotoGetParams
{
OwnerId = -ХХХХХХХХХХ,
AlbumId = PhotoAlbumType.Wall,
Extended = true
});
```

**Comment by ipbatman** [comment]
@Soniclev 
Вот так заработало, спасибо за наводку!

var get_photo = vk.Photo.Get(new VkNet.Model.RequestParams.PhotoGetParams
            {
                OwnerId = -ХХХХХХХХХХ,
                AlbumId = VkNet.Enums.SafetyEnums.PhotoAlbumType.Wall,
                Extended = true
            });

**Comment by inyutin-maxim** [comment]
Проблему считаю решенной, закрываю задачу
