### ISSUE TITLE
Как запостить запись с большим текстом?

### ISSUE THREAD

**Issue by Bezpro** [vknet/vk#396]
С помощью wall.post нельзя выкладывать длинные сообщения. Как это обойти?

**Comment by inyutin-maxim** [comment]
@Bezpro С нашей стороны все методы вызываются методом POST поэтому это не может быть ограничением нашей библиотеки, это ограничение самого vk. Поэтому не считаю это проблемой библиотеки

**Comment by AlexByte** [comment]
#386
