### ISSUE TITLE
Проблемы Users.Get?

### ISSUE THREAD

**Issue by Rammun** [vknet/vk#401]
Когда делаю запрос с одним id пользователя, получаю нужные мне счетчики (подписчиков). Когда делаю запрос с большим кол-вом id, поле counters равно null. Судя по исходникам, в обеих случаях выполняется один метод, поэтому сначала думал, что это задумка vk такая. Но в примерах запросов в доках vk, метод, с запросом из списка id, возвращает счетчик подписчиков.
![vkusers](https://cloud.githubusercontent.com/assets/12098829/23145945/75fb38e2-f7e3-11e6-990d-20821a812c4e.PNG)

- Пример кода для воспроизведения проблемы:
```csharp
  var users = _vkApi.Users.Get(new long[] {348298852, 380272040, 403111540}, ProfileFields.All);
```

![vkuser2](https://cloud.githubusercontent.com/assets/12098829/23146032/37a04b7c-f7e4-11e6-8e8c-76c8a7868c76.PNG)

**Comment by Soniclev** [comment]
Это задумка ВК ![-2](https://cloud.githubusercontent.com/assets/12499740/23316343/b5018a54-fad2-11e6-95a2-b0528684acf3.jpg)
А количество подписчиков для нескольких пользователей смотрите в поле [FollowersCount](https://github.com/vknet/vk/blob/master/VkNet.UWP/Model/User.cs#L427)

**Comment by Rammun** [comment]
Я это все уже смотрел.
![vkusers2](https://cloud.githubusercontent.com/assets/12098829/23334169/8c8ad9ee-fbaa-11e6-9696-4ade634677e5.PNG)
Можно посмотреть, что на странице есть подписчики.

**Comment by CaCTuCaTu4ECKuu** [comment]
Вышел фикс, обновитесь и проверьте

**Comment by inyutin-maxim** [comment]
@Rammun Пожалуйста отпишитесь решилась ли ваша проблема

**Comment by inyutin-maxim** [comment]
@Rammun  Переписал Класс MultivaluedFilter теперь ваш пример отрабатывает корректно
``` csharp
public static void Main(string[] args)
{
	var api = new VkApi();
	api.Authorize(auth);

	var users = api.Users.Get(new long[] {api.UserId.Value, 348298852, 380272040, 403111540 }, ProfileFields.All);
	Console.WriteLine(string.Join(Environment.NewLine, users.Select(x => $@"{x.FirstName} {x.LastName} - Подписчиков: {x.FollowersCount}")));
	Console.ReadLine();
}
```
