### ISSUE TITLE
Ошибка подключения через Proxy: UriFormatException

### ISSUE THREAD

**Issue by festelo** [vknet/vk#403]
Добрый день! Не получается авторизоваться через прокси.

```
ApiAuthParams par = new ApiAuthParams()
{
    Login = login,
    Password = password,
    ApplicationId = appid,
    Settings = VkNet.Enums.Filters.Settings.All,
    Host = "127.0.0.1",
    Port = 8080,
};
await vk.AuthorizeAsync(par);
```

Выдается исключение System.UriFormatException

**Comment by festelo** [comment]
https://github.com/vknet/vk/issues/385

**Comment by festelo** [comment]
v1.27.0: - Исправлена ошибка WebProxy

Ошибка осталась.

**Comment by Bizunow** [comment]
Тоже столкнулся с этой ошибкой. Кто нибудь может подсказать как ее обойти?

**Comment by inyutin-maxim** [comment]
@festelo, @Bizunow 
А вы логин и пароль для самого прокси точно отдаете?

**Comment by Bizunow** [comment]
@inyutin-maxim 
Конечно:
```
Host = "185.155.235.67",
Port = 4040,
ProxyLogin = "usr5241650",
ProxyPassword = "ps52411487787650"
```

**Comment by Bizunow** [comment]
@inyutin-maxim, если нет прокси, я могу предоставить для теста.

**Comment by inyutin-maxim** [comment]
@Bizunow Было бы здорово, мои контакты ( [VK](https://vk.com/inyutin_maxim), [telegram](
https://telegram.me/inyutin_maxim))

**Comment by festelo** [comment]
Загрузил исходники с гитхаба, собрал и теперь всё работает,

Сейчас использую это (последний коммит, на котором нет "failure the travis ci build failed") :
https://github.com/vknet/vk/tree/cd8cfe8344fa8e43d1fcb981aa15f74a0fc41095
В ней прокси работает исправно (правда там нужно было в одном методе string отредактировать, но, судя по последним коммитам, вы это уже сделали).

**Comment by inyutin-maxim** [comment]
@festelo 
> В ней прокси работает исправно (правда там нужно было в одном методе string отредактировать, но, судя по последним коммитам, вы это уже сделали).

Прокомментируйте пожалуйста, это поможет исправить проблемму

**Comment by inyutin-maxim** [comment]
@Bizunow Пожалуйста попробуйте собрать библиотеку из github и попробуйте, у меня все отработало корректно на предоставленном прокси. Жду от вас комментариев. Спасибо

**Comment by myAvatar** [comment]
Подскажите все таки  работает авторизация через прокси или нет? у меня так и не заработало из поста ниче не понял
