### ISSUE TITLE
Отправка сообщения из сообщества

### ISSUE THREAD

**Issue by Bezpro** [vknet/vk#405]
Как реализуется чтение и отправка сообщений из сообществ?

**Comment by CaCTuCaTu4ECKuu** [comment]
Перед тем как писать прочтите описание и изучите библиотеку. Люди здесь о
проблемах сообщают обычно, не нужно захламлять вопросам типа "как
пользоваться?" - все подробно описано, к каждому методу и классу
разьяснение, названия методов говорящие и в документации ВК все описано.
Также проверяйте закрытые проблемы, возможно вашу уже решили или давали
ответ на вопрос.
Если я не ошибаюсь то message.send может это делать

01 марта 2017 г. 8:11 пользователь "Bezpro" <notifications@github.com>
написал:

**Comment by CaCTuCaTu4ECKuu** [comment]
https://vk.com/dev/messages.send

**Comment by Bezpro** [comment]
Все равно не могу понять, как это всё делается через вашу библиотеку. Хотелось бы увидеть пример авторизации и отправки сообщения через сообщество.

**Comment by Bezpro** [comment]
Спасибо. Разобрался, нашёл перегрузку public void Authorize(string accessToken, long? userId = null, int expireTime = 0)
