### ISSUE TITLE
Проблемы с версией 1.27.0

### ISSUE THREAD

**Issue by raphaelgolubev** [vknet/vk#406]
```csharp
void Auth(string _Login, string Pass)
        {
            try
            {
                vk.Authorize(new ApiAuthParams
                {
                    Login = _Login,
                    Password = Pass,
                    Settings = scope,
                    ApplicationId = appID
                });
            }
            catch (VkNet.Exception.VkApiAuthorizationException ex)
            {
                MessageBox.Show("Неверный логин или пароль ("+ex.Email+") ("+ex.Password+")");
            }
            if (vk.IsAuthorized)
            {
                MessageBox.Show("Is authorized");
            }
        }
```

В новой версии библиотеки при попытке авторизации выползает исключение о неверных введенных данных, однако в версии 1.25.0 при тех же введенных данных авторизация выполняется успешно.

**Comment by inyutin-maxim** [comment]
@raphaelgolubev Уточните какую сборку вы используете? .NET4.0 или NETStandard?

**Comment by raphaelgolubev** [comment]
@inyutin-maxim .NET4.0

**Comment by inyutin-maxim** [comment]
@raphaelgolubev есть подозрение что это вас вк рубит, у меня тоже такая ошибка проявлялась, вне зависимости от сборки и версии библиотеки

**Comment by inyutin-maxim** [comment]
@raphaelgolubev Проявляется ли у вас ошибка до сих пор? попробуйте так же собрать версию из github

**Comment by inyutin-maxim** [comment]
@raphaelgolubev Версия библиотеки в nuget обновилась, отпишитесь исправлена ли ваша проблема?

**Comment by raphaelgolubev** [comment]
@inyutin-maxim нет, авторизация все так же не выполняется.

**Comment by inyutin-maxim** [comment]
@raphaelgolubev [Рабочий пример](https://vk.com/doc32190123_445234609?hash=3b50c0d8d1402c0f25&dl=370a60672b8a45927b), ошибка не воспроизводится
