### ISSUE TITLE
System.NullReferenceException в Messages.GetDialogs, Messages.Get

### ISSUE THREAD

**Issue by azhidkov** [vknet/vk#41]
System.NullReferenceException при попытке получить данные от пользователя, у которого последнее (для GetDialogs) и какое-либо из получаемых (для Messages.Get) сообщение/ий содержит в себе изображение.

Original source: http://vk.codeplex.com/workitem/36

**Comment by CaCTuCaTu4ECKuu** [comment]
Исправлено в #68
