### ISSUE TITLE
UWP, ошибка: Error reading JObject from JsonReader 

### ISSUE THREAD

**Issue by raphaelgolubev** [vknet/vk#416]
В приложении существуют две страницы. Первая - страница авторизации, вторая - главная страница. После успешной авторизации вызывается метод с передачей объекта VkApi в качестве второго параметра:
```csharp
this.Frame.Navigate(typeof(MainPage), vk);
```
Далее я передаю этот параметр в переменную vk2:
```csharp
VkApi vk2 = new VkApi(); 
        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            if (e.Parameter is VkApi)
            {
                vk2 = e.Parameter as VkApi;
            }
            base.OnNavigatedTo(e);
        }
```
Затем пытаюсь получить список друзей:
```csharp
            var users = vk2.Friends.Get(new FriendsGetParams
            {
                UserId = vk2.UserId,
                Fields = ProfileFields.All,
            });
```
Непосредственно на вызове vk2.Friends.Get выскакивает исключение "Error reading JObject from JsonReader"

![22222](https://cloud.githubusercontent.com/assets/24896912/24310015/3cf9b19e-10df-11e7-9ede-eb5ed43e2283.jpg)

**Comment by inyutin-maxim** [comment]
@raphaelgolubev мне кажется вам нужно vk сделать синглтоном для начала

**Comment by raphaelgolubev** [comment]
@inyutin-maxim надеюсь, что я все правильно понял:
Страница авторизации AuthPage.xaml.cs
```csharp
        public class VKSingle
        {
            private static  VkApi instance;

            public static VkApi getInstance()
            {
                if (instance == null)
                    instance = new VkApi();
                return instance;
            }
        }
        VkApi vk = VKSingle.getInstance();
```
Страница MainPage.xaml.cs
```csharp
 VkApi vk = AuthPage.VKSingle.getInstance();
protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            if (e.Parameter is VkApi)
            {
                vk = e.Parameter as VkApi;
            }
            base.OnNavigatedTo(e);
        }
```

**Comment by inyutin-maxim** [comment]
@raphaelgolubev У вас получилось решить вашу проблему?
Если не получатся, то вот мои контакты:
1. [vk](https://vk.com/inyutin_maxim)
2. [Telegram](https://telegram.me/inyutin_maxim)

**Comment by Egoriy** [comment]
Нашли решение проблемы? Такая же ситуация возникла

**Comment by AlexByte** [comment]
Стек исключения приведите.

**Comment by inyutin-maxim** [comment]
@raphaelgolubev , @Egoriy [Рабочий пример](https://vk.com/doc32190123_445234609?hash=3b50c0d8d1402c0f25&dl=370a60672b8a45927b), ошибка не воспроизводится

**Comment by AlexByte** [comment]
@inyutin-maxim Файлы можно выкладывать прямо на Github.
[WpfApp1.zip](https://github.com/vknet/vk/files/976616/WpfApp1.zip)
