### ISSUE TITLE
Users.Get | Ошибка 414

### ISSUE THREAD

**Issue by razio** [vknet/vk#418]
![errvk](https://cloud.githubusercontent.com/assets/18007718/24366942/3bac9ad4-1334-11e7-8bad-e36a30143b24.png)

В общем, при попытке вызова Users.get с передачей туда 1000 айдишников вылетает такая ошибка. Странно, ведь раньше все работало, и вк так и не сменил это ограничение со своей стороны (по крайней мере так сказано в доках). Пробовал и 999 и 500 - одно и то же. Также пробовал запрашивать другие профайл филды - аналогично. Переустанавливал нугет пакет, конечно же.

**Comment by Soniclev** [comment]
@razio Попробуйте собрать библиотеку с GitHub.

**Comment by inyutin-maxim** [comment]
@razio У вас получилось собрать библиотеку и проверить?

**Comment by nshindarev** [comment]
Ребят, а ещё вот у Users.Career не возвращает поля никакие, это не реализовано ещё?

**Comment by inyutin-maxim** [comment]
@razio В nuget вышла новая версия попробуйте и отпишитесь по данной проблеме

**Comment by razio** [comment]
Да, спасибо, все прекрасно работает)
