### ISSUE TITLE
Messages.Send | System.Net.WebException; Удаленный сервер возвратил ошибку: (414) Request-URI Too Long

### ISSUE THREAD

**Issue by n0namer** [vknet/vk#420]
Использую последнюю версию из нугета.
При отправке сообщений с большим количеством текста вылетает ошибка из темы: (414) Request-URI Too Long.

В примере текст генерируется искусственно. На практике я пересылаю сообщениями тексты из постов и уже при длине string в 700-800 знаков получаю ошибку.

- Класс и метод в котором возникла проблема:
Messages.Send

- Пример кода для воспроизведения проблемы:
```csharp
var tempAnswer = new MessagesSendParams() 
{ UserId = UserId, // ID получателя
  RandomId = BitConverter.ToInt64(Guid.NewGuid().ToByteArray(), 8)
tempAnswer.Message = new string('A', 10000) };

var messageID = groupApi.Messages.Send(tempAnswer);

```

**Comment by inyutin-maxim** [comment]
@n0namer Какую версию библиотеки вы используете? актуальная 1.28

**Comment by n0namer** [comment]
Прошу прощения, стояла 1.27. В 1.28 всё ок.

**Comment by AlexByte** [comment]
#386
