### ISSUE TITLE
GroupsGetMembersParams.Filters

### ISSUE THREAD

**Issue by KopaiGora** [vknet/vk#425]
В методе Groups.GetMembers среди параметров есть Filters - Friends. Но этот самый "Friends" я не могу нигде откопать. Видимо, тип не тот.

**Comment by inyutin-maxim** [comment]
@KopaiGora В списке параметров для данного параметра указан неверный тип, известная проблема, по свободе поправим. Спасибо

**Comment by inyutin-maxim** [comment]
Исправлено, добавлено к следующему релизу

**Comment by KopaiGora** [comment]
Как скоро он будет?

**Comment by inyutin-maxim** [comment]
@KopaiGora В мае, я релизы выпускаю раз в месяц. Если вам очень срочно, то предлагаю собрать самому из github
