### ISSUE TITLE
Messages Send, chat_id не может быть больше 100000000

### ISSUE THREAD

**Issue by kot-mapku3** [vknet/vk#429]
- Класс и метод в котором возникла проблема:
Messages.Send
- Пример кода для воспроизведения проблемы:

```csharp
 vkApi.Messages.Send(185701257, false, textBoxMessage.Text);
```
Как мне отправить сообщение, если я не могу получить chat_id? 
Я пишу следующее: 
```csharp
var mess = vkApi.Messages.Get(new VkNet.Model.RequestParams.MessagesGetParams { });
```
Но как из этого получить id я не понимаю. 
Захожу через браузер вк, копирую id беседы. Естественно это не работает, как поправить это?
Узнать id беседы или диалога с конкретным человеком?

**Comment by inyutin-maxim** [comment]
Попробуйте так:
``` csharp
var mess = api.Messages.Get(new VkNet.Model.RequestParams.MessagesGetParams { });
mess.Messages[index].ChatId
```

**Comment by kot-mapku3** [comment]
А Messages по индексу что хранит?
Цель проста: взять все id всех бесед и написать сообщение в любую из них.

**Comment by kot-mapku3** [comment]
И можно сразу вопрос: почему ProfileFields.Uid возвращает странные цифры, а не действующий id пользователя?

**Comment by inyutin-maxim** [comment]
@kot-mapku3 не серьезные вопросы задаете, не хотите разбираться.
Messages - Коллекция личных сообщений, по индексу конкретное сообщение
Почему ProfileFields.Uid отдает странные цифры не могу сказать, читайте описание здесь: https://vk.com/dev/messages.get

**Comment by kot-mapku3** [comment]
Ну, вот смотрите:
Пишу Messages.Get и в параметрах как в документации {};
Он принимает, пишет что их больше 500к, но когда я прохожусь foreach по этим данным, то count равен 0 и ни одного сообщения нет.
