### ISSUE TITLE
Как работать с MessagesGetParams Filters?

### ISSUE THREAD

**Issue by kot-mapku3** [vknet/vk#431]
- Класс и метод в котором возникла проблема:
  GetMessages
- Пример кода для воспроизведения проблемы:

```csharp
  var messages = vk.Messages.Get(new MessagesGetParams { Count = 20, Filters = 1});
```
Как указать только непрочитанные сообщения? В классе метода и свойства нет, а int Filters не принимает.

**Comment by inyutin-maxim** [comment]
@kot-mapku3 Боюсь вам придется получить все сообщения и уже фильтровать в памяти по полю read_state [Документация метода](https://vk.com/dev/messages.get)
