### ISSUE TITLE
Поле MarkedAsAds класса Post не всегда true на рекламных постах.

### ISSUE THREAD

**Issue by n0namer** [vknet/vk#432]
Два рекламных поста
https://vk.com/gotovil?w=wall-140105161_70684
https://vk.com/gotovil?w=wall-140105161_69968

Получаю посты:
```
var wall = UserApi.Wall.GetById(new List<string>() { "-140105161_70684" });
var wall = UserApi.Wall.GetById(new List<string>() { "-140105161_69968" });
```

В первом случае MarkedAsAds  = false.
во втором всё ок и поле = true.
![image](https://cloud.githubusercontent.com/assets/26526650/25066423/a81182fe-222d-11e7-90c7-b4caf43be2b7.png)
![image](https://cloud.githubusercontent.com/assets/26526650/25066430/d55503d0-222d-11e7-8fc1-b1e3207bb62f.png)

**Comment by Soniclev** [comment]
API ВКонтакте почему-то возращает `marked_as_ads` равным нулю:
 ```json
"response": [{
"id": 70684,
"from_id": -140105161,
"owner_id": -140105161,
"date": 1492272010,
"marked_as_ads": 0,
```

**Comment by n0namer** [comment]
Понятно. Спасибо!
