### ISSUE TITLE
Не получается осилить longpool

### ISSUE THREAD

**Issue by Bezpro** [vknet/vk#433]
Так и не понял как работает longpool, может слишком туп, чтобы без чьей-то помощи разобраться. Делал всё как написано тут: https://github.com/vknet/vk/issues/365 Вроде всё сделал правильно, но вылазиет вот такой ексепшен. 
System.NotImplementedException

```
if (history != null)
            {
                Pts = history.NewPts;
                foreach (var m in history.Messages)
                    m.FromId = m.Type == VkNet.Enums.MessageType.Sended ? _account.UserId : m.UserId;
            }
            else
                throw new NotImplementedException(errorLog); <= отсюда 
```
Очень прошу показать пример или, если будет не затруднительно, кинуть простой проект с реализованным longpool.

**Comment by Bezpro** [comment]
UP! Неужели никто не может написать?

**Comment by CaCTuCaTu4ECKuu** [comment]
if history != null, как она может быть не null если вы еще ничего не
получили?

14 мая 2017 г. 1:45 PM пользователь "Bezpro" <notifications@github.com>
написал:

**Comment by dvygolov** [comment]
[Посмотрите вот тут!](https://ru.stackoverflow.com/questions/620342/vk-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F)
