### ISSUE TITLE
[Предложение] Выделить интерфейсы

### ISSUE THREAD

**Issue by bazarniy** [vknet/vk#434]
Из-за отсутствия интерфейсов объекты нельзя удобно замокать и для автотестирования приходится писать унылые обертки.

**Comment by bazarniy** [comment]
И ApiAuthParams хорошо бы сделать классом, чтобы не плодить в коде ==default(ApiAuthParams)

**Comment by inyutin-maxim** [comment]
@bazarniy Спасибо за предложение, рассмотрим, и при возможности внедрим как появится свободное время. Или вы можете сделать это сами и выслать pull request.

**Comment by inyutin-maxim** [comment]
@bazarniy  добавлено к следующему релизу. Либо можете собрать сами из GitHub.
спасибо за участие в жизни проекта. Прошу прощения что долго не получалось обработать пулл реквест
