### ISSUE TITLE
Не загружается количество просмотров поста

### ISSUE THREAD

**Issue by ilpoli** [vknet/vk#435]
Post.FromJson (1.28) - для загрузки количества просмотров используется view свойство вместо views.

**Comment by ilpoli** [comment]
PostView.FromJson - "count ", лишний пробел в конце.

**Comment by inyutin-maxim** [comment]
@ilpoli Пробел убрал, а вот насчет вашего первого вопроса, приведите пример метода в котором возникает проблема

**Comment by ilpoli** [comment]
@inyutin-maxim, спасибо.
Касательно "view":
* получить список постов Wall.Get
* свойство Views в любом посте будет null

**Comment by inyutin-maxim** [comment]
@ilpoli Добавлено к следующему релизу
