### ISSUE TITLE
PhotoCreateCommentParams и VideoCreateCommentParams attachments

### ISSUE THREAD

**Issue by Acuion** [vknet/vk#436]
В `MessagesSendParams`, `BoardCreateCommentParams`, `WallAddCommentParams` поле `Attachments` имеет тип `IEnumerable<MediaAttachment>`, в то время как в `PhotoCreateCommentParams` оно является `IEnumerable<Attachment>`, а в `VideoCreateCommentParams` и вовсе `IEnumerable<string>`.
Хотелось бы чтобы они все были одного типа - `IEnumerable<MediaAttachment>`, тк не вижу причин для подобного их обособления.

**Comment by inyutin-maxim** [comment]
@Acuion Скорее всего вы правы, и так и должно быть, но на данный момент нет свободного времени, вы можете сделать pull request с данными исправлениями

**Comment by inyutin-maxim** [comment]
@Acuion Добавлено к следующему релизу
