### ISSUE TITLE
Не считывает координаты с json

### ISSUE THREAD

**Issue by zetx16** [vknet/vk#437]
При чтении сообщения с местоположением объект Messgae.Geo.Coordinates всегда равен null, хотя в json координаты есть.

```csharp
var messgaes = vk.Messages.Get( new VkNet.Model.RequestParams.MessagesGetParams {
    TimeOffset = 0
} );

foreach ( var messgae in messgaes.Messages )
    if ( messgae.Geo != null )
        Console.WriteLine( messgae.Geo.Coordinates.Latitude ); //здесь исключение, т.к. Coordinates == null
```

Подебажил библиотеку, метод FromJson для класса Coordinates вообще не выполняется, для Place выполняется (обе свойства класса Geo).

Подебажил еще, проблема здесь https://github.com/vknet/vk/blob/master/VkNet.UWP/Utils/VkResponseToModelCastsGenerator.cs#L643, т.к. `_token` равен `{55.5555555 55.5555555}`, то свойство `HasValues` == `false`. Проверку данного свойства не убрать, т.к. файл генерируется автоматически.

**Comment by inyutin-maxim** [comment]
@zetx16 ждем от вас pull request

**Comment by zetx16** [comment]
@inyutin-maxim Подебажил еще, проблема здесь https://github.com/vknet/vk/blob/master/VkNet.UWP/Utils/VkResponseToModelCastsGenerator.cs#L643, т.к. _token равен {55.5555555 55.5555555}, то свойство HasValues = false. Проверку данного свойства не убрать, т.к. файл генерируется автоматически. Или можно сделать исключение в шаблоне.

**Comment by inyutin-maxim** [comment]
доступно в версии 1.29.1
