### ISSUE TITLE
В версии 1.29 у класса Post нет свойства MarkedAsAds

### ISSUE THREAD

**Issue by n0namer** [vknet/vk#440]
В документации https://vk.com/dev/objects/post это поле есть 

![image](https://cloud.githubusercontent.com/assets/26526650/25704782/8154d44e-30e3-11e7-9350-5f19c30c944f.png)

![image](https://cloud.githubusercontent.com/assets/26526650/25704800/9ed31850-30e3-11e7-9758-2032ccf418ed.png)

**Comment by inyutin-maxim** [comment]
@n0namer Исправлено в версии 1.29.1, доступно в nuget. видимо не та сборка подхватилась
