### ISSUE TITLE
В версии 1.29 в классе ApiAuthParams нет свойства AccessToken

### ISSUE THREAD

**Issue by n0namer** [vknet/vk#441]
В версии 1.28  был возможен такой вариант авторизации под группой:

```csharp
  groupApi.Authorize(new ApiAuthParams() { AccessToken = groupApiToken });
```
Как теперь авторизовываться под группой?

P. S.: библиотека отличная.

**Comment by inyutin-maxim** [comment]
@n0namer https://github.com/vknet/vk/blob/master/VkNet.UWP/Model/ApiAuthParams.cs#L35

**Comment by inyutin-maxim** [comment]
@n0namer Действительно нет, собери пока из github, я сделаю минорный релиз скоро

**Comment by inyutin-maxim** [comment]
@n0namer Исправлено в версии 1.29.1, доступно в nuget. видимо не та сборка подхватилась
