### ISSUE TITLE
Исключение в методе Wall.Get

### ISSUE THREAD

**Issue by gbagretsov** [vknet/vk#443]
При вызове метода Wall.Get на некоторых пользователях вылетает исключение:

An unhandled exception of type 'VkNet.Exception.InvalidParameterException' occurred in VkNet.dll
Additional information: The type 'photos_list' of attachment is not defined.

Авторизация пройдена.

Пример кода для воспроизведения проблемы:

```csharp
  var wallGetObject = vkApi.Wall.Get(new WallGetParams()
            {
                OwnerId = 6408999,
                Filter = WallFilter.Owner,
                Count = 100
            });

```

**Comment by gbagretsov** [comment]
Версия 1.28.0, на последней версии пока не могу протестировать

**Comment by RakeshAsm** [comment]
При вызове Newsfeed.Search(), что логично то же самое.

**Comment by inyutin-maxim** [comment]
#465 Добавил photos_list
