### ISSUE TITLE
Авторизация от имени сообщества

### ISSUE THREAD

**Issue by lordofhammsters** [vknet/vk#444]
Не нашел возможности авторизоваться от лица сообщества https://vk.com/dev/implicit_flow_group, не хватает параметра groups_ids, чтобы передать id группы.  Так же в scope есть доступ - manage.

`https://oauth.vk.com/authorize?client_id=1&groups_ids=1,123456&display=page&redirect_uri=http://example.com/callback&scope=friends&response_type=token&v=5.64 `

Может быть есть какой-то способ авторизоваться?

**Comment by Bezpro** [comment]
1)Зайди в свое сообщество и зайди в управление сообществом. 
2) Нажми на настройки и перейди в "Работа с API"
3) Создай ключ и сохрани его куда-нибудь
4) Авторизуйся так:
`api.Authorize("ключ")`
5)...
6)PROFIT!

**Comment by Rogogomogofl** [comment]
Начал разбираться в этой библиотеке. Нигде не могу найти указаний как авторизоваться через сообщество, а указный выше метод не работает. Прошу помощи

![image](https://user-images.githubusercontent.com/42636244/53143661-90791b80-35cb-11e9-82dc-7f54a58d3118.png)
