### ISSUE TITLE
Сделать необходимостью указывать сервисный ключ приложения в случае вызова методов без авторизации

### ISSUE THREAD

**Issue by dvygolov** [vknet/vk#445]
Согласно [вот этому документу ](https://vk.com/dev/service_token) вызовы без сервисного ключа не будут работать. Поэтому нужно сделать возможность задать этот ключ и все вызовы без авторизации делать, указывая этот ключ.

**Comment by AlexByte** [comment]
Сейчас сервисный ключ не нужен.

**Comment by AlexByte** [comment]
> Сейчас сервисный ключ доступа обязателен для работы с этими методами (не включая методы секции secure): 
> newsfeed.search 
> wall.search

**Comment by greymem** [comment]
`client = new VkApi();
client.UserId = long.Parse(<ID юзера>);
client.Authorize(new ApiAuthParams { AccessToken = <сервисныйКлючЮзера>, ApplicationId = ulong.Parse(<id приложения>), UserId = client.UserId });`

Вроде заработало

**Comment by arciv** [comment]
Здравствуйте. Спасибо за библиотеку, отличная библиотека!
Но вот этот дефект очень мешает. Популярные методы Wall.Get и Wall.Search не работают. 
Ругается: Invalid request: method is unavailable without access token
Или может есть fork где подобная доработка уже реализована?
Спасибо.

**Comment by AlexByte** [comment]
@arciv что непонятного?
> Этот метод можно вызвать с сервисным ключом доступа. Возвращаются только общедоступные данные.

**Comment by arciv** [comment]
@AlexByte 

Ну вот я так вызываю и возникает Exception с сообщением:
Invalid request: method is unavailable without access token.
К сожалению, у меня нет студии, под которую разработан проект, поэтому в отладчике посмотреть не могу, но я так подозреваю, что access_token (со значением сервисного ключа) в параметрах Request'а не передается.

api = new VkApi();
api.Authorize(new ApiAuthParams
{
  ApplicationId = 5800585,
  Login = "info@yandex.ru",
  Password = "xxx",
  UserId = 334727125,
  AccessToken = "18029fa018029fa018029fa0d7185a1d291180218029fa0415824d5e83514f4f5baaefe",
   Settings = Settings.All
});

var Posts =api.Wall.Get(new WallGetParams() {OwnerId = groupID, Count = 100, Offset = (ulong) offset}, true);

Хотя, например, поиск по документам api.Docs.Search, например, отлично работает с пустым AccessToken.

**Comment by AlexByte** [comment]
Можешь через Fiddler посмотреть.

**Comment by arciv** [comment]
@AlexByte 
Ясно. Спасибо большое за разъяснение.
Я думал skipAuthorization пропускает повторную авторизацию с помощью login/password.
Просто привык, что до апрельских изменений api этот код работал.
Так бы я конечно разобрался, просто VS 2015 на Windows 7 не ставится.
Спасибо еще раз.

**Comment by AlexByte** [comment]
Кроме токена никакие параметры при авторизации указывать не нужно.

**Comment by AlexByte** [comment]
Чем бы тебе студия помогла? Почему именно 2015 нужна? Вообще-то VS 2015 даже XP поддерживает.

**Comment by arciv** [comment]
@AlexByte 
Ну мог бы запустить на отладку исходники и посмотреть наглядно.
Посмотрел требования, действительно, на Windows 7 оказывается можно установить VS 2015.
Буду знать.
Может я путаю и vknet и вообще не требует VS 2015, просто довольно часто сталкиваюсь, что в VS 2013 не могу открыть многие проекты.

**Comment by Soniclev** [comment]
@arciv посмотри, может нужно винду 7 обновить или какие-нибудь обновления поставить, у меня как-то тоже студия не ставилась.

**Comment by arciv** [comment]
@Soniclev спасибо, посмотрю

**Comment by AlexByte** [comment]
Может открыть ты и не можешь, но создать новый проект с vknet можно.

**Comment by dvygolov** [comment]
Думаю, что нужно убрать параметр skipAuthorization, поскольку он теперь не нужен и всегда используется ключ.

**Comment by AlexByte** [comment]
Почему всегда используется ключ?

**Comment by dvygolov** [comment]
Ну потому что [вк так сделал](https://vk.com/dev/service_token).

**Comment by AlexByte** [comment]
Он только для двух методов обязателен из ранее общедоступных.
