### ISSUE TITLE
Groups.Edit не устанавливает параметр Messages при значении false

### ISSUE THREAD

**Issue by sel1** [vknet/vk#446]
Пример
```csharp
 Groups.Edit(new GroupsEditParams
                      {
                          GroupId = 1,
                          Messages = false,
                      });
```
Покопавшись в исходниках обнаружил, что в комменте к методу VkParameters.Add(string name, bool? nullableValue) присутствует такой текст

> Если передан null или значение параметра false, то добавление не производится.

Как в этом случае установить значение параметра в false?

**Comment by inyutin-maxim** [comment]
@sel1 Обычно false это значение по умолчанию, уточните о каком параметре идет речь?

**Comment by inyutin-maxim** [comment]
@sel1 [Документация VK](https://vk.com/dev/groups.edit)

**Comment by sel1** [comment]
> Обычно false это значение по умолчанию, уточните о каком параметре идет речь?

Да, но его можно поменять на true. А вот обратно на false не меняется. Проблема с параметром **Messages**

**Comment by inyutin-maxim** [comment]
@sel1 [Напишите мне в Telegram](https://telegram.me/inyutin_maxim)

**Comment by inyutin-maxim** [comment]
> если ты передать messages true то оно применяется, а если передать false то значение остается в true

Проверить nullable параметры на то что они имеют значение по умолчанию

**Comment by inyutin-maxim** [comment]
добавлено к следующему релизу
