### ISSUE TITLE
[Предложение] Перидовать методы через Execute 

### ISSUE THREAD

**Issue by NOCELL** [vknet/vk#448]
VK API позволяет отправлять 3 запроса в секунду с одного токена. За один метод Execute можно выполнить до 25 других методов, при этом Execute считается одним запросом. Можно паковать запросы в Execute для обхода ограничений VK. Особенно актуально для ботов.
vk.com/dev/execute

**Comment by inyutin-maxim** [comment]
@NOCELL [Метод реализован](https://github.com/vknet/vk/blob/master/VkNet.UWP/Categories/ExecuteCategory.cs#L39)
