### ISSUE TITLE
ошибка при сборке

### ISSUE THREAD

**Issue by rashk1n** [vknet/vk#449]
Хотел собрать библиотеку и вылетает такая ошибка, где этот файл найти?
"VkNet.UWP\Utils\ModelToVkParametrsCastGenerator.cs' не найден."

**Comment by inyutin-maxim** [comment]
@rashk1n T4 шаблоны пересобирали?

**Comment by rashk1n** [comment]
@inyutin-maxim , нет, как скачал, так и запустил сборку

**Comment by rashk1n** [comment]
вот полная ошибка
> Состояние подавления
> Ошибка		выход из команды "C:\Users\User\Downloads\vk-master\vk-master\tools\TextTransform.exe C:\Users\User\Downloads\vk-master\vk-master\VkNet.UWP\Utils\ModelToVkParametrsCastGenerator.tt -out C:\Users\User\Downloads\vk-master\vk-master\VkNet.UWP\Utils\ModelToVkParametrsCastGenerator.cs" с кодом 1.	VkNet	C:\Users\User\Downloads\vk-master\vk-master\VkNet\VkNet.csproj	1512

**Comment by inyutin-maxim** [comment]
@rashk1n Меню - Сборка - ... Т4 шаблоны

**Comment by rashk1n** [comment]
@inyutin-maxim , сбой 3-х шаблонов
Выполняется преобразование шаблона EnumTests.tt с TextTemplatingFileGenerator ... сбой.
Выполняется преобразование шаблона MultivaluedFilterTest.tt с TextTemplatingFileGenerator ... сбой.
Выполняется преобразование шаблона SafetyEnumTests.tt с TextTemplatingFileGenerator ... сбой.

**Comment by inyutin-maxim** [comment]
@rashk1n Тесты чинить надо, вообще по хорошему выкинуть генерацию тестов оттуда, можете просто выгрузить проект пока
