### ISSUE TITLE
В nuget 1.29.1 не работает капча

### ISSUE THREAD

**Issue by sel1** [vknet/vk#450]
В последней версии из nuget (1.29.1) при запросе капчи валится ошибка. В предыдущей версии такого не наблюдалось

StackTrace прилагается
System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   в Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   в VkNet.Utils.VkResponse.get_Item(Object key)
   в VkNet.Exception.VkApiException..ctor(VkResponse response)
   в VkNet.Exception.CaptchaNeededException..ctor(VkResponse response)
   в VkNet.Utils.VkErrors.IfErrorThrowException(String json)
   в VkNet.VkApi.Invoke(String methodName, IDictionary`2 parameters, Boolean skipAuthorization)
   в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization)
   в VkNet.Categories.BoardCategory.AddTopic(BoardAddTopicParams params)

**Comment by inyutin-maxim** [comment]
@sel1 попробуйте собрать библиотеку сами, возможно что то не так с библиотекой Newtonsoft.Json, с ее версией

**Comment by qwitriy** [comment]
Такое же исключение при спаме Friends.Add

**Comment by antibrr** [comment]
кто-нибудь решил проблему? сборка проблему не решила, смена Newton'а тоже

**Comment by inyutin-maxim** [comment]
@antibrr @qwitriy @sel1 каково состояние проблемы?

**Comment by inyutin-maxim** [comment]
За отсутствием обратной связи считаю проблему не действительной
