### ISSUE TITLE
Сделать замену отступов в табах на пробелы

### ISSUE THREAD

**Issue by AlexByte** [vknet/vk#451]

**Comment by inyutin-maxim** [comment]
@AlexByte Обоснуйте)) У нас принято наоборот, использовать табы

**Comment by AlexByte** [comment]
По умолчанию в VS протоколы используется и в pull request табу заменяются на проблемы

**Comment by CaCTuCaTu4ECKuu** [comment]
Никаких пробелов, я не знаю в каких это учебных заведениях учат пробелы использовать.

**Comment by inyutin-maxim** [comment]
@AlexByte Не согласны, разводить холивар не вижу смысла

**Comment by AlexByte** [comment]
Напиши в README чтобы не заменяли табы на пробелы.
