### ISSUE TITLE
Ошибка при авторизации пользователей с отключенной 2х факторной аутентификацией

### ISSUE THREAD

**Issue by VanKrock** [vknet/vk#452]
Если в аккаунте отключена двойная аутентификация, то войти не удастся, т.к. приложение будет постоянно выкидывать ошибку с содержимым "Form element not found".

Мы не можем знать заранее, будет ли у пользователя включена 2х факторная аутентификация.

**Comment by AlexByte** [comment]
Лови исключение и авторизуй без двойной

**Comment by VanKrock** [comment]
@AlexByte как раз суть в использовании Func в том, чтобы вызвать его если он понадобится.

**Comment by AlexByte** [comment]
И что ты предлагаешь?

**Comment by VanKrock** [comment]
@AlexByte  Предлагаю после ввода логина и пароля сделать проверку на появление формы 2х факторной аутентификации и вызывать Func только если форма появилась, а не делать решение на основе того, указал разработчик Func или нет.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу

**Comment by dvygolov** [comment]
Использую библиотеку в Azure Function. При авторизации выдаётся та же ошибка, что и у камрада выше: Form Element Not Found. Двухфакторка в аккаунте, который используется в работе, отключена. Код совершенно обычный:
```

            var vk = new VkApi();
            var authParams = new ApiAuthParams()
            {
                ApplicationId = appId,
                Login = "xxx@gmail.com",
                Password = "xxxx",
                Settings =
                    Settings.Documents | Settings.Friends | Settings.Groups | Settings.Messages |
                    Settings.Notes | Settings.Offline | Settings.Pages | Settings.Photos |
                    Settings.Video | Settings.Wall
            };
            vk.Authorize(authParams);

```
Прикладываю скрины с Azure Portal. 
![image](https://user-images.githubusercontent.com/9249545/35223519-166892f6-ff9b-11e7-9636-c30820ec4414.png)
![image](https://user-images.githubusercontent.com/9249545/35223546-2d3fcf4e-ff9b-11e7-883d-c351c14b36e2.png)
