### ISSUE TITLE
При вызове метода выдает ошибку 

### ISSUE THREAD

**Issue by ThomasCarlyle** [vknet/vk#453]
Code<<<
`VkApi vk = new VkApi();
vk.Authorize(new ApiAuthParams { ApplicationId = 123, Login = "myLogin", Password = "myPass", Settings = Settings.All });
vk.Users.Get(1,ProfileFields.All);`

ERROR>>>>>
VkNet.Exception.UserAuthorizationFailException: 'User authorization failed: access_token was given to another ip address.'

**Comment by inyutin-maxim** [comment]
@ThomasCarlyle access_token was given to another ip address.
access_token был дан другому IP-адресу

**Comment by ThomasCarlyle** [comment]
@inyutin-maxim Я понимаю. но как ? если программа работает на моем компе, и access_token запрашивает сам код.

**Comment by inyutin-maxim** [comment]
@ThomasCarlyle Прокси не используете? сложно сказать в чем причина, изучать нужно

**Comment by ThomasCarlyle** [comment]
@inyutin-maxim  нет, не использую. thanks ;)

**Comment by inyutin-maxim** [comment]
@ThomasCarlyle Подозреваю что вы пишете ботов, и где то в вашей сети уже был запущен бот вот он и ругнулся таким образом, ваша проблема как то решилась? мы можем закрывать задачу?

**Comment by ThomasCarlyle** [comment]
@inyutin-maxim да все нормально уже, Большое спасибо !!!

**Comment by evgenso** [comment]
> @inyutin-maxim да все нормально уже, Большое спасибо !!!
Подскажите пожалуйста как решили проблему? У меня похожая, но только при использовании прокси...
