### ISSUE TITLE
Класс FriendsGetRequestsParams не содержит параметр NeedViewed

### ISSUE THREAD

**Issue by qwitriy** [vknet/vk#454]
- Класс и метод в котором возникла проблема: 
FriendsGetRequestsParams конструктор

- Пример кода для воспроизведения проблемы:
```csharp
 FriendsGetRequestsParams param = new FriendsGetRequestsParams()
            {
                Offset = 0,
                Count = 100,
                NeedMutual = false,
                Extended = false,
                Sort = false,
                Out = false,
                NeedViewed = true
            };
```
"FriendsGetRequestsParams" не содержит определение для "NeedViewed"

Однако в [документации ](https://vknet.github.io/vk/friends/getRequests/)параметр присутствует

**Comment by inyutin-maxim** [comment]
@qwitriy Добавлено к следующему релизу. Спасибо за pull request
