### ISSUE TITLE
В nuget 1.29.1 не попали исправления количества просмотров поста

### ISSUE THREAD

**Issue by VanKrock** [vknet/vk#457]
В nuget 1.29.1 не попал коммит https://github.com/vknet/vk/commit/4a4e4da4a2ed1e78741dca7bf8dc102b2da97c06 хотя в Release Notes указано, что эти исправления есть.

**Comment by inyutin-maxim** [comment]
@VanKrock Странно, ну либо соберите сами, либо подождите релиза, как освободится время выложу

**Comment by inyutin-maxim** [comment]
@VanKrock библиотека была переопубликована, доступна версия 1.29.2 пожалуйста сообщите воспроизводится ли проблема

**Comment by VanKrock** [comment]
@inyutin-maxim Views работают в 1.29.2
