### ISSUE TITLE
исключение VkNet.Exception.CannotBlacklistYourselfException 

### ISSUE THREAD

**Issue by PhiseySt** [vknet/vk#458]
Это мелкое замечание, не принципиальная ошибка.
Версия пакета VkNet 1.29.2 под NetCore:
При попытке отправки сообщения следующим образом, возникает неправильный текст исключения:
VkNet.Exception.CannotBlacklistYourselfException: 'Access denied: no access to call this method'
что вводит в заблуждение о причине ошибки, так как с Blacklistом это не связано.

Просто строка с разрешениями к функции закомментирована // authorize.Settings = settings;
и нет прав на отправку сообщения.

Логичнее чтобы как в версии 1.28 было исключение   'Access denied: no access to call this method'

            var authorize = new ApiAuthParams();
            Settings settings = Settings.Messages ; 
            var vk = new VkApi();
            // authorize.Settings = settings;
            authorize.Login = _vkSettings.VkLogin;
            authorize.Password = _vkSettings.VkPassword;
            authorize.ApplicationId = _vkSettings.VkAppId;
            vk.Authorize(authorize); 
            var mesSend = new MessagesSendParams();
            mesSend.Message= body;
            mesSend.UserId =_vkSettings.UserRecepientId;
            var send = vk.Messages.Send(mesSend);

**Comment by inyutin-maxim** [comment]
@PhiseySt Сложно сказать, нужно смотреть какой ErrorCode пришел в ответе если 15 то все корректно
с точки зрения библиотеки, некорректно сам ВК отдает ошибку

**Comment by inyutin-maxim** [comment]
Список кодов был дополнен, метод возвращает другие ошибки

**Comment by daniilminakov** [comment]
Здравствуйте! Подскажите пожалуйста, как добавить комментарий от имени группы с помощью wall.CreateComment? Я передал флаг 0 в FromGroup  и у меня получилось добавить коммент от имени пользователя. Но когда пробую флаг 1, прилетает exception. +		$exception	{"Access denied: could not access to this community"}	VkNet.Exception.CannotBlacklistYourselfException
Заранее спасибо!

**Comment by inyutin-maxim** [comment]
@daniilminakov Нужно авторизоваться от имени сообщества

**Comment by daniilminakov** [comment]
@inyutin-maxim А не подскажите, как авторизоваться от имени сообщества?Заранее спасибо!

**Comment by CaCTuCaTu4ECKuu** [comment]
@daniilminakov опишите тип вашего сообщества и какие настройки вы указываете при авторизации (ApiAuthParams.Settings) ?
Эта ошибка присутствует на текущей версии с github или с nuget?

**Comment by daniilminakov** [comment]
@CaCTuCaTu4ECKuu Группа открытая , настройки Settings.All

**Comment by daniilminakov** [comment]
@CaCTuCaTu4ECKuu Устанавливал либу из nuget.

**Comment by CaCTuCaTu4ECKuu** [comment]
@daniilminakov в данной конкретной ошибке не уверен, не не могли бы вы подтвердить ее на версии с гитхаба, недавно настройки были сильно переделаны из за проблем в работе с группами

**Comment by daniilminakov** [comment]
@CaCTuCaTu4ECKuu Я нашел причину ошибки. У меня не отправляются комментарии от имени группы, средствами самого вк. Я связался с поддержкой, они ответили, что доступ, для отправки комментариев от имени малочисленных  и недавно созданных групп, закрыт. Соответственно точные цифры, сколько должна существовать группа и сколько участников должно быть, никто не сказал.
