### ISSUE TITLE
Возникает ошибка NullReferenceException при попытке получить сообщения сообщества

### ISSUE THREAD

**Issue by v-moroz** [vknet/vk#459]
Авторизация проходит успешно (проверял на других методах). Авторизация выполнялась с помощью **ключа доступа сообщества**. С помощью функции **Messages.Get** пытаюсь получить список сообщений **СООБЩЕСТВА**. 
Выдает исключение _NullReferenceException: Object reference not set to an instance of an object._ после вызова библиотечного метода **VkNet.Model.MessagesGetObject.FromJson(VkResponse response).**

Функцию вызываю таким образом:
```csharp
var messages = vk.Messages.Get(new MessagesGetParams() { Count = 10, Offset = 0 });
```
P.S. Использую .NET Core

**Comment by inyutin-maxim** [comment]
System.NullReferenceException при получении сообщений пользователя #471
Добавлено к следующему релизу
