### ISSUE TITLE
Не получается опубликовать сообщение в группе с использованием Ключ доступа сообщества

### ISSUE THREAD

**Issue by DmitryEm506** [vknet/vk#460]
Всем привет!
Создал группу, получил ключ доступа группы (Настройки -> Работа с API -> создать ключ)
Права доступа: сообщения сообщества, фотографии, документы

После чего ApiAuthParams прокинул полученный токен и вызвал метод авторизации .Authorize

Не могу понять как на стене этой же группы опубликовать сообщение.
Пользовался методом .Messages.Send()

Может быть не указал необходимые аргументы.

**Comment by Shifu462** [comment]
Используйте метод wall.post, если хотите опубликовать запись на стене сообщества.
https://vk.com/dev/wall.post
https://vknet.github.io/vk/wall/post/
