### ISSUE TITLE
Cannot access child value on Newtonsoft.Json.Linq.JValue

### ISSUE THREAD

**Issue by toyozoyes** [vknet/vk#461]
почему не дает ссылку на профиль?>

var message = vk.Messages.Send(new VkNet.Model.RequestParams.MessagesSendParams
{
UserId = 423741868,
Message = $"{friends.LastName}{friends.FirstName} : URL - {friends.Domain}"
});

**Comment by toyozoyes** [comment]
Сейчас указал вернуть 9 человек из друзей - вернуло всего 8 на 9 ошибка эта - список более 3к

**Comment by inyutin-maxim** [comment]
@toyozoyes Нужно больше кода. Не понятно по какой причине код падает
