### ISSUE TITLE
Преобразование созданного опроса в коллекцию 

### ISSUE THREAD

**Issue by AKr0nizz** [vknet/vk#463]
Добрый день. Как преобразовать созданный опрос в коллекцию, как например делает Photo.SaveWallPhoto? В документации polls слабо описаны. 

            List<string> answersList = new List<string>();

            answersList.Add("1");
            answersList.Add("2");
            answersList.Add("3");
            answersList.Add("4");
            answersList.Add("5");

            var polls = vkAPI.PollsCategory.Create(new PollsCreateParams { Question = "Ну какой вопрос?", AddAnswers = answersList, OwnerId = -123 });

            var messages = vkAPI.Wall.Post(new WallPostParams
            {
                //Attachments = polls,
                Message = "test photo",
                OwnerId = -123,
            });

А если скажем необходимо прикрепить картинку и опрос?

**Comment by inyutin-maxim** [comment]
@AKr0nizz  я думаю опрос можно прикрепить к посту, а пост можете вложить все что заблагорассудиться

**Comment by AKr0nizz** [comment]
Спасибо. Реализовал так:

List<string> answersList = new List<string>();
            answersList.Add("1");
            answersList.Add("2");
            answersList.Add("3");
            answersList.Add("4");
            answersList.Add("5");

            var polls = vkAPI.PollsCategory.Create(new PollsCreateParams { Question = "Ну какой вопрос?", AddAnswers = answersList, OwnerId = -123 });
            
            List<VkNet.Model.Attachments.MediaAttachment> attList = new List<VkNet.Model.Attachments.MediaAttachment>();

            attList.Add(polls);            

            var uploadServer = vkAPI.Photo.GetWallUploadServer(123);

            var wc = new WebClient();

            var responseFile = Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, @"1.png"));

            System.Collections.ObjectModel.ReadOnlyCollection<VkNet.Model.Attachments.Photo> photos = vkAPI.Photo.SaveWallPhoto(responseFile, null, 123);

            foreach (var element in photos)
            {
                attList.Add(element);
            }
           
            var messages = vkAPI.Wall.Post(new WallPostParams
            {
                Attachments = attList,
                Message = "test photo",
                OwnerId = -123,
            });

/close
