### ISSUE TITLE
Linux будет?

### ISSUE THREAD

**Issue by LiptonOlolo** [vknet/vk#464]
Ошибка при запуске на Linux'e: [https://pastebin.com/b38pgr1R](https://pastebin.com/b38pgr1R)
Система: Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
Mono: Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-10)
.net: 4.5.2

**Comment by inyutin-maxim** [comment]
@LiptonOlolo Катастрофически нет времени в данный момент, но в теории NetStandard работать должен, но нужно поправить данную ошибку авторизации. Были бы рады пулл реквестам

**Comment by LiptonOlolo** [comment]
@inyutin-maxim При добавлении в Main 
```C# 
ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
```
Ошибка сокращается до [https://pastebin.com/T3i85wTV](https://pastebin.com/T3i85wTV)

**Comment by inyutin-maxim** [comment]
@LiptonOlolo любопытно, может в воскресенье посмотрю что к чему, но ничего обещать не могу)) продолжайте, может докопаетесь до проблемы

**Comment by LiptonOlolo** [comment]
@inyutin-maxim Ну как там дела? Нашли что-то?

**Comment by LiptonOlolo** [comment]
@inyutin-maxim hallo?

**Comment by EarsKilla** [comment]
когда пробовал запустить на debian8 c mono 4.* версии, там winhttp.dll просило.

**Comment by inyutin-maxim** [comment]
@LiptonOlolo , @EarsKilla   работает на ubuntu 16.04, с использованием .net core 2.0. соберите из github или подождите релиза
