### ISSUE TITLE
InvalidParameterException: "The type 'photos_list' of attachment is not defined

### ISSUE THREAD

**Issue by greymem** [vknet/vk#465]
Есть [такой пост](https://vk.com/wall323804977_4) , а у него есть поля 
> "attachments": [{
> "type": "photo",
> "photo": {
> ...
> }
> }, {
> **"type": "photos_list",**
> "photos_list": ["323804977_381415995"]
> }],

И именно при попытке получить этот псто поиском, вылетает Exception

**- Класс и метод в котором возникла проблема:**
_VkNet.Exception.InvalidParameterException: "The type 'photos_list' of attachment is not defined. "_

**- Пример кода для воспроизведения проблемы:**
```csharp
  client = new VkApi();
  //Авторизация....
  var resp = client.NewsFeed.Search(new VkNet.Model.RequestParams.NewsFeedSearchParams { Query = "#alfabankcareer", Count = 200});
```
С остальными пока всё норм, поиск работает

**Comment by CaCTuCaTu4ECKuu** [comment]
нужно изменить поля в методах FromJson

15 июля 2017 г. 6:35 PM пользователь "Vasily" <notifications@github.com>
написал:

**Comment by greymem** [comment]
@CaCTuCaTu4ECKuu  этот класс не partial. Я не могу его дополнять по-своему. А править исходники не хочется, так как изменения потеряются при обновлении

**Comment by inyutin-maxim** [comment]
@greymem Если сделать pull request то не потеряются, а вольются в следующую версию

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу
