### ISSUE TITLE
Многопоточность VkNet

### ISSUE THREAD

**Issue by AMBULATUR** [vknet/vk#468]
В общем как я понял, многопоточность пока не реализована в VkNet ? допустим я организовал 2а потока и в каждом авторизовался. 
```csharp
 Threads = new Thread[1000]; // 

                    for (int i = 0; i < 2; i++) // 
                    {
               Threads[i] = new Thread(this.Auth);
                        Threads[i].IsBackground = true;
                        Threads[i].Start();
_sleep(1000)
                    }
```

```csharp
private void Auth(){
   vkApi.Authorize(new ApiAuthParams
                {
                    ApplicationId = Convert.ToUInt32(ApiBox.Text),
                    Login = Login,
                    Password = Password,
                    Settings = Settings.All,
                    CaptchaKey = Key,
                    CaptchaSid = csid,
                    Host = PHost,
                    Port = Convert.ToInt32(PPort),
                });

Message(vkApi.UserId);
}
```
Допустим авторизовался с двух совершенно разных аккаунтов и запустил метод Message.

```csharp
private void Message(long? CurrentUserId)
{
 ReadOnlyCollection<VkNet.Model.User> users;
 long chatID;

  users = vkApi.Friends.Get(new VkNet.Model.RequestParams.FriendsGetParams
                 {
                 UserId = 0,
                });
//#
chatID = vkApi.Messages.CreateChat(users.Select(user => (ulong)user.Id), ChatName); // создание чата
//#
vkApi.Messages.RemoveChatUser(chatID, (long)CurrentUserId); // удаления себя из созданного чата
}
```
Так вот, если метод Message(); будет вызван одновременно в 2-ух потоках, то при выполнении 1-ым потоком vkApi.Messages.RemoveChatUser(chatID, (long)CurrentUserId); будет вызван exception который будет гласить что у него нет прав для удаления данного пользователя(себя) из чата(созданного собою же) ,это связано с тем, что 2-ым потоком AccessToken 1ого аккаунта в VkApi был изменен после Auth(); на AccessToken 2ого аккаунта .
Поэтому предлагаю в методы 
vkApi.Friends.Get
vkApi.Messages.DeleteDialog
vkApi.Messages.RemoveChatUser
vkApi.Messages.Send
vkApi.Messages.CreateChat
Добавить параметр AccessToken(Токен аккаунта с которого будет выполняться данное действие.)

**Comment by Soniclev** [comment]
Можно создать два объекта VkApi для двух аккаунтов.

**Comment by AMBULATUR** [comment]
@Soniclev , боже, спасибо. Совсем забыл об этом, я - идиот.

**Comment by CaCTuCaTu4ECKuu** [comment]
На каждого пользователя нужен отдельный VkApi, реализовать это через один и тот же, но с использованием разных accessToken не заложена в архитектуру и придется всё методы дописывать и перегружать вариацией, которая принимает токен. Не представляю в какой ситуации эта робота будет стоить результата небольшого выигрыша в производительности.
