### ISSUE TITLE
Link Attachemt

### ISSUE THREAD

**Issue by AMBULATUR** [vknet/vk#470]
В vkNet присутсвует возможность отправки attachment "PHOTO" , как реализовать отправку attachment "LINK" , судя по vk dev странице, api позоляет это сделать. 
`https://vk.com/pages?oid=-1&p=%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BE%D0%BB%D1%8F_attachments`
http://i.imgur.com/xnh4cSI.png

```csharp
        var photos = vkApi.Photo.Save(new VkNet.Model.RequestParams.PhotoSaveParams
            {
                SaveFileResponse = responseFile,
                AlbumId = album.Id
            });

   vkApi.Messages.Send(new VkNet.Model.RequestParams.MessagesSendParams
                {
                    ChatId = 123,
                    Message = "photo",
                    Attachments = photos,
                });
```

Так вопрос, как реализовать отправку приложения вида "Link" ? (выделение 2)
http://i.imgur.com/ZWALPr0.png

**Comment by inyutin-maxim** [comment]
@AMBULATUR При [отправке сообщения](https://vk.com/dev/messages.send) это не работает, только при [публикации записи на стене](https://vk.com/dev/wall.post)
