### ISSUE TITLE
Не удаётся установить библиотеку из Nuget

### ISSUE THREAD

**Issue by adeldolgov** [vknet/vk#474]
Установка "VkNet 1.29.2".
"VkNet 1.29.2" успешно установлен.
Добавление "VkNet 1.29.2" в ConsoleApplication4.
Удаление "VkNet 1.29.2".
"VkNet 1.29.2" успешно удален.
Не удалось выполнить установку. Идет откат...
Не удалось установить пакет "VkNet 1.29.2". Вы пытаетесь установить этот пакет в проект, требуемая версия платформы которого — ".NETFramework,Version=v4.5", но в пакете нет ссылок на сборки или файлов содержимого, совместимых с этой платформой. Дополнительные сведения можно получить у автора пакета.

**Comment by kot-mapku3** [comment]
Такая же проблема, только с vk-capthca-analyzer

**Comment by inyutin-maxim** [comment]
@adeldolgov Какая версия .net framework используется в проекте?

**Comment by kot-mapku3** [comment]
4.5

**Comment by kot-mapku3** [comment]
Поменял на 4.5.2 вроде, установило VkNet и робит, хз в чем проблема была

**Comment by adeldolgov** [comment]
Спасибо за помощь, но я уже без библиотеки пишу :)

21 авг. 2017 г. 12:29 пользователь "Артём Черница" <notifications@github.com>
написал:
