### ISSUE TITLE
VkNet.Exception.VkApiException: Invalid name in response

### ISSUE THREAD

**Issue by mittorn** [vknet/vk#477]
Такое происходит при получении списка пользователей в беседе, в которой есть сообщества (например бот "молодец")

**Comment by inyutin-maxim** [comment]
@mittorn нужно больше данных и пример чтобы отладиться

**Comment by mittorn** [comment]
Чем не достаточно приведённого в заголовке исключения?
```
if (response["name"] != null)
{
// Разделить имя и фамилию
var parts = ((string)response["name"]).Split(' ');
if (parts.Length < 2)
{
throw new VkApiException("Invalid name in response");
}
user.FirstName = parts[0];
user.LastName = parts[1];
}
```
https://github.com/vknet/vk/blob/a341e9cc24bb0d564e8800639cb897dc5529e969/VkNet/Model/User.cs#L584
Имя бота состоит из одного слова, потому кидается исключения

**Comment by inyutin-maxim** [comment]
@mittorn Недостаточно было тем что проект наизусть никто не знает, а с примером проще и быстрее разобраться. Чем больше исходных данных, тем быстрее проблема будет устранена. Спасибо за дополнение. В ближайшее время поправим

**Comment by inyutin-maxim** [comment]
@mittorn добавлено к следующему релизу
