### ISSUE TITLE
Метод Messages.GetDialogs - ошибка NullReferenceException

### ISSUE THREAD

**Issue by vese** [vknet/vk#478]
Метод Messages.GetDialogs все время выдает ошибку NullReferenceException.
Причина этого - отсутствие в файле MessagesGetObject.cs директивы 
```csharp
  using VkNet.Model;
```
Без неё не видно класс Message
```csharp
  public ReadOnlyCollection<Message> Messages { get; set; }
```

**Comment by roman412** [comment]
IMHO, лучше strong-typed:
`public VkNet.Model.ReadOnlyCollection<Message> Messages { get; set; }`

**Comment by vese** [comment]
Тогда уж так:
`        public ReadOnlyCollection<VkNet.Model.Message> Messages { get; set; }`

**Comment by roman412** [comment]
👍 , @vese , спасибо, сонный был и даже не заметил, что недостаёт определения класса Message вместо коллекции.

**Comment by roman412** [comment]
Можно, up? Жить не могу без этого метода!

**Comment by Soniclev** [comment]
@vese а можно по-подробнее, у меня метод работает

**Comment by Bezpro** [comment]
до сих пор не работает(

**Comment by inyutin-maxim** [comment]
@Bezpro , @roman412 , @vese . Метод работает, необходимо задавать обязательный параметр count. Может иметь положительное число до 200. Привоже пример кода:
``` csharp
var result = api.Messages.GetDialogs(new MessagesDialogsGetParams
{
    Count = 20
});
```
