### ISSUE TITLE
Нет ли вспомогательных методов для удобной загрузки файлов?

### ISSUE THREAD

**Issue by asimaranov** [vknet/vk#480]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

- Класс и метод в котором возникла проблема:

- Пример кода для воспроизведения проблемы:

```csharp
  // Вставьте пример кода сюда
```

- Если в примере не указаны конкретные значения параметров запроса укажите их здесь:

- PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/vknet/vk?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by inyutin-maxim** [comment]
@asimaranov Вспомогательных средств нет. Некоторые примере по загрузке файлов находятся [здесь](https://github.com/vknet/vk/wiki/FAQ)
