### ISSUE TITLE
Метод Call

### ISSUE THREAD

**Issue by asimaranov** [vknet/vk#481]
Добрый день. Пытаюсь использовать метод Call, получаю из него исключение 

```
VkNet.Utils.VkParameters param = new VkNet.Utils.VkParameters { { "type", "audio_message" } };
            string us = api.Call("docs.getUploadServer", param);//Необработанное исключение типа "System.ArgumentException" в Newtonsoft.Json.dll

Дополнительные сведения: Can not convert Object to String.
```

Я что-то делаю не так, или метод call не работает нужным образом?

**Comment by vese** [comment]
Метод Call возвращает не строку.
Сделайте так:
`var us = api.Call("docs.getUploadServer", param);`

Также для аудио сообщений нужно использовать другой метод вместо "docs.getUploadServer";
