### ISSUE TITLE
Добавление ссылки в Attachments

### ISSUE THREAD

**Issue by HEYHEYHEEEEY** [vknet/vk#483]
Есть проблема в том, что необходимо сделать пост с фото и ссылкой.

Сам код:
```
var attach = new List<MediaAttachment>();
VkNet.Model.Attachments.Link link  = new VkNet.Model.Attachments.Link();
Uri url = new Uri(URL);
link.Uri = url;
link.IsExternal = true;
attach.AddRange(photos);
//attach.AddRange(link);
```
photos имеет тип System.Collections.ObjectModel.ReadOnlyCollection<VkNet.Model.Attachments.Photo>, код с которым загружает картинку на сервер.
Attachments является типом ienumerable<MediaAttachment>. 
//attach.AddRange(link); показывает ошибку не удается неявно преобразовать тип "VkNet.Model.Attachments.Link" в "System.Collections.Generic.IEnumerable<VkNet.Model.Attachments.MediaAttachment>"

По идее надо перевести VkNet.Model.Attachments.Link link в System.Collections.Generic.IEnumerable<VkNet.Model.Attachments.MediaAttachment>, я прав в догадке?

**Comment by Soniclev** [comment]
Правильно будет не `//attach.AddRange(link);`, а `attach.Add(link);`
