### ISSUE TITLE
Загрузка фото в пост из интернета

### ISSUE THREAD

**Issue by HEYHEYHEEEEY** [vknet/vk#484]
Для загрузки фото из интернета я с помощью webclient-а загружаю его на комп, а после отправляю на сервер. 
Если создавать пост вручную, то при написании ссылки на фото типа http://адрес/фото.jpg эта картинка сразу подцепляется к посту. Почитал документацию на сайте вк, ничего подобного с приложением link не нашёл. Если прикрепить к посту ссылку на фото с помощью VK Net, оно автоматически загрузится? На вряд ли конечно, но спросить стоит.

Просто хочется найти более удобный способ загрузки изображений из Интернета в пост без сохранения на ПК, а webclient не может.

**Comment by inyutin-maxim** [comment]
@HEYHEYHEEEEY вы можете сохранять фото в `Stream` а дальше отправлять документ из оперативной памяти на сервер ВК
