### ISSUE TITLE
Задаем заголовок прикрепленной ссылки, а заголовок не появляется

### ISSUE THREAD

**Issue by HEYHEYHEEEEY** [vknet/vk#485]
Приветсвую всех.
Написал небольшую функцию, которая позволит сделать отложенную запись с ссылкой. Проблема этой функции в том, что прикреплённая ссылка будет без заголовка и описания. В чём может быть дело?
```
string Post (DateTime Time, string URL, string PictureName, string Text, int Group, string URLImage)
        {
                var attach = new List<MediaAttachment>();
                VkNet.Model.Attachments.Link link  = new VkNet.Model.Attachments.Link();
                Uri url = new Uri(URL);
                link.Uri = url;
                link.IsExternal = true;
                link.Title = "тайтл";
                link.Description = "дескрипшен";
                link.Image = URLImage;
                attach.Add(link);
                var post = vk.Wall.Post(new VkNet.Model.RequestParams.WallPostParams
                {
                    OwnerId = Group,
                    FromGroup = true,
                    Message = Text,  
                    Signed = true,
                    PublishDate = Time,
                    Attachments = attach,
                });
}
```

**Comment by HEYHEYHEEEEY** [comment]
При редактировании такого поста вручную через браузер ссылка пропадает.

**Comment by HEYHEYHEEEEY** [comment]
Этот код даёт такое приложение в виде ссылки без заголовка и описания - https://i.imgur.com/G1LAsNs.png
Что по идее должно быть - https://i.imgur.com/WHMmQUl.png

Пробую разные варианты, но в итоге все они делают ссылку без заголовка и описания(

В чём же может быть проблема?

**Comment by Skrims** [comment]
Дело в том, что апи не предоставляет функционал для отправки ссылки в своем формате.
В документации к методу https://vk.com/dev/wall.post сказано, что для прикрепления ссылки нужно указать ее в аттачментах:

> Также в поле attachments может быть указана ссылка на внешнюю страницу, которую Вы хотите разместить в записи, например:
photo66748_265827614,http://habrahabr.ru

Никаких дополнительных параметров форматирования ссылки метод не принимает. Поэтому ваши попытки не дают результата. Все эти свойства у класса ссылки используются для получения объекта с форматированной ссылкой (который был размещен вручную).

**Comment by HEYHEYHEEEEY** [comment]
Хм, здесь вы меня поставили в тупик. 
По документации контакта всё выглядит довольно просто: добавь ссылку в приложения, а контакт за тебя всё сам сделает. 
Эта библиотека использует класс MediaAttachments, только его можно подставить для параметра Attachments метода vk.Wall.Post. У этого класса есть дочерние классы, одним из которых является Link. Если я укажу только ссылку в свойстве Link.Uri, то результат будет как прежде, а точнее без картинки и заголовка.
В документации библиотеки VK Net что-то о Link не нашёл(
Так как всё же получить нормальную ссылку с помощью VK NET?

**Comment by HEYHEYHEEEEY** [comment]
Если делать через запрос с помощью формы в конце страницы https://vk.com/dev.php?method=wall.post - всё хорошо.
Если делать в виде GET-запроса https://api.vk.com/method/wall.post?owner_id=-groupId&attachments=http://habrahabr.ru&access_token=blablabla - тоже всё хорошо. 

Я даже не знаю, с чем может быть это связано.

**Comment by azhidkov** [comment]
@HEYHEYHEEEEY если через форму и GET-запрос работает, ошибка где-то в библиотеке. Попробуйте поставить точки останова в методе создания запросв, классе WebCall, и посмотреть что там формируется.

**Comment by HEYHEYHEEEEY** [comment]
Вобщем, это косяк ВК, но я даже не знаю, когда они его исправят(
Вот что они написали: 
"По Вашему обращению создана задача для разработчиков.
Мы надеемся, что проблему удастся решить в кратчайшие сроки.

К сожалению, иногда исправление даже незначительных неполадок может занять много времени.
Пожалуйста, наберитесь терпения. Мы ждем вместе с Вами.

Как только появятся новости, Вы получите автоматическое уведомление в этом диалоге."

**Comment by inyutin-maxim** [comment]
@HEYHEYHEEEEY Приложите ссылку на баг в трекере vk

**Comment by HEYHEYHEEEEY** [comment]
Техподдержка не хочет давать мне доступ к этому баг-трекеру, чтобы я выложил запись об этом баге там. Говорят, что его скоро закроют.
А тем временем баг до сих пор не убрали(

**Comment by inyutin-maxim** [comment]
@HEYHEYHEEEEY Сообщите как что то измениться, спасибо

**Comment by inyutin-maxim** [comment]
![default](https://user-images.githubusercontent.com/1781005/33450109-d1f0e2de-d61b-11e7-9934-50602453ea68.png)
``` csharp
var result = api.Wall.Post(new WallPostParams
            {
                OwnerId = 32190123,
                Attachments = new List<MediaAttachment>
                {
                    new StringLink()
                    {
                        Link = "http://habrahabr.ru"
                    }
                }
            });
```
Добавил класс StringLink, имеет строковое поле Link. Заголовки и все прочее создается автоматически основываясь на данных ссылки

**Comment by lexxxxxer** [comment]
@HEYHEYHEEEEY Удалось ли решить проблему?

**Comment by HEYHEYHEEEEY** [comment]
Неа, контакт так и не исправил этот баг при работе с API (пробовал напрямую, без библиотеки). Техподдержка меня культурно посылает ждать.

**Comment by lexxxxxer** [comment]
@HEYHEYHEEEEY Написал им тоже. Упомянул то что вы уже ранее подавали и до сих пор не исправлено.

**Comment by t1maccapp** [comment]
Тоже столкнулся с этой проблемой.

**Comment by HEYHEYHEEEEY** [comment]
Недавно ВК починил эту проблему, теперь заголовок и картинка прикрепляются к ссылке при использовании VK NET

**Comment by BearBump** [comment]
Как изменить заголовок прикрепленной ссылки? В вк при наведении на заголовок появляется карандашик, при нажатии на который можно изменить заголовок. Есть ли возможность сделать это с помощью апи?
