### ISSUE TITLE
Выбор нескольких прав доступа

### ISSUE THREAD

**Issue by HEYHEYHEEEEY** [vknet/vk#486]
Всем привет.
При авторизации можно задать права доступа к аккаунту. Проблема в том, что в моей задаче мне нужны только два права, а не все. Параметр scope имеет тип Settings, так что два права поставить не получается.
Какой может быть выход из данной ситуации?

**Comment by HEYHEYHEEEEY** [comment]
Из возможных решений появилось такое: создать приложение, которое будет отвечать за photos, создать другое, которое будет отвечать за wall. Сделать два объекта var vk = new VkApi(), которые будут обращаться только к своим приложениям соответственно.
Есть ли другие варианты?

**Comment by Skrims** [comment]
Попробуйте так:
```c#
var authParams = new ApiAuthParams
{
    Login = login,
    Password = password,
    ApplicationId = appId,
    Settings = Settings.Audio | Settings.Video | Settings.Friends
};

var vkClient = new VkApi();
vkClient.Authorize(authParams);
```
