### ISSUE TITLE
Лишние пакеты для .net framework

### ISSUE THREAD

**Issue by ivanovevgeny** [vknet/vk#487]
Версия 1.29.2 при установке в проект .net framework (не .net core) предлагает поставить пакеты для net core.

![image](https://user-images.githubusercontent.com/8840414/31214328-2c4591dc-a9c4-11e7-937e-2ee9c09df4ea.png)

**Comment by inyutin-maxim** [comment]
Исправлено в версии 1.29.3
![image](https://user-images.githubusercontent.com/1781005/32953511-7ce999c0-cbc1-11e7-9db6-99ae38d9d77d.png)

**Comment by inyutin-maxim** [comment]
На NET40 тоже проверил
![image](https://user-images.githubusercontent.com/1781005/32954027-f91f939a-cbc2-11e7-808b-3730710ee89c.png)
