### ISSUE TITLE
Функция Messages.Get() все время возвращает System.NullReferenceException

### ISSUE THREAD

**Issue by Iarden13** [vknet/vk#490]
Я новичок в этом деле, но ни как не работает функция на получение сообщения, притом что GetHistory работает.
Использую:
var q = api.Messages.Get(new MessagesGetParams {
                Count = 1, Out = MessageType.Received
            });

**Comment by Skrims** [comment]
Да, при установке с NuGet'a присутствует данная ошибка, при сборке с гитхаба ее нет.
Соберите сборку самостоятельно, либо ожидайте когда нугет пакет будет обновлен.

**Comment by inyutin-maxim** [comment]
@Iarden13 В актуальной версии 1.29.3 проблема не воспроизводится
