### ISSUE TITLE
Newtonsoft.Json.JsonConvert не сериализует объекты в JSON

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#491]
При сериализации объектов возвращает пустой Json объект ([], [{},{}]).
Проверено на VkNet.Model.User

**Comment by CaCTuCaTu4ECKuu** [comment]
Создал пул потому что на самом деле не понимаю почему. Сказано что сериализатор должен вовзращать всё публичные параметры, но ведь у User всё в порядке с параметрами, они публичные.

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu ты имел ввиду метод Utilities.SerializeToJson(object)?

**Comment by CaCTuCaTu4ECKuu** [comment]
Нет, другие сборки, в которых я подключаю VkNet, получаю объект, и использую Newtonsoft.Json.JsonConvert чтобы сериализовать уже в своем приложении

**Comment by inyutin-maxim** [comment]
ну это скорее тогда issue для [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json). наша либа тут не при делах

**Comment by CaCTuCaTu4ECKuu** [comment]
Может быть, а может и нет, тогда я посмотрю еще

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu проблема в атрибуте объекта [DataContract]

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu исходя из [теста](https://github.com/JamesNK/Newtonsoft.Json/blob/a0403492ad79398be8d97979acae00a2aca4dfdd/Src/Newtonsoft.Json.Tests/Documentation/Samples/Serializer/DataContractAndDataMember.cs) в сериализацию попадают поля с атрибутом [DataMember]

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu заменю все [DataContract] на

**Comment by CaCTuCaTu4ECKuu** [comment]
Так, а стоп, у меня рандомные обьекты которые я там у себя создаю они норм сериализуются, я чет не обратил внимания что там где-то есть этот аттрибут, но в любом случае я так понял если мне надо сериализовать VkNet объект в Json я могу заюзать Utilities.SerializeToJson и он сработает

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu подожди пока я выложу фикс, и собери для себя версию

**Comment by inyutin-maxim** [comment]
Utilities.SerializeToJson - это обертка над JsonConvert.SerializeObject

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу
