### ISSUE TITLE
Ошибка при выполнении некоторых действий с неподтверждённого пользователя

### ISSUE THREAD

**Issue by GooG2e** [vknet/vk#492]
Суть ошибки такова - в вк пользователя могут потребовать подтвердить свой телефон.
Эта проверка может вылезти и в апи т.е. при попытке написания чего-то на стену возвращается примерно вот такой json
`{
   "error" : {
      "error_code" : 17,
      "error_msg" : "Validation required: please open redirect_uri in browser",
      "redirect_uri" : "https://m.vk.com/activation?act=validate&api_hash=****&hash=****",
      "request_params" : [
         {
            "key" : "oauth",
            "value" : "1"
         },
         {
            "key" : "method",
            "value" : "wall.post"
         },
         {
            "key" : "owner_id",
            "value" : "-66666"
         },
         {
            "key" : "from_group",
            "value" : "1"
         },
         {
            "key" : "message",
            "value" : "Test"
         },
         {
            "key" : "v",
            "value" : "5.64"
         }
      ]
   }
}
`
Сейчас при получении такой ошибки происходит краш...

**Comment by inyutin-maxim** [comment]
@GooG2e Приведите код который приводит к крашу

**Comment by GooG2e** [comment]
```
            ApiAuthParams p = new ApiAuthParams();
            p.AccessToken = Properties.Settings.Default.vk_token;
            VkApi vk = new VkApi();
            vk.Authorize(p);
            WallPostParams wp = new WallPostParams();
            wp.OwnerId = -1 * 153877099;
            wp.FromGroup = true;

            wp.Message = "Test";
            wp.Signed = false;
            long post_id = vk.Wall.Post(wp);
```

**Comment by GooG2e** [comment]
Стек
`   в VkNet.Utils.VkResponse.get_Item(Object key)
   в VkNet.Exception.VkApiException..ctor(VkResponse response)
   в VkNet.Exception.NeedValidationException..ctor(VkResponse response)
   в VkNet.Utils.VkErrors.IfErrorThrowException(String json)
   в VkNet.VkApi.Invoke(String methodName, IDictionary`2 parameters, Boolean skipAuthorization)
   в VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization)
   в VkNet.Categories.WallCategory.Post(WallPostParams params)`

**Comment by inyutin-maxim** [comment]
@GooG2e Спасибо. Если у вас есть возможность поправить проблему будем рады пул реквесту, не знаю когда у меня появится свободное время на решение проблемы.

**Comment by GooG2e** [comment]
@inyutin-maxim  к сожалению на данный момент я даже толком не понимаю даже как запустить тесты в этом проекте(

**Comment by dvygolov** [comment]
Так вот здесь же этот вопрос решён! #374

**Comment by inyutin-maxim** [comment]
@GooG2e Попробуйте собрать из github и проверить возникновение данной ошибки

**Comment by inyutin-maxim** [comment]
@dvygolov Спасибо за участие в жизни проекта
