### ISSUE TITLE
.Net Core 2.0, Ubuntu 16.04, ошибка при аутентификации

### ISSUE THREAD

**Issue by Renerick** [vknet/vk#494]
При попытке входа на Ubuntu 16.04 выбрасывается ошибка
```
VkNet.Exception.VkApiAuthorizationException: Invalid authorization with login - password
   at VkNet.VkApi.Authorize(UInt64 appId, String emailOrPhone, String password, Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(UInt64 appId, String emailOrPhone, String password, Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey)
   at VkNet.VkApi.Authorize(ApiAuthParams params)
   at VKBot.Program.Main(String[] args) in /app/Program.cs:line 15
```

```csharp
  var vk = new VkApi();
  vk.Authorize(new ApiAuthParams()
  {
           Login = login,
           Password = password,
           ApplicationId = id,
           Settings = Settings.All,
           TwoFactorAuthorization = Console.ReadLine
  });

```

На компьютере с Windows 10 с теми же данными все работает нормально, аутентификация проходит успешно. 

Что интересно, при двухфакторной аутентификации в обоих случаях ВК присылает уведомление и код, но успешно войти удается только на Windows

**Comment by Renerick** [comment]
В общем, я занялся отладкой и обнаружил, что в методе RedirectTo ([WebCall.cs:130](https://github.com/vknet/vk/blob/df2d72c8c58038a380eae781b28562571a224d7b/VkNet.UWP/Utils/WebCall.cs#L130)) при выполнении  `call._request.GetAsync(url).Result` с `url`, содержащим `#access_token=token...`, ответы на разных системах. На Windows в свойство RequestMessage.RequestUri записывается полный Url с токеном, а на Ubuntu обрезается часть после символа #  (то есть токен). 

То есть в итоге в [`authorizationFormPostResult`](https://github.com/vknet/vk/blob/70164a53b68cc1aaf33ec7d64c8661597f637534/VkNet.UWP/Utils/Browser.cs#L190) свойство ResponceUrl содержит только `https://oauth.vk.com/blank.html`, в то время как на Windows это же свойство содержит полный Url с токеном

Windows:
![image](https://user-images.githubusercontent.com/20725046/32143657-27df51c2-bcc6-11e7-9385-40ad23b22e9e.png)

Ubuntu:
![image](https://user-images.githubusercontent.com/20725046/32143663-478aff9e-bcc6-11e7-9103-df8cef4ee8b6.png)

Не уверен, является это особенностью ВК или реализации .Net core

**Comment by CaCTuCaTu4ECKuu** [comment]
Я планирую полностью заменить эту часть. Я скопипастил и изменил здешний
WebCall и он у меня работает там, где VkNet падает

29 окт. 2017 г. 3:37 PM пользователь "Renerick" <notifications@github.com>
написал:

**Comment by b1tc0re** [comment]
Поделитесь вашим WebCall

**Comment by CaCTuCaTu4ECKuu** [comment]
@b1tc0re https://github.com/CaCTuCaTu4ECKuu/BasicWebCallLibrary

**Comment by inyutin-maxim** [comment]
@b1tc0re соберите из github поправил в https://github.com/vknet/vk/commit/d97efdd682d0779460821ca26e174726826de474

**Comment by CaCTuCaTu4ECKuu** [comment]
Просьба к тем, у кого возникает подобная ошибка, прислать дамп fiddler-а или какой-то трейс запросов к ВК. Возможно проблема из-за капчи при авторизации и нужно исходные данные чтобы отловить и обработать запрос капчи. Не забудьте стереть личные данные из дампа.

**Comment by SanteR1** [comment]
@CaCTuCaTu4ECKuu , @inyutin-maxim 
Заметил вот такую проблему c правами Settings.All, авторизация не проходит и выпадает ошибка при авторизации, как писал выше. Собрал последнюю сборку, ошибка "URI должен содержать токен!". С правами Wall авторизация например проходит, а со Status не проходит, НО!, если перед этим пройти авторизацию через сайт посредством ->
`https://oauth.vk.com/authorize?client_id=0000000&scope=ads,audio,docs,email,friends,groups,market,messages,notes,notifications,notify,pages,photos,stats,status,video,wall&redirect_uri=https://oauth.vk.com/blank.html&display=page&response_type=token/*строка скопирована из vknet и вот с такими полными правами ALL через браузер авторизация проходит и в ответ получаю токен*/`
Тогда например через VKNet проходит и авторизация с правами Wall | Status, но с All все равно не проходит через VKNet.

**Comment by inyutin-maxim** [comment]
@Renerick  добрый день. Всегда прохожу авторизацию с полными правами. ОС: kubuntu 16.04, dotnet core 2.0.0. Авторизация проходит успешно. Вопрос, при авторизации через браузер с полными правами отображалась ли у вас капча? и еще прошу собрать через фиддлер, весь процесс авторизации, с полными правами и отдельно Wall | Status, и выслать нам дамп  запросов. Не забудть в дампе подтереть логины и пароли. Спасибо.

@CaCTuCaTu4ECKuu Чтобы тебе копия письма упала

**Comment by SanteR1** [comment]
@inyutin-maxim , Капча через браузер не отображается, только ОС у меня Windows используется, dotnet 4.0

**Comment by SanteR1** [comment]
@inyutin-maxim, @CaCTuCaTu4ECKuu 
Выгрузил в текстовый, вроде везде заменил приватность :)
Первая авторизация нормально прошла, вторая ошибка - "URI должен содержать токен!"
[dump](https://gist.github.com/SanteR1/947ec1a50990edd8b93f538f4644723e)

**Comment by inyutin-maxim** [comment]
Kubuntu mono 5.4.1.6 dotnet40, авторизация полет нормальный

**Comment by inyutin-maxim** [comment]
@SanteR1 Windows 10 x64, dotnet framework 4.0, авторизация полет нормальный. Сложно воспроизвести пока что

**Comment by inyutin-maxim** [comment]
#511 @SanteR1 @Renerick @b1tc0re добавил логгер в класс авторизации. Приведите пожалуйста лог здесь

**Comment by Nelo-cool** [comment]
Windows 10, есть ошибка, сейчас соберу версию с джита и сброшу лог.

**Comment by Nelo-cool** [comment]
Я так понял NLog на консоль настроен. Вот вывод:
12:04:35 VkApi VkApi Initialization successfully
12:04:36 VkApi Старт авторизации
12:04:36 VkApi Шаг 1. Открытие диалога авторизации
12:04:37 VkApi Шаг 2. Заполнение формы логина
12:04:37 VkApi Проверка наличия двухфакторной авторизации
12:04:37 VkApi Запрос: https://oauth.vk.com/authorize?client_id=6303917&redirect_uri=https://oauth.vk.com/blank.html&response_type=token&scope=65536&v=&state=&display=page&__q_hash=e71c531ab793cae9b3ae981280da5d2f
12:04:37 VkApi Ответ: https://oauth.vk.com/authorize?client_id=6303917&redirect_uri=https://oauth.vk.com/blank.html&response_type=token&scope=65536&v=&state=&display=page&__q_hash=e71c531ab793cae9b3ae981280da5d2f

Это текст ошибки:
URI должен содержать токен!

**Comment by Nelo-cool** [comment]
ну если перейти по этой ссылке это будет запрос доступа приложения к акаунту.

**Comment by Nelo-cool** [comment]
После чего имеем уже успешный лог:
12:07:06 VkApi VkApi Initialization successfully
12:07:07 VkApi Старт авторизации
12:07:07 VkApi Шаг 1. Открытие диалога авторизации
12:07:07 VkApi Шаг 2. Заполнение формы логина
12:07:08 VkApi Запрос: https://oauth.vk.com/authorize?client_id=6303917&redirect_uri=https://oauth.vk.com/blank.html&response_type=token&scope=65536&v=&state=&display=page&__q_hash=f2fd6a015d635954f81259345a6b7d83
12:07:08 VkApi Завершение авторизации
12:07:08 VkApi Авторизация прошла успешно
12:07:08 VkApi Установка свойств токена
12:07:08 VkApi Авторизация прошла успешно

**Comment by Nelo-cool** [comment]
Но потом, при вызове метода Video имеем снова ошибку с токеном:)
User authorization failed: no access_token passed.

12:07:06 VkApi VkApi Initialization successfully
12:07:07 VkApi Старт авторизации
12:07:07 VkApi Шаг 1. Открытие диалога авторизации
12:07:07 VkApi Шаг 2. Заполнение формы логина
12:07:08 VkApi Запрос: https://oauth.vk.com/authorize?client_id=6303917&redirect_uri=https://oauth.vk.com/blank.html&response_type=token&scope=65536&v=&state=&display=page&__q_hash=f2fd6a015d635954f81259345a6b7d83
12:07:08 VkApi Завершение авторизации
12:07:08 VkApi Авторизация прошла успешно
12:07:08 VkApi Установка свойств токена
12:07:08 VkApi Авторизация прошла успешно
12:07:36 VkApi Вызов метода video.get, с параметрами videos=_456240736,v=5.69

**Comment by inyutin-maxim** [comment]
@Nelo-cool Спасибо за аналитику, Скажите а какие настройки вы используете?
![image](https://user-images.githubusercontent.com/1781005/34149481-516b8598-e4b6-11e7-9b2a-45b0edd22172.png)

**Comment by Nelo-cool** [comment]
Настройки при авторизации? Или где?

**Comment by inyutin-maxim** [comment]
@Nelo-cool да да, есть подозрение что вы не указали **Settings.Video** или **Settings.All**

**Comment by Nelo-cool** [comment]
Указал Settings.Offline :)

**Comment by Nelo-cool** [comment]
Если ставлю All ошибка не уходит даже если в ручную перейти по ссылке и подтвердить выдачу прав.

**Comment by inyutin-maxim** [comment]
Этого не достаточно)) для разных разделов нужен свой тип прав. Они указываются через **|**. Не могли бы вы показать логи для полных прав

**Comment by Nelo-cool** [comment]
Сейчас сделаю, просто у вас не флаговый энум сделан, я не допер.

**Comment by inyutin-maxim** [comment]
@Nelo-cool 
``` csharp
public static readonly Settings All = Notify | Friends | Photos | Audio | Video | Pages | Status | Notes | Messages | Wall | Ads | Documents | Groups | Notifications | Statistic | Email | Market;
```

**Comment by Nelo-cool** [comment]
![image](https://user-images.githubusercontent.com/902820/34149926-d82f4b0e-e4b7-11e7-902e-da470766eabe.png)

12:23:21 VkApi VkApi Initialization successfully
12:23:22 VkApi Старт авторизации
12:23:22 VkApi Шаг 1. Открытие диалога авторизации
12:23:22 VkApi Шаг 2. Заполнение формы логина
12:23:23 VkApi Проверка наличия двухфакторной авторизации
12:23:23 VkApi Запрос: https://oauth.vk.com/authorize?client_id=6303917&redirect_uri=https://oauth.vk.com/blank.html&response_type=token&scope=140491935&v=&state=&display=page&__q_hash=мойХэш
12:23:23 VkApi Ответ: https://oauth.vk.com/authorize?client_id=6303917&redirect_uri=https://oauth.vk.com/blank.html&response_type=token&scope=140491935&v=&state=&display=page&__q_hash=мой_хэш

Ну и после ошибка уже в catch вылетает:
Со стеком
   в VkNet.Utils.Browser.GetTokenUri(WebCallResult webCallResult) в VkNet\Utils\Browser.cs:строка 272
   в VkNet.Utils.Browser.EndAuthorize(WebCallResult result, IWebProxy webProxy) в C:\Users\VladimirKolyada.THISISLOGIC\Downloads\vk-master\VkNet\Utils\Browser.cs:строка 184
   в VkNet.Utils.Browser.Authorize(IApiAuthParams authParams) в VkNet\Utils\Browser.cs:строка 71
   в VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams) в VkApi.cs:строка 819
   в VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams) в VkApi.cs:строка 650
   в VkNet.VkApi.Authorize(IApiAuthParams params) в \VkNet\VkApi.cs:строка 385
   в VKApiTest.Program.Main(String[] args) в VKApiTest\Program.cs:строка 33

**Comment by inyutin-maxim** [comment]
@Nelo-cool А у аккаунта включена 2-хфакторная авторизация? Свяжитесь со мной в [телеграм](
https://t.me/inyutin_maxim)

**Comment by Nelo-cool** [comment]
Нет, не включена, в телеграмме решили вопросы. Возможно вечером починим.

**Comment by inyutin-maxim** [comment]
@Nelo-cool @Renerick @CaCTuCaTu4ECKuu @b1tc0re @SanteR1  добавлено к следующему релизу. Либо можете собрать сами из GitHub
