### ISSUE TITLE
Не работает Метод Account.LookupContacts

### ISSUE THREAD

**Issue by formusiclgl** [vknet/vk#495]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

- Класс и метод в котором возникла проблема:
Account.LookupContacts
- Пример кода для воспроизведения проблемы:

```csharp
  // Вставьте пример кода сюда
var vk = new VkApi();
            vk.Authorize(new ApiAuthParams
            {
                ApplicationId = 12345678,
                Login = "+1234567890",
                Password = "1234567890",
                Settings = Settings.Friends
            });
var lookupContacts = vk.Account.LookupContacts(new List<string> { "test@mail.ru" }, Services.Email);
```

- Если в примере не указаны конкретные значения параметров запроса укажите их здесь:

**Comment by inyutin-maxim** [comment]
@formusiclgl  Данный метод устарел и может быть отключён через некоторое время, пожалуйста, избегайте его использования.
Найденные пользователи могут быть также в дальнейшем получены методом friends.getSuggestions. 
На странице [документации ](https://vk.com/dev/account.lookupContacts) при юбом наборе параметров возвращает ошибку доступ запрещен
