### ISSUE TITLE
Метод .Docs.Add вместо CaptchaNeededException выбрасывает System.InvalidOperationException; Cannot access child value on Newtonsoft.Json.Linq.JValue

### ISSUE THREAD

**Issue by n0namer** [vknet/vk#496]
Использую версию 1.29.2

Ошибка похожа на эту https://github.com/vknet/vk/issues/89

В методе .Docs.Add не реализована обработка капчи

На скриншоте (из Fiddler 4) видно, как сервер в ответ присылает json со ссылкой на капчку и доп. инфой.

![image](https://user-images.githubusercontent.com/26526650/32740537-507844dc-c8b4-11e7-9110-b3ef0f184407.png)

**Comment by inyutin-maxim** [comment]
@n0namer добавил в метод Docs.Add поля для обработки капчи. Попробуйте собрать библиотеку и протестировать метод. Очень жду обратной связи

**Comment by n0namer** [comment]
Я зеленый совсем. Вы не подскажите, как мне грамотно подсунуть в packages скомпиленный проект? И как отдать ВК качпу. Я бы реализовал обработку, повторил ошибку и отписался вам.

**Comment by inyutin-maxim** [comment]
@n0namer Читайте внимательно пост выше. Я указал что реализовал поля для капчи. Не совсем понимаю что вы имеете ввиду под грамотно подсунуть в packages скомпиленный проект. Так же в nuget доступна свежая сборка от 03.12.2017

**Comment by inyutin-maxim** [comment]
#450 Дублирует
