### ISSUE TITLE
IsDeleted returns always null value

### ISSUE THREAD

**Issue by ilya-vas** [vknet/vk#50]
Метод message.IsDeleted всегда возвращает null, независимо от того, удалено сообщение или нет

**Comment by CaCTuCaTu4ECKuu** [comment]
Вы не могли бы еще раз проверить и сообщить осталась ли эта проблема?

**Comment by inyutin-maxim** [comment]
В актуальной версии API нет  метода message.IsDeleted. закрываю задачу.
