### ISSUE TITLE
Метод friends.getRequests возвращает новое поле count_unread. 

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#503]

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu кинь заявку в друзья чтобы запилить таску

**Comment by inyutin-maxim** [comment]
нужна помощь в реализации данного метода:
или у кого есть **непрочтенные** заявки в друзья пришлите результат со [страницы документации метода](https://vk.com/dev/friends.getRequests) (json с полем count_unread)

**Comment by inyutin-maxim** [comment]
@Skrims Для получения данного поля у аккаунта должно быть:
- Заявка в друзья. Ни в коем случае нельзя ее просматривать, иначе не сработает.
- Полагаю что нужно передать поле extended, возможно еще какие то

ps буду признателен если у вас получится

**Comment by Skrims** [comment]
На аккаунтах были как старые не просмотренные заявки, так и отсылал новые, использовал разные параметры. Увы, пока попытки безуспешны. Если все же получится отловить, отпишусь.

**Comment by inyutin-maxim** [comment]
https://vk.com/support?act=show&id=27456861

**Comment by inyutin-maxim** [comment]
Поправить GetRequestsExtended
