### ISSUE TITLE
Ошибка при установке пакетов

### ISSUE THREAD

**Issue by ShapeDev** [vknet/vk#509]
В общем у меня возникает такая проблема:

Install-Package : Не удалось установить пакет «VkNet 1.29.2». Вы пытаетесь установить этот пакет в проект, требуемая вер 
сия платформы которого — «native,Version=v0.0», но в пакете нет ссылок на сборки или файлов содержимого, совместимых с э 
той платформой. Дополнительную информацию можно получить у автора пакета. 

Появляется ошибка при установке ЛЮБОГО пакета NuGet. 
Пробовал гуглить, ничего не помогает.

**Comment by inyutin-maxim** [comment]
@ShapeDev Интересная у вас платформа в проекте, наша библиотека рассчитана под NET40 и Netstandard1.2. Сложно вам подсказать, нужно больше информации по проекту
