### ISSUE TITLE
Ошибка VkNet.Exception.VkApiException ("URI должен содержать токен!") на версии 1.29.4 при авторизации.

### ISSUE THREAD

**Issue by n0namer** [vknet/vk#511]
Обновился до версии 1.29.4 через nuget.

При использовании кода, указанного ниже, стала вылетать ошибка "VkNet.Exception.VkApiException; URI должен содержать токен!"

- Пример кода для воспроизведения проблемы:

```csharp
                    api.Authorize(new ApiAuthParams
                    {
                        ApplicationId = (ulong)appIds[i],
                        Login = emails[i],
                        Password = passwords[i],
                        Settings = Settings.All
                    });
```
На версии 1.29.3 работает без нареканий.

**Comment by vitalikdemko** [comment]
У меня та же проблема (

**Comment by inyutin-maxim** [comment]
@n0namer @vitalikdemko добавил логгер при авторизации, прошу собрать библиотеку и запустить в режиме отладки и показать лог при возникновении ошибки. Спасибо за содействие.

**Comment by inyutin-maxim** [comment]
@n0namer @vitalikdemko задачу закрываю, обсуждение прошу перенести в задачу #494 . Так как эта дублирует ее. Спасибо
