### ISSUE TITLE
Добавить глобальный параметр lang

### ISSUE THREAD

**Issue by BorisFX** [vknet/vk#512]
Предлагаю добавить глобальный параметр к запросам, для получения ответов, на выбранном языке, всего их 8.
ru (0) — русский,
ua (1) — украинский,
be (2) — белорусский,
en (3) — английский,
es (4) — испанский,
fi (5) — финский,
de (6) — немецкий,
it (7) — итальянский.
Пример: 
https://api.vk.com/database.getCountries?params[need_all]=1&params[count]=5&params[v]=5.69&lang=de в данном случае указываем язык немецкий.

**Comment by inyutin-maxim** [comment]
@BorisFX  добавлено к следующему релизу. Либо можете собрать сами из GitHub
