### ISSUE TITLE
vk.Video.Get(parameters) throw "User authorization failed: no access_token passed." exception

### ISSUE THREAD

**Issue by Nelo-cool** [vknet/vk#516]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

- Класс и метод в котором возникла проблема:
vk.Video.Get(parameters) 
- Пример кода для воспроизведения проблемы:

```csharp
public static void Main(string[] args)
        {
            var appID =ul;                      // ID приложения
            var email = "";         // email или телефон
            var pass = "";               // пароль для авторизации
            var scope = Settings.All | Settings.Offline;      // Приложение имеет доступ к друзьям

            var vk = new VkApi();

            try
            {
                var autorizeParams = new ApiAuthParams
                {
                    ApplicationId = appID,
                    Login = email,
                    Password = pass,
                    Settings = scope,
                };

                vk.Authorize(autorizeParams);

                var parameters = new VideoGetParams()
                {
                    Videos = new[] { new Video() { OwnerId = -101685153, Id = 456240736 } }
                };

                var videos = vk.Video.Get(parameters);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

            Console.ReadKey();
        }
```

- Если в примере не указаны конкретные значения параметров запроса укажите их здесь:
![image](https://user-images.githubusercontent.com/902820/34153794-5aeb0ebe-e4c4-11e7-9c00-f9a2bf1a4a01.png)

![image](https://user-images.githubusercontent.com/902820/34153762-4266414c-e4c4-11e7-83cb-9afeef54465d.png)

- PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/vknet/vk?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by inyutin-maxim** [comment]
@Nelo-cool Добавлено к следующему релизу
