### ISSUE TITLE
Не работают ForwardMessages

### ISSUE THREAD

**Issue by Blood13** [vknet/vk#517]
MessagesSendParams.ForwardMessages. При отправке сообщения с заполненным свойством ForwardMessages в сообщении, которое приходит пользователю, нет пересылаемых сообщений. При этом если заполнить свойство Text, то текст сообщения отображается (пересылаемых сообщений всё так же нет).

**Comment by inyutin-maxim** [comment]
@Blood13 https://vk.com/dev/messages.send
Проверьте пожалуйста здесь, и отпишитесь получилось ли у вас напрямую из API. Спасибо

**Comment by inyutin-maxim** [comment]
странно, у меня работает. Собирал из github, но это не должно иметь значения, для разбора конкретной ситуации пишите в [телеграмм](https://t.me/joinchat/CHFCHxHqca0waHIe3-Fuqg)
``` csharp
var result = api.Messages.Send(new MessagesSendParams
            {
                ForwardMessages = new long[]{211000},
                Message = "не обращай внимания, для тестирования",
                PeerId = 442461000
            });
```
