### ISSUE TITLE
Ошибка обработки исключений

### ISSUE THREAD

**Issue by Xambey** [vknet/vk#519]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

- Класс и метод в котором возникла проблема:
VkApiException
- Пример кода для воспроизведения проблемы:
var sVideo = api.Video.Save(new VideoSaveParams()
                                {
                                    Name = item.Value.Snippet.Title,
                                    Link = $"https://www.youtube.com/watch?v={item.Key}",
                                    Wallpost = false,
                                    GroupId = int.Parse(channel.VkGroupId) // Почему здесь требуют положительный ID, а в других со знаком - ? Бред какой-то (хоть и в vk api они прописаны отрицательными)
                                });
                                api.Wall.Post(new WallPostParams() // Падает внутри
                                {
                                    FromGroup = true,
                                    OwnerId = -(int.Parse(channel.VkGroupId)),
                                    Message = "Test", // Если не заполнить - исключение вылетает
                                    Attachments = new List<MediaAttachment>()
                                    {
                                        sVideo
                                    }
                                });
```csharp
 		/// <summary>
		/// Инициализирует новый экземпляр класса VkApiException
		/// </summary>
		/// <param name="response">Ответ от сервера vk</param>
		// Token: 0x060012DB RID: 4827 RVA: 0x0001DCC6 File Offset: 0x0001BEC6
		public VkApiException(VkResponse response) : base(response["error_msg"])
		{ // Пытается распарсить JSON и валиться, на error_msg.  Строка приходит уже с ESC последовательностью. Я проследил до сюда, статус 214, доступ запрещен, больше 50 постов за день. (тестил в группе). 
			this.ErrorCode = response["error_code"];
		}
```
"   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)\n   at VkNet.Utils.VkResponse.get_Item(Object key)\n   at VkNet.Exception.VkApiException..ctor(VkResponse response)\n   at VkNet.Exception.PostLimitException..ctor(VkResponse response)\n   at VkNet.Utils.VkErrors.IfErrorThrowException(String json)\n   at VkNet.VkApi.Invoke(String methodName, IDictionary`2 parameters, Boolean skipAuthorization)\n   at VkNet.VkApi.Call(String methodName, VkParameters parameters, Boolean skipAuthorization)\n   at VkNet.Categories.WallCategory.Post(WallPostParams params)\n   at YtToVkReposter.YtReposter.HandlerRepostMessage(Object state) in /home/xambey/GitHub/YtToVkReposter/YtToVkReposter/YtToVkReposter/YtReposter.cs:line 279"
Не возможно получить доступ к ребенку в json при парсинге
(not allowed to child json)

И чисто из любопытства вопрос: планируется вообще сделать более нормальную обработку ссылок на видео? Мне кажется не совсем нормальным, что приходиться в ручную грузить фотографии с того же ютуб при загрузке видео в ваше хранилище. Чтобы в последствие еще одним запросом создавать post. + в Post запросе с attachments нельзя опустить Message, как написано. Выкидывает исключение о не валидности Message

Пожелания: было бы неплохо зашить загрузку видео внутри метода создания поста с вложениями. Чтобы в attacments добавлять видео, фото и тп. А внутри, что нужно, автоматически загружалось и тп.

**Comment by inyutin-maxim** [comment]
@Xambey А что vk возвращает в ответе? есть подозрение что не возвращается какое то обязательное поле, и нужно бы сделать его необязательным

**Comment by Xambey** [comment]
@inyutin-maxim Сначала о том, что я сделал. Я таки разобрался и сделал, как хотел. Хотя меня и жутко бесит, что требуется отдельно загружать видео либо к юзеру, либо в группу прежде чем добавить видео на стену. Теперь об ответе: Его нету. Вылетает Exception о невозможности парсинга json сообщения об ошибке внутри VkApiException. (см код). Сообщение для парсинга там (дословно не помню). вроде "Доступ запрещен. Лимит в 50 постов за сутки превышен" (на Eng), вот это сообщение приходит с ESC последовательностями внутри и оно не может быть распарсено. Хз как у вас это тесты прошло

**Comment by inyutin-maxim** [comment]
@Xambey  Ответ кроется в вашем же описании, это ограничение самого вк, к библиотеке отношения не имеет, наша библиотека по большому счету представляет из себя объектную модель, мы являемся сторонними разработчиками и напрямую отношения к вк не имеем, и еще философия библиотеки реализовать апи самого вк, если вам нужно облегчить какой то процесс реализуйте вспомогательные методы, вы можете предложить свои изменения и если с ними все ок, они войдут в библиотеку. спасибо

**Comment by Xambey** [comment]
@inyutin-maxim баг с VkApiException вы надеюсь закроете?)

**Comment by inyutin-maxim** [comment]
@Xambey закроем, если вас не затруднит, пришлите ответ на запрос от вк когда падает ошибка. Например дамп фидлера, меня интересует сам json

**Comment by Xambey** [comment]
@inyutin-maxim это проблема...(Времени сейчас нет писать тест с отдельными данными для авторизации) Чтобы получить этот баг, нужно превысить число постов за сутки в группе и тогда при след. Post запросе вылетит этот Exception. Отловить можно, как я уже написал, через какой-нибудь десериализатор. Путь -> Post -> vk.Call -> this.Invoke -> VkErrors.IfErrorThrowException(answer); => case 214 PostLimitException -> VkApiException -> конструктор с (VkResponse response) -> Ошибка
