### ISSUE TITLE
vk net net framework 3.5

### ISSUE THREAD

**Issue by DC4-SERGEY** [vknet/vk#520]
Добрый день - поделитесь vk net под net framework 3.5.
С nuget.org не качает версию 1.0.12
![image](https://user-images.githubusercontent.com/32691168/34647361-f01f21c4-f391-11e7-85dd-e50e2d115fbc.png)
![image](https://user-images.githubusercontent.com/32691168/34647362-f7513d42-f391-11e7-9aae-ae2a17956abd.png)

**Comment by inyutin-maxim** [comment]
@DC4-SERGEY вы можете сделать форк библиотеки, откатить изменения до времени когда вышла библиотека нужной вам версии и подключить в решение проект. К сожалению мы больше не поддерживаем .NET 3.5
