### ISSUE TITLE
Group не имеет поля member_status

### ISSUE THREAD

**Issue by sashok2k** [vknet/vk#536]
Group не имеет поля member_status - невозможно определить будет ли пользователь участвовать в событии

**Comment by inyutin-maxim** [comment]
@sashok2k https://github.com/vknet/vk/blob/014d86bd2a41ef1ddb1710d1a56ef085b41e2f4f/VkNet/Model/Group/Group.cs#L232

**Comment by inyutin-maxim** [comment]
@sashok2k но частично вы правы, поле не сериализовалось, поправлено и добавлено к следующему релизу
