### ISSUE TITLE
SaveWallPhoto имеет обязательный параметр, который является необязательным

### ISSUE THREAD

**Issue by HEYHEYHEEEEY** [vknet/vk#538]
Всем привет.
Есть метод https://vknet.github.io/vk/photos/saveWallPhoto/ . У него есть два параметра для определения, на какую стену постить: user_id и group_id. Только одно из этих двух значений может быть применено. Раньше для постинга на стенку я user_id задавал как null, теперь этого сделать нельзя, так как переменную сделали обязательной. Видимо, я неправильно работаю с этим параметром после новой версии, как теперь его использовать?

**Comment by inyutin-maxim** [comment]
@HEYHEYHEEEEY Вы правы, баг

**Comment by inyutin-maxim** [comment]
@HEYHEYHEEEEY Исправлено и добавлено к следующему релизу
