### ISSUE TITLE
В классе ProfileFields отсутствует поле Photo_id 

### ISSUE THREAD

**Issue by GerLord** [vknet/vk#539]
- Класс и метод в котором возникла проблема:

В классе **ProfileFields** отсутствует поле Photo_id и соответственно методы user.get, user.search и т.п. не могут вернуть Photo_id, хотя в классе user имеется поле photo_id. Попытка вызвать ProfileFields.All не решает проблему, поле Photo_id так и остаётся пустое.

**Comment by GerLord** [comment]
Скорее всего, надо будет и **запросы обновить**, а так же приходящий **json** при распарсивании, что бы передать _Photo_Id_ в _User_

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу
