### ISSUE TITLE
Message = "Удаленный сервер возвратил ошибку: (401) Несанкционированный."

### ISSUE THREAD

**Issue by nihau** [vknet/vk#54]
Authorize выдает исключение при некоторых настройках (Messages, All например), но работает при Friends. 
Скорее всего вообще не работают личные сообщения. Ни в какую не хочет ни отправлять, ни получать,  Попадает в VkNet.Utils.VkErrors.IfErrorThrowException(string json) с error_code №20.

**Comment by CaCTuCaTu4ECKuu** [comment]
Ошибка еще есть?
