### ISSUE TITLE
Изменение типа Group Id?

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#549]
Вопрос и предложение всем, кого это касается.
VkNet.Model.Group имеет id <long> тогда как методы для работы с Model.CallbackServerItem (GroupCategory.GetCallbackServers, AddCallbackServer) требует тип группы ulong.
Что и к какому какому типу привести?

По хорошему нyжно Group.Id к ulong но много менять так что я просто в методы выставлю long и буду проверять на неотрицательное значение, если никто другой не воодушевится

**Comment by CaCTuCaTu4ECKuu** [comment]
Также заметил, что методы AddCallbackServer возвращают тип Id сервера long, а методы вроде GetCallbackServers принимают список ulong id серверов

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu Нужно выделить время и по переписать, это все в основном невнимательность наверное

**Comment by superkeka** [comment]
Groups.GetById() 
Вообще принимает Id в виде IEnumerable<string> первым параметром и string - вторым. Можно было бы разделить методы или перегрузку сделать.

**Comment by Panuchi** [comment]
> Groups.GetById()
> Вообще принимает Id в виде IEnumerable первым параметром и string - вторым. Можно было бы разделить методы или перегрузку сделать.

Потому что там метод может принимать короткое имя сообщества либо идентификатор

**Comment by ghost** [comment]
Уже кто-то переписал.
