### ISSUE TITLE
CaptchaNeededException

### ISSUE THREAD

**Issue by SkyQuant** [vknet/vk#55]
Как ввести капчу при отправке сообщения методом Messages.Send? Что удивительно, на локальной машине в тестах метод работает нормально, а тот же самый код на сервере выдаёт исключение: Exception of type 'VkNet.Exception.CaptchaNeededException' was thrown.

**Comment by CaCTuCaTu4ECKuu** [comment]
@azhidkov а есть что-то встроенное для получения сразу изображения в виде byte[] или Bitmap?
С капчей можно разобраться через тот же AntiGate
Я вот только не нашел как VK само изображение можно получить (то есть загрузить с сервера ВК)? Он отслеживает заголовки и кукисы при переходе по url или можно через HttpWebRequest или через сокеты прочитать поток не вводя никаких данных?

**Comment by CaCTuCaTu4ECKuu** [comment]
Что с проблемой? Все еще актуальна?

**Comment by Dramacydal** [comment]
капчу если кому интересно, скачивал так
```
            var client = new WebClient();
            var image = Image.FromStream(new MemoryStream(client.DownloadData(url)));
            captchaPictureBox.Image = image;
```
ну а обрабатывал так
```
                        long? captcha_sid = null;
                        string captcha_key = null;
                        for (; ; )
                        {
                            try
                            {
                                rtt = api.Docs.Save(file, tmpFileName, null, captcha_sid, captcha_key);
                            }
                            catch (CaptchaNeededException ex)
                            {
                                captcha_sid = ex.Sid;
                                var form = new CaptchaForm(ex.Img);
                                form.ShowDialog();
                                captcha_key = form.CaptchaKey;
                                continue;
                            }
                            break;
                        }
```

**Comment by SkyQuant** [comment]
актуальна

**Comment by CaCTuCaTu4ECKuu** [comment]
Создайте новую тему, я здесь уже ничего не понимаю и с самого начала не понимал что вообще за проблема, потому что у меня на рабочем проекте все как нужно работает

**Comment by SkyQuant** [comment]
> уже ничего не понимаю и с самого начала не понимал что вообще за проблема
Аналогично! Не понимаю, по какому алгоритму в одних случаях капча запрашивается, а в других нет. В тесте на клиенте всё ок, а на сервере вылетает исключение. Проблема поднималась уже дважды, зачем третью ветку плодить?

**Comment by CaCTuCaTu4ECKuu** [comment]
Ладно, пойдем по другому. В каких случаях капча должна быть, а ее нет? Вы можете показать код? Вы уверены что капча вообще пришла? Что показывает анализатор траффика? Вы Вуди не работаете вслепую, вы проверяете через анализатор работу своей программы?

**Comment by SkyQuant** [comment]
> В каких случаях капча должна быть, а ее нет?

Это ко мне вопрос?..
Мне на сервере ловить баги нелегко. Но в лог удалось вывести такое сообщение 
```Exception of type 'VkNet.Exception.CaptchaNeededException' was thrown```
Точно такой же код на локальной машине работает исправно, без запроса капчей. И подразумеваю, что автор фреймворка знает логику работы VK API.

**Comment by CaCTuCaTu4ECKuu** [comment]
А вы знаете для чего нужен Exception и как с ним работать? У вас в коде он обработан как то?

**Comment by SkyQuant** [comment]
Я так понимаю из исключения надо выцепить картинку и руками ввести то, что там нацарапано.

**Comment by CaCTuCaTu4ECKuu** [comment]
Господи, да вам же уже приводили пример кода полноценный, причём я, кажется, тоже отписывался. Все правильно, у вас просит капчу, вы никак эту просьбу не обрабатываете, программа виснет. Проблема то в чем?

**Comment by azhidkov** [comment]
Да, вы правильно понимаете. В исключение передается ссылка на картинку и её
идентификатор. Вам нужно как-то получить картинку (например, скачать её), и
заново вызвать метод, который выбросил исключение, передав идентификатор
капчи и её распознанное значение.

2015-06-23 10:30 GMT+03:00 SkyQuant <notifications@github.com>:

**Comment by CaCTuCaTu4ECKuu** [comment]
Исключение возвращает id капчи и ссылку сразу дает по которой можно капчу скачать

**Comment by SkyQuant** [comment]
> Проблема то в чем?

Во первых, непонятно точные причины запроса капчи, в каких случаях. В общем всё написано
Во вторых проблема актуальна в плане автоматизации. Я не контролирую ввод капчи пользователями.

**Comment by CaCTuCaTu4ECKuu** [comment]
Причина, по которой просит капчу, это правила сайта. Я почти уверен что автоматизация ваша связана именно с этим. Точная информация касательно безопасности ВК не оглашается нигде, но из опыта можно узнать. По секрета скажу что если вы занимаетесь этим то ответы на такие вопросы уже должны быть иначе вы не преуспеете. Я ответил на вопрос?

**Comment by SkyQuant** [comment]
пусть будет да

**Comment by CaCTuCaTu4ECKuu** [comment]
Капчу запрашивает при подозрительной активности стоаницы. VkNet это просто порт API. По поводу того как обработать капчу вам ответили, вопросы автоматизации работы с ВК это немного не сюда. Если вы пишите программу не нарушающую правила сайта то все впорядке - просто обрабатывайте капчу, но если нарушающую то я бы не советовал использовать апи впринципе - у вас все аккаунты привяжутся к приложению и забанят все и сразу
