### ISSUE TITLE
Указать короткий адрес пользователя в Users.Get

### ISSUE THREAD

**Issue by abigailstain** [vknet/vk#551]
Исходя из документации вк (https://vk.com/dev/users.get) в данном методе в параметре user_ids можно указать string, т.е. короткий адрес пользователя, там же и обычный числовой id.
В VkNet же в методе есть только long коллекция и короткий адрес вставить в неё невозможно.

**Comment by inyutin-maxim** [comment]
https://github.com/vknet/vk/blob/ef9924aaa416a1b882fe867172a4f8ebb577ef4b/VkNet/Abstractions/IUsersCategory.cs#L67
