### ISSUE TITLE
CanWritePrivateMessage всегда возвращает false

### ISSUE THREAD

**Issue by abigailstain** [vknet/vk#552]
var p = patterns.vknet.Users.Get(new List<string> { x.ToString() }); 

if (p[0].CanWritePrivateMessage) 
{ 
//if никогда не выполняется
}

Проверить можно на этом пользователе:  33603603
Но лучше проверять на тех, кто есть у тебя в друзьях, но у которых закрыто ЛС.

**Comment by inyutin-maxim** [comment]
@abigailstain Во первых Вы не передаете в параметры fields поле can_write_private_message
Проверил на странице документации указанного вами пользователя с указанием нужного параметра, вот ответ:
``` json
{
	"response": [{
		"id": 33603603,
		"first_name": "Данил",
		"last_name": "Кашин",
		"can_write_private_message": 0
	}]
}
```

**Comment by inyutin-maxim** [comment]
Обработка данного поля включена в классе:
https://github.com/vknet/vk/blob/ef9924aaa416a1b882fe867172a4f8ebb577ef4b/VkNet/Model/User.cs#L575
В данном случае проблема в том что вы поле не запрашиваете и вам возвращается значение по умолчанию
