### ISSUE TITLE
Конструкция  try cath не сробатывает при ловли капчи авторизации 

### ISSUE THREAD

**Issue by danila2002** [vknet/vk#553]
Есть код:

private void login_Click(object sender, EventArgs e)
        {

            label3.Show();
            if (textBox1.Text == "" || textBox2.Text == "")
                MessageBox.Show("Все поля должны быть заполненны");
            
            else
            {
                try
                {
                    string captchaKey = "";
                    
                    
                    
                        vkApi.Authorize( new ApiAuthParams
                        {
                            Login = textBox1.Text,
                            Password = textBox2.Text,
                            ApplicationId = 6362xxxxx,
                            Settings = Settings.All,
                            CaptchaKey = captchaKey,
                          
                            
                        });
                    
                }
                
                catch  (VkNet.Exception.CaptchaNeededException cap)
                {
                    pictureBox1.Show();

                    string captchaUrl = cap.Img.ToString();
                    
                    pictureBox1.ImageLocation = captchaUrl;
                    string captchaKey = textBox23.Text;
                }
Но  программа всеравно возвращает ошибку ввода капчи игнорируя блок  try cath. такое ошушение что как будто я   ловлю  другой тип ошибки.

**Comment by inyutin-maxim** [comment]
3840354320099fd818c514c9cdb94d289dd4cd47
