### ISSUE TITLE
Проблема при установке VK Net из Nuget

### ISSUE THREAD

**Issue by HEYHEYHEEEEY** [vknet/vk#557]
К сожалению, не смог найти в интернете справку об этой ошибке.

> Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
> Ошибка		Не удалось найти версию «NLog», совместимую с 'VkNet 1.31.0 ограничение: NLog (>= 4.5.0-rc03)'.			0	
> 
Попробовал установить последнюю версию NLog из Nuget, далее пошёл устанавливать vk net, но получил такую ошибку:

> Серьезность	Код	Описание	Проект	Файл	Строка	Состояние подавления
> Ошибка		Не удается разрешить зависимости. «NLog 4.4.12» не совместима с 'VkNet 1.31.0 ограничение: NLog (>= 4.5.0-rc03)'.			0	
>

**Comment by inyutin-maxim** [comment]
@HEYHEYHEEEEY Включаешь в nuget пререлиз, и ставишь сначала NLog (>= 4.5.0-rc03), а затем VkNet
