### ISSUE TITLE
Добавить асинхронный двухфакторный вход

### ISSUE THREAD

**Issue by LiptonDev** [vknet/vk#558]
Есть 2 метода авторизации: AuthorizeAsync и Authorize.
Почему в AuthorizeAsync нету возможности ввода двухфакторного кода асинхронно?
```c#
await API.AuthorizeAsync(new ApiAuthParamsAsync
{
	ApplicationId = AppID,
	Login = Login,
	Password = Password,
	Settings = Settings.Wall | Settings.Offline,
	TwoFactorAuthorizationAsync = GetCode
});

...

Task<string> GetCode() { .... }
```

**Comment by inyutin-maxim** [comment]
@LiptonOlolo Я долго думал, а для чего? асинхронность ради асинхронности? я считаю эта операцию должна быть синхронной

**Comment by LiptonOlolo** [comment]
@inyutin-maxim Ну смотри, есть, например, **ТОЛЬКО** асинхронная функция для, например, диалогового окна, в который я буду просить вводить человека код, но проблема в том, что если я запущу его синхронно (т.е. в конце добавлю .Result), то окно даже не появится, а вся форма попросту повиснет.
Это нужно.

**Comment by inyutin-maxim** [comment]
@LiptonOlolo Мы открыты к пулл реквестам, я не знаю когда у меня появится время разобраться.

**Comment by ghost** [comment]
```

var api = new VkApi();
await api.AuthorizeAsync(new ApiAuthParams
{
	ApplicationId = 3453535,
	Login = "",
	Password = "",
	Settings = Settings.All,
	TwoFactorAuthorizationAsync = GetCode()
});
	

private static async Task<string> GetCode()
{
	Console.WriteLine("Enter Code:");
	return Console.ReadLine();
}
```

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
