### ISSUE TITLE
Wall.Get выбрасывает ArgumentException

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#56]
>"Отрицательное значение.\r\nИмя параметра: count"

> в VkNet.Utils.VkErrors.ThrowIfNumberIsNegative(Expression`1 expr) в d:\vs projects\gt\vk\VkNet\Utils\VkErrors.cs:строка 39
>   в VkNet.Categories.WallCategory.Get(Int64 ownerId, Int32& totalCount, Nullable`1 count, Nullable`1 offset, WallFilter filter) в d:\vs-projects\gt\vk\VkNet\Categories\WallCategory.cs:строка 47

У меня возникло так:
* Пустая стена в группе, я получаю стену
* Пишу что-то на стену, загружаю
* Удаляю запись, пишу новую - исключение

Если проще, то когда я с периодичностью загружаю посты из стены одной и той же группы, то после удаления всех постов и написания новых при загрузке выскакивает ошибка

Пока только разбираюсь в вашей библиотеке, помочь с решением не смогу
Тестировал не все сценарии, может еще как-то вылезет ошибка

**Comment by azhidkov** [comment]
В данном случае срабатывает проверка, что ```count``` не может быть отрицательным. Возможно он также срабатывает и при нуле, это я проверю. Проверьте еще у себя почему у вас получается отрицательный ```count```.
