### ISSUE TITLE
Can not convert String to Int64.

### ISSUE THREAD

**Issue by SkyQuant** [vknet/vk#57]
Ошибка конвертации возникает когда ищу юзеров с параметром ```ProfileFields.All```. Если что-то конкретное указываю в перечислении, например ProfileFields.City, то исключения нет. При этом в Debug Trace данные есть, список юзеров возвращается. Кстати, можно по-подробнее, как их извлечь в переменную из 'response'. Будет как запасной вариант. Со строками не очень  понял:
            //string prettyUrl = Utilities.PreetyPrintApiUrl(url);
            //string prettyJson = Utilities.PreetyPrintJson(answer);

**Comment by azhidkov** [comment]
Посмотрю, как будет возможность. 
> Кстати, можно по-подробнее, как их извлечь в переменную из 'response'
В PrettyPrintJson к ответу от сервера вконтакте (в json формате) добавлятся строка ```const string json = <форматированный_json_от_вконткате>;``` это было сделано для более удобного создания юнит-тестов.

Соответственно вы можете воспользоваться двумя способами. Либо закомментировать три строчки в методе Utilities.PreetyPrintJson (файл https://github.com/vknet/vk/blob/master/VkNet/Utils/Utilities.cs).
Либо, **более предпочтительнее**, воспользоваться методом **Invoke** указав имя метода на сервере ВК и необходимые параметры. Этот метод специально создавался для прямого вызова методов которые еще не реализованы в библиотеки (ну или если реализованные косячат). Пример:
```csharp
var vk = new VkNet();
vk.Authorize(...);

// вызывем напрямую методы поиска пользователей, детали см. https://vk.com/dev/users.search
var parameters = new VkParameters();
parameters.Add("q", "паша дуров"); // ищем всех паш дуровых
parameters.Add("count", 20); // выбираем 20 записей
parameters.Add("offset", 3); // начиная с третьей

string users = vk.Invoke("users.search", parameters); // вызываем метод users.search с заданными параметрами поиска

// в users ответ от сервера ВК в формате json
// далее можно использоваться Json.NET для его разбора
```
Код писал сходу, надеюсь нигде не ошибся.

**Comment by SkyQuant** [comment]
Ага, спасибо, что-то приходит. А есть ли готовый тип для десериализации, чтоб не ```BirthDate``` из User.cs, а ```bdate``` спарсить?

**Comment by SkyQuant** [comment]
И ещё вопрос, в инструкции указано ```fields - Перечисленные через запятую поля анкет, необходимые для получения.``` Это как нужно перечислять элементы?

**Comment by SkyQuant** [comment]
А что-то в таком духе нельзя получить?
```
            VkResponseArray response = _vk.Call("users.search", parameters);
            var users = response[1];
```

**Comment by CaCTuCaTu4ECKuu** [comment]
А есть предположения почему эта ошибка то появляется, то ее нет? Это из-за сервера ВК или какая-то другая причина? У меня один и тот же код работает сутками и бывает сразу после запуска, бывает через время начинает появляться эта ошибка, причем почти всегда если не перезапустить все то усугубляется и она появляется все чаще и чаще.

**Comment by azhidkov** [comment]
> А есть ли готовый тип для десериализации, чтоб не BirthDate из User.cs, а bdate спарсить?

К сожалению нет, но можно создать свой класс со свойствами и попробовать десериализовать в него. Метод Invoke как раз подразумевает, что определенный функционал еще не реализован и вам придется сделать разбор json'a самим. 

> Это как нужно перечислять элементы?

Вы можете просто добавить коллекцию в VkParameters. Например так:
```csharp
var ids = new List<int>{1, 2, 3};
var parameters = new VkParameters();
parameters.Add("fields", ids); // в ids будет "1, 2, 3"
```

> А что-то в таком духе нельзя получить?

В этом случае вы получите объект класса VkResponse. Этот тип явно приводится к другим типам библиотеки например, User, Attachment (детали см. https://github.com/vknet/vk/blob/master/VkNet/Utils/VkResponseToModelCastsGenerator.cs). Поэтому, чтобы это заработало вам нужно явно указать к какому классу и как преобазовать VkResponse

**Comment by SkyQuant** [comment]
У меня тоже получалось периодически. Первые пять вызовов нормально прошли, потом всё, ошибка. Поэтому хочу разные параметры перепробовать вместо ProfileFields.All. Вопрос только как их комбинировать, что-то типа 
```
var fielsd = ProfileFields.BirthDate + ProfileFields.City + ProfileFields.Universities;
```

**Comment by azhidkov** [comment]
> А есть предположения почему эта ошибка то появляется, то ее нет?

Различные версии ВК апи возвращают результат в различном формаете. И скорее всего, проблема в идентификаторе, иногда он приходит как число, а иногда как строка. @CaCTuCaTu4ECKuu данное поведение возникают при вызове одного и того же метода, или разных?

**Comment by azhidkov** [comment]
> Вопрос только как их комбинировать
Вы можете объединить их так:
```csharp
var fields = ProfileFields.BirthDate | ProfileFields.City | ProfileFields.Universities;

```

**Comment by azhidkov** [comment]
> Первые пять вызовов нормально прошли, потом всё, ошибка.

Ошибка возникает если пять раз подряд вызывать метод Users.Search, правильно понял?

**Comment by CaCTuCaTu4ECKuu** [comment]
>Различные версии ВК апи возвращают результат в различном формаете. И скорее всего, проблема в идентификаторе, иногда он приходит как число, а иногда как строка. @CaCTuCaTu4ECKuu данное поведение возникают при вызове одного и того же метода, или разных?

Я с периодичностью определенной загружаю последние записи из стен различных сообществ (проверка новых постов). Предсказать эту ошибку я не могу, но фактически из-за нее мне приходиться заново вызывать метод (а на них ограничение 3 запроса в сек.). Проблема с идентификатором на стороне сервера или уже при разборе и ее можно исправить?

**Comment by SkyQuant** [comment]
> Ошибка возникает если пять раз подряд вызывать метод Users.Search, правильно понял?
Всё-таки было нормально пока я не стал использовать ProfileFields.All, вспомнил.
Ошибка конвертации указывает куда-то сюда:
```
public static implicit operator long?(VkResponse response)
		{
			return response != null ? (long?)response._token : null;
		}
```

**Comment by SkyQuant** [comment]
У меня такое ощущение, что не возвращаются поля City и RelationPartner.
И ещё вопрос, как передать расширенный список запросов, включающий не только возвращаемые поля, но и дату рождения, пол, вроде этого для Invoke:
```
            var parameters = new VkParameters
            {
                {"sex", 1},
                {"birth_day", 5},
                {"birth_month", 12},
                {"birth_year", 1995},
                {"fields", "nickname, screen_name, sex, bdate"},
            };
```

**Comment by azhidkov** [comment]
> Проблема с идентификатором на стороне сервера или уже при разборе и ее можно исправить?

А это та же самая ошибка, что и здесь https://github.com/vknet/vk/issues/56 ?

**Comment by azhidkov** [comment]
> И ещё вопрос, как передать расширенный список запросов, включающий не только возвращаемые поля, но и дату рождения, пол

Вы вроде всё правильно указали, возможно только нужно убрать пробелы после запятых. Но в этом не уверен. Весь список пареметров здесь https://vk.com/dev/fields

**Comment by SkyQuant** [comment]
Я, на самом деле, имел ввиду этот метод
```
var users = vk.Users.Search("Masha Ivanova", out count, fields, 100);
```
Кроме того, что мне нужна Маша, как я могу уточнить запрос? Получить список Маш исключительно женского пола :-)

**Comment by CaCTuCaTu4ECKuu** [comment]
> А это та же самая ошибка, что и здесь #56 ?

@azhidkov Да, это она

**Comment by CaCTuCaTu4ECKuu** [comment]
У меня все исключения, связанные с этой ошибкой вызываются в Newtonsoft.Json.Linq
Вот еще один появился и я не могу понять даже откуда он. "response" не null , значение _token тоже присутствует
![default](https://cloud.githubusercontent.com/assets/8963134/6201594/54eff7e6-b4c4-11e4-95fd-b4bfefe1e462.PNG)

**Comment by azhidkov** [comment]
>Кроме того, что мне нужна Маша, как я могу уточнить запрос? 

Преподалагаю, нужно задать параметр sex = 1 (1 - female, 2 - male, 0 -  not specified) когда вы заполняете объект ```VkParameters```.

**Comment by SkyQuant** [comment]
Это понятно. Вопрос только как и куда писать.

**Comment by azhidkov** [comment]
> У меня все исключения, связанные с этой ошибкой вызываются в Newtonsoft.Json.Linq

@CaCTuCaTu4ECKuu ошибки такого вида "что-то не может быть приведено к типу" указывают на этот метод (что на скриншоте), но реальную причину здесь не узнаешь, нужно смотреть что было ранее в Stack Trace. Причина ошибки будет в методе ***FromJson*** там можно посмотреть при разборе какого имеено свойства возникает ошибка и самое главное посмотреть что пытаются  в него присвоить.

**Comment by azhidkov** [comment]
@SkyQuant а пришлите код который вы используете сюда или мне на почту anton.v.zhidkov тузик гмейл.ком, я посмотрю детальнее.

**Comment by SkyQuant** [comment]
Ну я на самом деле просто имел ввиду куда вставить 1 или 2 в упомянутом выше куске кода: 
vk.Users.Search("Masha Ivanova", out count, fields, 100);

**Comment by azhidkov** [comment]
Понял вас. Сейчас этот метод устаревший и позволяет задавать только значения которые необходимо получить.

Но этот метод в вк апи позволяет сейчас задавать условия для поиска. Нужно будет обновить его в библиотеки.

Как вариант сейчас в этом файле https://github.com/vknet/vk/blob/master/VkNet/Categories/UsersCategory.cs вы можете найти метод Search, добавить в сигнатуру метода необходиые параметры, и затем прописать их в иницилизации VkParameters). Для примера можете посмотерть как это сделано сейчас для параметров query, count, offset, fields.

**Comment by alexander-onoprienko** [comment]
> добавить в сигнатуру метода необходиые параметры, и затем прописать их в иницилизации VkParameters.

Параметров поиска слишком много, предлагаю вынести их в отделтный класс, которяый будет поддерживать перечисления и необходимые ограничения.

**Comment by CaCTuCaTu4ECKuu** [comment]
Я, честно говоря, уже не пойму в чем проблема (возможно она уже даже исправлена), так что я, наверное это закрываю и если проблема осталась вы напишите заново

**Comment by alikhil** [comment]
![image](https://cloud.githubusercontent.com/assets/7482065/9022949/754a46f6-38a2-11e5-9505-582b0d33870d.png)
Проблема все еще актуальна

**Comment by inyutin-maxim** [comment]
Метод Users.Search был приведен в актуальное состояние, параметры запроса вынесены в отдельный класс, проблема была в отсутствии версии API (думаю она актуальна и для других мест), поэтому не все поля возвращались
