### ISSUE TITLE
Получить ид групп из поиска

### ISSUE THREAD

**Issue by SadikMaxLK** [vknet/vk#574]
Как можно получить ид групп из поиска?
![image](https://user-images.githubusercontent.com/26010161/37060405-43ede76c-21a1-11e8-954d-ced300877619.png)

**Comment by Anamorf** [comment]
В чем проблема? Это работа с обычными коллекциями:
```
var groups = vk.Groups.Search(new GroupsSearchParams {Query = "Тест", Count = 1000});
var ids = groups.Select(group => group.Id).ToList();
```
