### ISSUE TITLE
Как сделать проверку на непрочитанное сообщение?

### ISSUE THREAD

**Issue by SadikMaxLK** [vknet/vk#576]
Нужно сделать отправку сообщений, но, если сообщение  пользователь не прочитал (тот, который отправляет), то писать не нужно
`
if(Проверка на сообщение){
vk.Messages.Send(new MessagesSendParams
                        {
                            PeerId = 123,
                            Message = msg.ToString(),
                        });
} else {
    MessageBox.Show("Уже ответили");
}
`
![image](https://user-images.githubusercontent.com/26010161/37141061-e9ef4196-22c4-11e8-8fc4-32812131d893.png)

**Comment by Anamorf** [comment]
Ознакомьтесь с методом [messages.GetDialogs](https://vk.com/dev/messages.getDialogs).
Он возвращает информацию о последнем сообщении из каждого диалога. У сообщений есть свойство `read_state`, через которое можно узнать прочитано оно или нет, а также есть  `out`, указывающее на то является сообщение исходящим или входящим.

**Comment by SadikMaxLK** [comment]
`var msg = vk.Messages.Get(new MessagesGetParams {Count = 1 });
if (msg.Messages[0].ReadState == VkNet.Enums.MessageReadState.Readed)
`
