### ISSUE TITLE
Как авторизваться без приложения?

### ISSUE THREAD

**Issue by kabanpunk** [vknet/vk#581]
К примеру на питоне с помощью библиотеки vk_api, можно авторизваться зная только login и пароль.

```
# -*- coding: utf-8 -*-
import vk_api, requests
session = requests.Session()
vk_session = vk_api.VkApi(login, password)
try:
    vk_session.auth()
except vk_api.AuthError as error_msg:
    print(error_msg)
vk = vk_session.get_api()
```

как сделать такое же, но только с помощью VkNet'а ?

**Comment by inyutin-maxim** [comment]
На данный момент никак, этот флоу пока не реализован, запланировано на будущее

**Comment by jenokizm** [comment]
А в чем разница через приложение или без него? Есть какие то ограничения на действия пользователя?

**Comment by inyutin-maxim** [comment]
@jenokizm Вообще насколько я понимаю совсем без приложения вроде как нельзя авторизоваться, это просто другой флоу. а в той либе ид приложения был зашит в исходниках

**Comment by jenokizm** [comment]
> а в той либе ид приложения был зашит в исходниках

вот это другое дело. надо найти это чтобы точно знать)

**Comment by jenokizm** [comment]
Внатуре https://github.com/python273/vk_api/blob/3eba6688b05fdf09e97f1b75282fe4969c23fb92/vk_api/vk_api.py#L88

**Comment by inyutin-maxim** [comment]
@jenokizm Мне же нет смысла врать, просто по другому в вк не авторизоваться. я как нибудь найду времени чтобы допилить AuthFlows
