### ISSUE TITLE
Ошибка в Ubuntu 16.04

### ISSUE THREAD

**Issue by serber** [vknet/vk#582]
Для воспроизведения ошибки достаточно:
1. Добавить в проект ссылку на пакет `VkNet`
2. Собрать приложение с RID ubuntu.16.04-x64
3. Запустить приложение командой dotnet [dll_name].dll

При запуске приложение падает с ошибкой:

> Failed to initialize CoreCLR, HRESULT: 0x80004005

Если удалить ссылку на пакет, то приложение запускается без ошибок.
Предполагаю, что дело в одной из зависимости пакета `VkNet`.

Информация о среде:

> Product Information:
>  Version:            2.1.101
>  Commit SHA-1 hash:  6c22303bf0
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  16.04
>  OS Platform: Linux
>  RID:         ubuntu.16.04-x64
>  Base Path:   /usr/share/dotnet/sdk/2.1.101/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.6
>   Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by inyutin-maxim** [comment]
Kubuntu 16.04 x64 полет нормальный, с самым последним обновлением dotnet все работает

https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main


``` bash
>raven@raven-JW6H:~/RiderProjects/VkTest/VkTest$ dotnet --version
2.0.2

>raven@raven-JW6H:~/RiderProjects/VkTest/VkTest$ dotnet run -p VkTest.csproj --runtime ubuntu.16.04-x64
Enter code:
766580
```

**Comment by inyutin-maxim** [comment]
```bash
raven@raven-JW6H:~/RiderProjects/VkTest/VkTest$ dotnet --info
Программы командной строки .NET (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
