### ISSUE TITLE
Конфликт VkNet с Xamarin

### ISSUE THREAD

**Issue by faridjannatov** [vknet/vk#585]
После установки VkNet в проект Xamarin.Forms запускаю приложение и появляются ошибки
![screenshot_37](https://user-images.githubusercontent.com/35075262/39021888-fa55359a-4443-11e8-82a8-dce8142b27a9.png)

Платформа NETStandard2.0

**Comment by inyutin-maxim** [comment]
при данной конфигурации приложения библиотека устанавливается без проблем
![image](https://user-images.githubusercontent.com/1781005/39069537-bcad59ac-44e8-11e8-997a-f2528ca3c250.png)
