### ISSUE TITLE
Двухфакторная авторизация & Captcha Solver.

### ISSUE THREAD

**Issue by LiptonOlolo** [vknet/vk#591]
Привет.
1) При авторизации использую св-во TwoFactorAuthorization в методе AuthorizeAsync, в котором возвращаю "левый" код (т.е. не правильный), после чего код дальше не идет, нет ни ошибок, что код не правильный и прочего. (Проверил через брейкпоинт, метод вызывается только 1 раз).

2) Реализовал интерфейс ICaptcheSolver, возвращаю код капчи из метода и... Капча выскакивает еще раз. Так же вызывается 2-ой метод, что якобы капча не правильная.

С чем могут быть связаны проблемы?

**Comment by inyutin-maxim** [comment]
@LiptonOlolo По капче скорее всего исправление выйдет уже в следующем релизе, а про двухфакторку нужно дорабатывать

**Comment by inyutin-maxim** [comment]
@LiptonOlolo или я может не до конца понял насчет капчи, при авторизации или при выполнении методов?

**Comment by inyutin-maxim** [comment]
@LiptonOlolo если у вас desctop приложение предлагаю сделать как по ссылке, внутренний механизм авторизации нужно перерабатывать
https://github.com/vknet/vk/blob/d8afbe16a33b24749dd6314953392124ba1147ca/examples/VkNet.Wpf/MainWindow.xaml.cs#L14

**Comment by LiptonOlolo** [comment]
@inyutin-maxim Жду новую версию

**Comment by itsokto** [comment]
Обсуждение проблем с авторизацией переносится в #997
