### ISSUE TITLE
Пол пользователя приходит равный -1

### ISSUE THREAD

**Issue by TheZebraz** [vknet/vk#594]
Привет, есть проблема с парсингом пола пользователя, падает исключение. Иногда у заблокированных или удаленных пользователей значение пола приходит равное -1. Такая проблема наблюдается, например, у пользователя с id 118312730.

Вот что отдает вк: https://vk.com/dev/users.get?params[user_ids]=118312730&params[fields]=sex&params[name_case]=Nom&params[v]=5.74

![image](https://user-images.githubusercontent.com/7344776/39832738-b4d9d344-53d0-11e8-98d8-2e2a587bfe77.png)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу.  Добавил в перечисление новый тип:
```csharp
Sex.Deactivated
```
