### ISSUE TITLE
Docs.Save и Docs.SaveAsync

### ISSUE THREAD

**Issue by banyrule** [vknet/vk#596]
- `Vk.Docs`, методы Save` и `SaveAsync`
- Пример кода для воспроизведения проблемы:

            dynamic responce= JsonConvert.DeserializeObject(responseJson);
            string fileValue = responce.file;          
            vkApi.Docs.Save(fileValue, responce.title).FirstOrDefault();

`ReadOnlyCollection<Document> Save(string file, string title, string tags = null, long? captchaSid = null, string captchaKey = null);`

Метод выполняет лишний, неочевидный парсинг аргумента `file`, предполагая что там находится весь json-ответ, полученный после загрузки документа на сервер. Из-за чего код выше работать не будет. Зато сработает `vkApi.Docs.Save(responseJson, "sample_title").FirstOrDefault();`, что выглядит совсем не очевидно.

**Comment by banyrule** [comment]
Я не уверен что это можно назвать багом, т.к. по факту json-ответ ничего кроме поля file не содержит, и текущая реализация делает использования метода чуть проще, если знать эту особенность. Тут скорее `<param name="file">Параметр, возвращаемый в результате загрузки файла на сервер. Обязательный параметр.</param>`  заменить на 
`<param name="file">JSON-объект с полем file, возвращаемый после успешной загрузки документа сервер</param>`

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу
