### ISSUE TITLE
Авторизация требует подтверждения прав

### ISSUE THREAD

**Issue by SanteR1** [vknet/vk#603]
Судя по логу, авторизация зациклилась, потому как никакой Exception не сработал.
Ранее этот аккаунт спокойно проходил авторизацию и работал.
[logvk.txt](https://gist.github.com/SanteR1/813e2eb3d803d5350896f4dfeced7499)

```csharp
try{
                    var api = new VkApi(_logger);
                    ApiAuthParams auth = new ApiAuthParams()
                    {
                        ApplicationId = *******,
                        CaptchaKey = null,
                        CaptchaSid = null,
                        Login = "**",
                        Password = "**",
                        Settings = Settings.All,
                        TwoFactorAuthorization = null
                    };
                        api.Authorize(auth);
}
catch(Exception e)
{
     _logger.Error(e.Message);
}
```

**Comment by inyutin-maxim** [comment]
@SanteR1  У вас Desctop приложение? если да как временный WorkArround предлагаю реализовать как в WPF примере:
Требуется только реализация интерфейса [IBrowser как здесь](https://github.com/vknet/vk/blob/master/examples/VkNet.Wpf/WpfAuthorize.cs)

**Comment by hexnone** [comment]
Циклится также и авторизация с неверными данными логин/пароль. Думаю, что это действительно нужно исправлять. Исключение не выбрасывается.

**Comment by inyutin-maxim** [comment]
@hexnone Попробуйте из альфа канала или дождитесь релиза. 
Альфа канал: https://www.myget.org/F/vknet

**Comment by hexnone** [comment]
> 
> 
> @hexnone Попробуйте из альфа канала или дождитесь релиза.
> Альфа канал: https://www.myget.org/F/vknet

Использую сборку из альфа-канала v.1.44.0-135
<details>
  <summary>Log</summary>

18:31:56 [Debug]: VkApi Initialization successfully 

18:31:56 [Debug]: Старт авторизации 

18:31:56 [Debug]: Авторизация с использование капчи. 

18:31:56 [Debug]: Ввод логина и пароля. 

18:31:56 [Debug]: Капча. 

18:31:56 [Debug]: Капча. 

18:31:57 [Debug]: Капча. 

18:31:57 [Debug]: Капча. 

18:31:57 [Debug]: Капча. 

18:31:57 [Debug]: Капча. 

18:31:57 [Debug]: Капча. 

18:31:58 [Debug]: Капча. 

18:31:58 [Debug]: Капча. 

18:31:58 [Debug]: Капча. 

18:31:58 [Debug]: Капча. 
</details>
При этом методы ICaptchaSolver не вызываются.

**Comment by inyutin-maxim** [comment]
@hexnone Здесь бы неплохо пример иметь. А еще лучше пообщаться в чатике https://t.me/VkDotNet

**Comment by itsokto** [comment]
Обсуждение проблем с авторизацией переносится в #997
