### ISSUE TITLE
System.Net.Http.WinHttpException при вызове .Authorize()

### ISSUE THREAD

**Issue by AntonAlekseevAA** [vknet/vk#611]
- Класс и метод в котором возникла проблема:
`VkApi.Authorize(IApiAuthParams)`

Здравствуйте, следующая проблема при отправке запроса на авторизацию. Вылетает исключение `System.Net.Http.WinHttpException`. Последовательность действий, которая привела к возникновению проблемы:

1. Установил последнюю версию пакета (`1.35.1`) с помощью nuget.
2. Попробовал согласно примеру авторизоваться в приложении. Двухфакторную авторизацию не использую.

```csharp
try
            {
                var vkApi = new VkApi();
                vkApi.Authorize(new ApiAuthParams
                {
                    ApplicationId = 6500878,
                    Login = "<email от аккаунта Vk>",
                    Password = "<пароль от аккаунта Vk>",
                    Settings = Settings.Email
                });

                var token = vkApi.Token;
            }
            catch (Exception e)
            {

            }
```
3. Запрос отработал корректно. Затем потребовалось получить доступ к переменной `vkApi` вне блока `try`. Перенес инициализацию переменной следующим образом.
```csharp
var vkApi = new VkApi();
try
            {
                ...Вызов метода Authorize()
            }
            catch (Exception e)
            {

            }
```
4. После этого при вызове `Authorize()` стабильно стало возникать `AggregateException` исключение со следующим `InnerException`:
```csharp
{System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Недопустимые данные
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()}
```
5. Вывод консоли Output следующий:
![image](https://user-images.githubusercontent.com/39969902/41003645-f78d6af2-691f-11e8-96d9-91c57cdfd2fc.png)

6. Откат изменений в состояние, когда все работало, к сожалению не помог. Пробовал запускать несколько раз (чтобы убедиться, что проблема не случайна, к сожалению больше успешного выполнения увидеть не удалось). На всякий случай пробовал выходить из VK с помощью TerminateAllSessions, так-же перезагружал сетевое соединение.

Заранее благодарю за рассмотрение.

**Comment by inyutin-maxim** [comment]
@AntonAlekseevAA Добрый день!
1. Используете ли вы при работе VPN, Proxy, и т.д?
1. Какую версию .NET используете Официально поддерживаем .net 4.0, .net 4.5, NETStandard2.0

Проблема со внешней зависимостью искали ли проблему в google?

**Comment by AntonAlekseevAA** [comment]
1. Vpn не использую.
2. Использую .netcore 2.0.1
3. Пробовал искать в google, из того, что просмотрел - проблема решалась отключением VPN; либо была связана SSL сертификатом. ( https://stackoverflow.com/questions/43265186/net-core-api-post-exception-gives-nativeerrorcode-12175 ). К сожалению, ни один из этих сценариев не совпадает с моим.

**Comment by inyutin-maxim** [comment]
@AntonAlekseevAA Выложи код на гитхаб, так будет проще воспроизвести

**Comment by AntonAlekseevAA** [comment]
Ссылка на репозиторий: https://github.com/AntonAlekseevAA/vkNetAuthorizeHttpExceptionProjectSample.git

Перед публикацией ответа решил еще раз проверить, не случайной ли была ошибка. Сценарий повторился - первый раз авторизация прошла успешно, при последующих же запусках вылетало исключение в том же месте. Но также 1 раз вылетело несколько иное исключение:

```csharp
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Произошла ошибка безопасности
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
```
Внутри WinHttpException код ошибки `12175`. Гуглил по этой ошибке, но меня привело опять на уже знакомые темы с проблемой VPN. Также, например здесь https://stackoverflow.com/questions/43265186/net-core-api-post-exception-gives-nativeerrorcode-12175 говорится, что проблема может возникать при проверке SSL сертификата, и решается навешиванием пользовательского обработчика на Callback. Но сомневаюсь, что это может как-то помочь, ведь первый же раз метод отрабатывает нормально.

Попробовал вызвать метод с заведомо неправильными неправильными параметрами. В этом случае удалось продвинуться до ошибки авторизации в VK. Могу предположить, что в этом случае удалось корректно обработать данные формы (без исключения).
![image](https://user-images.githubusercontent.com/39969902/41061785-722b2eae-69dc-11e8-9c1e-62f1a40c411f.png)

Небольшое дополнение - насчет комментария к вызову метода `Authorized()` с произвольным токеном (что я написал в комментарии к коду) - извиняюсь, более внимательно прочитал документацию, вопрос исчез.

**Comment by CaCTuCaTu4ECKuu** [comment]
Воспроизвести не удалось
![image](https://user-images.githubusercontent.com/8963134/41389118-baa1687c-6f97-11e8-809a-dc2be9605fda.png)
Я добавил код для отладки подобных ошибок т.к. информации из StackTrace недостаточно, а анализаторами трафика никто пользоваться не умеет .
https://github.com/vknet/vk/commit/6148bab272d767a2216ef79edda9f733dd3622ec

Скачайте последнюю версию библиотеки.
Раскомментируйте директиву DEBUG_HTTP и включите запись в файл (В файлы по ссылке на коммит).
Запустите проект и наберите в лог данных по вашим ошибкам (запустите с различными параметрами которые вызывают разные ошибки). Лишнего набирать не нужно, по 1 запуску для каждой ошибки для начала будет достаточно.
Не забудьте вручную проверить лог и убрать важные данные (логин, пароль, токены и хеши).
Файлы должен осесть в папке с скомпилированным проектом, пришлите его чтобы посмотреть конкретно.

**Comment by AntonAlekseevAA** [comment]
Благодарю за проделанную работу, надеюсь это мне поможет.

**Comment by inyutin-maxim** [comment]
@AntonAlekseevAA  У вас Desctop приложение? если да как временный WorkArround предлагаю реализовать как в WPF примере:
Требуется только реализация интерфейса IBrowser как здесь
И подсунуть ее в конструктор 3-м параметром

**Comment by itsokto** [comment]
Ошибка символизирует о проблеме с сертификатом и никак к VkNet не относится. В текущей версии VkNet используется HttpClient вы можете отключить валидацию сертификата (гуглите how to), сконфигурированый HttpClient зарегистрируйте в ServiceCollection [Пример с прокси](https://github.com/vknet/vk/wiki/Proxy-Configuration) и посмотрите поможет ли.
