### ISSUE TITLE
Проблема с Authorize и AuthorizeAsync

### ISSUE THREAD

**Issue by otsomkalov** [vknet/vk#614]
1. Версия библиотеки: 1.35.1
2. Целевая платформа: .NET Standart 2.0
  
3. Класс и метод в котором возникла проблема:
VkApi.Authorize
VkApi.AuthorizeAsync

4. При вызове Authorize вылетает следующие исключения:

Внутреннее исключение 1:
HttpRequestException: The SSL connection could not be established, see inner exception.

Внутреннее исключение 2:
AuthenticationException: The remote certificate is invalid according to the validation procedure.

Код:
```csharp
Vk.Authorize(new ApiAuthParams
            {
                ApplicationId = 6434402,
                Login = "login",
                Password = "pass",
                Settings = Settings.All
            });
```

Трассировка стека:
```csharp
  System.AggregateException
  HResult=0x80131500
  Сообщение = One or more errors occurred.
  Источник = System.Private.CoreLib
  Трассировка стека:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at VkNet.Utils.WebCall.MakeCall(String url, IWebProxy webProxy)
   at VkNet.Utils.Browser.Authorize(IApiAuthParams authParams)
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at MessageForwarder.Program.<Main>d__2.MoveNext() in D:\Documents\Projects\MessageForwarder\MessageForwarder\Program.cs:line 38
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MessageForwarder.Program.<Main>()
```

Консольный вывод:
![image](https://user-images.githubusercontent.com/16070015/41528431-c32984c6-72f2-11e8-928b-95b87019d54a.png)

5. При вызове AuthorizeAsync исключения не возникает, поток выполнения просто не идёт дальше кода:
```csharp
await Vk.AuthorizeAsync(new ApiAuthParams
            {
                ApplicationId = 6434402,
                Login = "log",
                Password = "pass",
                Settings = Settings.All
            });
```

Консольный вывод:
![image](https://user-images.githubusercontent.com/16070015/41528560-1bcb2d1e-72f3-11e8-826a-f3733f22d4e4.png)

6. Откат на предыдущую версию библиотеки не помог.
P.S. Ни VPN, ни прокси не использую

**Comment by CaCTuCaTu4ECKuu** [comment]
Используйте расширенные инструменты отладки, доступные в последней версии на гите. Файл, если не ошибаюсь, Utils\WebCall.
Включите отладку в файл, очистите файл от конф. информации, пришлите содержимое запросов с ошибкой.
У нас не получается воспроизвести ее, мы бы тоже хотели увидеть подробности

**Comment by otsomkalov** [comment]
Проблема найдена: мой украинский провайдер всё таки решил заблокировать vk.com и api.vk.com, и при запросе к ним редиректить на свой сайт с нерабочим сертификатом, так что проблема не библиотеки, а провайдера.
