### ISSUE TITLE
Отсутствует обработка пагинации в методе NewsFeed.Search

### ISSUE THREAD

**Issue by Kishgal** [vknet/vk#620]
Для сравнения, в методе NewsFeed.Get возвращается объект типа NewsFeed, который содержит в себе поле next_from, что позволяет вернуть следующий набор результатов, а метод Newsfeed,Search возвращает ReadOnlyColection<NewsSearchResult>, в котором это поле отсутствует. Сам API этот параметр возвращает и принимает в виде start_from

1. Target для .NET используемый в проекте:
  - [ ] .net 4.5
  
2. Класс и метод в котором возникла проблема:
VkNet.Newsfeed.Search(NewsSearchParams params)
класс NewsFeedSearchParams так же не содержит в себе поле start_from

**Comment by inyutin-maxim** [comment]
https://github.com/vknet/vk/blob/d8afbe16a33b24749dd6314953392124ba1147ca/VkNet/Model/RequestParams/NewsFeed/NewsFeedSearchParams.cs#L65

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу
