### ISSUE TITLE
Выбрасывается исключение "Непредвиденная ошибка авторизации" при двухфакторной авторизации из примера в документации

### ISSUE THREAD

**Issue by ghost** [vknet/vk#622]
1. .NET Framework 4.7.1
2. VkNet.Utils.Browser, EndAuthorize()
3. Код полностью повторяет двухфакторную авторизацию, описанную в документации:
```csharp
        var api = new VkApi();
	api.Authorize(new ApiAuthParams
	{
		ApplicationId = [Здесь ID приложения, я использовал случайный - 3502561],
		Login = "[Здесь верный номер телефона, например 89530351122]",
		Password = "[Здесь верный пароль]",
		Settings = Settings.All,
		TwoFactorAuthorization = () =>
		       {
			Console.WriteLine("Enter Code:"); 
				return Console.ReadLine(); // Код приходит, вводим его сюда
			}
		});
	Console.WriteLine(api.Token);
	var res = api.Groups.Get(new GroupsGetParams());

	Console.WriteLine(res.TotalCount);

	Console.ReadLine();
```

В методе VkNet.Utils.Browser.HasCaptchaInput() у объектов request и response в поле _nameValues после парсинга uriFragment хранятся только ключи act и hash. uriFragment не содержит ключ  "__q_hash", вследствие чего метод VkNet.Utils.Browser.HasCaptchaInput() возвращает null что порождает исключение в вызывающем методе.

**Comment by itsokto** [comment]
Обсуждение проблем с авторизацией переносится в #997
