### ISSUE TITLE
Возникновение неочевидной ошибки при попытке авторизоваться с заблокированного аккаунта

### ISSUE THREAD

**Issue by Kishgal** [vknet/vk#625]
При вызове метода Authorize https://github.com/vknet/vk/blob/e3ed31938ff825cda4f050a81d7e02bcdf43e8f5/VkNet/VkApi.cs#L164
 с временно (или постоянно) заблокированным аккаунтом выбрасывается странное исключение. Текст исключения: "Form element not found."

1. Target для .NET используемый в проекте:
  - [x] .net 4.5
  
2. Класс и метод в котором возникла проблема: VkApi.cs, VkNet.Utils.WebForm

3. Пример кода для воспроизведения проблемы:

Stack trace:   
   в VkNet.Utils.WebForm.GetFormNode()
   в VkNet.Utils.WebForm.ParseInputs()
   в VkNet.Utils.WebForm..ctor(WebCallResult result)
   в VkNet.Utils.Browser.EndAuthorize(WebCallResult result, IWebProxy webProxy)
   в VkNet.Utils.Browser.Authorize(IApiAuthParams authParams)
   в VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   в VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   в VkNet.VkApi.Authorize(IApiAuthParams params)

**Comment by inyutin-maxim** [comment]
@Kishgal У вас Desctop приложение? если да как временный WorkArround предлагаю реализовать как в WPF примере:
Требуется только реализация интерфейса [IBrowser как здесь](https://github.com/vknet/vk/blob/master/examples/VkNet.Wpf/WpfAuthorize.cs)

**Comment by Kishgal** [comment]
@inyutin-maxim Да, приложение десктопное. Спасибо за помощь!

**Comment by inyutin-maxim** [comment]
Ну мне кажется это ожидаемый эффект, вот эта проблема применима только к консольным приложениям, для всех остальных рекомендую выносить авторизацию в вебвью, либо если это веб приложение сам бог велел в браузере после авторизации редирректить на твой сервис

**Comment by itsokto** [comment]
Обсуждение проблем с авторизацией переносится в #997
