### ISSUE TITLE
MessageAction 

### ISSUE THREAD

**Issue by SadikMaxLK** [vknet/vk#632]
![photo_2018-07-12_00-36-45](https://user-images.githubusercontent.com/26010161/42600644-c6795ef4-856b-11e8-9e46-51135988cc89.jpg)
![photo_2018-07-12_00-36-46](https://user-images.githubusercontent.com/26010161/42600645-c69a3b9c-856b-11e8-82ae-9d89d3fec157.jpg)
![image](https://user-images.githubusercontent.com/26010161/42600651-cf921328-856b-11e8-8490-1d1f274be24b.png)

Не срабатывает условие

**Comment by itsokto** [comment]
#639 #640 эти PRs решили проблему?

**Comment by SadikMaxLK** [comment]
Все работает
