### ISSUE TITLE
Ошибка при подгрузке чата

### ISSUE THREAD

**Issue by Lsdenis** [vknet/vk#64]
Error: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'Newtonsoft.Json.Linq.JArray'.

File: VkResponse.cs, line 49.

**Comment by CaCTuCaTu4ECKuu** [comment]
Та же ерунда, не загружает ничего =\
![default](https://cloud.githubusercontent.com/assets/8963134/6361742/87d7c5ba-bc96-11e4-9a4b-092b612ef8f8.PNG)

**Comment by CaCTuCaTu4ECKuu** [comment]
Исправлено в #71

**Comment by CaCTuCaTu4ECKuu** [comment]
Исправлено в #68
