### ISSUE TITLE
Deadlock в Groups.GetById

### ISSUE THREAD

**Issue by Uriel6575** [vknet/vk#641]
.net 4.5, консольное приложение.
Авторизация проходит без проблем как в Async-варианте, так и в синхронном. А вот при попытке запроса группы получаю блокировку. Причём пробовал и честный async/await и танцы с ConfigureAwait(false) и вынос вызова этого метода в другой поток.

**Comment by Uriel6575** [comment]
Да, ставил с NuGet'а последнюю версию.
Попробовал сделать WinForms приложение, а также консольное core-приложение. Результат везде один и тот же. Причём да, виснет, по ходу дела, любой метод, кроме авторизации. Получение списка фотографий, человека по айди - не важно. При том, что в других проектах TPL мы используем и через async/await и кое-где через более низкоуровневое API и всё работает.
Прошу прощения, но в этом смысле чувствую себя слегка мамонтом и аккаунта в Телеграме и прочих не имею. :)

**Comment by inyutin-maxim** [comment]
@Uriel6575 Пожалуйста соберите проект из гитхаб и попробуйте воспроизвести проблему вновь, спасибо

**Comment by Uriel6575** [comment]
Нет, к сожалению пока всё то же самое. Пробовал снова консоль (core) и WinForms (net45).

**Comment by Uriel6575** [comment]
Да, конечно. Забавный факт. Если закомментировать строчку про Settings, то начнёт зависать и авторизация. Последним в логе будет "Шаг 1".
[vk.test.zip](https://github.com/vknet/vk/files/2266387/vk.test.zip)

**Comment by Uriel6575** [comment]
Видимо дело всё-таки не в проекте. Почему-то сразу не сообразил проверить на другой машине. Там бинарник, собранный у меня, отрабатывает без проблем.
Странно только, что у меня это не работает и под полновесным framework'ом и под core'ом. То есть дело скорее всего не в библиотеках из их поставки, а в чём-то системном. Но при этом говорю, что в других проектах async/await работает без каких-либо нареканий.
Поэтому не знаю, наверное вопрос можно закрыть.
