### ISSUE TITLE
Отправка сообщений от имени сообщества

### ISSUE THREAD

**Issue by ykorshev** [vknet/vk#647]
Добрый день.

Прошу подсказать, какие методы необходимо использовать чтобы:

1. Авторизоваться от имени сообщества
2. Отправить сообщение от имени сообщества

Сейчас я использую:
```
await ApiClient.Messages.SendAsync(new MessagesSendParams()
{
                UserId = userId,
                PeerId = Convert.ToInt64(ConfigurationManager.AppSettings["VKGroupId"]),
                Message = message,
});
```
Однако сообщения отправляются от моего имени.

**Comment by inyutin-maxim** [comment]
Предлагаю перенести обсуждение простых вопросов в наш телеграм канал https://t.me/VkDotNet.
А вообще нужно авторизоваться с токеном группы
