### ISSUE TITLE
Отсутствует метод получения attachement(фотографии/видео и тому подобное) из истории сообщений

### ISSUE THREAD

**Issue by Artur2** [vknet/vk#658]
Добрый день. 
У вас отсутствует обертка метода для получения истории attachement-ов.

API - https://vk.com/dev/messages.getHistoryAttachments

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - [x] .net 4.0
  - [x] .net 4.5
  - [x] NETStandard2.0
  - [x] другое. Указать строкой ниже.

**Comment by inyutin-maxim** [comment]
Пруф что есть

https://github.com/vknet/vk/blob/f361d98505986fc2eb4437f3649930edbf5d1b05/VkNet/Categories/MessagesCategory.cs#L526

**Comment by Artur2** [comment]
@inyutin-maxim Тогда наверное документацию нужно обновить)
Спасибо)
