### ISSUE TITLE
Отсутствуют методы Edit, GetSettings и др. в разделе Audio

### ISSUE THREAD

**Issue by objaa** [vknet/vk#66]
Добрый вечер, подскажите, есть ли в планах расширять \обновлять некоторые классы для работы с API?
VK внедряет новые методы, а здесь их пока нету. причем большей части :(

Например получение настроек для группы groups.getSettings

**Comment by azhidkov** [comment]
Добрый день!

Планы то есть, но нет времени. Сейчас я не использую её для своих разработок, поэтому на поддержку практически нет времени.

Не хотели бы вы поучаствовать? По-сути, там ничего сложного :)

**Comment by CaCTuCaTu4ECKuu** [comment]
У меня нет времени перепроверять весь функционал, которым я не пользуюсь, но если скажете что конкретно вам нужно могу в свободное время сделать

**Comment by Inyutin** [comment]
https://vk.com/dev/groups.search

**Comment by inyutin-maxim** [comment]
Закрываю задачу, было реализовано мной ранее
