### ISSUE TITLE
Работа с NLog

### ISSUE THREAD

**Issue by Seekeer** [vknet/vk#661]
В проекте, который работает c vknet, используется NLog. И Debug и Trace сообщения VKNet выводятся у меня в консоль с вот такой настройкой NLog. Как бы мне избавиться от них, а то всю консоль забивает?

  <targets>

    <target xsi:type="Console" name="console" layout="${longdate}|${level:uppercase=true}|${logger}|${message}${newline}" />
    
    <target name="fileLog" xsi:type="File"
        layout="${longdate} ${logger} ${message}" 
        fileName="${basedir}/logs/log.txt" 
        archiveFileName="${basedir}/archives/log.{#####}.txt"
        archiveAboveSize="10240"
        archiveNumbering="Sequence"
        concurrentWrites="true"
        keepFileOpen="false"
        encoding="utf-8" />
    
    <target name="fileError" xsi:type="File"
        layout="${longdate} ${logger} ${exception-message}${newline}${stacktrace}${newline}${message}${newline}${newline}" 
        fileName="${basedir}/logs/error.txt" 
        archiveFileName="${basedir}/archives/error.{#####}.txt"
        archiveAboveSize="10240"
        archiveNumbering="Sequence"
        concurrentWrites="true"
        keepFileOpen="false"
        encoding="utf-8" />
    
    <target name="sentry" type="Sentry" dsn="https://a152e001b4744db099743406c60bbe8f:a3f18691e4324f178e32554eb6f06514@sentry.io/771565" environment="develop" />

    <target xsi:type="Null" name="BlackHole" formatMessage="false"  />
  </targets>
  
  <rules>

    <logger name="*" minlevel="Trace" writeTo="Null" />
    <logger name="*" minlevel="Debug" writeTo="Null" />
    
    <logger name="*" level="Info" writeTo="console" />
    <logger name="*" level="Error" writeTo="fileError" />
    <logger name="*" level="Fatal" writeTo="sentry" />
  </rules>

**Comment by inyutin-maxim** [comment]
@Seekeer В настоящее время нужно сконфигурировать экземпляр логгера **NLog** отдельно например через DI как показано в примере https://vknet.github.io/vk/authorize/

Начиная с релиза 1.37.1 логгер будет отвязан от конкретной реализации (**NLog**) и можно будет использовать вообще любой который реализует провайдер для **Microsoft.Extensions.Logging.Abstractions**

Так же у нас есть уютный чатик где есть активное сообщество, которое помогает решать некоторые проблемы https://t.me/VkDotNet

**Comment by inyutin-maxim** [comment]
@Seekeer Опубликован новый релиз
