### ISSUE TITLE
Отсутствие поля close_comments в методе Wall.Post

### ISSUE THREAD

**Issue by roland-x** [vknet/vk#662]
Добрый день, пытался кинуть пост на стену и закрыть комментирование к нему

```
long wallId = _api.Wall.Post(new WallPostParams
                {
                    OwnerId = Convert.ToInt64(userId),
                    Message = message,
                    Attachments = att
                });
```
Но, в WallPostParams отсутствует поле close_comments. Прошу добавить. Спасибо!

**Comment by inyutin-maxim** [comment]
@roland-x  добавлено к следующему релизу. Либо можете собрать сами из GitHub

**Comment by roland-x** [comment]
Спасибо
