### ISSUE TITLE
Access denied: this wall available only for community members

### ISSUE THREAD

**Issue by igorlevashov** [vknet/vk#672]
При попытке вызвать метод Wall.Get появляется ошибка "Access denied: this wall available only for community members".  Являюсь участником группы. В чём может быть проблема?

**Comment by inyutin-maxim** [comment]
@igorlevashov Попробуйте выполнить запрос с теми же параметрами здесь: https://vk.com/dev/wall.get
Это может быть либо отсутствие какого то параметра, или наоборот при передаче из библиотеки присутствие какого то лишнего

Так же рекомендую присоединиться к чатику в телеграм: https://t.me/VkDotNet

**Comment by inyutin-maxim** [comment]
@igorlevashov Вам удалось решить проблему?

**Comment by igorlevashov** [comment]
Нет, так и не смог решить.

**Comment by ghost** [comment]
@igorlevashov Отпишите с какими параметрами выполняли запрос
У меня всё работает, и с закрытой группой, и с частной.

**Comment by inyutin-maxim** [comment]
@igorlevashov актуален ли тикет?

**Comment by itsokto** [comment]
Не воспроизводится. Если еще актуально, отпишите с какими параметрами вызываете метод. А пока я закрою issue.
