### ISSUE TITLE
groups.getById Market не соответствует возвращаемому объекту

### ISSUE THREAD

**Issue by SapiPapik** [vknet/vk#673]
Выгружаю аналитику по группе.
Для этого использую `CallAsync`, т.к. `_api.Groups` не имеет полного списка доступных параметров.

Примерно так:
```csharp
  var result = (await _api.CallAsync("groups.getById", new VkParameters(parameters: new Dictionary<string, string>()
                {
                    { "group_id", groupId},
                    { "fields", "activity,age_limits,ban_info,market ..." }
                })
            )).ToReadOnlyCollectionOf<Group>(x => x).FirstOrDefault();
```

JSON ответ:
```json
{
"response": [{
...
"market": {
"enabled": 1,
"price_min": "0",
"price_max": "10000000",
"main_album_id": *,
"contact_id": ********,
"currency": {
"id": ***,
"name": "RUB"
},
...
}]
}
```
Market же содержит:
```csharp
public class Market {
    public long Id { get; set; }
    public long? OwnerId { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public Price Price { get; set; }
    public MarketCategory Category { get; set; }
    public Uri ThumbPhoto { get; set; }
    public DateTime? Date { get; set; }
    public ProductAvailability Availability { get; set; }
    public ReadOnlyCollection<Photo> Photos { get; set; }
    public bool? CanComment { get; set; }
    public bool? CanRepost { get; set; }
    public Likes Likes { get; set; }
}
```

Может я что-то не углядел или данный функционал действительно содержит ошибку?

**Comment by inyutin-maxim** [comment]
@SapiPapik Просто с течением времени API изменяется и соответственно меняются и модели данных:
Вот так объект выглядит в документации: https://vk.com/dev/objects/market_item

**Comment by SapiPapik** [comment]
@inyutin-maxim При тестировании методов, сменил версию api на 3.0
Объект так же не соответствует документации: [https://vk.com/dev/groups.getById](https://vk.com/dev/groups.getById?params[group_id]=meetmeatkrsk&params[fields]=description%2Cmarket&params[v]=3.0)
Предлагаю добавить данный объект(GroupMarket) к Group.

**Comment by inyutin-maxim** [comment]
@SapiPapik Будем изучать проблему, думаю к следующему релизу поправим

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете собрать сами из GitHub
