### ISSUE TITLE
Добавить параметр wait в Messages.GetLongPollHistory() 

### ISSUE THREAD

**Issue by manhunt0465** [vknet/vk#682]
Из документации (https://vk.com/dev/using_longpoll):
wait — время ожидания (так как некоторые прокси-серверы обрывают соединение после 30 секунд, мы рекомендуем указывать wait=25). Максимальное значение — 90.

Без этого параметра запросы к long poll серверу приходится делать очень часто для получения моментальных уведомлений.

**Comment by inyutin-maxim** [comment]
@IronScorp Параметр **wait** не имеет отношения к [Messages.GetLongPollHistory()](https://vk.com/dev/messages.getLongPollHistory)
А сам лонг пул у нас пока не реализован
