### ISSUE TITLE
Error ? Exception  System.ArgumentException: 'Can not convert Object to String.'

### ISSUE THREAD

**Issue by PatrickAgeev** [vknet/vk#689]
var api = new VkNet.VkApi();
			api.Authorize(new vk.ApiAuthParams
			{
				AccessToken = "XXXXX",
				ApplicationId = 11111,
			});

			Console.WriteLine("Hello Test VK!");
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!var users = api.Users.Search(new UserSearchParams
			{
				Query = "Вася",
				Fields = VkNet.Enums.Filters.ProfileFields.BirthDate,
				Count = 10
			});
			Console.WriteLine(users.Count);

!!!!!!!!!!!!!!!!!!!!!!!!!!System.ArgumentException: 'Can not convert Object to String.'

**Comment by PatrickAgeev** [comment]
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
An unhandled exception of type 'System.ArgumentException' occurred in Newtonsoft.Json.dll
Can not convert Object to String.

**Comment by itsokto** [comment]
@PatrickAgeev не удалось воспроизвести 
![](https://user-images.githubusercontent.com/36706257/46432950-367cd400-c758-11e8-9a09-04395838e26f.png)

**Comment by PatrickAgeev** [comment]
Тест на net/Core и Net Framework! первая часть где просто читается пользователь срабатывает , а где поиск exception!

**Comment by PatrickAgeev** [comment]
![untitled](https://user-images.githubusercontent.com/19599237/46435075-24059900-c75e-11e8-9e5b-310446a9a1dc.png)

**Comment by itsokto** [comment]
@PatrickAgeev 
-  **Добавьте следующие пакеты из Nuget:**
Microsoft.Extensions.Logging
NLog
NLog.Extensions.Logging

- **Сконфигурируйте логгер и передайте его в конструктор VkApi** 
```
private static ILogger<T> InitLogger<T>()
{
    var consoleTarget = new ColoredConsoleTarget
    {
        UseDefaultRowHighlightingRules = true,
        Layout = "${level} ${longdate} ${message}"
    };
    var fileTarget = new FileTarget
    {
        FileName = "log.txt",
        DeleteOldFileOnStartup = true,
        Layout = "${level} ${longdate} ${message}"
    };
    var config = new LoggingConfiguration();
    config.AddTarget("console", consoleTarget);
    config.AddTarget("file", fileTarget);
    var rule = new LoggingRule("*", LogLevel.Trace, consoleTarget);
    var rule1 = new LoggingRule("*", LogLevel.Trace, fileTarget);
    config.LoggingRules.Add(rule);
    config.LoggingRules.Add(rule1);
    LogManager.Configuration = config;

    var loggerFactory = new LoggerFactory();
    loggerFactory.AddNLog(new NLogProviderOptions
        {CaptureMessageTemplates = true, CaptureMessageProperties = true});
    return loggerFactory.CreateLogger<T>();
}
```
`VkApi api = new VkApi(InitLogger<VkApi>());`

- **Отправьте log.txt после выброса исключения**

**Comment by inyutin-maxim** [comment]
@PatrickAgeev Так же на всякий случай замените важные персональные данные например на ***
