### ISSUE TITLE
Messages.GetDialogs выбрасывает ArgumentException

### ISSUE THREAD

**Issue by ResPasha** [vknet/vk#69]
"System.ArgumentException" в Newtonsoft.Json.dll
Дополнительные сведения: Accessed JArray values with invalid key value: "count". Array position index expected.

Newtonsoft.Json.dll v 6.0.8
VkNet.dll v 1.0.16

Возвращаемый json
{"response":[55,{"mid":52567,"date":1425508102,"out":0,"uid":175127202,"read_state":1,"title":" ... ","body":"text"},{...}]}

**Comment by CaCTuCaTu4ECKuu** [comment]
Это с новыми исходниками? mid возвращается при версии API ниже 5.0, а у текущего метода GetDialogs указан API 5.28, возможно это причина.

**Comment by ResPasha** [comment]
Проблема в том, что у метода указан API 5.28, а в запросе, который он отправляет API 5.14.

**Comment by CaCTuCaTu4ECKuu** [comment]
Все работает правильно. Перекомпилируйте исходники
![default](https://cloud.githubusercontent.com/assets/8963134/6495404/c68197b0-c2da-11e4-8d78-eb139ed15cfe.PNG)

**Comment by ResPasha** [comment]
Спасибо, заработало.

**Comment by ResPasha** [comment]
Спасибо
