### ISSUE TITLE
Добавить методы leadForms

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#691]
https://vk.com/dev/leadForms

- [x] [leadForms.create](https://vk.com/dev/leadForms.create)
- [x] [leadForms.delete](https://vk.com/dev/leadForms.delete)
- [x] [leadForms.get](https://vk.com/dev/leadForms.get)
- [x] [leadForms.getLeads](https://vk.com/dev/leadForms.getLeads)
- [x] [leadForms.getUploadURL](https://vk.com/dev/leadForms.getUploadURL)
- [x] [leadForms.list](https://vk.com/dev/leadForms.list)
- [x] [leadForms.update](https://vk.com/dev/leadForms.update)

**Comment by CaCTuCaTu4ECKuu** [comment]
Эмм..
https://github.com/vknet/vk/blob/develop/VkNet/Categories/LeadFormsCategory.cs
Чего-то не хватает?

**Comment by inyutin-maxim** [comment]
> Эмм..
> https://github.com/vknet/vk/blob/develop/VkNet/Categories/LeadFormsCategory.cs
> Чего-то не хватает?

Всего. это просто заглушки

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
