### ISSUE TITLE
Не удается прикрепить свое изображение к прикрепленной ссылке

### ISSUE THREAD

**Issue by justerman** [vknet/vk#693]
private void PostingImgWallGroup(VkApi Api, ulong groupID, string pathPic)
        {
            var uploadServer = Api.Photo.GetWallUploadServer((long)groupID);

            var wc = new WebClient();
            var responseFile = Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, pathPic));

            var photos = Api.Photo.SaveWallPhoto(responseFile, null, groupID);
            var attach = new List<MediaAttachment>();
            Link link = new Link();
            link.Uri = new Uri("");//линк на мой ютуб канал
            link.Image = photos[0].ToString();//photo[мой_id]_456241196
            //link.Photo = photos[0];
            //attach.Add(photos[0]);
            attach.Add(link);

            try
            {
                Api.Wall.Post(new WallPostParams
                {
                    Attachments = attach,
                    Message = "Смотрим!",
                    OwnerId = -(long)groupID
                });
                SetTextSafe("Отправлено!");
            }
            catch (CaptchaNeededException cEx)
            {
                save_cap(cEx.Img.ToString());

                ExampleImageToText();

                try
                {
                    Api.Wall.Post(new WallPostParams
                    {
                        Attachments = attach,
                        OwnerId = -(long)groupID,
                        CaptchaSid = cEx.Sid,
                        CaptchaKey = Data.answerCap
                    });
                    SetTextSafe("Отправлено!");
                }
                catch { SetTextSafe("Капча не разгадана!"); }
            }
        }

В общем пытаюсь заменить изображение моего канала на другое, но изображение не меняется, я делаю что то не так, или это всё таки баг?

**Comment by itsokto** [comment]
@justerman 
https://vk.com/dev/wall.post
Link недоступен в attachments.

**Comment by justerman** [comment]
Не совсем вас понял, а почему тогда линк публикуется словно я его руками в браузере запостил? единственное что не работает так это то что я не могу своё изображение прикрепить.

**Comment by itsokto** [comment]
Скорей всего через Api не получится такое реализовать, т.к. формат вложения должен быть
`link100172_166443618` 
т.е. объект ссылки должен быть известен заранее, что невозможно.

**Comment by inyutin-maxim** [comment]
@justerman Проблема мне кажется у вас надуманная, через сайт вы неявно через апи создаете объект Link

**Comment by justerman** [comment]
Я правильно понимаю, что не получится заменить изображение?

**Comment by inyutin-maxim** [comment]
@justerman Нет, изображение заменить возможно, только другим путем, предлагаю таск закрыть а общение продолжить здесь: https://t.me/VkDotNet
