### ISSUE TITLE
Ошибка авторизации

### ISSUE THREAD

**Issue by pj-promo** [vknet/vk#697]
При попытке авторизации, исключение "URI должен содержать токен!".
v1.38, FW 4.7.2.
До ошибки 2 дня работала стабильно.
Win 7

Реализация подключения:
```
setting = new ApiAuthParams
                    {
                        ApplicationId = _account.AppId,
                        Login = _account.Email,
                        Password = _account.Password,
                        Settings = Settings.All,
                        
                        Host = _account.Proxy.Address,
                        Port = int.Parse(_account.Proxy.Port),
                        ProxyLogin = _account.Proxy.UserName,
                        ProxyPassword = _account.Proxy.Password,
                    };
```
...
`api.Authorize(setting);`

Скрин ошибки:
![image](https://user-images.githubusercontent.com/1692479/46718228-06679080-cc84-11e8-8fed-22b52c868063.png)

**Comment by inyutin-maxim** [comment]
@pj-promo Рекомендую для отладки пользоваться бесконечным токеном. Причина скорее всего в капче, которую мы не обрабатываем при авторизации. Так же если у тебя Desctop приложение то авторизацию лучше реализовать примерно как в примере: https://github.com/vknet/vk/blob/develop/examples/VkNet.Wpf/WpfAuthorize.cs

Так же у нас есть чат в телеграмме  где сообщество активно помогает друг другу: https://t.me/VkDotNet

**Comment by itsokto** [comment]
Обсуждение проблем с авторизацией переносится в #997
