### ISSUE TITLE
Group.Get

### ISSUE THREAD

**Issue by kristx300** [vknet/vk#70]
var sr = vkapi.UserId;  
 var group = vkapi.Groups.Get(sr, true, GroupsFilters.Moderator, GroupsFields.All);
пишет
 An unhandled exception of type 'System.ArgumentException' occurred in Newtonsoft.Json.dll

Additional information: Can not convert Array to String.
почему у вас в примере, всё работает а у меня нет...

**Comment by kristx300** [comment]
А как обновить?

**Comment by kristx300** [comment]
пробовал через Nuget Update-Package 
не помогло

**Comment by CaCTuCaTu4ECKuu** [comment]
@kristx300 Скачать исходники, скомпилировать и взять VkNet.dll оттуда

**Comment by kristx300** [comment]
которые на главной странице?

**Comment by CaCTuCaTu4ECKuu** [comment]
https://github.com/vknet/vk

**Comment by kristx300** [comment]
http://i68.fastpic.ru/big/2015/0308/f5/a72939909f8d3743113786e85d1a0ef5.jpg
ошибки :С

**Comment by CaCTuCaTu4ECKuu** [comment]
Скачайте пока отсюда https://github.com/CaCTuCaTu4ECKuu/vk
я сделаю pull request
Там 2 файла в папках есть, но они не внесены в проект в этом репозитории

**Comment by kristx300** [comment]
там тож ероры красные :С
мб .dll скинешь?)))))

**Comment by kristx300** [comment]
куда легче будет и тебе и мне :) :100:

**Comment by CaCTuCaTu4ECKuu** [comment]
Все собирается и в папке Debug появился VkNet.dll
![default](https://cloud.githubusercontent.com/assets/8963134/6545857/dd5599d0-c5ac-11e4-8da3-5e6c30325ca8.PNG)

**Comment by CaCTuCaTu4ECKuu** [comment]
Получилось?

**Comment by kristx300** [comment]
нет :С

**Comment by CaCTuCaTu4ECKuu** [comment]
Опишите последовательность действий, которые вы выполняете начиная с загрузки репозитория себе на ПК

**Comment by kristx300** [comment]
качаю .zip 
экспорт в папку
запуск sln файла 
build
error

**Comment by CaCTuCaTu4ECKuu** [comment]
Скрин в студию

**Comment by kristx300** [comment]
http://1drv.ms/1GjApFC    - файл output
http://i58.fastpic.ru/big/2015/0309/08/5bcf18336b8b42c083e4524f037bf408.jpg  картинка еррор

**Comment by CaCTuCaTu4ECKuu** [comment]
У вас версия .Net Framework какая? Если < 4.0 попробуйте изменить в настройках проекта на 4.5

**Comment by CaCTuCaTu4ECKuu** [comment]
Я закоммитил изменения. То, что у вас было это тесты, вы, видимо, пересобирали весь проект, а не только VkNet. Сейчас у меня работает сборка решения, после успешной сборки запускается инжектор который выдает ошибку, но библиотекой можно пользоваться

**Comment by kristx300** [comment]
у меня установлены все версии
но текущая 4.5.2

**Comment by CaCTuCaTu4ECKuu** [comment]
Сорян я не до конца разобрался пока как здесь все работает)

**Comment by kristx300** [comment]
всё ок :)
завтра тестану Get.Group

**Comment by kristx300** [comment]
Извини за нервотрёпку :)
там крч гулпость какая то  моя :)
кстати будет ли библиотека под WinRT for WinStore и для WP

**Comment by CaCTuCaTu4ECKuu** [comment]
Да там непонятное что-то, я 2 раза качал у меня сначала собирало, но ошибку в конце выдавало, а потом заново скачал и после сборки уже не было ошибки и в принципе перестало собираться через "Запуск" и теперь только через сборку...
>кстати будет ли библиотека под WinRT for WinStore и для WP
Это зависит от тех, кто пользуется библиотекой, у меня сейчас нет потребности в этом поэтому я не буду в ближайшее время заниматься точно, автор сейчас вообще с ней не работает и от него тоже жать нет смысла. Если сами разве что сделаете и добавите pull request

**Comment by kristx300** [comment]
а можно ли урезать библиотеку?)
ну что бы в ней было то, что я хочу и не более
тк я пользуюсь в принципе 5тью запросами
и 1 invoke

**Comment by CaCTuCaTu4ECKuu** [comment]
Насколько я знаю для того исходники и существуют чтобы переделывать их в то, что нужно, а иначе пользоваться .dll

**Comment by azhidkov** [comment]
> будет ли библиотека под WinRT for WinStore и для WP
Под WinRT не будет, т.к. там различные классы для работы с сетью. Под XP тоже, т.к. на него нельзя поставить .Net Framework 4.5. Но можно пересобрать под 3.5 или 4 и тогда заработает на XP.

**Comment by kristx300** [comment]
мне XP не нужно :3
уж больно мне не нравится :С
а вот WinRt жалко :С

**Comment by azhidkov** [comment]
Сделал заявку на поддержку WinRT https://github.com/vknet/vk/issues/78
