### ISSUE TITLE
Wall.Get throws exception

### ISSUE THREAD

**Issue by Seekeer** [vknet/vk#701]
**Describe the bug**
Some groups throw NullRef exceptions on Wall.Get

**To Reproduce**
Code sample is as simple as:

                _apiVKNet.Authorize(new ApiAuthParams() { ApplicationId = (ulong)appId, Settings = VkNet.Enums.Filters.Settings.All, Login = login, Password = pass });

                var param = new VkNet.Model.RequestParams.WallGetParams() { Count = 30, Extended = true, OwnerId = -39490001 };
                var posts = _apiVKNet.Wall.Get(param);

**Screenshots**
![image](https://user-images.githubusercontent.com/2019187/46824555-e4f8c880-cd99-11e8-9bc5-741865f5fd24.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10

**Comment by inyutin-maxim** [comment]
@Seekeer if you from Russia, please write on Russian language. You can configure logging as [here](https://github.com/vknet/vk/wiki/Logging). And attach log file to this issue

**Comment by itsokto** [comment]
@Seekeer 137ba9a исправлено. Была проблема с опросами.
Соберите с GitHub или подключите альфа канал в Nuget https://www.myget.org/F/vknet
Не забудьте включить пререлизы.

**Comment by Seekeer** [comment]
Спасибо. Уже прикрутил самописное решение, подожду стабильного релиза)

**Comment by inyutin-maxim** [comment]
@Seekeer Выпустил релиз, проверьте и отпишитесь по проблеме пожалуйста

**Comment by ghost** [comment]
@inyutin-maxim 
``` csharp
            var param = new VkNet.Model.RequestParams.WallGetParams() 
            { 
                        Count = 30, 
                        Extended = true, 
                        OwnerId = -39490001 
            };
                        var posts = _apiVKNet.Wall.Get(param);
```
С указанными @Seekeer параметрами, ошибка не обнаружилась)
