### ISSUE TITLE
Отсуствуют поля для администратора бесед.

### ISSUE THREAD

**Issue by davidsl4** [vknet/vk#705]
Перед созданием нового бага, пожалуйста попробуйте использовать последнюю версию из nuget. 
Если проблема продолжает воспроизводиться, то для создания нового бага отразите краткую суть проблемы в заголовке и заполните следующие пункты:

1. Target для .NET используемый в проекте: (Официально поддерживаем , .net 4.5, NETStandard2.0) (поставьте 'x' в квадратных скобках)
  - Все.
  
2. Класс и метод в котором возникла проблема:
  - В разделе бесед.

3. Пример кода для воспроизведения проблемы, пожалуйста указавыйте конкретные значения параметров запроса: Не имеет значение

4. JSON ответа: VK API возвращает теперь администраторов бесед, массив.

5. Если в примере не указаны конкретные значения параметров запроса укажите их здесь: Добавить массив администраторов беседы, для удобной работы.

6. PS Если у вас появился вопрос по работе функциональности, то обратитесь за помощью в [![Telegram Chat](https://img.shields.io/badge/Chat-Telegram-0F80C1.svg)](https://t.me/VkDotNet), или напишите [мне](https://telegram.me/inyutin_maxim), не нужно плодить задачи типа как работает ф-я X, в противном случае буду закрывать без объяснения причины. После разбора проблемы будем дополнять документацию более полными примерами

**Comment by inyutin-maxim** [comment]
@davidsl4 
Приложите JSON ответа от vk: https://github.com/vknet/vk/wiki/Logging
В документации ничего такого не нашел: https://vk.com/dev/objects/conversation

**Comment by davidsl4** [comment]
![Пример](https://i.imgur.com/4AtSWrh.png)
[Метод](https://vk.com/dev/messages.getConversationsById?params[v]=5.101)
