### ISSUE TITLE
Access denied при вызове GetUploadServer или GetMessagesUploadServer

### ISSUE THREAD

**Issue by jenokizm** [vknet/vk#708]
Привет, в чем может быть проблема?
Код:
```
           var api = new VkApi();

            api.Authorize(new ApiAuthParams
            {
                AccessToken = token
            });
            Console.WriteLine(api.Token);
            var res = api.Groups.Get(new GroupsGetParams());

            Console.WriteLine(res.TotalCount);

            var getUploadServer = api.Docs.GetUploadServer();
```
Токен исправен. Пользователь тоже. Группы получает. А вот когда дело доходит до GetUploadServer выкидывает исключение:

> VkNet.Exception.CannotBlacklistYourselfException: "Access denied: no access to call this method"

**Comment by inyutin-maxim** [comment]
@jenokizm  а ты уверен что в токене содержится скоуп разрешающий дергать эту категорию методов?
А еще у нас есть уютный канал в телеграмме с активным сообществом https://t.me/VkDotNet

**Comment by jenokizm** [comment]
> @jenokizm а ты уверен что в токене содержится скоуп разрешающий дергать эту категорию методов?

А вот незнаю) Он есть, но токен от вк лайва. Возможно там запрет на лайв может быть. Или может дело в том что акк. без подтвержденного номера телефона)


> А еще у нас есть уютный канал в телеграмме с активным сообществом https://t.me/VkDotNet

хм)

**Comment by jenokizm** [comment]
Да ты прав. Не хватало прав) Получил новый токен со всеми правами, теперь работает)
