### ISSUE TITLE
Почему истекает токен?

### ISSUE THREAD

**Issue by jenokizm** [vknet/vk#714]
При авторизации параметр TokenExpireTime не задавал. По дефолту написано он равен 0, а значит действия токена бесконечно. Но воспользовавшись им спустя 3 дня после получения выскакивает ошибка

> VkNet.Exception.UserAuthorizationFailException: "User authorization failed: access_token has expired."

Мне кажется такого быть не должно. У меня есть токен от vk live которому пол года и он прекрасно работает до сих пор.

**Comment by itsokto** [comment]
Если при авторизации не передаётся `Settings.Offline`, то токен бессрочным не будет.
По умолчанию токен активен в течении **86400** сек.

**Comment by jenokizm** [comment]
Хм, так я ставил Settings.All

**Comment by jenokizm** [comment]
Аа щас прочел что Settings.All без Settings.Offline. А как задать Settings.All + Settings.Offline ?

**Comment by inyutin-maxim** [comment]
@jenokizmSettings.All + Settings.Offline  в коде должно выглядеть как:
```csharp
Settings = Settings.All | Settings.Offline 
```
