### ISSUE TITLE
GetDialogs невозможно получить количество непрочитанных сообщений

### ISSUE THREAD

**Issue by ResPasha** [vknet/vk#72]
Json:
response: {count: 57,unread_dialogs: 1,items: [{unread: 1,message: {id: 53481,date: 1425732679,out: 0,user_id: 123456789,read_state: 0,title: ' ... ',body: 'Проверка'}}]}

Поле unread элемента массива items просто игнорируется. Метод GetDialogs в любом случае возвращает ReadOnlyCollection of Message.
Api 5.28

**Comment by CaCTuCaTu4ECKuu** [comment]
out unreadCount возвращает количество диалогов, в которых содержатся непрочитанные сообщения, а не общее кол-во непрочитанных сообщений
unreadCount = unreadDialogs

**Comment by CaCTuCaTu4ECKuu** [comment]
Оу, я понял о чем вы, если нужно добавлю конечно =)

**Comment by ResPasha** [comment]
Нужно) Спасибо
