### ISSUE TITLE
Не удаётся вернуть UserId активного аккаунта.

### ISSUE THREAD

**Issue by Shark-vil** [vknet/vk#730]
UserId аккаунта постоянно выдаёт 0.

Кратко о коде. Авторизация происходит вот таким образом:
```C++
VkApi[] zombie = new VkApi[rows];
for (int i = 0; i < rows; i++)
{
  if (logs) Console.WriteLine("Авторизация бота...");
  zombie[i] = new VkApi();
  zombie[i].Authorize(new ApiAuthParams
  {
    AccessToken = zombie_list[i],
  });
}
```
Все активные аккаунты хранятся в массиве **zombie**. После чего, в другом цикле я пытаюсь получить список друзей:
```C++
var GetFriends = zombie[i].Friends.Get(new VkNet.Model.RequestParams.FriendsGetParams
{
  UserId = zombie[i].UserId.Value,
  Count = 5000,
});
```
Однако тут критует ошибку, ибо UserId всегда возвращает 0. В чём может быть проблема?

К слову, не важно как я пишу:
```C++
zombie[i].UserId.Value
// или
zombie[i].UserId
// ноль вернёт в обоих случаях
```

**Comment by truecooler** [comment]
Вы авторизовываетесь с помощью токена, который может принадлежать не только пользователю, но и например группе. Ид пользователя автоматически выставляется при авторизации через логин,пароль и ид приложения. Вы можете использовать этот способ, если это приемлемо для вашего приложения. Не уверен, но возможно есть метод у апи ВК, который позволит вытянуть ид по токену

**Comment by Shark-vil** [comment]
> Вы авторизовываетесь с помощью токена, который может принадлежать не только пользователю, но и например группе. Ид пользователя автоматически выставляется при авторизации через логин,пароль и ид приложения. Вы можете использовать этот способ, если это приемлемо для вашего приложения. Не уверен, но возможно есть метод у апи ВК, который позволит вытянуть ид по токену

То есть, используя токен пользователя, эти данные не получится получить, только при обычной авторизации возможно?

**Comment by itsokto** [comment]
@Shark-vil как написали уже выше UserId присваивается только при авторизации через логин:пароль.
Как вариант можно использовать: `Users.Get(new List<long> {}).FirstOrDefault();` для получении информации о профиле.

**Comment by Shark-vil** [comment]
> @Shark-vil как написали уже выше UserId присваивается только при авторизации через логин:пароль.
> Как вариант можно использовать: `Users.Get(new List<long> {}).FirstOrDefault();`

Спасибо большое, работает )
