### ISSUE TITLE
Попытка конвертировать строку в числовое представление выдает исключение

### ISSUE THREAD

**Issue by impaxel** [vknet/vk#732]
Столкнулся с такой неприятностью, когда выгружал участников голосования. Вернулся пользователь, у которого перепутаны поля "facebook" и "facebook_name".

![default](https://user-images.githubusercontent.com/15705702/48261678-e79a1c80-e430-11e8-9c10-0cb469d10f4c.png)

Из-за чего, при попытке преобразовать значение поля "facebook" в `long FacebookId`, все падает.

Запрос:

> `var user = api.Users.Get(new List<long> { 476800262 }, ProfileFields.Connections);`

StackTrace:

>    в System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    в System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
>    в System.Convert.ToInt64(String value)
>    в VkNet.Utils.Utilities.GetNullableLongId(VkResponse response)
>    в VkNet.Model.Connections.FromJson(VkResponse response)
>    в VkNet.Utils.VkResponse.op_Implicit(VkResponse response)
>    в VkNet.Model.User.FromJson(VkResponse response)
>    в VkNet.Utils.VkResponse.op_Implicit(VkResponse response)
>    в VkNet.Categories.UsersCategory.<>c.<Get>b__12_0(VkResponse x)
>    в System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
>    в System.Collections.Generic.List`1..ctor(IEnumerable1 collection)
>    в VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable1 source)
>    в VkNet.Utils.VkResponseEx.ToReadOnlyCollectionOf[T](IEnumerable1 responses, Func2 selector)
>    в VkNet.Categories.UsersCategory.Get(IEnumerable1 userIds, ProfileFields fields, NameCase nameCase, Boolean skipAuthorization)

**Comment by itsokto** [comment]
Это скорее баг вк, чем vknet. Можно конечно https://github.com/vknet/vk/blob/aa8d1cf45fffd427dddbd8831e7af5d9e55a292c/VkNet/Model/Connections.cs#L25
сделать как строку.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
