### ISSUE TITLE
5.90 Параметр random_id в методе messages.send обязателен.

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#749]
Параметр **random_id** в методе [messages.send](https://vk.com/dev/messages.send) обязателен.

**Comment by CaCTuCaTu4ECKuu** [comment]
А это вроде работает. Поле есть, всё отправляется. Или здесь что-то другое имеется в виду?

**Comment by CaCTuCaTu4ECKuu** [comment]
В 1.40.0 уже была поднята версия API так что ошибка теперь вылетает если отправить без этого поля

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
