### ISSUE TITLE
5.92 Новый формат объекта message

### ISSUE THREAD

**Issue by GooG2e** [vknet/vk#750]
Начиная с апи 5.92 объект message имеет новый формат https://vk.com/dev/objects/message
В частности разделяются пересланные сообщения и сообщение, на которое дался ответ.
Принципиальное отличие в том, что для отвеченного сообщения возвращается уникальный id

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
