### ISSUE TITLE
Add Logout() method

### ISSUE THREAD

**Issue by worldbeater** [vknet/vk#751]
**Is your feature request related to a problem? Please describe.**

Currently, there is no way to clean the `VkApi` instance from cached auth data. See https://github.com/vknet/vk/blob/develop/VkNet/VkApi.cs#L693

**Describe the solution you'd like**

It's worth adding `Logout()` method to `VkApi` class, so a VkNet user can simply call the logout method to remove saved access_token etc.

**Additional context**

Possibly related to https://github.com/vknet/vk/issues/588 and could be implemented in the auth manager.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet

**Comment by worldbeater** [comment]
Супер-пупер ✨, спасибо!
