### ISSUE TITLE
GetCounters NullReferenceException

### ISSUE THREAD

**Issue by ghost** [vknet/vk#757]
``` csharp
            var counters = _api.Account.GetCounters(CountersFilter.All);
            Console.WriteLine(counters.Groups.ToString());
            Console.ReadKey();
```
https://vk.com/dev/account.getCounters - не работает только у меня?

**Comment by itsokto** [comment]
NullReferenceException выбрасывает в 

> `Console.WriteLine(counters.Groups.ToString());`

Метод возвращает `null`, если счётчики пусты.

**Comment by ghost** [comment]
Ошибся) 
Смотрел не те счётчики))
