### ISSUE TITLE
NullReferenceException в Document.Type

### ISSUE THREAD

**Issue by vabka** [vknet/vk#762]
![image](https://user-images.githubusercontent.com/17644379/50051884-66732b00-013c-11e9-9dd5-33a5f2002a95.png)
В документации к последней версии API данное поле хранит только число, которое обозначает тип документа
https://vk.com/dev/objects/doc

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
