### ISSUE TITLE
Утечка памяти (pinnablebuffercache leak)

### ISSUE THREAD

**Issue by sel1** [vknet/vk#763]
Неправильное использование HttpClient  приводит к утечке памяти. За сутки работы объем процесса превышает 1 Гб. Подробное описание проблемы и варианты решения можно посмотреть по ссылкам ниже. Если вкратце, то не нужно при каждом запросе создавать HttpClient или HttpWebRequest. Лучше всего создать одну инстанцию HttpClient/HttpWebRequest в VkApi и делать все запросы через неё.

Ссылки
[YOU'RE USING HTTPCLIENT WRONG AND IT IS DESTABILIZING YOUR SOFTWARE](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong)

[HttpClient приводит к утечке Node <Object> в mscorlib](http://qaru.site/questions/617509/httpclient-resulting-in-leaking-nodeobject-in-mscorlib)

Больше информации можно найти по запросу pinnablebuffercache leak в гугле

**Comment by inyutin-maxim** [comment]
@sel1 Довольно странно, у нас HttpClient зарегистрирован как Синглтон.
https://github.com/vknet/vk/blob/cfda9a28200f8c02d04a0d2b2ec2de90bae2e8b1/VkNet/Utils/TypeHelper.cs#L39

Возьмем на проработку

**Comment by truecooler** [comment]
> @sel1 Довольно странно, у нас HttpClient зарегистрирован как Синглтон.
> [vk/VkNet/Utils/TypeHelper.cs](https://github.com/vknet/vk/blob/cfda9a28200f8c02d04a0d2b2ec2de90bae2e8b1/VkNet/Utils/TypeHelper.cs#L39)
> 
> Line 39 in [cfda9a2](/vknet/vk/commit/cfda9a28200f8c02d04a0d2b2ec2de90bae2e8b1)
> 
>  container.TryAddSingleton<HttpClient>(); 
> Возьмем на проработку

httpclient действительно создается каждый раз при новом запросе
[vk/VkNet/Utils/RestClient.cs](https://github.com/vknet/vk/blob/cfda9a28200f8c02d04a0d2b2ec2de90bae2e8b1/VkNet/Utils/RestClient.cs#L90)

**Comment by inyutin-maxim** [comment]
> > @sel1 Довольно странно, у нас HttpClient зарегистрирован как Синглтон.
> > [vk/VkNet/Utils/TypeHelper.cs](https://github.com/vknet/vk/blob/cfda9a28200f8c02d04a0d2b2ec2de90bae2e8b1/VkNet/Utils/TypeHelper.cs#L39)
> > Line 39 in [cfda9a2](/vknet/vk/commit/cfda9a28200f8c02d04a0d2b2ec2de90bae2e8b1)
> > container.TryAddSingleton();
> > Возьмем на проработку
> 
> httpclient действительно создается каждый раз при новом запросе
> [vk/VkNet/Utils/RestClient.cs](https://github.com/vknet/vk/blob/cfda9a28200f8c02d04a0d2b2ec2de90bae2e8b1/VkNet/Utils/RestClient.cs#L90)

Хм, да, действительно, но код теперь обернут в using и по выполнении должен диспоузиться

**Comment by sel1** [comment]
Похоже после этих правок перестала работать настройка прокси. Ниже привожу код инициализации api, после чего запросы к VK отправляются минуя прокси.
nuget package VkNet version="1.43.0"
          
```
api.Authorize(new ApiAuthParams
                {
                    AccessToken = accessToken,
                    Host = host,
                    Port = port,
                });
```

**Comment by inyutin-maxim** [comment]
@sel1 Теперь это происходит иначе. @itsokto подскажи пожалуйста

**Comment by sel1** [comment]
Поясните пожалуйста, как теперь осуществляется работа через прокси. Не нашёл в документации

**Comment by itsokto** [comment]
> Поясните пожалуйста, как теперь осуществляется работа через прокси. Не нашёл в документации

После релиза 1.44.0 работа с прокси станет легче. В [Wiki](https://github.com/vknet/vk/wiki) напишу как настроить. 
Сейчас нужно установить пакет [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http/) и далее:
``` C#
var serviceCollection = new ServiceCollection(); 
var httpProxy = new WebProxy("88.147.254.202:3128");
serviceCollection.AddHttpClient<IRestClient, RestClient>().ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler { Proxy = httpProxy, UseProxy = true });
var api = new VkApi(serviceCollection);
```

**Comment by sel1** [comment]
Версия 1.44 уже вышла, рекомендация из предыдущего письма к ней применима? Как понял эта рекомендация для проекта net core, у меня проект на net framework 4.5, пакет Microsoft.Extensions.Http по всей видимости только для core. Нового описания работы с proxy в wiki не нашел

**Comment by itsokto** [comment]
> Версия 1.44 уже вышла, рекомендация из предыдущего письма к ней применима? Как понял эта рекомендация для проекта net core, у меня проект на net framework 4.5, пакет Microsoft.Extensions.Http по всей видимости только для core. Нового описания работы с proxy в wiki не нашел

Используйте рекомендации из этого комментария https://github.com/vknet/vk/issues/845#issuecomment-500034996 и issue https://github.com/vknet/vk/issues/845 чтобы отслеживать прогресс.

Этот issue будет закрыт, т.к. ошибка исправлена еще в версии 1.42.0.
