### ISSUE TITLE
Метод Docs.Save не возвращает значения.

### ISSUE THREAD

**Issue by roland-x** [vknet/vk#772]
Добрый вечер, нашёл баг в методе _api.Docs.Save

Проблема заключается в том, что метод не возвращает ответа. Объект остается пустым.
```csharp
// Получить адрес сервера для загрузки.
var uploadServer = _api.Docs.GetUploadServer();
// Загрузить файл.
var wc = new WebClient();
wc.Proxy = wp;
var responseFile = System.Text.Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, documentPath));
// Сохранить загруженный файл
var doc = _api.Docs.Save(responseFile, documentName);
string docId = doc[0].Id.ToString();
string ownerId= doc[0].OwnerId.ToString();
```

По логу видно, что ответ приходит, но метод ничего не возвращает.
Лог прикрепляю.

![default](https://user-images.githubusercontent.com/36973678/50577240-03b4ab80-0e2d-11e9-8289-0a705f1c820a.png)
[file.txt](https://github.com/vknet/vk/files/2719708/file.txt)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
