### ISSUE TITLE
Too thin fonts on Documentation GitHub Pages

### ISSUE THREAD

**Issue by nevack** [vknet/vk#773]
**Describe the bug**
Documentation on GitHub Pages is rendered with too thin font Helvetica Neue on macOS.

**To Reproduce**
1. Open documentation on an apple device

**Expected behavior**
Normal weight font, like Helvetica (not Neue) or Arial

**Screenshots**
![image](https://user-images.githubusercontent.com/8330119/50666437-cc2d3700-0fc5-11e9-847a-3408c09fa73f.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - Browser Chrome 73

**Comment by nevack** [comment]
Same in latest Safari 12

**Comment by CaCTuCaTu4ECKuu** [comment]
Is this a full screen screenshot? I cannot compare scale to UI elements.
Also how about scaling to like 50% ?)

**Comment by nevack** [comment]
> Is this a full screen screenshot?
Nope.

This one is 100%.
![image](https://user-images.githubusercontent.com/8330119/50710967-98ade380-107d-11e9-9f79-b4fc9b96cf7c.png)
50%
![image](https://user-images.githubusercontent.com/8330119/50711001-b7ac7580-107d-11e9-8e49-f137c1c0cc44.png)

**Comment by CaCTuCaTu4ECKuu** [comment]
That's, actually, not that bad as i thought, but definitely not user friendly

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. **Спасибо за проделанную работу**
