### ISSUE TITLE
message.PhotoPreviews

### ISSUE THREAD

**Issue by DeNcHiK3713** [vknet/vk#778]
Вызываю метод Messages.GetById, получаю VkCollection<Message>
Далее для одного сообщения вызываю message.PhotoPreviews, мне возвращает(по факту не возвращает) ссылки(разных размеров) на одну фотографию. По идее мне должен возвратится список/массив т.к. в сообщениях может быть до 10 фото.

**Comment by inyutin-maxim** [comment]
@DeNcHiK3713 Приложите логи https://github.com/vknet/vk/wiki/Logging

**Comment by DeNcHiK3713** [comment]
Вот код:
```csharp
using System;
using Microsoft.Extensions.DependencyInjection;
using VkNet;
using VkNet.NLog.Extensions.Logging;
using VkNet.Model;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using VkNet.NLog.Extensions.Logging.Extensions;

namespace vkapi
{
    class Program
    {
        static void Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddSingleton<ILoggerFactory, LoggerFactory>();
            services.AddSingleton(typeof(ILogger<>), typeof(Logger<>));
            services.AddLogging(builder =>
            {
                builder.ClearProviders();
                builder.SetMinimumLevel(LogLevel.Trace);
                builder.AddNLog(new NLogProviderOptions
                {
                    CaptureMessageProperties = true,
                    CaptureMessageTemplates = true
                });
            });
            NLog.LogManager.LoadConfiguration("Properties\\nlog.config");
            VkApi vkApi = new VkApi(services);
            vkApi.Authorize(new ApiAuthParams { AccessToken = "" });
            List<string> photosids = new List<string>();
            foreach (Message message in vkApi.Messages.GetById(new List<ulong> { 61717, 61718, 61719, 61720, 61721, 61722 }, new List<string>()))
            {
                Previews previews = message.PhotoPreviews;
                Console.WriteLine(previews.PhotoMax);
            }
            Console.Read();
        }
    }
}
```
Вот лог: 
[file.txt](https://github.com/vknet/vk/files/2772463/file.txt)
Токен и ссылки на сами фото я убрал(изначально было "url": "...")

**Comment by DeNcHiK3713** [comment]
Console.WriteLine(previews.PhotoMax); выдавало пустую строку

**Comment by inyutin-maxim** [comment]
Ошибки нет никакой, vk такой json присылает, исходя из ответа в **message.PhotoPreviews** и не должно было быть ничего

**Comment by DeNcHiK3713** [comment]
Нет, я же говорю в json были ссылки на фото, я их убрал. Также PhotoPreviews всегда возвращает 1 экземпляр Previews, и MaxPhoto возвращает только 1 ссылку(не массив из одного элемента). Пример, у меня 10 фото в одном сообщении, получаю message.PhotoPreviews.MaxPhoto. Какое из них мне вернется?

**Comment by inyutin-maxim** [comment]
@DeNcHiK3713 Попробуйте здесь:

https://vk.com/dev/messages.getById

И я уверен что ответ придет тот же, а значит это vk такие данные присылает.
telegram: https://t.me/VkDotNet

**Comment by DeNcHiK3713** [comment]
нет, как раз таки там тоже были ссылки. Мне вчера нужно было скачать 60 фото, из 6 сообщения, только там и скачал

**Comment by DeNcHiK3713** [comment]
![image](https://user-images.githubusercontent.com/35270280/51406099-2c48df00-1b69-11e9-9e3a-6dd94b7fdddd.png)

**Comment by inyutin-maxim** [comment]
@DeNcHiK3713 Так и не увидел поля соответствующее PhotoPreviews

**Comment by DeNcHiK3713** [comment]
а sizes?

**Comment by inyutin-maxim** [comment]
@DeNcHiK3713 Sizes принадлежит полю attachements в котором лежат вложения типа Photo в котором есть поле sizes

https://github.com/vknet/vk/blob/e585c88ce181dccb989889ab743d8e74d5b74847/VkNet/Model/Attachments/Photo.cs#L52

**Comment by DeNcHiK3713** [comment]
Большое спасибо, извиняюсь за потраченное время и свою глупость
