### ISSUE TITLE
Сделать сборку под WinRT

### ISSUE THREAD

**Issue by azhidkov** [vknet/vk#78]

**Comment by CaCTuCaTu4ECKuu** [comment]
Я думаю стоит подождать выхода Windows 10 и там уже разбираться что да как, собираются ведь сделать платформу одну на всех устройствах. Или я не видел или нет инфы как это будет выглядеть для программистов

**Comment by kristx300** [comment]
Выход анонсирован на осень 2015.
Мб сделаете сборку для WinRT с одним методом Invoke? :)
сейчас просто сам копаюсь в winrt как создать браузер и работать с api....
пытаюсь сам писать... но всё через одно место :)
Надеюсь вы поможете

**Comment by inyutin-maxim** [comment]
> прочитал закрытую тему
https://github.com/vknet/vk/issues/78
так вот
Выход анонсирован на осень 2015.
Мб сделаете сборку для WinRT с одним методом Invoke? :) и соответственно аутентификацией
 сейчас просто сам копаюсь в winrt как создать браузер и работать с api....
пытаюсь сам писать... но всё через одно место :)
Надеюсь вы поможете
с моей же стороны я могу помочь, заполнением методов с vk.com/dev/methods
и будет нам збс :)
P.S. если что свяжитесь со мной maelstorm_wf@list.ru

Так как задача #85 полностью дублирует эту то ее закрываю а комментарий переношу сюда, для истории сообщений

**Comment by CaCTuCaTu4ECKuu** [comment]
Думаю RT будет не скоро если вообще кто-то за это возьмется

**Comment by inyutin-maxim** [comment]
#318
