### ISSUE TITLE
Не удалось загрузить файл или сборку "Microsoft.Extensions.DependencyInjection.Abstractions"

### ISSUE THREAD

**Issue by VanKrock** [vknet/vk#783]
Ошибка при использовании DependencyInjection

Не удалось загрузить файл или сборку "Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=8df3f1eee85cc956" либо одну из их зависимостей. Найденное определение манифеста сборки не соответствует ссылке на сборку. (Исключение из HRESULT: 0x80131040)

Такая же проблема при использовании Microsoft.Extensions.Logging.Abstractions

Я так понимаю проблема кроется в использовании кастомных пакетов

**Comment by itsokto** [comment]
@VanKrock https://docs.microsoft.com/ru-ru/nuget/reference/migrate-packages-config-to-package-reference

**Comment by VanKrock** [comment]
@itsokto У меня так и используется

``` xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.2.0" />
    <PackageReference Include="VkNet" Version="1.41.0" />
  </ItemGroup>
```

И в коде вызываю так:
``` csharp
      var services = new ServiceCollection();
      services.AddLogging(x => x.AddConsole());
      services.AddSingleton<VkAuthorizer>();
      services.AddSingleton(x => new VkAuthSettings
      {
          ClientId = "My client id",
          Scopes = new[] { "wall", "offline", "pages" }
      });
      services.AddSingleton<IAuthorizationFlow, VkAuthorizationFlow>();
      services.AddSingleton<IVkApi, VkApi>();
      services.AddSingleton<ICaptchaSolver>(x => null);
      var provider = services.BuildServiceProvider();
      var vkApi = provider.GetRequiredService<IVkApi>();
```

На последней строке ловлю исключение, так как Public Token у сборок не совпадает

**Comment by VanKrock** [comment]
Это тоже не помогает
``` xml
  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
```

**Comment by itsokto** [comment]
@VanKrock Вы пробовали установить Microsoft.Extensions.DependencyInjection.**Abstractions**?

**Comment by itsokto** [comment]
https://github.com/vknet/vk/wiki/Logging

**Comment by VanKrock** [comment]
@itsokto Да пробовал, то же самое, по сути у меня нет проблем с Microsoft.Extensions.DependencyInjection.Abstractions так как dll из этого проекта загружена в домен. У меня проблема, что NetFx.Extensions.DependencyInjection.Abstractions не может положить свою сборку в bin
Логирование я знаю как настроить, на данный момент мне нужно только в консоль.

**Comment by itsokto** [comment]
@VanKrock можно отключить логирование в файл немного подправив config.

**Comment by VanKrock** [comment]
@itsokto Я знаю, но это не суть вопроса

**Comment by VanKrock** [comment]
@itsokto Логирование у меня работает, у меня не работает сборка VkApi через DI

**Comment by itsokto** [comment]
@VanKrock попробуйте оставить в зависимостях только **VkNet** и **VkNet.NLog.Extensions.Logging**

**Comment by VanKrock** [comment]
@itsokto Так заработает, так как будут использоваться только библиотеки NetFX, но у меня есть и другие библиотеки которые зависят от Microsoft.Extensions.DependencyInjection.Abstractions, получается, что их я не смогу использовать. Так же логирование у меня через log4net, а не Nlog, поэтому я везде использую только абстракцию Microsoft.Extensions.Logging.Abstractions

**Comment by inyutin-maxim** [comment]
14303cfe8edfc56e3908adca3f9a1d479488d551
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
