### ISSUE TITLE
Не возвращается поле from_id в методе Messages.getHistory

### ISSUE THREAD

**Issue by ResPasha** [vknet/vk#79]
response: {count: 577,items: [{id: 54755,body: 'txt',user_id: 111111,from_id: 555555,date: 1426027892,read_state: 1,out: 1}]}

Такой JSON приходит пользователю 555555, если сообщение было отправлено пользователю 111111.

В остальных случаях (для сообщений групповых конференций и входящих личных сообщений) from_id совпадает с user_id.

**Comment by inyutin-maxim** [comment]
Реализовал недостающие поля класса Message. Закрываю задачу
