### ISSUE TITLE
Исключение при использовании двухфакторной авторизации с Windows Forms

### ISSUE THREAD

**Issue by pitfisher** [vknet/vk#793]
Описание
Попытка вызвать функцию Authorize с двухфакторной авторизацией по нажатию кнопки в приложении Windows Forms приводит к выбрасыванию исключения System.InvalidOperationException: "Эта операция не поддерживается для относительных URI-адресов."

Воспроизведение
1. Создать в Visual Studio 2017 проект с Windows Forms
2. Добавить на форму кнопку
3. Добавить в метод button_Click вызов функции api.Authorize
4. Запустить проект и нажать на кнопку

Скриншот кода
![default](https://user-images.githubusercontent.com/25454223/52339871-5894a480-2a1f-11e9-8832-d994aa656d1f.JPG)

Подробности:
System.InvalidOperationException
  HResult=0x80131509
  Сообщение = Эта операция не поддерживается для относительных URI-адресов.
  Источник = System
  Трассировка стека:
   в System.Uri.get_AbsoluteUri()
   в VkNet.Utils.WebCall.MakeRequest(HttpResponseMessage response, Uri uri, IWebProxy webProxy)
   в VkNet.Utils.WebCall.Post(WebForm form, IWebProxy webProxy)
   в VkNet.Utils.Browser.FilledTwoFactorForm(Func`1 code, WebCallResult loginFormPostResult)
   в VkNet.Utils.Browser.Authorize(IApiAuthParams authParams)
   в VkNet.Utils.Browser.Authorize()
   в VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   в VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   в VkNet.VkApi.Authorize(IApiAuthParams params)
   в VkNet.VkApi.Authorize(ApiAuthParams params)
   в WindowsFormsApp1.Form1.button1_Click(Object sender, EventArgs e) в C:\Users\Petr-PC\source\repos\WindowsFormsApp1\WindowsFormsApp1\Form1.cs:строка 27
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   в System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   в System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   в System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   в System.Windows.Forms.Application.Run(Form mainForm)
   в WindowsFormsApp1.Program.Main() в C:\source\repos\WindowsFormsApp1\WindowsFormsApp1\Program.cs:строка 22

ПК
 - Windows 10
 - Visual Studio 2017

Пакет VK.API был установлен посредством nuget.

**Comment by inyutin-maxim** [comment]
Предлагаю как временный WorkArround предлагаю реализовать как в WPF примере:
Требуется только реализация интерфейса [IBrowser как здесь](https://github.com/vknet/vk/blob/master/examples/VkNet.Wpf/WpfAuthorize.cs)
И подсунуть ее в конструктор 3-м параметром

**Comment by pitfisher** [comment]
Спасибо, так и сделаю.

**Comment by inyutin-maxim** [comment]
@petrohiv Вам удалось решить свою проблему?

**Comment by pitfisher** [comment]
Использовал авторизацию через IBrowser, полностью как в WPF примере, но начиная со вторника стала появляться ошибка, представленная на скриншоте. Удалось установить, что проблема не в VkNet - с id тестового приложения всё работает корректно. Но, может, вы могли бы подсказать, в чём тут может быть дело? 
![vknet error](https://user-images.githubusercontent.com/25454223/53185143-79f4b380-360f-11e9-8226-955679919320.JPG)

**Comment by itsokto** [comment]
Проблема в дефолтном WebBrowser в WPF. Попробуйте использовать что-нибудь другое.

**Comment by itsokto** [comment]
Обсуждение проблем с авторизацией переносится в #997
