### ISSUE TITLE
Не получается отослать параметр PublishDate в метод wall.post

### ISSUE THREAD

**Issue by SunrayIsbro** [vknet/vk#794]
Для получение unixTime использовал такую функцию:
public static double UnixEncoding(DateTime date){
            DateTime origin = new DateTime(1970, 1, 1, 0, 0, 0, 0);
            TimeSpan diff = date - origin;
            return Math.Floor(diff.TotalSeconds);
}
Время получаю, но при вызове wall.post получаю ошибки. Написано, что PublishDate принимает тип данных DateTime, но не смотря на это получается ошибка: "Недопустимое приведение...".
Пробовал так: PublishDate = DateTime, PublishDate = Convert.ToDateTime(unixTime),
PublishDate = Convert.ToString(unixTime), PublishDate = unixTime и еще сотнями способами, но ни один из способов не дал результатов. Без параметра PublishDate все работает отлично. В чем моя ошибка?
P.s: Пишу на гитхабе первый раз, мог написать не туда, простите.

**Comment by CaCTuCaTu4ECKuu** [comment]
Проверьте что там нигде не закралась временная зона. У меня была проблема когда я приводил DateTime.MinDate потому что он приписывал мне зону +3 и в результате DateTimeOffset был отрицательным

**Comment by SunrayIsbro** [comment]
С помощью научного тыка каким-то образом решил свою проблему. Спасибо за быстрый ответ 👍

**Comment by Soniclev** [comment]
Вчера встречался с похожей проблемой, VkNet при отправке даты переводит в UniversalTime (метод DateTime, не знаю как по другому описать), поэтому на сервер отправляется время с 0 часовым поясом, даже если текущая временная зона +3 часа. Если указывать 00:00 сегодняшнего числа, то ВК получит дату как 21:00 вчерашнего числа.
