### ISSUE TITLE
Friends.GetMutual не работает со списком

### ISSUE THREAD

**Issue by mashed-potatoes** [vknet/vk#795]
Код:
```csharp
var mut = api.Friends.GetMutual(new FriendsGetMutualParams
{
    SourceUid = api.UserId,
    TargetUids = new long[] { 123123123 }
});
```

При любом значении `TargetUids` VkNet крашится:
```System.ArgumentException
Can not convert Object to Int64.
   в Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   в VkNet.Categories.FriendsCategory.<>c.<GetMutual>b__24_0(VkResponse x)
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в VkNet.Utils.VkResponseEx.ToReadOnlyCollectionOf[T](IEnumerable`1 responses, Func`2 selector)
   в VkNet.Categories.FriendsCategory.GetMutual(FriendsGetMutualParams params)
   в FriendsFromVK.Collector.GenerateConnections(Int64[] ids) в c:\users\mashed-potatoes\source\repos\FriendsFromVK\FriendsFromVK\Collector.cs:строка 27
```
Visual Studio 2017
Windows 10 LTSC 1809

**Comment by inyutin-maxim** [comment]
@mashed-potatoes Приложите пожалуйста логи
https://github.com/vknet/vk/wiki/Logging

**Comment by itsokto** [comment]
@inyutin-maxim там ответ от сервера в случае с `TargetUids` - массив объектов, а если `TargetUid` - массив чисел.

**Comment by itsokto** [comment]
Я думаю надо сделать два метода: один с `TargetUids`, а другой с `TargetUid`

**Comment by inyutin-maxim** [comment]
Ох вк, как я их ненавижу за такие вещи

**Comment by mashed-potatoes** [comment]
После добавления логгера в проект VS требует ссылку `Microsoft.Extensions.DependencyInjection.Abstractions`, которая уже есть. Мда.

**Comment by mashed-potatoes** [comment]
> Я думаю надо сделать два метода: один с `TargetUids`, а другой с `TargetUid`

Скорее всего это лучший вариант, либо сделать что-то вроде `FriendsGetMultipleMutualParams` и добавить перегрузку к `GetMutual`.
Вот ответ API при `target_uid`:
```json
{
  "response": [123]
}
```
При `target_uids`:
```json
{
  "response": [{
    "id": 123,
    "common_friends": [123],
    "common_count": 1
  }]
}
```

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet

**Comment by mashed-potatoes** [comment]
Всем спасибо!:tada:
