### ISSUE TITLE
У класса Call не хватает поля Duration

### ISSUE THREAD

**Issue by gagashaggy** [vknet/vk#796]
Если вызвать метод Messages.GetHistory для чата, в котором есть записи о голосовых вызовах, вылетает InvalidParameterException. Таким образом, получить историю чата в этом случае становится невозможно.

`The type 'call' of attachment is not defined. `

**Comment by inyutin-maxim** [comment]
@gagashaggy  Приложите пожалуйста логи
https://github.com/vknet/vk/wiki/Logging

**Comment by gagashaggy** [comment]
Весь лог прикладывать не буду, но вот фрагменты ответа от сервера с этими сообщениями:
```
{
        "date": 1549652603,
        "from_id": 78612071,
        "id": 323675,
        "out": 0,
        "peer_id": 78612071,
        "text": "",
        "conversation_message_id": 4713,
        "fwd_messages": [],
        "important": false,
        "random_id": 0,
        "attachments": [
          {
            "type": "call",
            "call": {
              "initiator_id": 78612071,
              "receiver_id": 177471085,
              "state": "reached",
              "time": 1549652603,
              "duration": 289
            }
          }
        ],
        "is_hidden": false
      },
```
и
```
{
        "date": 1549652274,
        "from_id": 78612071,
        "id": 323673,
        "out": 0,
        "peer_id": 78612071,
        "text": "",
        "conversation_message_id": 4711,
        "fwd_messages": [],
        "important": false,
        "random_id": 0,
        "attachments": [
          {
            "type": "call",
            "call": {
              "initiator_id": 78612071,
              "receiver_id": 177471085,
              "state": "canceled_by_initiator",
              "time": 1549652274
            }
          }
        ],
        "is_hidden": false
      },
```

**Comment by gagashaggy** [comment]
И стектрейс на всякий случай:
`An unhandled exception occurred: An unhandled exception occurred: The type 'call' of attachment is not defined. 
Тип исключения: VkNet.Exception.InvalidParameterException
Exception data:
   в VkNet.Model.Attachments.Attachment.FromJson(VkResponse response)
   в VkNet.Utils.JsonConverter.AttachmentJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   в Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   в VkNet.VkApi.Call[T](String methodName, VkParameters parameters, Boolean skipAuthorization, JsonConverter[] jsonConverters)
   в VkNet.Categories.MessagesCategory.GetHistory(MessagesGetHistoryParams params)
   в VkontakteChatGaga_Win.Controls.ChatControl.<<UserControl_Loaded>b__33_0>d.MoveNext() в D:\Users\Gagashaggy\Source\Repos\vkontaktechatgaga_win\VkontakteChatGaga_Win\VkontakteChatGaga_Win\Controls\ChatControl.xaml.cs:строка 322
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by itsokto** [comment]
@gagashaggy обновитесь до последней версии

https://github.com/vknet/vk/blob/495bfc342ba940a7c485d6953e28de1fc021258c/VkNet/Model/Attachments/Call.cs#L17

**Comment by gagashaggy** [comment]
Спасибо!

**Comment by inyutin-maxim** [comment]
@gagashaggy Проблема решена?

**Comment by gagashaggy** [comment]
Да

**Comment by gagashaggy** [comment]
Только не хватает поля Duration в классе Call

**Comment by inyutin-maxim** [comment]
a036ae60d7be74d7d6eb4cec0ea667a3c2b0c98f

Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
