### ISSUE TITLE
НЕ получается работать с массивом Items в wall.search

### ISSUE THREAD

**Issue by olovootsos** [vknet/vk#797]
Класс и метод в котором возникла проблема:
vkApi.Wall.Search

Код:
```csharp
  var search = vkApi.Wall.Search(new WallSearchParams
            {
                OwnerId = 267084143,
                Query = "планшет",
                OwnersOnly = true,
                Extended = false   
            });
            using (StreamWriter sw = new StreamWriter(@"C:\Users\Рустам\Desktop\Вк\txtId.txt", false, System.Text.Encoding.Default))
            {
                    sw.WriteLine(items[0]);
            }
```
Как мне работать с этим массивом? Программа просто его не видит. Он по другому называется? Например, в методе users.search с массивом users все отлично. А здесь нет.

**Comment by itsokto** [comment]
@olovootsos массив **items** это откуда вообще? Должно быть`sw.WriteLine(search.WallPosts[0]);`.

**Comment by inyutin-maxim** [comment]
@olovootsos https://github.com/vknet/vk/blob/44736d1a85d885540cff2b13cb5a44f9d1d34215/VkNet/Model/WallGetObject.cs#L12
