### ISSUE TITLE
Proxy  authorization V1.42

### ISSUE THREAD

**Issue by UltWolf** [vknet/vk#798]
Доброе время суток, у меня в стране запрещен ВК и хотелось бы как-то устранить эту проблему, более удобным и комфортным способом, но к сожалению, вылазит ошибка : 
`SocketException: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из`
Вот код, где реализуется добавление прокси :
```
 IWebProxy httpProxy = new System.Net.WebProxy(proxy);
                ServiceCollection serviceCollection = new ServiceCollection();
                serviceCollection.AddHttpClient<IRestClient, RestClient>().ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler() { Proxy = httpProxy, UseProxy = true });
                var api = new VkApi(serviceCollection);
                api.Authorize(new ApiAuthParams
                {
                    ApplicationId = *****,
                    Login = Email.Text,
                    Password = Password.Text,
                    Settings = Settings.Messages,
                });
                api.Messages.Send(new VkNet.Model.RequestParams.MessagesSendParams
                {
                    ChatId = api.UserId.Value,
                    Message = "message"
                });
```
Прокси рабочее, тестировал на простом соединении с ВК через HttpWebRequest, логин и пароль для него не нужен.  
Платформа: Windows 10. VS 2017. Версия библиотеки: 1.42.00

**Comment by itsokto** [comment]
@UltWolf если у вас прокси вида **ip**:**port**, то нужно инициализировать WebProxy так:
`... = new WebProxy(ip, port);`

**Comment by UltWolf** [comment]
Это какое-то расширение,  или какая-то другая либа? Просто   VkNet.Utils и  System.NET WebProxy у меня не содержат конструктор принимающий две строки, если это нужно отправлять, как  строки, конечно.

**Comment by UltWolf** [comment]
Переписав под IP и порты, все равно выдаёт ту-же ошибку

**Comment by UltWolf** [comment]
Нужно было добавить : _api.Browser.Proxy  и туда кинуть Proxy .
