### ISSUE TITLE
BigPhotoSrc возвращает null

### ISSUE THREAD

**Issue by SunrayIsbro** [vknet/vk#799]
Не получается получить ссылку на фотографию с максимальным размером. 
```javascript
 IEnumerable<string> m_oEnum = new List<string>() { "141555078_456258276" };
            var get = api.Photo.GetById(photos:m_oEnum);
            foreach(var ph in get)
            {
                listBox2.Items.Add(ph.BigPhotoSrc);
            }
        }
```
![image](https://user-images.githubusercontent.com/24867061/53018217-dbc3ea80-3462-11e9-8e6f-211466c1eb03.png)

**Comment by itsokto** [comment]
@SunrayIsbro поле устарело. Используй **Sizes**.
Подробнее в [документации ](https://vk.com/dev/objects/photo)ВК.

**Comment by SunrayIsbro** [comment]
@itsokto , Получаю все размеры, а есть возможность получить только самое большое изображение?
![image](https://user-images.githubusercontent.com/24867061/53019780-8d184f80-3466-11e9-8140-5e4999938363.png)

**Comment by itsokto** [comment]
@SunrayIsbro самое большое с типом **w**
