### ISSUE TITLE
Лимит подключений по Api

### ISSUE THREAD

**Issue by mat0thew** [vknet/vk#80]
Как быть с лимитами подключений по api?

К примеру реальный кейс: у меня есть 5000 аккаунтов вк и я хочу проверить их на валидность.

**Comment by CaCTuCaTu4ECKuu** [comment]
Это Api для работы с Vk, а не решение всех рабочих проблем. Я использую его для личных проектов и подобные моменты решать должны вы. Я с лимитами пока не сталкивался, но полагаю разбивать на несколько машин с разными Ip

**Comment by mat0thew** [comment]
@CaCTuCaTu4ECKuu надо сперва проверить есть ли там вообще лимит

**Comment by CaCTuCaTu4ECKuu** [comment]
Тогда к чему вопрос? У Vk есть ограничение по запросам в секунду с аккаунта и для приложений с малым кол-вом участников это 3, на ограничение по кол-ву аккаунтов с одного Ip там нигде не написано, хоть 10 одновременно аккаунтов и каждый делает по 3 запроса

**Comment by azhidkov** [comment]
> К примеру реальный кейс: у меня есть 5000 аккаунтов вк и я хочу проверить их на валидность.

Как возможный вариант можно авторизоваться под каждым аккаунтом и проверить результат - если выбросится исключение - аккаунт невалидный, если всё ок и свойство AccessToken содержит информацию - аккаунт валидный. 

Примерный код
```csharp
var accounts = new Dictionary<string, string>  {
    {"login_or_email_1", "password"},
    ...
    {"login_or_email_5000", "password"},
};

foreach (var account in accounts) {
    var api = new VkApi();

    try
    {
        api.Authorize(appId, accounts.Key, accounts.Value, Settings.All);
    }
    catch
    {
        Console.WriteLine("account {0} is NOT valid", account.Key); 
        continue;
    }

    Console.WriteLine("account {0} {1} valid", account.Key, 
        string.IsNullOrEmpty(api.AccessToken) ? "is NOT" : "IS"); 
}
```

Код скорее всего не сбилдится, но показана общая схема как я вижу можно проверить 5000 аккаунтов.

**Comment by mat0thew** [comment]
Хм, а в библиотеке стандартный враппер для парсинга страниц?

**Comment by azhidkov** [comment]
Не совсем понял что имеете ввиду под стандартным враппером для парсинга страниц. Для разбора html используется HtmlAgilityPack.

**Comment by mat0thew** [comment]
@azhidkov забудьте :)

**Comment by CaCTuCaTu4ECKuu** [comment]
Так что, вопрос закрыт?)

**Comment by mat0thew** [comment]
+
