### ISSUE TITLE
Новые методы

### ISSUE THREAD

**Issue by novifyeer** [vknet/vk#800]
Появились новые методы:
- [x] https://vk.com/dev/database.getMetroStations
- [x] https://vk.com/dev/database.getMetroStationsById

В методе https://vk.com/dev/groups.edit появился параметр addresses (boolean) — включает/выключает адреса в сообществе.

**Comment by inyutin-maxim** [comment]
> В методе https://vk.com/dev/groups.edit появился параметр addresses (boolean) — включает/выключает адреса в сообществе.

https://github.com/vknet/vk/blob/d4510d3e42479aff1ae43edee25b8ffbc350c8e8/VkNet/Model/RequestParams/Groups/GroupsEditParams.cs#L247

**Comment by inyutin-maxim** [comment]
Методы категории Groups перенесены в #847
