### ISSUE TITLE
Проблема с вложением 

### ISSUE THREAD

**Issue by kachan28** [vknet/vk#801]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kachan28** [comment]
Добрый вечер. Пытаюсь прикрепить при отправке сообщения текстовый документ. Подскажите, пожалуйста, делаю все по документации, выдает ошибку:
Ошибка	CS0266	Не удается неявно преобразовать тип "System.Collections.ObjectModel.ReadOnlyCollection<VkNet.Model.Attachments.Attachment>" в "System.Collections.Generic.IEnumerable<VkNet.Model.Attachments.MediaAttachment>". Существует явное преобразование (возможно, пропущено приведение типов).	Вот код `File.WriteAllText(Path.Combine(ImageFilePath, "Images.txt"), string.Empty);
                File.WriteAllText(Path.Combine(ImageFilePath, "Images.txt"), crattachments);

                UploadServerInfo uploadServer = MainWindow.api.Docs.GetUploadServer();
                // Загрузить файл.
                WebClient wc = new WebClient();
                string responseFile = Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, Path.Combine(ImageFilePath, "Images.txt")));
                // Сохранить загруженный файл
                var attachments = MainWindow.api.Docs.Save(responseFile, "doc");


                try
                {
                    api.Messages.Send(new MessagesSendParams
                    {
                        UserId = idsob,
                        RandomId = randid,
                        Message = crmessage,
                        Attachments = attachments
                    });
                }`

**Comment by itsokto** [comment]
``` C# 
var attachments = MainWindow.api.Docs.Save(responseFile, "doc").Select(x => x.Instance);
 ```

**Comment by vse3211** [comment]
А нельзя было сразу в Wiki обновить информацию?
Люди столько времени убивают на то, чтобы разобраться самостоятельно и все в пустую

**Comment by vse3211** [comment]
Я 2 часа потратил из-за не корректно написанной статьи: [https://vknet.github.io/vk/docs/save/](url)

**Comment by inyutin-maxim** [comment]
> Я 2 часа потратил из-за не корректно написанной статьи: [https://vknet.github.io/vk/docs/save/](url)

Ждем от вас Pull Request
