### ISSUE TITLE
Ошибка при попытке получить видео из альбомов "загруженные/добавленные"

### ISSUE THREAD

**Issue by myavbet** [vknet/vk#803]
В группах системные альбомы видео "добавлено" и "загружено" имеют отрицательный Id (-1 и -2 соответственно). Если эти id подставлять в параметры вызова video.get() то получаем ошибку вида 
Exception = System.ArgumentException: Отрицательное значение.
Имя параметра: AlbumId
   в VkNet.Utils.VkErrors.ThrowIfNumberIsNegative(Expression`1 expr)
   в VkNet.Categories.VideoCategory.Get(VideoGetParams params)
    ....
Отрицательное значение.
Имя параметра: AlbumId

В примерах в ВК к этой функции video.Get() в форме для тестового запроса есть возможность запросить данные c Id=-1/-2.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
