### ISSUE TITLE
Обновить класс GroupsEditParams

### ISSUE THREAD

**Issue by FireGM** [vknet/vk#805]
Не хватает полей для установки города и страны для группы
Временное решение конвертировать GroupsEditParams в VkParameters, добавлять нужные поля и вызывать напрямую VkApi.Call(method, VkParametrs)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
