### ISSUE TITLE
Добавление ICaptchaSolver в ServiceCollection

### ISSUE THREAD

**Issue by FireGM** [vknet/vk#806]
При добавлении только реализации ICaptchaSolver не решает проблему с капчой. Приходится добавлять свою реализацию ICaptchaHandler со своей реализацией ICaptchaSolver внутри.

```csharp
var services = new ServiceCollection();

services.TryAddSingleton<ICaptchaSolver, MyCaptchaSolver>();
services.TryAddSingleton<ICaptchaHandler, MyCaptchaHandler>(); <-- без этого не будет работать, но если не добавить, то и никаких ошибок нет

api = new VkNet.VkApi(services);
```

**Comment by inyutin-maxim** [comment]
Очень странное поведение. Нужно изучать. В контейнере оно зарегистрировано
https://github.com/vknet/vk/blob/d671179ed6ce58bd0e354e893f7b663146aca0cb/VkNet/Utils/TypeHelper.cs#L36

**Comment by hexnone** [comment]
Это должно решить проблему [fix](https://github.com/vknet/vk/pull/813)

**Comment by inyutin-maxim** [comment]
Исправлено в #813
