### ISSUE TITLE
Добавить возможность получения кода через СМС при двухфакторной аутентификации

### ISSUE THREAD

**Issue by LGoldware** [vknet/vk#809]
В документации есть информация об этом, а в текущем классе ApiAuthParams, отсутствуют свойство для указания средства получения кода
https://vk.com/dev/auth_direct

**Comment by itsokto** [comment]
https://github.com/vknet/vk/blob/bfb2221f0db7c144fe8aa2032ac8118b5f04ff1d/VkNet/Model/ApiAuthParams.cs#L25

**Comment by LGoldware** [comment]
Прочите раздел о двухфакторной авторизации, там указано что можно ввести код из генератора кодов, но если я хочу получить код по смс?

**Comment by itsokto** [comment]
Этот флоу пока не реализован.
Вы можете написать свою реализацию [авторизации](https://github.com/vknet/vk/blob/e8229249afd8d1c0d360f9edc1892bc1c1de7580/VkNet/Abstractions/Authorization/IAuthorizationFlow.cs). 
 Унаследовавшись от [IApiAuthParams](https://github.com/vknet/vk/blob/e8229249afd8d1c0d360f9edc1892bc1c1de7580/VkNet/Model/IApiAuthParams.cs) добавьте нужное свойство.
После передайте это флоу в конструктор VkApi или в ServiceCollection.

**Comment by itsokto** [comment]
@LGoldware уточните вы используете [AudioBypass](https://github.com/shelln1ght/VkNet.AudioBypass)?
Поскольку по умолчанию в библиотеке авторизация происходит с помощью эмуляции браузера это будет тяжело реализовать.

**Comment by LGoldware** [comment]
Да, использую

**Comment by itsokto** [comment]
> Да, использую

Отлично, тогда для этого почти всё готово.

**Comment by itsokto** [comment]
@LGoldware готово.
Установите в `ApiAuthParams`  `ForceSms = true`
https://github.com/shelln1ght/VkNet.AudioBypass/tree/r/1.4.0
