### ISSUE TITLE
NullReferenceException при вызове VkApi.Messages.GetChat(...)

### ISSUE THREAD

**Issue by AlekseyLebedev** [vknet/vk#81]
NullReferenceException вылетает при вызове VkApi.Messages.GetChat(...).
Если исправить строчку 44 файла ```vk/VkNet/Model/Chat.cs``` 
```         chat.Id = response["id"];```
на
```         chat.Id = response["chat_id"];```
то вроде начинает работать. В API прописана именно ```chat_id```

**Comment by CaCTuCaTu4ECKuu** [comment]
Message.ID будет
