### ISSUE TITLE
Скачать вложение

### ISSUE THREAD

**Issue by kachan28** [vknet/vk#810]
Доброго времени суток!
Подскажите, пожалуйста, как можно скачать attachment из сообщения? Как правило, во вложении текстовый файл.
Искал в инете, но все тщетно. Заранее большое спасибо за ответ)

**Comment by itsokto** [comment]
Например с помощью [WebClient](https://docs.microsoft.com/ru-ru/dotnet/api/system.net.webclient?view=netframework-4.7.2):
``` C#
using(var webClient = new WebClient())
{
    webClient.DownloadFile(url, downloadPath));
}
```

**Comment by kachan28** [comment]
> Например с помощью [WebClient](https://docs.microsoft.com/ru-ru/dotnet/api/system.net.webclient?view=netframework-4.7.2):
> 
> ```cs
> using(var webClient = new WebClient())
> {
>     webClient.DownloadFile(url, downloadPath));
> }
> ```
То есть на месте аргумента url должна быть ссылка на вложение? А как тогда ее получить? Пытаюсь получить вложения вот так:`
var getHistoryAttachments = get.Messages.GetHistoryAttachments(new MessagesGetHistoryAttachmentsParams
                    {
                        PeerId = userid,
                    }, nextFrom : out);
`
Но компилятор выдает ошибку: Недопустимый термин ")" в выражении.

**Comment by Soniclev** [comment]
Примерно так:
```csharp
var documentAttachment = message.Attachments.First(x => x.Type == typeof(Document));
var uri = ((Document)documentAttachment.Instance).Uri;
```
