### ISSUE TITLE
Критует ошибку при вызове GetConversation.

### ISSUE THREAD

**Issue by Shark-vil** [vknet/vk#811]
**Вывод ошибки в консоли**
![Screenshot_5](https://user-images.githubusercontent.com/13109606/54590169-7bf83980-4a38-11e9-8d17-2eab5d470f2e.jpg)

**Процедуры вызова и параметры авторизации (Полные права)**
![Screenshot_3](https://user-images.githubusercontent.com/13109606/54590201-94685400-4a38-11e9-9430-4a0e36ba58bc.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/13109606/54590205-94685400-4a38-11e9-97fb-561372be1848.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/13109606/54590206-9500ea80-4a38-11e9-8051-12e3c00dcab3.jpg)

**Вопрос.**
В чём может быть проблема?

**Comment by inyutin-maxim** [comment]
@Shark-vil https://vk.com/dev/messages_api

**Comment by Soniclev** [comment]
https://github.com/hikiblade/VkNet.AudioBypass
