### ISSUE TITLE
Исключение типа System.TypeLoadException

### ISSUE THREAD

**Issue by frgt10cs** [vknet/vk#812]
При запуске простого приложения выдаёт следующее:

> Необработанное исключение типа "System.TypeLoadException" в Неизвестный модуль.
Не удалось загрузить тип "VkNet.VkApi" из сборки "vkNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null".

В коде просто:
`var api = new VkApi();`

Версия: 1.43.0

**Comment by itsokto** [comment]
Каким образом библиотека установлена в проект? Тип проекта, версия фреймворка?

**Comment by frgt10cs** [comment]
> Каким образом библиотека установлена в проект? Тип проекта, версия фреймворка?

Через Nuget, консольное .net приложение, 4.7.1

**Comment by itsokto** [comment]
Не думаю, что это ошибка VkNet. Попробуйте переустановить пакет / отчистить кэш nuget / создать новый проект.

**Comment by frgt10cs** [comment]
> Не думаю, что это ошибка VkNet. Попробуйте переустановить пакет / отчистить кэш nuget / создать новый проект.

Добавил в проект путём скачивания VKNet с GitHub. Ошибка пропала. Возможно с NuGet не всё прилетает?

**Comment by itsokto** [comment]
Возможно.
Я создал проект на .NET 4.7.1 добавил VkNet из Nuget и у меня все OK.

**Comment by frgt10cs** [comment]
> Возможно.
> Я создал проект на .NET 4.7.1 добавил VkNet из Nuget и у меня все OK.

Чтож, ладно. Зато теперь знаю, что делать в таком случае. Спасибо, что уделили внимание.
