### ISSUE TITLE
Ошибка при двухфакторной аутентификации

### ISSUE THREAD

**Issue by kachan28** [vknet/vk#817]
Доброго времени суток! Делаю двухфакторную аутентификацию, механизм реализовал как в документации(\examples\VkNet.Wpf). При попытке начать диалог вылезает такая ошибка
![image](https://user-images.githubusercontent.com/38868795/54882980-0bef1680-4e71-11e9-8b2b-77cf809496f4.png)
Добавление AudiobypassService не помогло.
Код :
`private void Have_is_Clicked(object sender, RoutedEventArgs e)
        {
            api = new VkApi(InitDi());

            if (api.IsAuthorized)
            {
                return;
            }

            api.Authorize(new ApiAuthParams
            {
                ApplicationId = 6723320,
                Settings = Settings.All
            });

            MainWindow main = new MainWindow();
            Close();
            main.Show();
        }

        private static ServiceCollection InitDi()
        {
            var di = new ServiceCollection();
            di.AddSingleton<IBrowser, WpfAuthorize>();
            di.AddAudioBypass();
            return di;
        }`
Класс WpfAuthorize один в один с примером из документации. Заранее большое спасибо за ответ)

**Comment by inyutin-maxim** [comment]
@kachan28 Это ошибка VK при выполнении метода, какого именно непонятно. Что любопытно ты пытаешься скрестить два метода авторизации, и так как WpfAuthorize зарегистрирован раньше то байпас игнорируется

**Comment by kachan28** [comment]
Если bypass раньше добавляю, то тоже никакого результата.

**Comment by inyutin-maxim** [comment]
@kachan28 Если есть возможность перейти в телеграмм, то можем более динамично обсудить проблему там: https://t.me/VkDotNet

**Comment by inyutin-maxim** [comment]
@kachan28 Опишите пожалуйста решение проблемы

**Comment by kachan28** [comment]
Проблема решена, сделал окно с авторизацией и окно с кодом. Вне зависимости от того, двухфакторная аутентификация или нет, пользователь вводит в первом окне свой логин и пароль, происходит попытка авторизации. Если у пользователя двухфакторка, то вылезает ошибка ArgumentNullException.В этом случае отлавливаем ее и высвечиваем окно с кодом. Логин и пароль передаем из первого окна. Пользователь вводит код в поле и происходит авторизация. Profit!
Код из основного окна 
try
                {
                    Auth(username, password, ref api);
                    MainWindow main = new MainWindow();
                    this.Close();
                    main.Show();
                    if ((bool)Remember.IsChecked)
                    {
                        Save_Data(username, password);
                    }
                }
                catch (ArgumentNullException)
                {
                    TwoFactWin codewin = new TwoFactWin();
                    codewin.Show();
                    Close();
                }


Код из окна с кодом
private void Button_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                Login.api.Authorize(new ApiAuthParams
                {
                    ApplicationId = appid,
                    Login = Login.username,
                    Password = Login.password,
                    Settings = Settings.All,
                    TwoFactorAuthorization = () =>
                    {
                        string code = "";
                        Dispatcher.BeginInvoke(new ThreadStart(delegate { code = Code.Text; }));
                        return code;
                    }
                });
                MainWindow main = new MainWindow();
                main.Show();
                Close();    
            }
            catch (Exception t)
            {
                MessageBox.Show(t.ToString());
            }
        }
