### ISSUE TITLE
[5.93] API

### ISSUE THREAD

**Issue by itsokto** [vknet/vk#824]
Метод [wall.createComment](https://vk.com/dev/wall.createComment) возвращает новую ошибку 222.

**Comment by inyutin-maxim** [comment]
https://github.com/vknet/vk/blob/3da653ead427202a195c42b3f65a6ddd795fd2bd/VkNet/Utils/ErrorCode.cs#L359

**Comment by inyutin-maxim** [comment]
https://github.com/vknet/vk/blob/3da653ead427202a195c42b3f65a6ddd795fd2bd/VkNet/Exception/PostLinksDeniedException.cs#L11
