### ISSUE TITLE
[5.95] API

### ISSUE THREAD

**Issue by itsokto** [vknet/vk#825]
В методах[ wall.getComments](https://vk.com/dev/wall.getComments), [market.getComments](https://vk.com/dev/market.getComments), [photos.getComments](https://vk.com/dev/photos.getComments), [video.getComments](https://vk.com/dev/video.getComments),[ board.getComments](https://vk.com/dev/board.getComments) граффити вынесен в отдельный тип attach. 

Методы [market.add](https://vk.com/dev/market.add), [market.edit](https://vk.com/dev/market.edit) принимают параметр url. Объект market теперь может возвращать url и button_title.

**Comment by inyutin-maxim** [comment]
> Методы market.add, market.edit принимают параметр url.

https://github.com/vknet/vk/blob/3da653ead427202a195c42b3f65a6ddd795fd2bd/VkNet/Model/RequestParams/Market/MarketProductParams.cs#L99

**Comment by inyutin-maxim** [comment]
> В методах wall.getComments, market.getComments, photos.getComments, video.getComments, board.getComments граффити вынесен в отдельный тип attach.

https://github.com/vknet/vk/blob/3da653ead427202a195c42b3f65a6ddd795fd2bd/VkNet/Model/Attachments/Graffiti.cs#L11

**Comment by inyutin-maxim** [comment]
> Объект market теперь может возвращать url и button_title.

https://github.com/vknet/vk/blob/d4510d3e42479aff1ae43edee25b8ffbc350c8e8/VkNet/Model/Attachments/Market.cs#L78-L87
