### ISSUE TITLE
Добавить 2 скрытых account метода

### ISSUE THREAD

**Issue by ghost** [vknet/vk#828]
account.getPrivacySettings - список настроек приватности
account.setPrivacy - установить настройки приватности

**Comment by inyutin-maxim** [comment]
@shelln1ght Есть полное описание входных параметров и результатов ответа?

**Comment by ghost** [comment]
> @shelln1ght Есть полное описание входных параметров и результатов ответа?

# account.getPrivacySettings
* Response - https://pastebin.com/WtFicYWH (параметры для setPrivacy)
* Request params: 
```
v=5.68&lang=ru&https=1&access_token=TOKEN&sig={sig}
```
# account.setPrivacy
* Response
```
{"response":["значение из value"]}
```
* Request params:
```
v=5.68&lang=ru&https=1&key={key}&value={value}&access_token={token}&sig={sig}
```

## Sig param
* sig
```
md5("/method/account.methodName?lang=ru&v=5.92&access_token={token}&https=1{secret}")
```
**secret** - защищенный ключ приложения (можно взять от официального или пользовательского)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
