### ISSUE TITLE
messages.getDialogs

### ISSUE THREAD

**Issue by Mereng** [vknet/vk#83]
Выпрыгивает исключение при использовании метода messages.getDialogs
"An unhandled exception of type 'System.ArgumentException' occurred in Newtonsoft.Json.dll

Additional information: Accessed JArray values with invalid key value: "count". Array position index expected."

**Comment by CaCTuCaTu4ECKuu** [comment]
Приложите, пожалуйста, ответ в виде Json и я исправлю

**Comment by Mereng** [comment]
const string url = "https://api.vk.com/method/messages.getDialogs?count=2&unread=0&v=5.14&access_token=8c4dd953624ac8ccaafdaae0cc01353033d56116a28d5827b6c668127f6c5a95250bea2e617d54156fc47";
            const string json =
                @"{
                    'response': {
                      'count': 351,
                      'items': [
                        {
                          'message': {
                            'id': 482,
                            'date': 1427126198,
                            'out': 1,
                            'user_id': 24003299,
                            'read_state': 0,
                            'title': ' ... ',
                            'body': 'j'
                          }
                        },
                        {
                          'message': {
                            'id': 477,
                            'date': 1424681744,
                            'out': 0,
                            'user_id': 254186693,
                            'read_state': 1,
                            'title': ' ... ',
                            'body': 'Привет'
                          }
                        }
                      ]
                    }
                  }";

**Comment by CaCTuCaTu4ECKuu** [comment]
Текущая версия используемого API для Message.GetDialogs - 5.28
Если вы используете свой запрос с другой версией API (через метод Invoke) вам придется самим разбирать Json
Скачайте отсюда исходники и перекопмилируйте их чтобы использовать все последние обновления в библиотеке
