### ISSUE TITLE
обновления

### ISSUE THREAD

**Issue by novifyeer** [vknet/vk#833]
Обновления в методе: https://vk.com/dev/messages.send

Новый параметр disable_mentions позволяет отключить уведомление об упоминании в сообщении.

Также добавили подробные ошибки в обработчик поля keyboard, например:
Keyboard format is invalid: button [0][0] label should be not more than 40 letters length.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
