### ISSUE TITLE
Изменить нумерацию версий чтобы она совпадала с версией API VK

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#840]
В этом плане версия API сразу будет видна, да еще и последняя версия VkNet ниже чем у API VK, так что можно указать последнюю более-менее совместимую версию.

Мажорная версия по прежнему будет указывать на VkNet, а апи сместится на минорную и будет 1.44 => 1.5.95, а минорную версию можно указывать после (1.5.95-44.0)
Может у кого будет вариант получше, мне кажется это отличная идея отражать версии API в версии сборки

**Comment by inyutin-maxim** [comment]
новую версию 2.0 можно будет сделать 5.95.ПатчВерсии а текущую так не получится как ты предлагаешь
минорная версия уже больше чем 5я и даунгрейдится не правильно

**Comment by ghost** [comment]
ВК забили на версионирование и часто обновляют API без обновления версий.
