### ISSUE TITLE
Реализовать Execute Errors

### ISSUE THREAD

**Issue by ivanmem** [vknet/vk#841]
![image](https://user-images.githubusercontent.com/33786293/57555719-b5d12680-737d-11e9-8931-2af5e3bc5326.png)

"execute_errors": 
"method"
"error_code"
"error_msg"

**Comment by inyutin-maxim** [comment]
Все ошибки будут собираться в **AggregationException** для чего он и предназначен.
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
