### ISSUE TITLE
Чето Stories у вас не работает получение статистики

### ISSUE THREAD

**Issue by jenokizm** [vknet/vk#843]
Версия библиотеки последняя с нугета.
Если делаю так
`var stat = api.Stories.GetStats(user_id, (ulong)stor.Id);`
то неполучаю внятного результата. вся статистика по нулям.
Думаю ок ну ладно обойдусь мол только просмотрами, пробую так
`var stat = api.Stories.GetViewers(user_id, (ulong)stor.Id);`
и получаю остановку программы с исключением:

> Необработанное исключение типа "Newtonsoft.Json.JsonSerializationException" в Newtonsoft.Json.dll
> Error converting value (тут число) to type 'VkNet.Model.User'. Path 'response.items[0]', line 1, position 41.

**Comment by inyutin-maxim** [comment]
@jenokizm  пришлите пожалуйста лог ответа.
https://github.com/vknet/vk/wiki/Logging

**Comment by inyutin-maxim** [comment]
Проверил, все ок, и тесты на это написаны

**Comment by jenokizm** [comment]
Не знаю что у вас там за тесты, наверное такие же кривые как код. Но лично помню тогда сам исправлял чтобы работало, кроме того там где то методы возвращают не те данные, какие то пустышки или дублирующие. Тему можете не открывать мне все равно, я уже перестал работать с вк, но рано или поздно вы к этому вернетесь.

**Comment by inyutin-maxim** [comment]
@jenokizm Вместо токсичного ответа приложили бы json данные было бы в разы продуктивнее.
Раз что то исправляли почему не поделились с общественностью в виде PR?

**Comment by jenokizm** [comment]
Потому что я всегда на коленке исправляю, качал архивом. Мой код всегда работает но за аккуратностью я не слежу и предпочитаю не влезать в чужую работу.

**Comment by jenokizm** [comment]
А чтобы json приложить там целое дело с каким то фалом конфигурации. Сделайте проще одной булевой командой вкл. выкл. эти логи.

**Comment by itsokto** [comment]
@jenokizm 
1. С методом `Stories.GetViewers` действительно есть проблемы. Вк возвращает разные данные при передаче `extended = false/true` в поле `items`. (метод отрабатывает при `extended = true`)
2. `Stories.GetStats` отрабатывает корректно. Но статистика и правда вся по нулям, не зависимо вызывается ли метод через VkNet или на странице https://vk.com/dev/stories.getStats.
Скорей всего баг Vk Api.

**Comment by itsokto** [comment]
> кроме того там где то методы возвращают не те данные, какие то пустышки или дублирующие. 

Можно по подробнее? Или откройте issue с описанием проблемных методов.
