### ISSUE TITLE
Проблема с прокси

### ISSUE THREAD

**Issue by evgenso** [vknet/vk#845]
Добрый день!
У меня в проекте присутствует такая проблема:
Когда прокси не используется, все работает нормально, но когда подключаю прокси, то авторизация проходит нормально, а вот попытка любого последующего запроса приводит к  "User authorization failed: access_token was given to another ip address." 
Подскажите пожалуйста, что я делаю не так...

**Comment by itsokto** [comment]
@evgenso покажите как вы подключаете прокси.

**Comment by evgenso** [comment]
> @evgenso покажите как вы подключаете прокси.
```
ApiAuthParams apiAuthParams = new ApiAuthParams();
apiAuthParams.ApplicationId = Convert.ToUInt64(settings.VkAppId);
apiAuthParams.Login = settings.VkLogin;
apiAuthParams.Password = settings.VkPassword;
apiAuthParams.Settings = VkNet.Enums.Filters.Settings.All;
if(settings.VkProxyEnabled)
   {
      apiAuthParams.Host = settings.VkProxyHost;
      apiAuthParams.Port = settings.VkProxyPort;
       if (settings.VkProxyUser.Length > 0) apiAuthParams.ProxyLogin = settings.VkProxyUser;
       if (settings.VkProxyPassword.Length > 0) apiAuthParams.ProxyPassword =settings.VkProxyPassword;
    }
 apiVk.Authorize(apiAuthParams);
```

**Comment by itsokto** [comment]
@evgenso похоже что прокси таким способом устанавливается только для авторизации. Я посмотрю что с этим можно сделать.

Начиная с VkNet 1.44.0 для запросов используется [Flurl](https://github.com/tmenier/Flurl). 
Вы можете установить прокси вот так:

- Создайте класс `ProxyHttpClientFactory`

``` C#
using Flurl.Http.Configuration;

public class ProxyHttpClientFactory : DefaultHttpClientFactory {
 private string _address;

 public ProxyHttpClientFactory(string address) {
  _address = address;
 }

 public override HttpMessageHandler CreateMessageHandler() {
  return new HttpClientHandler {
   Proxy = new WebProxy(_address),
    UseProxy = true
  };
 }
}
```
 - Теперь можно установить прокси:
``` C#
FlurlHttp.Configure(settings => {
 settings.HttpClientFactory = new ProxyHttpClientFactory("http://myproxyserver");
});
```
P.S. используйте это вместе с установкой прокси через параметры авторизации.

**Comment by evgenso** [comment]
> ```cs
> FlurlHttp.Configure(settings => {
>  settings.HttpClientFactory = new ProxyHttpClientFactory("http://myproxyserver");
> });
> ```

Не помогло... Все тоже самое...

**Comment by slay9090** [comment]
Недавно столкнулся с весьма не тривиальной задачей, на работе для доступа к интернету используется **фильтрующий** прокси-сервер.

в версии VkNet 1.44 
```
 api = new VkApi();
                    api.Authorize(new ApiAuthParams
                    {
                        ApplicationId = 00000,
                        Login = login_vk,
                        Password = pass_vk,
                        Host = textBox3.Text, //тут прокси сервер
                        Port = int.Parse(textBox4.Text), // порт                                      
                        Settings = Settings.All                                            
                     });
```
При использовании корпоративного прокси сервера **ISA** возникает ошибка: Удаленный сервер возвратил ошибку: (407) Требуется проверка подлинности посредника. 

Как выяснилось, ошибка **не** возникает в версии VkNet 1.35.1.

При дальнейшем изучении вопроса было выявлено, что в последних версиях было переработано  ядро и теперь используется зависимость Flur.

В библиотеке Flur не реализован явно механизм UseDefaultCredentials, вот что пишет автор: 

> In your particular case, yes it would be nice. :) I'm a little picky about what extension methods get baked into the core - generally things that are extremely common, or not trivial to implement (like cookies). I don't know how common UseDefaultCredentials is, personally I've never had a need for it. For things like this I try to make the library as easily extensible as possible.

Так же, он предлагает такое решение:

> I think it's even easier than that. As a user I probably don't want to have to specify WithWindowsAuth() on every call - chances are you want to do it on every call to the same host. Also, tinkering with request.Client.HttpMessageHandler is not thread safe. So, create and register a custom factory:

```
public class WindowsAuthClientFactory : DefaultHttpClientFactory
{
    public override HttpMessageHandler CreateMessageHandler() {
        return new HttpClientHandler { UseDefaultCredentials = true };
    }
}

FlurlHttp.ConfigureClient("https://www.somedomain.com", cli =>
    cli.Settings.HttpClientFactory = new WindowsAuthClientFactory());
```

> So no, you shouldn't have to create tons of extension methods or "hack around" anything. You can even use this factory app-wide via FlurlHttp.Configure rather than FlurlHttp.ConfigureClient if you're hitting many domains that all require it.

Попытки задать (переопределить) прокси в дочернем классе и параметры UseDefaultCredentials = true, PreAuthorize  = true, как описали выше - не увенчались успехом.

Причина данной проблемы, в том что: 
"Вам необходимо установить учетные данные, данные прокси-серверу , иначе он в первую очередь откажется подключить вас к серверу. Учетные данные, которые вы предоставляете прокси-серверу, могут отличаться от тех, которые вы предоставляете серверу. Если вы ошибетесь, вы получите 407 ответ. Вы получаете 407, потому что вы никогда не устанавливали их вообще."

В итоге моё решение выглядит так: 

```
class WindowsAuthClientFactory : DefaultHttpClientFactory 
    {
       
        public override HttpMessageHandler CreateMessageHandler() //переопределяем
        {
            return new HttpClientHandler
            {
                DefaultProxyCredentials = CredentialCache.DefaultCredentials // получаем параметры в дефолт
        };
        }
     
    }

//Затем, где нибудь просто единожды вызвать конструктор
 FlurlHttp.Configure(settings => {
                settings.HttpClientFactory = new WindowsAuthClientFactory();
            });

```
Нам необходимо просто переопределить стандартный HttpMessageHandler и присвоить DefaultProxyCredentials = CredentialCache.DefaultCredentials, таким образом, мы будем использовать дефолтные данные учётной записи и прокси по умолчанию операционной системы. т.е. того прокси который прописан у  нас в  Панель управления/Свойства браузера/Подключения/Настройка сети

Это работает для ISA прокси.

**Comment by sel1** [comment]
Поскольку проблему #857 перенесли сюда, продублирую тут не решенные вопросы.
Вообще ситуация с прокси странная: в версии 1.29.1 были проблемы, но работало, сейчас вообще не работает  (п.2 ниже), и долгое время не исправляется. Никто не пользуется проси?

Target .net 4.5

1. Класс ApiAuthParams. Параметры Host и Port по всей видимости библиотекой игнорируются. Если так, их нужно удалить совсем
Пример кода
            var api = new VkApi(serviceCollection);
            api.Authorize(new ApiAuthParams
                {
                    AccessToken = botContext.Account.AccessToken,
                    Host = "88.147.254.202",
                    Port = 3128
                });          
2. Как понимаю, настроить прокси сейчас можно только глобально для всего приложения через FlurlHttp.Configure(...). В версии 1.29.1 была возможность настраивать прокси для каждого экземпляра VkApi, просьба это вернуть.

**Comment by ghost** [comment]
При авторизации игнорируется глобальная настройка Flurl, но при вызове методов Flurl начинает работать, в итоге ошибка "access_token was given to another IP", приходится использовать Settings.Offline .

**Comment by inyutin-maxim** [comment]
@Panuchi есть решение, нужно реализовать IWebProxy и зарегистрировать в ServiceCollection, и тогда для регистрации тоже будет прокси использоваться

**Comment by inyutin-maxim** [comment]
рабочий вариант для авторизации
``` cs
var serviceCollection = new ServiceCollection();
serviceCollection.AddSingleton<IWebProxy>(new WebProxy(_address){...creds...});
var api = new VkApi(serviceCollection);
```

и так же выполните по инструкции как здесь для запросов
https://github.com/vknet/vk/issues/845#issuecomment-500034996

**Comment by itsokto** [comment]
Была проделана работа над запросами в VkNet, все проблемы упоминаемые в этом issue теперь должны быть решены. Создана документация по настройке прокси. Перейдите в упомянутый pull request за подробностями.
