### ISSUE TITLE
Добавить новые типы кнопок клавиатуры бота

### ISSUE THREAD

**Issue by danil-kuk** [vknet/vk#846]
На данный момент при создании кнопки для клавиатуры бота из класса MessageKeyboardButton в поле Action.Type с помощью класса KeyboardButtonActionType можно сделать только клавишу типа Text. Хотелось бы иметь возможность создавать кнопки с типами Location, VK Pay, VK Apps.
Информация про каждый из типов: https://vk.com/dev/bots_docs_3

**Comment by danil-kuk** [comment]
Как я понял, другие типы нельзя добавить, потому что для них по-умолчанию создаются свойства, которых у них не должно быть. Например, для кнопки с типом Location не нужно указывать Label. Более серьезной проблемой является то, что свойство Сolor может иметь только кнопка с типом Text. Но из-за того, что по-умолчанию объект MessageKeyboardButton создается с данным свойством, нельзя создать кнопки других типов. То есть постоянно возвращается ошибка " 911. Keyboard format is invalid"

**Comment by danil-kuk** [comment]
Я уже сделал функционал, который позволяет добавить эти кнопки. Постараюсь сделать Pull Request в ближайшее время

**Comment by inyutin-maxim** [comment]
@danil-kuk Я запилил функционал правда не проверял, после сборки можно попробовать из альфаканала, если чего то было недостаточно дополните в вашем PR

**Comment by danil-kuk** [comment]
@inyutin-maxim Спасибо за наводку, обязательно попробую

**Comment by inyutin-maxim** [comment]
@danil-kuk Можно попробовать. Канал здесь: https://www.myget.org/F/vknet

Если что то не будет работать просьба переоткрыть эту задачу

**Comment by danil-kuk** [comment]
@inyutin-maxim К сожалению, ваш вариант выдает ту же ошибку. Это связано с тем, что у вас осталось свойство Color в классе MessageKeyboardButton. Из-за этого свойства при создании любой кнопки кроме Text будет ошибка "911. Keyboard format is invalid", так как он отравляет json, где у него есть Color, когда он может быть только у Text

**Comment by danil-kuk** [comment]
Это же касается свойства Label в классе MessageKeyboardButtonAction, данное свойство есть только у кнопки Text, при наличии его в json для других кнопок он так же точно выдаст ошибку "Keyboard format is invalid"

**Comment by inyutin-maxim** [comment]
@danil-kuk Пришлите ваш PR

**Comment by danil-kuk** [comment]
@inyutin-maxim Я его обязательно пришлю, когда полностью доделаю. То есть мне удалось добиться нормальной работы с любым типом кнопок, но там ещё нужна доработка. Можете посмотреть, что я хочу сделать здесь: https://github.com/danil-kuk/vk/tree/newKeyboardButtons

**Comment by danil-kuk** [comment]
@inyutin-maxim На основе вашего способа сделал пару правок, чтобы все работало как нужно. Отправил PR: https://github.com/vknet/vk/pull/848

**Comment by inyutin-maxim** [comment]
@danil-kuk Забрал, спасибо
