### ISSUE TITLE
return Сборка RT

### ISSUE THREAD

**Issue by kristx300** [vknet/vk#85]
прочитал закрытую тему
https://github.com/vknet/vk/issues/78
так вот
Выход анонсирован на осень 2015.
Мб сделаете сборку для WinRT с одним методом Invoke? :) и соответственно аутентификацией
 сейчас просто сам копаюсь в winrt как создать браузер и работать с api....
пытаюсь сам писать... но всё через одно место :)
Надеюсь вы поможете
с моей же стороны я могу помочь, заполнением методов с vk.com/dev/methods
и будет нам збс :)
P.S. если что свяжитесь со мной maelstorm_wf@list.ru

**Comment by inyutin-maxim** [comment]
так как основное обсуждение происходило в задаче #78 ваш комментарий я перенес туда, а эту задачу закрываю как дубликат
