### ISSUE TITLE
5.101 Обложки в объекте видео теперь передаются в полях image и first_frame в виде массивов объектов video_image

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#853]
5.101 Обложки в объекте [видео](https://vk.com/dev/objects/video) теперь передаются в полях _image_ и _first_frame_ в виде массивов объектов [video_image](https://vk.com/dev/objects/video_image).

**Comment by itsokto** [comment]
Добавил эти поля в объект video.

Последние изменения можете получить здесь:
https://www.myget.org/F/vknet
