### ISSUE TITLE
5.101 Обложки в объекте альбома видео теперь передается в поле image в виде массива объектов video_image.

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#854]
Обложки в объекте [альбома видео](https://vk.com/dev/objects/video_album_full) теперь передается в поле _image_ в виде массива объектов [video_image](https://vk.com/dev/objects/video_image).

**Comment by itsokto** [comment]
Добавил поле image в объект video_album.

Последние изменения можете получить здесь:
https://www.myget.org/F/vknet
