### ISSUE TITLE
Ошибка при использовании типов чата в блоке case.

### ISSUE THREAD

**Issue by kvazzimodo** [vknet/vk#855]
Не могу создать блок case типа peer.type (беседы, пользователя или группы), ошибка:
**требуется постоянное значение.**

**Код**
```
var chats = vkApi.Messages.GetConversations(new GetConversationsParams
{
    Count = 200
});

foreach (var chat in chats.Items)
{
    if (true == chat.Conversation.CanWrite.Allowed)
    {
        switch (chat.Conversation.Peer.Type)
        {
             case ConversationPeerType.Chat: // error
                break;
        }
    }
}
```

VkNet 1.44.0

**Comment by itsokto** [comment]
Поскольку `ConversationPeerType` не является Enum, а кастомным типом, поэтому у вас такая ошибка
https://github.com/vknet/vk/blob/10ad71e1be0d08b0f7ffa71242449ae18c1b7e14/VkNet/Enums/SafetyEnums/ConversationPeerType.cs#L9
В VkNet 2.0 мы откажемся от SafetyEnum

**Comment by CaCTuCaTu4ECKuu** [comment]
А разве у него нет какого-то поля стрингового типа чтобы делать
switch Type.Name
case  ConversationPeerType.Chat.Name

**Comment by itsokto** [comment]
@CaCTuCaTu4ECKuu Нет. И строка должна быть константой чтобы это работало.

**Comment by ghost** [comment]
#1414 Work in progress
