### ISSUE TITLE
Добавить новый параметр ref в FriendsCategory

### ISSUE THREAD

**Issue by novifyeer** [vknet/vk#856]
https://vk.com/dev/friends.get?params[user_id]=6492&params[order]=name&params[count]=3&params[offset]=5&params[fields]=city%2Cdomain&params[name_case]=ins&params[ref]=255&params[v]=5.101

в json отображается "track_code"

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
