### ISSUE TITLE
Проблемы с прокси 2

### ISSUE THREAD

**Issue by sel1** [vknet/vk#857]
Target .net 4.5  

1) Класс **ApiAuthParams**. Параметры **Host** и **Port** по всей видимости библиотекой игнорируются. Если так, их нужно удалить совсем
Пример кода 
```csharp
            var api = new VkApi(serviceCollection);
            api.Authorize(new ApiAuthParams
                {
                    AccessToken = botContext.Account.AccessToken,
                    Host = "88.147.254.202",
                    Port = 3128
                });          

```

2) Как понимаю, настроить прокси сейчас можно только глобально для всего приложения через **FlurlHttp.Configure(...)**. В версии 1.29.1 была возможность настраивать прокси для каждого экземпляра VkApi, просьба это вернуть. У меня многопоточное приложение, при текущей реализации невозможно использовать разные прокси для потоков

**Comment by itsokto** [comment]
Дальнейшее обсуждение этой задачи будет происходить здесь #845
