### ISSUE TITLE
Большинство методов, возвращающих коллекции, не имеют вывода response/count.

### ISSUE THREAD

**Issue by ghost** [vknet/vk#86]
Большинство методов, возвращающих коллекции, не имеют вывода response/count.
Из за этого, к примеру, при получении списка пользователей, лайкнувших определенную запись, приходится городить свои велосипеды, заключающиеся в поблоковой загрузке по 1000 элементов, с проверкой на количество возвращенных элементов.

**Comment by CaCTuCaTu4ECKuu** [comment]
Не совсем понял в чем проблема?
Как я понял когда вы загружаете список лайков вы пишите цикл в котором загружаете по 1000 лайков и делаете инкремент оффсета и загружаете снова пока кол-во лайков в ответе не будет меньше 1000?
Проблема в том что нельзя одним методом загрузить весь список лайков или в том что нет переменной out в которой пишется сколько всего лайков или как?

**Comment by chingachgook** [comment]
Проблема именно в отсутствии переменной out, а также в том, что она не всем нужна, чтобы менять каждый метод (ну бред же, согласитесь).
Для себя нашел пока следующий выход, в методе Call добавил:
```
VkResponse vkResponse = new VkResponse(rawResponse) { RawJson = answer };
CountFromLastResponse = vkResponse["count"];
return vkResponse;
```
вместо того, что было:
```
return new VkResponse(rawResponse) { RawJson = answer };
```
И там, где мне нужно, просто читаю из vk.api.CountFromLastResponse.

**Comment by CaCTuCaTu4ECKuu** [comment]
Думаю пока переменная out к большинству методов добавлено не будет, но если много людей скажут что это нужно то добавлю.

Никогда не замечал насчет тысячи, но может так и есть, всегда делал while > 0

**Comment by chingachgook** [comment]
Пока что проблема с "меньше тысячи" точно есть у `Likes.GetList()`.

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu , @azhidkov Предлагаю избавиться от out параметров (Что является плохой практикой программирования) в методах, в пользу предложенного выше варианта с полем Count в классе VkApi, как вы на это смотрите? при этом разумеется сохранив обратную совместимость с уже реализованными методами.

**Comment by azhidkov** [comment]
Что-то мне не особо нравится идея с глобальным свойством у класса VkApi из-за возможных проблем с многопоточностью. Я предлагаю возвращать обертку с двумя свойствами - элементами и их общим количеством. И сделать implicit-преобразование этой обертки к ICollection или IEnumerable.

**Comment by inyutin-maxim** [comment]
@azhidkov да ты прав, я не подумал за многопоточность. Я подумаю на досуге как это лучше сделать, напишу здесь и подумаем вместе

**Comment by mainefremov** [comment]
@azhidkov, @inyutin-maxim, это автор идеи, пишу с нового аккаунта. Смотрите, что мы имеем.
Счетчик, значение которого важно только для того потока, который его использует. Другому потоку абсолютно плевать, сколько элементов вернул метод в другом потоке, ему даже неизвестно, что это были за элементы. То есть нам нужен локальный счетчик, для текущего потока.

Всё, что нам нужно, уже изобретено. Атрибут ThreadStatic.
Важно помнить одно, если мы инициализируем ThreadStatic, то будет инициализирован только экземпляр первого потока, это нужно иметь ввиду (см. разницу между ThreadStatic и ThreadLocal<T>).

```
[ThreadStatic]
public static int CountFromLastResponse;
```

> A static field marked with ThreadStaticAttribute is not shared between threads. Each executing thread has a separate instance of the field, and independently sets and gets values for that field. If the field is accessed on a different thread, it will contain a different value.

**Comment by CaCTuCaTu4ECKuu** [comment]
Есть же возвращаемый результат типа wallgetresponse или groupgetresponse и
т.д. Зачем все усложнять? Или я не совсем понял цель этих манипуляций?

**Comment by inyutin-maxim** [comment]
@CaCTuCaTu4ECKuu  Эти типы данных ввел я, можно конечно все так переделать, но это большая задача, а цель вышеуказанных манипуляций заключается в том чтобы избавиться от Out параметров в методах, просто на самом деле далеко не всем нужны эти параметры

**Comment by mainefremov** [comment]
@inyutin-maxim, как мне видится, в возвращаемом значении должна быть только коллекция запрашиваемых элементов, что логично, а out-параметры, вы правы, мало того, что они не удобны, и не всем нужны, так еще и будь добр передать в этот out что-то, а плодить бесполезные сущности без необходимости напрягает.

**Comment by kkohno** [comment]
я бы предложил сделать специальную коллекцию данных, заточенную под ответы. Она будет реализовывать интерфейс IEnumerable и содержать Count - количество элементов, непосредственно полученных и TotalCount - количество элементов, сколько всего есть, тоесть тот самый count из респонса

**Comment by inyutin-maxim** [comment]
@mainefremov , @kkohno 

Все реализованные классы категорий методов были переведены на класс VkCollection - унаследованный от ReadonlyCollection но имеет многострадальное поле Count. Для использования соберите библиотеку из ветки VkCollection. Задачу считаю закрытой
