### ISSUE TITLE
Получения статуса.

### ISSUE THREAD

**Issue by Vergiliy1** [vknet/vk#87]
Status s = vk.Status.Get(17575027);
Console.WriteLine(s);

В консоле пишет VkNet.Model.Status

**Comment by CaCTuCaTu4ECKuu** [comment]
Не работал с этим классом, но ошибка детская.
Console.WriteLine(s.ХХХ); , где ХХХ - поле с текстом статуса (скорее всего Text и называется)

**Comment by Vergiliy1** [comment]
Спасибо, я только учусь.
