### ISSUE TITLE
Ошибка при получении списка подарков

### ISSUE THREAD

**Issue by kengisep** [vknet/vk#870]
При получении списка подарков выходит исключение System.OverflowException: Значение было недопустимо малым или недопустимо большим для UInt64.
Насколько я понял, это может быть связано с тем, что с версии 5.42 метод gifts.get может вернуть отрицательный from_id.

**Comment by itsokto** [comment]
Ошибка исправлена.
Получить последние изменения можете из https://www.myget.org/F/vknet
