### ISSUE TITLE
Нельзя взять количество репостов фотографии.

### ISSUE THREAD

**Issue by survival-suit** [vknet/vk#874]
Имеется такой вот код:
`
albumPhotos = api.Photo.Get(new PhotoGetParams
                        {
                            OwnerId = groupId,
                            AlbumId = PhotoAlbumType.Id(a.Id),
                            Reversed = true,
                            Extended = true,
                            PhotoSizes = true,
                            Count = 100,
                            Offset = (ulong)j,
                        });

                        foreach (var ap in albumPhotos)
                        {
                            //заполняем модель
                            var apModel = new albumPhotoModel
                            {                              
                                PhotoLikes = ap.Likes.Count.ToString(),
                                PhotoShares = ap.Reposts.Count.ToString()
                            };`

Не берутся посты, потому что в модели нету  Reposts и нельзя использовать ap.Reposts.Count.ToString().
Если заглянуть, в самом API вк в методе photos.get есть возвратный параметр reposts.
Сможете добавить?

**Comment by itsokto** [comment]
Добавил это поле.

Последние изменения можете получить здесь:
https://www.myget.org/F/vknet
