### ISSUE TITLE
[ВОПРОС] - посты с документом

### ISSUE THREAD

**Issue by apepenkov** [vknet/vk#879]
Как делать посты с документом?
```
var uploadServer = vkClient.Docs.GetWallUploadServer();
var wc = new WebClient();
var responseFile = Encoding.ASCII.GetString(wc.UploadFile(uploadServer.UploadUrl, @attachment));
var document = vkClient.Docs.Save(file: responseFile, title: attachmentNameFile)[0];
vkClient.Wall.Post(new VkNet.Model.RequestParams.WallPostParams
{
        Message = postBody,
        Attachments = new List<VkNet.Model.Attachments.MediaAttachment> { document } // Тут и не подходит, т.к. document это Attachment, а надо MediaAttachment
});
```
![изображение](https://user-images.githubusercontent.com/39992738/66273254-efe61c00-e87a-11e9-9933-2e1b57251e12.png)

**Comment by apepenkov** [comment]
доки - не гиф, а всякие .docx

**Comment by itsokto** [comment]
> Attachments = new List<VkNet.Model.Attachments.MediaAttachment> { document } не подходит, т.к. document это Attachment, а надо MediaAttachment

`document.Instance`

**Comment by itsokto** [comment]
https://github.com/vknet/vk/issues/720

**Comment by itsokto** [comment]
Вопрос решен?

**Comment by apepenkov** [comment]
Я пока не у пк, приду - проверю

**Comment by apepenkov** [comment]
да, .Instance решило проблему.
