### ISSUE TITLE
Если не сложно.

### ISSUE THREAD

**Issue by Vergiliy1** [vknet/vk#88]
Можете привести пример получения сообщения с помощью метода Messages.Get.
Я новичок и никогда с библиотеками не работал.
Заранее спасибо.

**Comment by CaCTuCaTu4ECKuu** [comment]
подключаете VkNet через using
Создаете экземпляр VkApi api = new VkApi();
авторизуетесь через VkApi.Authorize();
Смотрите что там возвращает api.Message.Get() - возвращаемый тип (по-моему Model.Messages)
Создаете Model.Messages msg = api.Message.Get();
По поводу того что передавать в метод - смотрим документацию на https://vk.com/dev/main
