### ISSUE TITLE
5.102 Для методов ads.createTargetGroup и ads.updateTargetGroup параметр lifetime станет обязательным.

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#883]
Для методов ads.createTargetGroup и ads.updateTargetGroup параметр lifetime станет обязательным. Параметр будет принимать значения от 1 до 720.

**Comment by itsokto** [comment]
https://github.com/vknet/vk/blob/516b12322fe8591d696acbd2fc8d65bce1b3a515/VkNet/Model/RequestParams/Ads/CreateTargetGroupParams.cs#L38
https://github.com/vknet/vk/blob/516b12322fe8591d696acbd2fc8d65bce1b3a515/VkNet/Model/RequestParams/Ads/UpdateTargetGroupParams.cs#L51
