### ISSUE TITLE
Ошибка авторизации при запросе части разрешений

### ISSUE THREAD

**Issue by Oifer** [vknet/vk#886]
При попытке авторизации с ApiAuthParams.Settings != Settings.All исключение "Неверный логин или пароль.". Данные и id приложения - рабочие, при установке ApiAuthParams.Settings = Settings.All все начинает работать.
Vknet version 1.47.0
Одинаковая ошибка на WPF(.net framework 4.5.2) и Xamarin.Forms(.net standart 2.0)

Авторизация:
с ошибкой
![image](https://user-images.githubusercontent.com/43473428/66716358-97140780-edd5-11e9-96e3-2f8ebdfdca4b.png)
без
![image](https://user-images.githubusercontent.com/43473428/66716367-c165c500-edd5-11e9-9ebe-04cbcf4fdd68.png)

**Comment by Soniclev** [comment]
Возможно, это из-за сообщений, попробуйте использовать https://github.com/shelln1ght/VkNet.AudioBypass

**Comment by Oifer** [comment]
Уже используется.

**Comment by itsokto** [comment]
@Oifer эта ошибка возникает при использовании AudioBypass?
Если так, уберите ApplicationId, Settings из параметров авторизации. Они игнорируются при использовании AudioBypass (похоже Settings не игнорируется, но должен).

**Comment by Oifer** [comment]
@itsokto AudioBypass подключен к проекту.

По результатам экспериментов подключение AudioBypass к проекту вообще не играет роли, авторизация работает без Settings, при указании Settings.Messages кидает "Неверный логин или пароль", при отсутствии ApplicationId кидает "Form element not found."

**Comment by itsokto** [comment]
Если не используется AudioBypass, то эти параметры обязательны. 
Для сообщений использование AudioBypass обязательно, при этом Settings и ApplicationId передавать не нужно.

**Comment by Oifer** [comment]
Во-первых, "использование AudioBypass" - это подключение к проекту, или необходимо сделать что-то еще?

Во-вторых:
>Для сообщений использование AudioBypass обязательно, при этом Settings и ApplicationId передавать не нужно.

Без Settings и ApplicationId кидает исключения

**Comment by itsokto** [comment]
Да. Прочтите readme на странице AudioBypass. Делается в две строки

**Comment by Oifer** [comment]
Благодарю
