### ISSUE TITLE
Не могу задать параметр EndDate в PollsCreateParams

### ISSUE THREAD

**Issue by belchusov** [vknet/vk#887]
в PollsCategory.Create при задании PollsCreateParams есть параметр EndDate по типу DateTime, но в подсказке, говорится то он должен быть целым числом. По факту как его не задавай выходит ошибка. Можно,  работающий пример того, как задать этот параметр.

**Comment by itsokto** [comment]
По подробнее
Какая ошибка? Как задаёте?

**Comment by belchusov** [comment]
Сначала авторизуюсь
 var services = new ServiceCollection();
        services.AddAudioBypass();
        Settings scope = Settings.All;
        var vk = new VkApi(services);
        vk.Authorize(
           new ApiAuthParams
           {
               Login = login,
               Password = password,
           });
Все проходит без проблем.
Затем задаю список ответов, и сам вопрос
 List<string> answersList = new List<string>();
        answersList.Add("Answer1");
        answersList.Add("Answer2");
        answersList.Add("Answer3");
        answersList.Add("Answer4");
        VkNet.Model.Attachments.Poll polls = vk.PollsCategory.Create(new VkNet.Model.RequestParams.Polls.PollsCreateParams { Question = "Ну какой вопрос?", AddAnswers = answersList, EndDate=DateTime.Now.AddDays(5)});
В итоге получаю ошибку
Исключение типа "VkNet.Exception.ParameterMissingOrInvalidException" возникло в VkNet.dll, но не было обработано в коде пользователя
Дополнительные сведения: One of the parameters specified was missing or invalid: end_date not integer
Если вообще не пишу EndDate, т.е. вызываю так
VkNet.Model.RequestParams.Polls.PollsCreateParams { Question = "Ну какой вопрос?", AddAnswers = answersList)});
то все равно получаю туже самую ошибку

**Comment by itsokto** [comment]
Исправил.
Последние изменения можете получить здесь:
https://www.myget.org/F/vknet

**Comment by belchusov** [comment]
![image](https://user-images.githubusercontent.com/10412860/67977675-97136480-fc29-11e9-9375-21e0be8aaee2.png)

**Comment by belchusov** [comment]
Версию обновил, но теперь выходят новые ошибки.

**Comment by belchusov** [comment]
![image](https://user-images.githubusercontent.com/10412860/67977778-c88c3000-fc29-11e9-9b3f-df5ee90deee7.png)

**Comment by itsokto** [comment]
Таргет вашего приложения? 
NET Core, Framework, netstandard

**Comment by itsokto** [comment]
Можете присоединиться к чату в телеграмм https://t.me/VkDotNet за помощью.

**Comment by belchusov** [comment]
Присоединился
 
Анатолий

**Comment by belchusov** [comment]
Framework 4.5
