### ISSUE TITLE
Что происходит с вашей сборкой, если нужна Captcha?

### ISSUE THREAD

**Issue by kristx300** [vknet/vk#89]
Что происходит с вашей сборкой, если нужна Captcha?

**Comment by Dramacydal** [comment]
Вылезает окно для ввода капчи?

**Comment by azhidkov** [comment]
Выбрасывается исключение CaptchaNeededException в котором есть идентификатор капчи (sid) и Url-адрес изображения с капчей (Img).

Далее, в приложении вы можете выводить изображение капчи и сделать текстовое поле куда пользователь будет её вводить. Далее вам нужно будет выполнить тот же метод, что выбросил исключение плюс дополнительно указать идентификатор капчи и её значение. 

Если метод не принимает таких параметров (значит я не успел это сделать :)), напишите об этом комментарием к этой задаче.

**Comment by kristx300** [comment]
а можно пример кода как всё это выглядит?

**Comment by CaCTuCaTu4ECKuu** [comment]
VkApi api = new VkApi;
api.Authorize();
try {
api.Message.Send();
} catch (CaptchaNeededException **cEx**) {
string captchaUrl = cEx.Img;
string captchaKey = SomeCaptchaHandler(captchaUrl); /// *Обработка капчи: загружаем через что-то изображение, выводим его, вводим ответ, идем дальше*
api.Message.Send(..... , **cEx.Sid**, **captchaKey**);
}

**Comment by kristx300** [comment]
А если пользователь не верно ввел капчу?
какие дальше будут действия?

**Comment by CaCTuCaTu4ECKuu** [comment]
В данном случае снова вылезет ошибка. Вы пишете обработку как вам угодно, как напишете так и будет, можно вогнать в цикл с проверкой и не выходить из него пока выскакивает CaptchaNeededException.

**Comment by kristx300** [comment]
Хотелось бы методы с капчей  такие как :+1:  : 
wall.Get
wall.GetComment
wall.Delete
wall.DeleteComment

**Comment by CaCTuCaTu4ECKuu** [comment]
А разве когда при вызове этих моментов вылазит капча она отображается не как CaptchaNeededException? Все ошибки отлавливаются в одном месте и соответственно работают для всех методов, разве что в ответ на эти методы приходит другой номер ошибки

**Comment by kristx300** [comment]
я про api.Message.Send(..... , cEx.Sid, captchaKey);

**Comment by CaCTuCaTu4ECKuu** [comment]
Я ничего не понял

**Comment by kristx300** [comment]
Хотелось бы методы с капчей такие как :+1: : 
wall.Get
 wall.GetComment
 wall.Delete
 wall.DeleteComment
То есть, доп. перегрузки с SID и CaptchaKey
например обычный wall.Get(owner_id,count , etc  + SID + CaptcjaKey);

**Comment by CaCTuCaTu4ECKuu** [comment]
Вот оно что, как будет время - тогда. Если у вас есть возможность - можете сами делать исправления, обновления и присылать сюда, так будет гораздо быстрее. 
А насчет Get и GetComment, эти методы вообще не должны вызывать капчу насколько я знаю

**Comment by kristx300** [comment]
Спасибо :)
а за денюжку работаете?))

**Comment by mainefremov** [comment]
> Если у вас есть возможность - можете сами делать исправления, обновления и присылать сюда, так будет гораздо быстрее.
В связи с чем вопрос. Никогда не работал с тестами, насколько это большая помеха? Если да, какие наикратчайшие пути решения? Просто есть множество идей, которые по причине своей безграмотности не решаюсь отправит в пулл.

**Comment by CaCTuCaTu4ECKuu** [comment]
>Спасибо :)
>а за денюжку работаете?))

Да, поэтому и нет времени :)

@mainefremov 
Сами тесты я тоже не особо умею писать, я без них писал, только исправил парочку под новые мметоды. Если вы что то добавили и проверили - отправляйте, я протестирую и сделаю пулл

**Comment by kristx300** [comment]
а какие расценки?)
например мне нид
вот этот вкапи, ток не опенсорс
методов auth + 15 методов + exceptions

**Comment by CaCTuCaTu4ECKuu** [comment]
Напиши мне на скайп (такой же как и ник)

**Comment by alexsuslin** [comment]
vk.Wall.Post тоже не работает с каптчей?

**Comment by kovart** [comment]
Что то как-то не удобно работает обработка капчи, слишком много придется try..catch писать.

**Comment by thisiswhite** [comment]
Товарищи работаю с audio.serch грамоздкий цикл капча таки выпадает!!!

**Comment by CaCTuCaTu4ECKuu** [comment]
На с аудио есть ограничения, думаю или я или кто-то еще в ближайшее время
сделает структуру параметров для основных методов

**Comment by inyutin-maxim** [comment]
@thisiswhite Я работаю над этим классом, в ближайшее время внесу необходимые изменение.

**Comment by thisiswhite** [comment]
Тогда могу я вас попросить внести поле битрейт для каждого элемента audio и поле размер ?

**Comment by inyutin-maxim** [comment]
@thisiswhite Да, конечно. Я стараюсь добавлять отсутствующие поля.

**Comment by thisiswhite** [comment]
спасибо! Я начинающий, но вот покопался в вашем коде и если обратить внимание на https://vk.com/dev/audio_object там нет доступа к полям ни bittrate ни file size. и на сколько понимаю просто так путем response ["size"]  не добавить?

**Comment by inyutin-maxim** [comment]
@thisiswhite Просто с развитием API  добавляются новые поля, а в библиотеке далеко не все классы находятся в актуальном состоянии, а некоторых и вовсе нет пока что. Со временем я думаю мы приведем библиотеку в актуальное состояние, а там поддерживать ее станет проще

**Comment by mrsatana666** [comment]
А если капча при авторизации возникла мы уже не можем под прокси авторизоваться получается? В перечислении autorize нет нужного, где задаются порт, хост, сид капчи и текст капчи ((

**Comment by Bezpro** [comment]
Не могу понять, что за проблема.  
string captchaKey="";
private void button1_Click(object sender, EventArgs e)
        {
           try
           {
               if (captchaKey == "")
               {
                   login = boxLogin.Text;
                   pass = boxPass.Text;
                   api.Authorize(new ApiAuthParams
                   {
                       Login = login,
                       Password = pass,
                       ApplicationId = appid,
                       Settings = Settings.All
                   });
               }
               else
               {
                   api.Authorize(new ApiAuthParams
                    {
                        Login = login,
                        Password = pass,
                        ApplicationId = appid,
                        Settings = Settings.All,
                        CaptchaKey = captchaKey,
                        CaptchaSid = csid
                        
                    });
               }

                
           }
           catch (CaptchaNeededException cne)
           {
                csid = cne.Sid;
                string captchaUrl = cne.Img.AbsoluteUri;
                pictureBox1.ImageLocation = captchaUrl;
                string captchaKey = textBox2.Text;
           }
Даже после ввода капчи при новом нажатии на кнопку, все равно вылазит exception

**Comment by Soniclev** [comment]
@Bezpro в блоке catch Вы определили captchaKey, которая "перекрывает" captchaKey в классе формы.
До:
catch (CaptchaNeededException cne)
       {
            csid = cne.Sid;
            string captchaUrl = cne.Img.AbsoluteUri;
            pictureBox1.ImageLocation = captchaUrl;
            **string** captchaKey = textBox2.Text;
       }
После:
```
catch (CaptchaNeededException cne)
       {
            csid = cne.Sid;
            string captchaUrl = cne.Img.AbsoluteUri;
            pictureBox1.ImageLocation = captchaUrl;
            captchaKey = textBox2.Text;
       }
```

**Comment by Sasha95** [comment]
@Soniclev Всё равно не получается. даже если сделать так как вы написали.
