### ISSUE TITLE
GetCallbackConfirmationCode() возвращает неверный code

### ISSUE THREAD

**Issue by ant1b0t** [vknet/vk#899]
Неверный результат, полученный методом GetCallbackConfirmationCode(), и верный результат, полученный методом Vk.ApiCall().

**Comment by ant1b0t** [comment]
Или ВК их меняет так, что в методах разные коды приходят

**Comment by itsokto** [comment]
> Обратите внимание, что код, возвращаемый методом, можно использовать только для настройки сервера средствами API. В настройках Вашего сообщества на сайте ВКонтакте код будет отличаться.
