### ISSUE TITLE
GetDialogs

### ISSUE THREAD

**Issue by Vergiliy1** [vknet/vk#90]
int totalCount = 0;
ReadOnlyCollection<Message msg = vk.Messages.GetDialogs(out totalCount, 20,null,null,false);

Необработанное исключение типа "System.ArgumentException" в Newtonsoft.Json.dll

Дополнительные сведения: Accessed JArray values with invalid key value: "count". Array position index expected.

**Comment by CaCTuCaTu4ECKuu** [comment]
Исходники взяты отсюда и скомпилированы или скачена DLL-ка? Какой JSON приходит в ответ?

**Comment by Vergiliy1** [comment]
Ставил через NuGet. Извините я не знаю как посмотреть JSON.

**Comment by kristx300** [comment]
Json ответ можно посмотреть в табличке снизу - поле называется OutLine

**Comment by Vergiliy1** [comment]
+		_array	{[
  {
    "message": {
      "id": 217950,
      "date": 1431027241,
      "out": 1,
      "user_id": 199921995,
      "read_state": 1,
      "title": " ... ",
      "body": "Точно не знаю"
    }
  }
]}	Newtonsoft.Json.Linq.JArray

**Comment by CaCTuCaTu4ECKuu** [comment]
Скачайте исходники с сайта и запустите проект у себя, потом добавьте в свой проект полученную DLL-ку. Большая часть ошибок была исправлена и поправлены многие метода работы с API, в вашем случае VkNet работает не может обработать ответ новой версии API.
Можете подождать пока автор обновит NuGet пакеты, но не думаю что это будет скоро
