### ISSUE TITLE
Groups.GetMembers: Can not convert Object to Int64.

### ISSUE THREAD

**Issue by itsokto** [vknet/vk#902]
![image](https://user-images.githubusercontent.com/36706257/68528340-6f478f00-0302-11ea-8e6a-2960b3fb03df.png)
![image](https://user-images.githubusercontent.com/36706257/68528348-7d95ab00-0302-11ea-8a5f-0f6cced5b81c.png)

**Comment by inyutin-maxim** [comment]
eba388fad66cc27f99abc13bbcaa8dc79c52c5aa
