### ISSUE TITLE
Ошибка когда идет рассылка от группы по пользователям, и у пользователя закрыт доступ группе

### ISSUE THREAD

**Issue by odi1n** [vknet/vk#904]
Когда по группе идет рассылка сообщений и у пользователя стоит "не принимать сообщения от группы", во в лог вылазит эта ошибка
![image](https://user-images.githubusercontent.com/22261158/68541421-54cbef00-03b0-11ea-9e64-97fc1d4cb1f3.png)
Софт продолжает работать, не падает, но таких пользователей просто игнорирует и выводит это сообщение.

**Comment by itsokto** [comment]
При вызове какого метода появляется эта ошибка?

**Comment by odi1n** [comment]
> Причиной этой ошибки?
Ну при рассылке. Пользователей в сообщениях группы получаю все нормально. А отправка сообщений с помощью "Messages.Send".

**Comment by itsokto** [comment]
Т.е. при вызове messages.send? Проверьте ещё раз. Попробуйте словить ошибку в дебагере, нужно точное название метода.

**Comment by CaCTuCaTu4ECKuu** [comment]
Была когда-то такая ошибка, но давно её не замечал. Если не ошибаюсь там в модели что-то устарело. Сейчас рассылки по 100 id в запросе ошибок не выдают. По 1 не уверен, но должно быть тоже все в порядке.
Какую версию API использует ваш экземпляр VkApi?

**Comment by ghost** [comment]
@CaCTuCaTu4ECKuu Последнюю версию он использовал. Лог + код прикрепил. 
System.ArgumentException: Can not convert Array to Int64.
   в Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   в VkNet.Utils.VkResponse.op_Implicit(VkResponse response)
   в VkNet.Categories.MessagesCategory.Send(MessagesSendParams params)
   в ConsoleApplication1.Program.Main(String[] args) в C:\Users\panuc\Desktop\vk\vk\ConsoleApplication1\Program.cs:строка 53


[file.txt](https://github.com/vknet/vk/files/4113087/file.txt)
![image](https://user-images.githubusercontent.com/41389318/73129499-75423780-3ff6-11ea-8989-205fcc7a66a5.png)

**Comment by CaCTuCaTu4ECKuu** [comment]
Ну вообще ошибка из разряда classic, но если ты не знаешь как исправить лучший вариант завернуть прям в либе метод в try catch и там, где при парсинге произойдет ошибка. Нужен оригинальный json (в лог или output куда-то), там будет видно что вернул ВК и какое конкретно поле не пришло или пришло другое.
Понятно о чем я говорю или более развернуто расписать?
Вообще у либы есть debug mode который включается переменной среды, но им никто не пользуется :(

**Comment by CaCTuCaTu4ECKuu** [comment]
Проблема сидела перед компьютером.
Для таких ребят сделал коммит d256d1a2690c6f288188ccb1b5d2c67b3ea8c42b
