### ISSUE TITLE
Ошибка при долгой работе бота BotLongPoll

### ISSUE THREAD

**Issue by odi1n** [vknet/vk#905]
Заметил такую проблему, если бота оставить работать например(ночью) и активности в нем не будет, то можно заметить такую вот проблему. Есть предположение что это возникает когда обновляется "failed" и вылазит это Сообщение. На работу это не влияет, бот так же нормально работает и все хорошо

![image](https://user-images.githubusercontent.com/22261158/68541453-bf7d2a80-03b0-11ea-82cf-6435cebb38c8.png)

**Comment by CaCTuCaTu4ECKuu** [comment]
Возможно ли что конкретно этот сервер по какой-то причине стал недоступен и при такой ошибке нужно получить новый?
Что насчет отлавливать её и запрашивать новый сервер?
Но вообще ситуация интересная

**Comment by nybry04** [comment]
Такое происходит и с другими библиотеками

**Comment by CaCTuCaTu4ECKuu** [comment]
Если так то такое поведение, скорее всего, связано с принципом работы ВК

**Comment by DarkTwistter** [comment]
С ВК ночью происходит что-то необъяснимое
