### ISSUE TITLE
Utils.ResolveScreenName и VkObjectType устарели

### ISSUE THREAD

**Issue by PickGG** [vknet/vk#906]
У enum VkObjectType не хватает параметра Page, возможно не хватает и других параметров о которых я не знаю. 
Ну и соответственно Utils.ResolveScreenName тоже нужно обновить потому что он возвращет VkObject который содержит VkObjectType

**Comment by inyutin-maxim** [comment]
@PickGG Не могли бы вы предоставить json в котором содержится новый тип поля. требуется для покрытия тестами

**Comment by PickGG** [comment]
@inyutin-maxim 
{
"response": {
"type": "page",
"object_id": 179331040
}
}
