### ISSUE TITLE
Rate limit reached

### ISSUE THREAD

**Issue by Cubody** [vknet/vk#908]
Ранее всё было отлично, и бот работал, но теперь постоянно выдаёт эту ошибку, почему так? Я ничего не менял. Ошибка при вызове VkApi.Groups.GetLongPollServer()
![изображение](https://user-images.githubusercontent.com/41028671/70067923-e118ad00-1610-11ea-8635-a3fbd698fe6c.png)

**Comment by itsokto** [comment]
Из документации документации Vk
![image](https://user-images.githubusercontent.com/36706257/70072840-d5c18380-1608-11ea-9c3c-48721f91ac32.png)

В вашем случае неправильное использование метода. Не нужно его вызывать каждый раз для получения обновлений.

**Comment by Cubody** [comment]
А как можно получить все последние сообщения, пришедшие группе вк?

**Comment by itsokto** [comment]
Так же как вы делаете сейчас, просто не нужно вызывать VkApi.Groups.GetLongPollServer() постоянно. Сохраните результат этого метода после вызова и используйте.

**Comment by Cubody** [comment]
Спасибо.
