### ISSUE TITLE
Как обратно преобразовать Photo в Attachment ?

### ISSUE THREAD

**Issue by EgorYasinovskiy** [vknet/vk#910]
Я сделал парсер постов и в каждом посте есть фото. Мне необходимо его изменить я могу взять Attachment.Isstance as Photo, но не могу в самом классе Post изменить Attachment и добавить в него новое фото. Есть ли у вас идеи как это сделать ?

**Comment by inyutin-maxim** [comment]
@EgorYasinovskiy Доброго времени суток. Все вложения которые вы модифицируете вы должны залить на сервера вк, и чтобы работать с измененными вложениями вы должны их отдельно запросить. У нас есть в телеграм беседа где я и другие участники попробуют ответить на ваш вопрос: https://t.me/VkDotNet

**Comment by EgorYasinovskiy** [comment]
> @EgorYasinovskiy Доброго времени суток. Все вложения которые вы модифицируете вы должны залить на сервера вк, и чтобы работать с измененными вложениями вы должны их отдельно запросить. У нас есть в телеграм беседа где я и другие участники попробуют ответить на ваш вопрос: https://t.me/VkDotNet

Дело в том, что изначаль я меняю ссылку на фотографию, которая уже лежит в вк, и я хочу, чтобы в Attachments эта фотография тоже изменилась. У меня экземпляр класса пост, который я немного изменяю. например post.Text = "Какой-то текст". Так же мне нужно изменить и фото в нем. Сами фото уже загружены в вк.

**Comment by itsokto** [comment]
@EgorYasinovskiy для начала получите пост, затем ознакомьтесь с этим https://vk.com/dev/wall.edit методом.

**Comment by itsokto** [comment]
Присоединяйтесь в чат, если остались еще вопросы.
