### ISSUE TITLE
исключение при длине больше 255 у payload в KeyboardBuilder

### ISSUE THREAD

**Issue by ivanmem** [vknet/vk#915]
У вк для payload ограничение в 255 символов (в документации написано 1к, но это опечатка).

Если у клавиатуры payload больше, то сообщение не доходит и возвращается исключение.
 
Поэтому нужно обрабатывать это заранее.

**Comment by ivanmem** [comment]
Да, кстати, ограничение на одну кнопку - 255, а общее ограничение - 1к символов, это не опечатка. Извиняюсь за дизинфу. @inyutin-maxim прошу это учесть.

**Comment by inyutin-maxim** [comment]
6a11403317301e8831bf522c63eb90213bd32179
e58da978221c6283c50980a5a1aeaffc42c0c141

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
