### ISSUE TITLE
GetDialogs

### ISSUE THREAD

**Issue by Vergiliy1** [vknet/vk#92]
int totalCount, unreadCount;
ReadOnlyCollection<Message> msg = vk.Messages.GetDialogs(0, 0, out totalCount, out unreadCount, false, null, null, null);

Необработанное исключение типа "VkNet.Exception.InvalidParameterException" в VkNet.dll

Дополнительные сведения: One of the parameters specified was missing or invalid: unread is accepted only from version 5.14

		json	"{\"error\":{\"error_code\":100,\"error_msg\":\"One of the parameters specified was missing or invalid: unread is accepted only from version 5.14\",\"request_params\":[{\"key\":\"oauth\",\"value\":\"1\"},{\"key\":\"method\",\"value\":\"messages.getDialogs\"},{\"key\":\"count\",\"value\":\"0\"},{\"key\":\"offset\",\"value\":\"0\"},{\"key\":\"unread\",\"value\":\"0\"}]}}"	string

**Comment by CaCTuCaTu4ECKuu** [comment]
У вас скомпилированные исходники? Что написано в файле Categories/MessageCategory над GetDialogs?
Должно быть
[Pure]
[ApiVersion("5.28")]

**Comment by Vergiliy1** [comment]
Вроде да. Так и написано.

**Comment by CaCTuCaTu4ECKuu** [comment]
Вроде написано или так и написано? Вы указали ссылку на перекомпилированный VkNet.dll? (Потому что если установлен был через NuGet то будет использоваться именно он)

**Comment by Vergiliy1** [comment]
Так и написано. dll Подменил. Ладно спасибо но мне с эти походу не разобратся.

**Comment by CaCTuCaTu4ECKuu** [comment]
Проверю на выходных и если найду ошибку исправлю, если нет спишемся

**Comment by CaCTuCaTu4ECKuu** [comment]
Все сработало как и должно. Исходя из ошибки у меня только один вариант сейчас - у вас подключена старая версия библиотеки
![default](https://cloud.githubusercontent.com/assets/8963134/7539161/a3ea4d72-f5ad-11e4-9970-2eb31c18bc03.PNG)

**Comment by Vergiliy1** [comment]
Делаю так: Скачал архив - запустил проект - пуск - в папке Debug появилась VkNet.dll - в своем проекте указываю ссылку на эту dll. Но что-то наверно делаю не так, та же ошибка. Простите меня за мою тупость.

**Comment by CaCTuCaTu4ECKuu** [comment]
Напиши мне в скайп (такой же как и ник).
Если это ошибка нужно выяснить почему она происходит

**Comment by CaCTuCaTu4ECKuu** [comment]
Такой вопрос. У вас есть возможность установить VS2013, а не релиз кандидат VS2015
На второй компьютер с W10 у меня не ставится, а на этот, честно говоря, не хотелось бы ставить, если не сложно попробуйте сделать все заново только в VS13, ну или подождите еще

**Comment by CaCTuCaTu4ECKuu** [comment]
Что с ошибкой, проблема еще актуальна? Пытались решить сами?

**Comment by artemvirused** [comment]
Visual Studio 2015 Cummunity, ошибка по-прежнему имеется

**Comment by inyutin-maxim** [comment]
Метод работает исправно)) студия давно добралась до релиза, закрываю.

**Comment by xzxzxc** [comment]
Такая же ошибка при выполнении:
![default](https://cloud.githubusercontent.com/assets/10341682/25048977/04e56810-2148-11e7-87a5-c4634c127e05.png)
Причем раньше ее не было(

**Comment by inyutin-maxim** [comment]
@xzxzxc   а зачем вы id 2 раза отдаете?

**Comment by xzxzxc** [comment]
@inyutin-maxim потому что метод принимает его 2 раза, а все другие методы помечены как устаревшие: 
![image](https://cloud.githubusercontent.com/assets/10341682/25056606/a7bbb3d0-2172-11e7-90ab-7e0421deb665.png)
