### ISSUE TITLE
Добавить поддержку граффити

### ISSUE THREAD

**Issue by aaplnv** [vknet/vk#921]
Docs.getMessagesUploadServer может принимать type=graffiti, не реализованный в vknet. (Хотя это и не заявлено в документации)
![image](https://user-images.githubusercontent.com/56654805/72834404-ce7a3600-3c99-11ea-9892-8df0ed080679.png)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
