### ISSUE TITLE
Для метода Photo.GetAlbums в объекте PhotoSize не отдается поле url.

### ISSUE THREAD

**Issue by proggmatic** [vknet/vk#922]
**Describe the bug**
Для метода Photo.GetAlbums в объекте PhotoSize (свойство Sizes) не отдается поле url.
Тем не менее, ВКонтакте отдает поле Src, которое помечено как Obsolete. Но в объект оно не попадает, т.к. уже не помечено атрибутом [JsonProperty("src")] и сделано get-полем.

**Comment by ghost** [comment]
@inyutin-maxim метод Photo.GetAlbums возвращает photo_sizes, если параметры need_covers и photo_sizes поставить true(Обложку альбома возвращает).
А на счёт поля src, то ВК забыли в описании его поменять на "url" (здесь https://vk.com/dev/objects/photo_sizes, написал уже, поменяют).
И да, почему название метода в ВК "photos", а в либе "Photo"? Куда "s" подевалась?

**Comment by inyutin-maxim** [comment]
> И да, почему название метода в ВК "photos", а в либе "Photo"? Куда "s" подевалась?

Так исторически сложилось, еще до моего прихода в проект. Остальное учтем в будущем
