### ISSUE TITLE
Ошибка при парсинге координат из JSON в VkNet.Model.Coordinates

### ISSUE THREAD

**Issue by serhiy1994** [vknet/vk#925]
**Describe the bug**
Баг при попытке спарсить значения координат (пост, фотография) из JSON.

**To Reproduce**
Лично в моем случае:
1. Вызвать метод NewsFeed.Search с достаточно большим количеством получаемых результатов (у меня - 20).
2. Попытаться распарсить результаты п. 1, выдирая в цикле id, текст, автора и т.д. каждого поста.
3. При обработке очередного (а иногда и первого) результата в цикле словить ошибку 

> Newtonsoft.Json.JsonSerializationException: Error converting value "46.542171889988 33.407921387605" to type 'VkNet.Model.Coordinates'. Path 'response.items[17].geo.coordinates', line ..., position ... . ---> System.ArgumentException: Could not cast or convert from System.String to  VkNet.Model.Coordinates.
> 

Код для примера:
```
NewsSearchResult n = api.NewsFeed.Search(new NewsFeedSearchParams
                    {
                        Query = word,
                        Extended = false,
                        Count = 20
                    });
                    foreach (var p in n.Items)
                    {
                        try
                        {
                            if (p.OwnerId < 0)
                            {
                                var groups = api.Groups.GetById(null, (p.OwnerId * -1).ToString(), null).FirstOrDefault();
                                holderName = groups.Name;
                            }
                            else
                            {
                                var users = api.Users.Get(new long[] { p.OwnerId }).FirstOrDefault();
                                holderName = users.FirstName + " " + users.LastName;
                            }
                            attachments = p.Attachments != null ? p.Attachments.Count : 0;
                            if (p.Text.Length > 0)
                            {
                                ListViewItem item = new ListViewItem(holderName); //holdername
                                item.SubItems.Add(p.OwnerId.ToString());
                                item.SubItems.Add(p.Id.ToString());
                                item.SubItems.Add(p.Date.ToString());
                                item.SubItems.Add(p.Text);
                                item.SubItems.Add(attachments.ToString());
                                item.SubItems.Add((i + 1).ToString() + "-" + number.ToString()); //№ п/п посту
                                listView4.Items.Add(item);
                                number++;
                            }
                        }
                        catch { continue; }
                    }
```

**Expected behavior**
Вывод в табличном виде на windows-форму результатов парсинга.

**Desktop (please complete the following information):**
Windows 7 x64, VS 2017, .NET Framework 4.6.1.

**Comment by serhiy1994** [comment]
[responseBadCoordinates.txt](https://github.com/vknet/vk/files/4144878/responseBadCoordinates.txt)

**Comment by inyutin-maxim** [comment]
> [responseBadCoordinates.txt](https://github.com/vknet/vk/files/4144878/responseBadCoordinates.txt)

Данный JSON парсится без проблем, воспроизвести не удалось. Не могли бы вы приложить именно тот на котором происходит падение.

Подмена значений на указанные выше ` "46.542171889988 33.407921387605"` так же результатов не дало, все парсится корректно

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
