### ISSUE TITLE
Метод Groups.Create/CreateAsync лишние обязательные параметры

### ISSUE THREAD

**Issue by StoryOff** [vknet/vk#926]
[https://vk.com/dev/groups.create](url)
![image](https://i.imgur.com/kaqDvTt.png)
![image](https://i.imgur.com/UE6EO9C.png)
Из обязательных параметров должен быть только Title

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
