### ISSUE TITLE
Execute может принимать входные параметры

### ISSUE THREAD

**Issue by ghost** [vknet/vk#930]
Метод execute.execute может принимать входные параметры также как и execute.storedProcedure
```
https://api.vk.com/method/execute?access_token=TOKEN&v=5.95&lang=ru&my_var=123&code=return+Args.my_var%3B
```
my_var - переменная, которую можно использовать внутри code

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
