### ISSUE TITLE
Проблема с api.Account.GetPrivacySettings()

### ISSUE THREAD

**Issue by BearBump** [vknet/vk#939]
У меня есть такая строка кода.
`var privateSettingsInfo = api.Account.GetPrivacySettings();`

В этом месте получаю данную ошибку.
> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.String[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'response.settings[0].value.category', line 1, position 116.

Есть подозрение, что ошибка в модели. Как исправить это?

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
