### ISSUE TITLE
Как скоро вы напишете метод Wall.DeleteComment?

### ISSUE THREAD

**Issue by kristx300** [vknet/vk#94]

**Comment by CaCTuCaTu4ECKuu** [comment]
Если бы вы написали, я бы добавил, пока нет времени. Я видел там кто то ведет ветку и добавляет методы, возможно когда он закончит и закоммитит там будут и эти методы

**Comment by kristx300** [comment]
/// <summary>
        /// Удаляет комментарий текущего пользователя к записи на своей или чужой стене. 
        /// </summary>
        /// <param name="commentId">Идентификатор пользователя, на чьей стене находится комментарий к записи. </param>
        /// <param name="ownerId">Идентификатор комментария.</param>
        /// <remarks>
        /// Для вызова этого метода Ваше приложение должно иметь права с битовой маской, содержащей <see cref="Settings.Wall"/>.
        /// Страница документации ВКонтакте <see href="http://vk.com/dev/wall.deleteComment"/>.
        /// </remarks>
        public bool DeleteComment(long ownerId, long commentId)
        {
            VkErrors.ThrowIfNumberIsNegative(() => commentId);

            var parameters = new VkParameters
                         {
                             { "owner_id", ownerId },
                             { "comment_id", commentId }
                         };

            return _vk.Call("wall.deleteComment", parameters);
        }
написал, но не знаю как к Вам добавить :)

**Comment by CaCTuCaTu4ECKuu** [comment]
Добавил -_^
