### ISSUE TITLE
NextFrom из NewsFeed.Get() возвращает null

### ISSUE THREAD

**Issue by B011111000000** [vknet/vk#953]
![Снимок](https://user-images.githubusercontent.com/62337693/76969936-a9ced180-695d-11ea-843d-8f20e6a2ed3a.PNG)

Через документацию вк все работает ожидаемо:
![Снимок2](https://user-images.githubusercontent.com/62337693/76971176-6d9c7080-695f-11ea-849b-6dc12c6c8414.PNG)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
