### ISSUE TITLE
"Access denied: no access to call this method" - Message.Send, VkNet.AudioBypass

### ISSUE THREAD

**Issue by amfy123** [vknet/vk#963]
Здравствуйте. авторизуюсь таким образом:
`var services = new ServiceCollection();
services.AddAudioBypass();

Singlet.Api = new VkApi(services);
Singlet.Api.Authorize(new ApiAuthParams
{
    AccessToken = token
});`

Но всё равно получаю ошибку при использовании **Messages.Send**

`Singlet.Api.Messages.Send(new VkNet.Model.RequestParams.MessagesSendParams
{
    UserId = user.id,
    RandomId = new Random().Next(),
    Message = "test"
});`

Подскажите, пожалуйста, что не так??

**Comment by itsokto** [comment]
Токен **должен** быть получен через VkNet.AudioBypass при авторизации через логин и пароль, только после этого вы можете вызывать методы этой категории. После авторизации можно сохранить токен и переиспользовать.

**Comment by amfy123** [comment]
То есть, безопасную авторизацию через сервера вк сделать не получится?

**Comment by itsokto** [comment]
Авторизация происходит через сервера Vk. Исходный код VkNet.AudioBypass открыт, можете сами убедится, что логин и пароль никуда не отправляется.

**Comment by amfy123** [comment]
Спасибо! :)
