### ISSUE TITLE
Если среди сообщений есть подарок - падает

### ISSUE THREAD

**Issue by Seekeer** [vknet/vk#97]
api.Messages.Get падает со следующим исключением:

An unhandled exception of type 'VkNet.Exception.InvalidParameterException' occurred in VkNet.dll
Additional information: The type 'gift' of attachment is not defined.

**Comment by CaCTuCaTu4ECKuu** [comment]
А еще падает или уже нет? Вроде уже правили все что касается аттачей

**Comment by inyutin-maxim** [comment]
Я не проверял, как то не пришлось к случаю. ничего не могу сказать насчет этого бага

**Comment by CaCTuCaTu4ECKuu** [comment]
Проверил - ничего не падает
