### ISSUE TITLE
Реализовать категорию PrettyCards

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#970]
- [x] prettyCards.create
- [x] prettyCards.delete
- [x] prettyCards.edit
- [x] prettyCards.get
- [x] prettyCards.getById
- [x] prettyCards.getUploadURL

**Comment by ghost** [comment]
Взял в работу.

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
