### ISSUE TITLE
При запросе users.get нету поля Город

### ISSUE THREAD

**Issue by DarkPlasticine** [vknet/vk#98]
при запросе с полями ProfileFields.AllUndocumented или ProfileFields.All или ProfileFields.City приходит null даже при открытой информации о городе в контактной информации.

**Comment by CaCTuCaTu4ECKuu** [comment]
Вы компилировали исходники или устанавливали через NuGet? У меня где то использовался этот метод и все работало. Но я, конечно,  проверю позже

**Comment by DarkPlasticine** [comment]
Устанавливал через NuGet

**Comment by CaCTuCaTu4ECKuu** [comment]
Скачайте исходники с сайта и перекомпилируйте. Было очень много обновлений и исправлений. Подпишитесь если все в порядке

**Comment by DarkPlasticine** [comment]
Скачал, City заработал, но есть вопрос, нужен поиск контактов по другим данным, к примеру по городу и дате рождения, с получением родного города это возможно?

**Comment by CaCTuCaTu4ECKuu** [comment]
Что то такое уже спрашивали, что-то вроде найти по полу и по имени, максим, пол женский хотели найти что-ли. В общем эта библиотека - полный порт VK API и если там есть возможность такого поиска значит здесь она может работать, а если не работает - тогда буду смотреть. Поищите интересующие вас вопросы там - http://vk.com/dev/main

**Comment by DarkPlasticine** [comment]
https://vk.com/dev/users.search - в библиотеке можно искать чисто по ключу q с возвратом необходимых полей, количеством человек и смещением. в документации же, можно еще фильтровать по многим параметрам. Либо я что то не так понял, тогда простите.
И при запросе users.get не возвращается поле hometown (https://vk.com/dev/fields) точно

**Comment by CaCTuCaTu4ECKuu** [comment]
Я понял. Нет параметров поиска в методе. Если хотите можете сами добавить, я смогу как освобожусь
