### ISSUE TITLE
JsonSerializationException VkNet.Model.VideoImage 

### ISSUE THREAD

**Issue by ivanmem** [vknet/vk#982]
https://gist.github.com/xeleoss/d4419feff82790fb803fe75c792fa51a

**Comment by ghost** [comment]
@inyutin-maxim вероятно уже было исправлено или была ошибка на стороне ВК, т.к. на данный момент json от ВК соответствует модели в VkNet.

**Comment by ghost** [comment]
Закрываю, ошибка не воспроизводится, вероятно уже исправлена.
