### ISSUE TITLE
Удалить свойства Items, Count из Photo

### ISSUE THREAD

**Issue by melphis** [vknet/vk#983]
Его нет в протоколе и по описанию какое-то странное и дублирует `Sizes`.
Я так понимаю, что оно было частично `sizes`, частично `Photos`.
```
/// <summary>
/// Размеры фотографий.
/// </summary>
[JsonProperty("items")]
public VkCollection<Photo> Items { get; set; }
```

**Comment by itsokto** [comment]
Это свойство было добавлено одним из контрибьюторов оно действительно лишнее и будет удаленно. Возможно не заметили при ревью.

[Commit reference](https://github.com/vknet/vk/pull/955/commits/870867fa64b97cbf71a044f9b0d307dbd3f8baf3)
