### ISSUE TITLE
User Get() может запрашивать капчу

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [vknet/vk#99]
Добавить возможность вызова метода с вводом капчи (перегрузкой или создать новый internal метод и ссылаться на него т.к. там несколько методов User Get).

**Comment by inyutin-maxim** [comment]
Проблема еще актуальна? сколько пытался воспроизвести так и не получилось

**Comment by CaCTuCaTu4ECKuu** [comment]
Когда свою программу на тестирование отдам попрошу поганять сообщения, может я тогда что-то напутал, с асинхронными методами там или просто что-то перепутал, это беру на себя полностью

**Comment by inyutin-maxim** [comment]
Единственная ошибка которую мне удавалось поймать 
error_code: 6,
error_msg: 'Too many requests per second'

Хорошо. Работы еще много займусь чем то еще

**Comment by CaCTuCaTu4ECKuu** [comment]
У ВК там алгоритмы есть, если по тем кто в списке бить или по своему городу, например, может не спросить, короче у меня будут тестировать там какраз всплывет если действительно есть (может была, но убрали)

**Comment by inyutin-maxim** [comment]
id: 205387401,
first_name: 'Tom',
last_name: 'Cruise',


Он явно не из моего города))))))

**Comment by CaCTuCaTu4ECKuu** [comment]
Это еще зависит от аккаунта, у ВК есть какой то внутренний показатель надежности аккаунта, я со своего, например, могу рассылать все сообщения по максимуму даже со ссылками без капчи, но с ботов каждые несколько сообщ. вылазит капча (это без API), плюс частота рассылки в длительном промежутке времени решает, количество жалоб на аккаунт

**Comment by inyutin-maxim** [comment]
> users.get
> Возвращает расширенную информацию о пользователях.
> Это открытый метод, не требующий access_token.

Думаю проблема потеряла актуальность. Для уверенности прогнал тест на 1000 запросов, капча не потребовалась
