### ISSUE TITLE
5.105 apps.get и объект приложения добавлены 2 новых поля:

### ISSUE THREAD

**Issue by inyutin-maxim** [vknet/vk#994]
[apps.get](https://vk.com/dev/apps.get) и [объект приложения](https://vk.com/dev/objects/app)  добавлены 2 новых поля:   
**mobile_controls_type**  и **mobile_view_support_type**, которые описывают, как отображаются элементы управления для игр в вебвью в нативных клиентах.

**mobile_controls_type** = _0_ - прозрачный элемент управления поверх области с игрой;   
**mobile_controls_type** = _1_ - чёрная полоска над областью с игрой;   
**mobile_controls_type** = _2_ - только для vk apps, без контроллов.   

**mobile_view_support_type** = _0_ - игра не использует нижнюю часть экрана на iPhoneX, черная полоса есть.   
**mobile_view_support_type** = _1_ -  игра использует нижнюю часть экрана на iPhoneX, черной полосы нет.

**Comment by itsokto** [comment]
В документации объекта и changelog api разногласия 
![image](https://user-images.githubusercontent.com/36706257/83338258-3e916c00-a2cb-11ea-94af-710c496bf53c.png)
