### ISSUE TITLE
возвращает null в user.FirstName

### ISSUE THREAD

**Issue by Lobrun** [vknet/vk#998]
![0JAVKEkuW6k](https://user-images.githubusercontent.com/48880493/83560447-f4082d80-a51e-11ea-8cc0-181aa23f28ba.jpg)

Здравствуйте, я создаю бота для сообщества ВКонтакте. Я работаю на языке C# и с библиотекой VkNet. Я хотел бы получить имя отправителя сообщения через id отправителя сообщения.
Приведу пример из кода :
User us = new User();
us.Id = (long)a.Message.FromId;
string name = us.FirstName.ToString();
Но выходит ошибка : VkNet.Model.User.FirstName.get вернул null. Хотя id отправителя сообщения я могу узнать. Я пробовал использовать сервисный access token и token сообщества и token объединенных группы и сообщества, но узнать имя отправителя сообщения я не смог. Можете мне помочь с данной проблемой. И если можете привести пример кода на языке C#

**Comment by 1dNDN** [comment]
И именуй, пожалуйста, переменные нормально
```(long)a.Message.FromId;
long[] id = new long[1] {userId};
ReadOnlyCollection<User> result = api.Users.Get(id, ProfileFields.Verified);
string name = result[0].FirstName;

**Comment by itsokto** [comment]
Просто создание объекта User не заполнит его свойства, выше вам дали ответ.
Присоединяйтесь к чатам VkNet в [Telegram](https://t.me/VkDotNet) или [Вконтакте](https://vk.me/join/AJQ1d5GGSBb/91JNBxgQu5cw) если что-то не понятно.
